// lessonsLazy.ts — TỆP SINH TỰ ĐỘNG, ĐỪNG SỬA TAY.
// Sinh bởi `npm run gen:stem-lesson-index` (scripts/gen-stem-lesson-index.ts).
// Thêm hoặc sửa bài học xong PHẢI chạy lại lệnh đó, nếu không chỉ mục lệch với nội dung thật.
import type { StemLessonSummary } from '@dhcb/core-contracts/stemLesson'
import type { MathLesson } from './lessonTypes.js'

export const LESSON_INDEX: StemLessonSummary[] = [
  {
    id: 'toan10-c1-b1',
    grade: '10',
    chapterNumber: 1,
    chapterTitle: 'Mệnh đề và tập hợp',
    lessonNumber: 1,
    title: 'Mệnh đề, mệnh đề kéo theo và mệnh đề phủ định',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan10c1',
  },
  {
    id: 'toan10-c1-b2',
    grade: '10',
    chapterNumber: 1,
    chapterTitle: 'Mệnh đề và tập hợp',
    lessonNumber: 2,
    title: 'Tập hợp và các phép toán trên tập hợp',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c1',
  },
  {
    id: 'toan10-c2-b1',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Bất phương trình và hệ bất phương trình bậc nhất hai ẩn',
    lessonNumber: 1,
    title: 'Miền nghiệm của bất phương trình bậc nhất hai ẩn',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c2',
  },
  {
    id: 'toan10-c3-b1',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Hệ thức lượng trong tam giác',
    lessonNumber: 1,
    title: 'Định lí côsin và định lí sin',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan10c3',
  },
  {
    id: 'toan10-c4-b1',
    grade: '10',
    chapterNumber: 4,
    chapterTitle: 'Vectơ',
    lessonNumber: 1,
    title: 'Vectơ và phép cộng vectơ',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c4',
  },
  {
    id: 'toan10-c4-b2',
    grade: '10',
    chapterNumber: 4,
    chapterTitle: 'Vectơ',
    lessonNumber: 2,
    title: 'Tích vô hướng của hai vectơ',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan10c4',
  },
  {
    id: 'toan10-c6-b1',
    grade: '10',
    chapterNumber: 6,
    chapterTitle: 'Hàm số, đồ thị và ứng dụng',
    lessonNumber: 1,
    title: 'Hàm số bậc hai và đồ thị parabol',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c6',
  },
  {
    id: 'toan10-c6-b2',
    grade: '10',
    chapterNumber: 6,
    chapterTitle: 'Hàm số, đồ thị và ứng dụng',
    lessonNumber: 2,
    title: 'Dấu của tam thức bậc hai và bất phương trình bậc hai',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan10c6',
  },
  {
    id: 'toan10-c7-b1',
    grade: '10',
    chapterNumber: 7,
    chapterTitle: 'Phương pháp toạ độ trong mặt phẳng',
    lessonNumber: 1,
    title: 'Phương trình đường thẳng và khoảng cách từ điểm đến đường thẳng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan10c7',
  },
  {
    id: 'toan10-c7-b2',
    grade: '10',
    chapterNumber: 7,
    chapterTitle: 'Phương pháp toạ độ trong mặt phẳng',
    lessonNumber: 2,
    title: 'Phương trình đường tròn',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan10c7',
  },
  {
    id: 'toan10-c8-b1',
    grade: '10',
    chapterNumber: 8,
    chapterTitle: 'Đại số tổ hợp',
    lessonNumber: 1,
    title: 'Hoán vị, chỉnh hợp và tổ hợp',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan10c8',
  },
  {
    id: 'toan10-c8-b2',
    grade: '10',
    chapterNumber: 8,
    chapterTitle: 'Đại số tổ hợp',
    lessonNumber: 2,
    title: 'Nhị thức Newton',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan10c8',
  },
  {
    id: 'toan10-c9-b1',
    grade: '10',
    chapterNumber: 9,
    chapterTitle: 'Tính xác suất theo định nghĩa cổ điển',
    lessonNumber: 1,
    title: 'Không gian mẫu, biến cố và xác suất cổ điển',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan10c9',
  },
  {
    id: 'toan11-c1-b1',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Hàm số lượng giác và phương trình lượng giác',
    lessonNumber: 1,
    title: 'Giá trị lượng giác của góc lượng giác và đường tròn lượng giác',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c1',
  },
  {
    id: 'toan11-c1-b2',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Hàm số lượng giác và phương trình lượng giác',
    lessonNumber: 2,
    title: 'Phương trình lượng giác cơ bản',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan11c1',
  },
  {
    id: 'toan11-c2-b1',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Dãy số. Cấp số cộng và cấp số nhân',
    lessonNumber: 1,
    title: 'Cấp số cộng và cấp số nhân',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c2',
  },
  {
    id: 'toan11-c5-b1',
    grade: '11',
    chapterNumber: 5,
    chapterTitle: 'Giới hạn. Hàm số liên tục',
    lessonNumber: 1,
    title: 'Giới hạn của dãy số và tổng cấp số nhân lùi vô hạn',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c5',
  },
  {
    id: 'toan11-c5-b2',
    grade: '11',
    chapterNumber: 5,
    chapterTitle: 'Giới hạn. Hàm số liên tục',
    lessonNumber: 2,
    title: 'Giới hạn của hàm số và hàm số liên tục',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan11c5',
  },
  {
    id: 'toan11-c6-b1',
    grade: '11',
    chapterNumber: 6,
    chapterTitle: 'Hàm số mũ và hàm số lôgarit',
    lessonNumber: 1,
    title: 'Lôgarit và các quy tắc tính',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan11c6',
  },
  {
    id: 'toan11-c6-b2',
    grade: '11',
    chapterNumber: 6,
    chapterTitle: 'Hàm số mũ và hàm số lôgarit',
    lessonNumber: 2,
    title: 'Phương trình mũ và phương trình lôgarit',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan11c6',
  },
  {
    id: 'toan11-c7-b1',
    grade: '11',
    chapterNumber: 7,
    chapterTitle: 'Quan hệ vuông góc trong không gian',
    lessonNumber: 1,
    title: 'Đường thẳng vuông góc với mặt phẳng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan11c7',
  },
  {
    id: 'toan10-c20-b1',
    grade: '10',
    chapterNumber: 20,
    chapterTitle: 'Chuyên đề bồi dưỡng học sinh giỏi cấp trường',
    lessonNumber: 1,
    title: 'Bất đẳng thức AM–GM và kỹ thuật tìm giá trị nhỏ nhất',
    track: 'advanced',
    advancedTier: 'hsg-truong',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan10c20',
  },
  {
    id: 'toan10-c20-b2',
    grade: '10',
    chapterNumber: 20,
    chapterTitle: 'Chuyên đề bồi dưỡng học sinh giỏi cấp trường',
    lessonNumber: 2,
    title: 'Chia hết và đồng dư cơ bản trong số học',
    track: 'advanced',
    advancedTier: 'hsg-truong',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan10c20',
  },
  {
    id: 'toan11-c9-b1',
    grade: '11',
    chapterNumber: 9,
    chapterTitle: 'Đạo hàm',
    lessonNumber: 1,
    title: 'Khái niệm đạo hàm và ý nghĩa hình học',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan11c9',
  },
  {
    id: 'toan11-c20-b1',
    grade: '11',
    chapterNumber: 20,
    chapterTitle: 'Chuyên đề bồi dưỡng học sinh giỏi cấp tỉnh',
    lessonNumber: 1,
    title: 'Bất đẳng thức Cauchy–Schwarz và kỹ thuật Cauchy–Schwarz dạng Engel',
    track: 'advanced',
    advancedTier: 'hsg-tinh',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan11c20',
  },
  {
    id: 'toan11-c20-b2',
    grade: '11',
    chapterNumber: 20,
    chapterTitle: 'Chuyên đề bồi dưỡng học sinh giỏi cấp tỉnh',
    lessonNumber: 2,
    title: 'Phương tích của một điểm và trục đẳng phương',
    track: 'advanced',
    advancedTier: 'hsg-tinh',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan11c20',
  },
  {
    id: 'toan12-c1-b1',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Ứng dụng đạo hàm để khảo sát và vẽ đồ thị hàm số',
    lessonNumber: 1,
    title: 'Tính đơn điệu và cực trị của hàm số',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan12c1',
  },
  {
    id: 'toan12-c1-b2',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Ứng dụng đạo hàm để khảo sát và vẽ đồ thị hàm số',
    lessonNumber: 2,
    title: 'Đường tiệm cận của đồ thị hàm số',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c1',
  },
  {
    id: 'toan12-c2-b1',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Vectơ và hệ trục toạ độ trong không gian',
    lessonNumber: 1,
    title: 'Vectơ trong không gian và các phép toán',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan12c2',
  },
  {
    id: 'toan12-c2-b2',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Vectơ và hệ trục toạ độ trong không gian',
    lessonNumber: 2,
    title: 'Toạ độ của điểm và của vectơ trong không gian Oxyz',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c2',
  },
  {
    id: 'toan12-c2-b3',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Vectơ và hệ trục toạ độ trong không gian',
    lessonNumber: 3,
    title: 'Biểu thức toạ độ của phép toán vectơ và tích vô hướng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c2',
  },
  {
    id: 'toan12-c2-b4',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Vectơ và hệ trục toạ độ trong không gian',
    lessonNumber: 4,
    title: 'Ứng dụng toạ độ: khoảng cách giữa hai điểm và góc giữa hai đường thẳng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c2',
  },
  {
    id: 'toan12-c3-b1',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Các số đặc trưng đo mức độ phân tán của mẫu số liệu ghép nhóm',
    lessonNumber: 1,
    title: 'Khoảng biến thiên và khoảng tứ phân vị của mẫu số liệu ghép nhóm',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan12c3',
  },
  {
    id: 'toan12-c3-b2',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Các số đặc trưng đo mức độ phân tán của mẫu số liệu ghép nhóm',
    lessonNumber: 2,
    title: 'Phương sai và độ lệch chuẩn của mẫu số liệu ghép nhóm',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c3',
  },
  {
    id: 'toan12-c3-b3',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Các số đặc trưng đo mức độ phân tán của mẫu số liệu ghép nhóm',
    lessonNumber: 3,
    title: 'So sánh độ phân tán giữa hai mẫu số liệu và vận dụng thực tế',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c3',
  },
  {
    id: 'toan12-c4-b1',
    grade: '12',
    chapterNumber: 4,
    chapterTitle: 'Nguyên hàm và tích phân',
    lessonNumber: 1,
    title: 'Nguyên hàm — phép toán ngược của đạo hàm',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c4',
  },
  {
    id: 'toan12-c4-b2',
    grade: '12',
    chapterNumber: 4,
    chapterTitle: 'Nguyên hàm và tích phân',
    lessonNumber: 2,
    title: 'Tích phân và ứng dụng tính diện tích, thể tích',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'toan12c4',
  },
  {
    id: 'toan12-c5-b1',
    grade: '12',
    chapterNumber: 5,
    chapterTitle: 'Phương pháp toạ độ trong không gian',
    lessonNumber: 1,
    title: 'Hệ toạ độ Oxyz và tích có hướng của hai vectơ',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c5',
  },
  {
    id: 'toan12-c5-b2',
    grade: '12',
    chapterNumber: 5,
    chapterTitle: 'Phương pháp toạ độ trong không gian',
    lessonNumber: 2,
    title: 'Phương trình mặt phẳng và mặt cầu',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c5',
  },
  {
    id: 'toan12-c6-b1',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Xác suất có điều kiện',
    lessonNumber: 1,
    title: 'Xác suất có điều kiện và công thức Bayes',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c6',
  },
  {
    id: 'toan12-c20-b1',
    grade: '12',
    chapterNumber: 20,
    chapterTitle: 'Chuyên đề bồi dưỡng học sinh giỏi quốc gia',
    lessonNumber: 1,
    title: 'Phương trình hàm Cauchy và kỹ thuật thế giá trị đặc biệt',
    track: 'advanced',
    advancedTier: 'hsg-quoc-gia',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c20',
  },
  {
    id: 'toan12-c20-b2',
    grade: '12',
    chapterNumber: 20,
    chapterTitle: 'Chuyên đề bồi dưỡng học sinh giỏi quốc gia',
    lessonNumber: 2,
    title: 'Bất biến và đơn biến trong bài toán tổ hợp',
    track: 'advanced',
    advancedTier: 'hsg-quoc-gia',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'toan12c20',
  },
]

export const CHAPTER_LOADERS: Record<string, () => Promise<MathLesson[]>> = {
  toan10c1: () => import('./lessons/toan10c1.js').then((m) => m.TOAN10_C1_LESSONS),
  toan10c2: () => import('./lessons/toan10c2.js').then((m) => m.TOAN10_C2_LESSONS),
  toan10c3: () => import('./lessons/toan10c3.js').then((m) => m.TOAN10_C3_LESSONS),
  toan10c4: () => import('./lessons/toan10c4.js').then((m) => m.TOAN10_C4_LESSONS),
  toan10c6: () => import('./lessons/toan10c6.js').then((m) => m.TOAN10_C6_LESSONS),
  toan10c7: () => import('./lessons/toan10c7.js').then((m) => m.TOAN10_C7_LESSONS),
  toan10c8: () => import('./lessons/toan10c8.js').then((m) => m.TOAN10_C8_LESSONS),
  toan10c9: () => import('./lessons/toan10c9.js').then((m) => m.TOAN10_C9_LESSONS),
  toan11c1: () => import('./lessons/toan11c1.js').then((m) => m.TOAN11_C1_LESSONS),
  toan11c2: () => import('./lessons/toan11c2.js').then((m) => m.TOAN11_C2_LESSONS),
  toan11c5: () => import('./lessons/toan11c5.js').then((m) => m.TOAN11_C5_LESSONS),
  toan11c6: () => import('./lessons/toan11c6.js').then((m) => m.TOAN11_C6_LESSONS),
  toan11c7: () => import('./lessons/toan11c7.js').then((m) => m.TOAN11_C7_LESSONS),
  toan10c20: () => import('./lessons/toan10c20.js').then((m) => m.TOAN10_C20_LESSONS),
  toan11c9: () => import('./lessons/toan11c9.js').then((m) => m.TOAN11_C9_LESSONS),
  toan11c20: () => import('./lessons/toan11c20.js').then((m) => m.TOAN11_C20_LESSONS),
  toan12c1: () => import('./lessons/toan12c1.js').then((m) => m.TOAN12_C1_LESSONS),
  toan12c2: () => import('./lessons/toan12c2.js').then((m) => m.TOAN12_C2_LESSONS),
  toan12c3: () => import('./lessons/toan12c3.js').then((m) => m.TOAN12_C3_LESSONS),
  toan12c4: () => import('./lessons/toan12c4.js').then((m) => m.TOAN12_C4_LESSONS),
  toan12c5: () => import('./lessons/toan12c5.js').then((m) => m.TOAN12_C5_LESSONS),
  toan12c6: () => import('./lessons/toan12c6.js').then((m) => m.TOAN12_C6_LESSONS),
  toan12c20: () => import('./lessons/toan12c20.js').then((m) => m.TOAN12_C20_LESSONS),
}
