// lessons/hoa10c7.ts — Hoá học 10, Chương 7: Nhóm halogen (2 bài).
import type { ChemLesson } from '../lessonTypes.js'

export const HOA10_C7_LESSONS: ChemLesson[] = [
  {
    id: 'hoa10-c7-b16',
    grade: '10',
    chapterNumber: 7,
    chapterTitle: 'Nhóm halogen',
    lessonNumber: 16,
    title: 'Nhóm halogen',
    hook:
      'Nước máy có mùi Chlorine — chính nguyên tố này khử trùng nước sinh hoạt của hàng tỷ ' +
      'người mỗi ngày. Vì sao nhóm halogen lại có tính oxi hoá mạnh đến vậy?',
    theory:
      'NHÓM HALOGEN (nhóm VIIA) gồm: Fluorine (F), Chlorine (Cl), Bromine (Br), Iodine (I) — ' +
      'đều có 7 electron lớp ngoài cùng, chỉ cần nhận thêm 1 electron để đạt octet.\n\n' +
      'Vì vậy halogen có TÍNH OXI HOÁ MẠNH (dễ nhận electron) — tính oxi hoá GIẢM DẦN theo ' +
      'chiều F > Cl > Br > I (đúng xu hướng độ âm điện giảm dần khi đi xuống nhóm).\n\n' +
      'Đơn chất halogen tồn tại ở dạng PHÂN TỬ HAI NGUYÊN TỬ (X₂), liên kết cộng hoá trị ' +
      'không cực. Trạng thái ở điều kiện thường: F₂ (khí), Cl₂ (khí), Br₂ (lỏng), I₂ (rắn) — ' +
      'màu sắc và trạng thái biến đổi theo chiều tăng khối lượng phân tử.\n\n' +
      'Tính chất hoá học đặc trưng: halogen phản ứng được với hầu hết kim loại tạo muối ' +
      'halide, phản ứng với hydrogen tạo hydrogen halide (HX), và các halogen mạnh hơn có ' +
      'thể ĐẨY halogen yếu hơn ra khỏi muối halide của nó (Cl₂ đẩy được Br₂ ra khỏi dung ' +
      'dịch muối bromide, do Cl có tính oxi hoá mạnh hơn Br).',
    workedExample: {
      problem: 'Cho khí Cl₂ vào dung dịch NaBr. Dự đoán hiện tượng xảy ra và giải thích.',
      steps: [
        'So sánh tính oxi hoá: Cl có độ âm điện lớn hơn Br (Cl đứng trên Br trong nhóm VIIA) ' +
          '⇒ Cl₂ có tính oxi hoá MẠNH HƠN Br₂.',
        'Chất có tính oxi hoá mạnh hơn sẽ đẩy được chất có tính oxi hoá yếu hơn ra khỏi muối ' +
          'của nó.',
        'Phản ứng xảy ra: Cl₂ + 2NaBr → 2NaCl + Br₂.',
        'Hiện tượng: dung dịch chuyển màu (xuất hiện Br₂ màu nâu đỏ/vàng cam).',
      ],
      answer: 'Cl₂ + 2NaBr → 2NaCl + Br₂ — dung dịch chuyển màu do Br₂ sinh ra.',
    },
    checkQuestions: [
      {
        prompt: 'Tính oxi hoá của các halogen biến đổi theo chiều nào (từ mạnh đến yếu)?',
        choices: [
          { id: 'a', label: 'F > Cl > Br > I' },
          { id: 'b', label: 'I > Br > Cl > F' },
          { id: 'c', label: 'Cl > F > I > Br' },
        ],
        answer: { kind: 'choice', correctIds: ['a'] },
        explain:
          'Đúng xu hướng độ âm điện giảm dần khi đi xuống nhóm VIIA: F có tính oxi hoá mạnh nhất, I yếu nhất trong 4 halogen phổ biến.',
      },
      {
        prompt: 'Nguyên tử halogen cần nhận thêm bao nhiêu electron để đạt cấu hình octet bền?',
        answer: { kind: 'numeric', value: 1 },
        explain:
          'Halogen có 7 electron lớp ngoài cùng, chỉ cần thêm 1e để đủ 8 — đây là lý do chúng có tính oxi hoá mạnh, dễ nhận electron.',
      },
    ],
    srsCards: [
      {
        hoi: 'Nhóm halogen gồm những nguyên tố nào?',
        dap: 'Fluorine (F), Chlorine (Cl), Bromine (Br), Iodine (I) — nhóm VIIA.',
      },
      {
        hoi: 'Tính oxi hoá của halogen biến đổi thế nào từ F đến I?',
        dap: 'Giảm dần: F > Cl > Br > I.',
      },
      {
        hoi: 'Đơn chất halogen tồn tại ở dạng gì?',
        dap: 'Phân tử hai nguyên tử (X₂), liên kết cộng hoá trị không cực.',
      },
    ],
    animation: {
      title:
        'Từ F₂ đến I₂: nhiệt độ nóng chảy, nhiệt độ sôi tăng và trạng thái đổi từ khí sang rắn',
      description:
        'Trục dọc là nhiệt độ (°C), bốn cột là F₂, Cl₂, Br₂, I₂. Mỗi cột đi từ nhiệt độ nóng chảy (chấm rỗng) lên nhiệt độ sôi (chấm đặc); giữa hai mốc đó chất ở thể lỏng. F₂ nóng chảy ở −220 °C, sôi ở −188 °C; Cl₂: −101 °C và −34 °C; Br₂: −7 °C và 59 °C; I₂: 114 °C và 184 °C — cả hai nhiệt độ đều tăng dần. Đường ngang 25 °C cho biết trạng thái ở điều kiện thường: cột F₂ và Cl₂ nằm hẳn dưới đường (đã quá nhiệt độ sôi) nên là chất khí; đường cắt ngang cột Br₂ (đã nóng chảy, chưa sôi) nên Br₂ lỏng; cột I₂ nằm hẳn trên đường (chưa tới nhiệt độ nóng chảy) nên I₂ rắn. Nguyên nhân là phân tử càng nặng, càng nhiều electron thì tương tác van der Waals giữa các phân tử càng mạnh, chứ không phải liên kết trong phân tử thay đổi.',
      viewBoxWidth: 440,
      viewBoxHeight: 252,
      durationMs: 7000,
      loop: true,
      shapes: [
        {
          kind: 'line',
          id: 'ty',
          x1: 60,
          y1: 212,
          x2: 60,
          y2: 36,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'line',
          id: 'tx',
          x1: 60,
          y1: 212,
          x2: 420,
          y2: 212,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'line',
          id: 'v-200',
          x1: 56,
          y1: 194.5,
          x2: 60,
          y2: 194.5,
          stroke: 'muted',
          strokeWidth: 1.5,
        },
        {
          kind: 'line',
          id: 'v-100',
          x1: 56,
          y1: 155.9,
          x2: 60,
          y2: 155.9,
          stroke: 'muted',
          strokeWidth: 1.5,
        },
        {
          kind: 'line',
          id: 'v0',
          x1: 56,
          y1: 117.3,
          x2: 60,
          y2: 117.3,
          stroke: 'muted',
          strokeWidth: 1.5,
        },
        {
          kind: 'line',
          id: 'v100',
          x1: 56,
          y1: 78.6,
          x2: 60,
          y2: 78.6,
          stroke: 'muted',
          strokeWidth: 1.5,
        },
        {
          kind: 'line',
          id: 'v200',
          x1: 56,
          y1: 40,
          x2: 60,
          y2: 40,
          stroke: 'muted',
          strokeWidth: 1.5,
        },
        {
          kind: 'line',
          id: 'phong',
          x1: 60,
          y1: 107.6,
          x2: 420,
          y2: 107.6,
          stroke: 'danger',
          strokeWidth: 1.5,
          dash: '5 4',
          opacity: 0,
          keyframes: [
            { atMs: 3000, opacity: 0 },
            { atMs: 3400, opacity: 1 },
          ],
        },
        {
          kind: 'rect',
          id: 'long0',
          x: 114,
          y: 189.9,
          w: 12,
          h: 12.4,
          fill: 'accent',
          opacity: 0,
          keyframes: [
            { atMs: 300, opacity: 0 },
            { atMs: 700, opacity: 0.55 },
          ],
        },
        {
          kind: 'circle',
          id: 'nc0',
          cx: 120,
          cy: 202.3,
          r: 5,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 300, opacity: 0 },
            { atMs: 700, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'soi0',
          cx: 120,
          cy: 189.9,
          r: 5,
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 300, opacity: 0 },
            { atMs: 700, opacity: 1 },
          ],
        },
        {
          kind: 'rect',
          id: 'long1',
          x: 194,
          y: 130.4,
          w: 12,
          h: 25.9,
          fill: 'accent',
          opacity: 0,
          keyframes: [
            { atMs: 950, opacity: 0 },
            { atMs: 1350, opacity: 0.55 },
          ],
        },
        {
          kind: 'circle',
          id: 'nc1',
          cx: 200,
          cy: 156.3,
          r: 5,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 950, opacity: 0 },
            { atMs: 1350, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'soi1',
          cx: 200,
          cy: 130.4,
          r: 5,
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 950, opacity: 0 },
            { atMs: 1350, opacity: 1 },
          ],
        },
        {
          kind: 'rect',
          id: 'long2',
          x: 274,
          y: 94.5,
          w: 12,
          h: 25.5,
          fill: 'accent',
          opacity: 0,
          keyframes: [
            { atMs: 1600, opacity: 0 },
            { atMs: 2000, opacity: 0.55 },
          ],
        },
        {
          kind: 'circle',
          id: 'nc2',
          cx: 280,
          cy: 120,
          r: 5,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 1600, opacity: 0 },
            { atMs: 2000, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'soi2',
          cx: 280,
          cy: 94.5,
          r: 5,
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 1600, opacity: 0 },
            { atMs: 2000, opacity: 1 },
          ],
        },
        {
          kind: 'rect',
          id: 'long3',
          x: 354,
          y: 46.2,
          w: 12,
          h: 27,
          fill: 'accent',
          opacity: 0,
          keyframes: [
            { atMs: 2250, opacity: 0 },
            { atMs: 2650, opacity: 0.55 },
          ],
        },
        {
          kind: 'circle',
          id: 'nc3',
          cx: 360,
          cy: 73.2,
          r: 5,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 2250, opacity: 0 },
            { atMs: 2650, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'soi3',
          cx: 360,
          cy: 46.2,
          r: 5,
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 2250, opacity: 0 },
            { atMs: 2650, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'cg-nc',
          cx: 70,
          cy: 14,
          r: 4.5,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2,
        },
        { kind: 'circle', id: 'cg-soi', cx: 176, cy: 14, r: 4.5, fill: 'primary' },
        { kind: 'rect', id: 'cg-long', x: 240, y: 8, w: 10, h: 12, fill: 'accent', opacity: 0.55 },
        {
          kind: 'label',
          id: 'vt-200',
          x: 52,
          y: 198,
          text: '−200',
          size: 9,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'vt-100',
          x: 52,
          y: 159.4,
          text: '−100',
          size: 9,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'vt0',
          x: 52,
          y: 120.8,
          text: '0',
          size: 9,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'vt100',
          x: 52,
          y: 82.1,
          text: '100',
          size: 9,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'vt200',
          x: 52,
          y: 43.5,
          text: '200',
          size: 9,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'soit0',
          x: 130,
          y: 193.4,
          text: '−188',
          size: 9,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 300, opacity: 0 },
            { atMs: 700, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'nct0',
          x: 130,
          y: 208.8,
          text: '−220',
          size: 9,
          anchor: 'start',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 300, opacity: 0 },
            { atMs: 700, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'ten0',
          x: 120,
          y: 228,
          text: 'F₂',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'tt0',
          x: 120,
          y: 244,
          text: 'khí',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 3800, opacity: 0 },
            { atMs: 4200, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'soit1',
          x: 210,
          y: 133.9,
          text: '−34',
          size: 9,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 950, opacity: 0 },
            { atMs: 1350, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'nct1',
          x: 210,
          y: 159.8,
          text: '−101',
          size: 9,
          anchor: 'start',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 950, opacity: 0 },
            { atMs: 1350, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'ten1',
          x: 200,
          y: 228,
          text: 'Cl₂',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'tt1',
          x: 200,
          y: 244,
          text: 'khí',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 4200, opacity: 0 },
            { atMs: 4600, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'soit2',
          x: 290,
          y: 98,
          text: '59',
          size: 9,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 1600, opacity: 0 },
            { atMs: 2000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'nct2',
          x: 290,
          y: 123.5,
          text: '−7',
          size: 9,
          anchor: 'start',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 1600, opacity: 0 },
            { atMs: 2000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'ten2',
          x: 280,
          y: 228,
          text: 'Br₂',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'tt2',
          x: 280,
          y: 244,
          text: 'lỏng',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 4600, opacity: 0 },
            { atMs: 5000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'soit3',
          x: 370,
          y: 49.7,
          text: '184',
          size: 9,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 2250, opacity: 0 },
            { atMs: 2650, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'nct3',
          x: 370,
          y: 76.7,
          text: '114',
          size: 9,
          anchor: 'start',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 2250, opacity: 0 },
            { atMs: 2650, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'ten3',
          x: 360,
          y: 228,
          text: 'I₂',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'tt3',
          x: 360,
          y: 244,
          text: 'rắn',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 5000, opacity: 0 },
            { atMs: 5400, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'cg-nct',
          x: 80,
          y: 18,
          text: 'nóng chảy',
          size: 10,
          anchor: 'start',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'cg-soit',
          x: 186,
          y: 18,
          text: 'sôi',
          size: 10,
          anchor: 'start',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'cg-longt',
          x: 256,
          y: 18,
          text: 'khoảng thể lỏng',
          size: 10,
          anchor: 'start',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'dv',
          x: 64,
          y: 40,
          text: '°C',
          size: 10,
          anchor: 'start',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'phongt',
          x: 420,
          y: 102.6,
          text: '25 °C (nhiệt độ thường)',
          size: 10,
          anchor: 'end',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 3000, opacity: 0 },
            { atMs: 3400, opacity: 1 },
          ],
        },
      ],
      captions: [
        {
          atMs: 0,
          text: 'Mỗi cột nối nhiệt độ nóng chảy (chấm rỗng) với nhiệt độ sôi (chấm đặc) — giữa hai mốc là thể lỏng.',
        },
        { atMs: 700, text: 'Từ F₂ tới I₂, cả nhiệt độ nóng chảy lẫn nhiệt độ sôi đều tăng dần.' },
        {
          atMs: 3400,
          text: 'Đường 25 °C: cột nằm dưới đường → khí; đường cắt qua cột → lỏng; cột nằm trên đường → rắn.',
        },
        { atMs: 4200, text: 'Ở nhiệt độ thường: F₂, Cl₂ là khí; Br₂ lỏng; I₂ rắn.' },
        {
          atMs: 5800,
          text: 'Phân tử càng nặng, tương tác van der Waals càng mạnh nên càng khó nóng chảy và khó sôi.',
        },
      ],
    },
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'hoa10-c7-b17',
    grade: '10',
    chapterNumber: 7,
    chapterTitle: 'Nhóm halogen',
    lessonNumber: 17,
    title: 'Hydrogen halide và một số phản ứng của ion halide',
    hook:
      'Acid trong dạ dày (HCl) giúp tiêu hoá thức ăn, nhưng cũng là hydrogen halide — cùng ' +
      'họ hoá chất với acid dùng để khắc kính (HF).',
    theory:
      'HYDROGEN HALIDE (HX, với X = F, Cl, Br, I) là hợp chất giữa hydrogen và halogen, liên ' +
      'kết cộng hoá trị CÓ CỰC (do halogen có độ âm điện lớn hơn hydrogen).\n\n' +
      'Khi tan trong nước, hydrogen halide tạo thành HYDROHALIC ACID (dung dịch acid). Độ ' +
      'mạnh acid tăng dần: HF (acid yếu, do liên kết H-F ngắn và bền) < HCl < HBr < HI (acid ' +
      'mạnh nhất).\n\n' +
      'PHẢN ỨNG NHẬN BIẾT ION HALIDE (Cl⁻, Br⁻, I⁻) bằng dung dịch AgNO₃: tạo kết tủa với ' +
      'màu sắc đặc trưng khác nhau —\n' +
      '— AgCl: kết tủa TRẮNG\n' +
      '— AgBr: kết tủa VÀNG NHẠT\n' +
      '— AgI: kết tủa VÀNG ĐẬM\n' +
      '(F⁻ không tạo kết tủa với Ag⁺ do AgF tan trong nước — đây là ngoại lệ đáng nhớ.)\n\n' +
      'Phản ứng tổng quát: X⁻ + Ag⁺ → AgX↓ (X = Cl, Br, I).',
    workedExample: {
      problem:
        'Có 2 dung dịch không màu đựng riêng biệt: NaCl và NaBr. Nêu cách phân biệt hai dung ' +
        'dịch này bằng một thuốc thử.',
      steps: [
        'Chọn thuốc thử: dung dịch AgNO₃ (bạc nitrate).',
        'Nhỏ AgNO₃ vào từng mẫu thử.',
        'Nếu xuất hiện kết tủa TRẮNG (AgCl) ⇒ mẫu đó là dung dịch NaCl.',
        'Nếu xuất hiện kết tủa VÀNG NHẠT (AgBr) ⇒ mẫu đó là dung dịch NaBr.',
      ],
      answer: 'Dùng AgNO₃: NaCl cho kết tủa trắng (AgCl), NaBr cho kết tủa vàng nhạt (AgBr).',
    },
    checkQuestions: [
      {
        prompt: 'Ion Cl⁻ tạo kết tủa màu gì khi phản ứng với dung dịch AgNO₃?',
        choices: [
          { id: 'trang', label: 'Trắng' },
          { id: 'vangnhat', label: 'Vàng nhạt' },
          { id: 'vangdam', label: 'Vàng đậm' },
        ],
        answer: { kind: 'choice', correctIds: ['trang'] },
        explain:
          'AgCl là kết tủa TRẮNG — dùng để nhận biết ion Cl⁻ (khác với AgBr vàng nhạt, AgI vàng đậm).',
      },
      {
        prompt: 'Trong 4 acid HF, HCl, HBr, HI, acid nào MẠNH NHẤT?',
        choices: [
          { id: 'HF', label: 'HF' },
          { id: 'HI', label: 'HI' },
        ],
        answer: { kind: 'choice', correctIds: ['HI'] },
        explain:
          'Độ mạnh acid tăng dần HF < HCl < HBr < HI — HI mạnh nhất do liên kết H-I dài, dễ phân li H⁺ nhất.',
      },
    ],
    srsCards: [
      { hoi: 'Kết tủa của AgCl có màu gì?', dap: 'Trắng.' },
      { hoi: 'Kết tủa của AgBr có màu gì?', dap: 'Vàng nhạt.' },
      { hoi: 'Ion halide nào KHÔNG tạo kết tủa với Ag⁺?', dap: 'F⁻ (vì AgF tan trong nước).' },
      {
        hoi: 'Độ mạnh acid của các hydrohalic acid tăng theo chiều nào?',
        dap: 'HF < HCl < HBr < HI.',
      },
    ],
    animation: {
      title: 'Nhiệt độ sôi bất thường của HF và trật tự tính acid HF < HCl < HBr < HI',
      description:
        'Đường nét đứt là dự đoán ngây thơ: phân tử càng nhẹ thì sôi càng thấp, nên HF lẽ ra phải nằm thấp nhất, khoảng −100 °C. Đường nét liền là số liệu thật: HCl sôi ở −85 °C, HBr ở −67 °C, HI ở −35 °C đúng như dự đoán, nhưng HF lại vọt lên +19,5 °C — cao hơn cả HI. Lý do hiện ở góc: giữa các phân tử HF có liên kết hydrogen nối F của phân tử này với H của phân tử kia, phải phá thêm lực đó mới bay hơi được. Thanh bên dưới cho thấy tính acid trong dung dịch lại đi theo chiều ngược của mạnh yếu liên kết H–X: HF là acid yếu, còn HCl, HBr, HI đều là acid mạnh và mạnh dần xuống HI.',
      viewBoxWidth: 470,
      viewBoxHeight: 250,
      durationMs: 8000,
      loop: true,
      shapes: [
        {
          kind: 'line',
          id: 'tx',
          x1: 55,
          y1: 175,
          x2: 430,
          y2: 175,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'line',
          id: 'ty',
          x1: 55,
          y1: 175,
          x2: 55,
          y2: 30,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'tyt',
          x: 60,
          y: 28,
          text: 'nhiệt độ sôi (°C)',
          size: 10,
          anchor: 'start',
          fill: 'muted',
        },
        {
          kind: 'polyline',
          id: 'dudoan',
          points: [
            [100, 152],
            [190, 140],
            [280, 125.6],
            [370, 100],
          ],
          stroke: 'muted',
          strokeWidth: 2,
          dash: '5 4',
        },
        {
          kind: 'label',
          id: 'ddt',
          x: 100,
          y: 168,
          text: 'dự đoán',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'polyline',
          id: 'that',
          points: [
            [100, 56],
            [190, 140],
            [280, 125.6],
            [370, 100],
          ],
          stroke: 'primary',
          strokeWidth: 2.5,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 1400, opacity: 0 },
            { atMs: 2400, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'q1',
          cx: 100,
          cy: 56,
          r: 7,
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 1400, opacity: 0 },
            { atMs: 1800, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'q2',
          cx: 190,
          cy: 140,
          r: 7,
          fill: 'primary',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 400,
              opacity: 0,
            },
            {
              atMs: 800,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'q3',
          cx: 280,
          cy: 125.6,
          r: 7,
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 700, opacity: 0 },
            { atMs: 1100, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'q4',
          cx: 370,
          cy: 100,
          r: 7,
          fill: 'primary',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 1000,
              opacity: 0,
            },
            {
              atMs: 1400,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'x1',
          x: 100,
          y: 194,
          text: 'HF',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'x2',
          x: 190,
          y: 194,
          text: 'HCl',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'x3',
          x: 280,
          y: 194,
          text: 'HBr',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'x4',
          x: 370,
          y: 194,
          text: 'HI',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'v1',
          x: 100,
          y: 46,
          text: '+19,5',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 1400, opacity: 0 },
            { atMs: 1800, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'v2',
          x: 198,
          y: 157,
          text: '−85',
          size: 10,
          anchor: 'start',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'v3',
          x: 280,
          y: 117,
          text: '−67',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'v4',
          x: 370,
          y: 92,
          text: '−35',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'lh',
          x: 300,
          y: 50,
          text: 'liên kết hydrogen F···H–F giữ HF lại',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 2600,
              opacity: 0,
            },
            {
              atMs: 3200,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'arrow',
          id: 'acid',
          x1: 100,
          y1: 224,
          x2: 370,
          y2: 224,
          stroke: 'accent',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 4600,
              opacity: 0,
            },
            {
              atMs: 5200,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'acidt',
          x: 235,
          y: 244,
          text: 'tính acid tăng: HF yếu → HCl, HBr, HI mạnh dần',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 4600,
              opacity: 0,
            },
            {
              atMs: 5200,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
      ],
      captions: [
        {
          atMs: 0,
          text: 'HCl, HBr, HI sôi cao dần theo khối lượng phân tử — đúng như dự đoán.',
        },
        {
          atMs: 1400,
          text: 'HF thì vọt lên +19,5 °C, phá vỡ quy luật.',
        },
        {
          atMs: 2600,
          text: 'Nguyên nhân: liên kết hydrogen giữa các phân tử HF, phải phá thêm mới bay hơi.',
        },
        {
          atMs: 4800,
          text: 'Ngược lại về tính acid: HF là acid yếu, HI mạnh nhất trong dãy.',
        },
      ],
    },
    track: 'core',
    reviewStatus: 'draft',
  },
]
