// lessons/hoa12c6.ts — Hoá học 12, Chương 6: Đại cương về kim loại (6 bài).
// Đối chiếu mục lục thật: tai-lieu-sgk/SGK-Hoa/12/page_0005.png (OCR 2026-08-31).
// reviewStatus='draft' — soạn từ docs/research/kho-kien-thuc-hoa-gdpt2018.md §3, chưa duyệt.
import type { ChemLesson } from '../lessonTypes.js'

export const HOA12_C6_LESSONS: ChemLesson[] = [
  {
    id: 'hoa12-c6-b18',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Đại cương về kim loại',
    lessonNumber: 18,
    title: 'Cấu tạo và liên kết trong tinh thể kim loại',
    hook:
      'Vì sao kim loại có thể dát mỏng như lá vàng, kéo sợi dài như dây đồng và dẫn điện tốt đến thế? ' +
      'Bí ẩn nằm ở những "electron tự do" bao quanh các ion dương kim loại.',
    theory:
      'LIÊN KẾT KIM LOẠI:\n' +
      '— Liên kết kim loại là liên kết được hình thành giữa các cation kim loại ở các nút mạng tinh thể và các electron tự do di chuyển hỗn loạn trong toàn bộ mạng tinh thể kim loại.\n\n' +
      'CẤU TRÚC TINH THỂ KIM LOẠI:\n' +
      '— Ở điều kiện thường, hầu hết kim loại ở trạng thái rắn và có cấu trúc tinh thể (riêng thuỷ ngân là chất lỏng).\n' +
      '— Ba kiểu mạng tinh thể kim loại phổ biến:\n' +
      '  1. Mạng lập phương tâm khối (body-centered cubic): Các nguyên tử/ion chiếm các đỉnh và tâm của hình lập phương (độ rỗng lớn, vd: Li, Na, K, Ba, Fe_α).\n' +
      '  2. Mạng lập phương tâm diện (face-centered cubic): Các nguyên tử/ion chiếm các đỉnh và tâm các mặt của hình lập phương (xếp khít hơn, vd: Al, Cu, Ag, Au).\n' +
      '  3. Mạng lục phương (hexagonal close-packed): Các nguyên tử/ion xếp khít nhau dạng lăng trụ lục giác đều (vd: Be, Mg, Zn).',
    workedExample: {
      problem:
        'Giải thích vì sao kim loại có tính dẻo, dễ rèn, dát mỏng và kéo sợi mà không bị vỡ vụn.',
      steps: [
        'Mạng tinh thể kim loại gồm các cation kim loại nằm cố định tại các nút mạng và dòng electron tự do di chuyển xung quanh.',
        'Khi chịu tác dụng của lực cơ học bên ngoài, các lớp mạng tinh thể kim loại trượt lên nhau.',
        'Sự trượt này không làm phá vỡ liên kết vì các electron tự do giống như một chất bôi trơn kết dính, liên tục di chuyển và giữ các cation kim loại lại với nhau.',
        'Kết quả: kim loại chỉ bị biến dạng (móp, dát mỏng) chứ không bị vỡ vụn như tinh thể muối ăn (liên kết ion).',
      ],
      answer: 'Do các electron tự do liên kết các lớp cation trượt lên nhau',
    },
    checkQuestions: [
      {
        prompt:
          'Liên kết kim loại được hình thành nhờ lực hút tĩnh điện giữa các cation kim loại với thành phần nào?',
        choices: [
          { id: 'anion', label: 'Các anion phi kim' },
          { id: 'electron', label: 'Các electron tự do' },
          { id: 'hatnhan', label: 'Hạt nhân nguyên tử bên cạnh' },
        ],
        answer: { kind: 'choice', correctIds: ['electron'] },
        explain:
          'Liên kết kim loại là lực hút tĩnh điện giữa các cation kim loại ở nút mạng và đám mây electron tự do di chuyển xung quanh.',
      },
      {
        prompt: 'Kiểu mạng tinh thể nào sau đây có cấu trúc rỗng nhất (độ xếp khít nhỏ nhất)?',
        choices: [
          { id: 'tamkhoi', label: 'Mạng lập phương tâm khối' },
          { id: 'tamdien', label: 'Mạng lập phương tâm diện' },
          { id: 'lucphuong', label: 'Mạng lục phương' },
        ],
        answer: { kind: 'choice', correctIds: ['tamkhoi'] },
        explain:
          'Mạng lập phương tâm khối chỉ lấp đầy khoảng 68% thể tích, nên rỗng nhất. Hai kiểu còn lại là lập phương tâm diện và lục phương đều thuộc nhóm xếp khít, cùng lấp đầy khoảng 74% thể tích.',
      },
    ],
    srsCards: [
      {
        hoi: 'Liên kết kim loại là gì?',
        dap: 'Liên kết hình thành bởi lực hút giữa các cation kim loại ở nút mạng với các electron tự do.',
      },
      { hoi: 'Kim loại duy nhất ở thể lỏng ở điều kiện thường?', dap: 'Thuỷ ngân (Hg).' },
      {
        hoi: 'Ba kiểu mạng tinh thể kim loại phổ biến?',
        dap: 'Lập phương tâm khối, lập phương tâm diện, và lục phương.',
      },
    ],
    animation: {
      title: 'Mạng tinh thể kim loại và biển electron tự do',
      description:
        'Các ion dương kim loại xếp đều đặn thành mạng, ở đây vẽ một ô lập phương tâm khối: tám ion ở tám đỉnh và một ion ở đúng tâm khối. Mỗi vị trí mạng là một ion dương chứ không phải nguyên tử trung hoà, vì các electron hoá trị đã rời khỏi nguyên tử của mình. Những chấm nhỏ chạy len lỏi khắp các khoảng trống chính là các electron đó: chúng không thuộc về ion nào riêng mà di chuyển tự do trong toàn khối — người ta gọi là biển electron. Liên kết kim loại chính là lực hút giữa biển electron chung này với tất cả các ion dương. Cách sắp xếp ấy giải thích trọn gói mọi tính chất của kim loại: electron chạy được nên kim loại dẫn điện và dẫn nhiệt, phản xạ ánh sáng nên có ánh kim, và các lớp ion trượt được lên nhau nên kim loại dẻo.',
      viewBoxWidth: 460,
      viewBoxHeight: 240,
      durationMs: 8000,
      loop: true,
      shapes: [
        {
          kind: 'rect',
          id: 'o1',
          x: 70,
          y: 60,
          w: 110,
          h: 110,
          stroke: 'muted',
          strokeWidth: 1.5,
          dash: '4 3',
        },
        {
          kind: 'rect',
          id: 'o2',
          x: 110,
          y: 36,
          w: 110,
          h: 110,
          stroke: 'muted',
          strokeWidth: 1.5,
          dash: '4 3',
        },
        {
          kind: 'line',
          id: 'k1',
          x1: 70,
          y1: 60,
          x2: 110,
          y2: 36,
          stroke: 'muted',
          strokeWidth: 1.5,
          dash: '4 3',
        },
        {
          kind: 'line',
          id: 'k2',
          x1: 180,
          y1: 60,
          x2: 220,
          y2: 36,
          stroke: 'muted',
          strokeWidth: 1.5,
          dash: '4 3',
        },
        {
          kind: 'line',
          id: 'k3',
          x1: 70,
          y1: 170,
          x2: 110,
          y2: 146,
          stroke: 'muted',
          strokeWidth: 1.5,
          dash: '4 3',
        },
        {
          kind: 'line',
          id: 'k4',
          x1: 180,
          y1: 170,
          x2: 220,
          y2: 146,
          stroke: 'muted',
          strokeWidth: 1.5,
          dash: '4 3',
        },
        {
          kind: 'circle',
          id: 'i1',
          cx: 70,
          cy: 60,
          r: 10,
          fill: 'primary',
        },
        {
          kind: 'circle',
          id: 'i2',
          cx: 180,
          cy: 60,
          r: 10,
          fill: 'primary',
        },
        {
          kind: 'circle',
          id: 'i3',
          cx: 70,
          cy: 170,
          r: 10,
          fill: 'primary',
        },
        {
          kind: 'circle',
          id: 'i4',
          cx: 180,
          cy: 170,
          r: 10,
          fill: 'primary',
        },
        {
          kind: 'circle',
          id: 'i5',
          cx: 110,
          cy: 36,
          r: 10,
          fill: 'primary',
        },
        {
          kind: 'circle',
          id: 'i6',
          cx: 220,
          cy: 36,
          r: 10,
          fill: 'primary',
        },
        {
          kind: 'circle',
          id: 'i7',
          cx: 110,
          cy: 146,
          r: 10,
          fill: 'primary',
        },
        {
          kind: 'circle',
          id: 'i8',
          cx: 220,
          cy: 146,
          r: 10,
          fill: 'primary',
        },
        {
          kind: 'circle',
          id: 'i9',
          cx: 145,
          cy: 103,
          r: 11,
          fill: 'primary',
        },
        {
          kind: 'label',
          id: 'i1-dau',
          x: 70,
          y: 64,
          text: '+',
          size: 12,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'i2-dau',
          x: 180,
          y: 64,
          text: '+',
          size: 12,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'i3-dau',
          x: 70,
          y: 174,
          text: '+',
          size: 12,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'i4-dau',
          x: 180,
          y: 174,
          text: '+',
          size: 12,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'i5-dau',
          x: 110,
          y: 40,
          text: '+',
          size: 12,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'i6-dau',
          x: 220,
          y: 40,
          text: '+',
          size: 12,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'i7-dau',
          x: 110,
          y: 150,
          text: '+',
          size: 12,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'i8-dau',
          x: 220,
          y: 150,
          text: '+',
          size: 12,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'i9-dau',
          x: 145,
          y: 107,
          text: '+',
          size: 12,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'iont',
          x: 145,
          y: 200,
          text: 'ion dương ở nút mạng (lập phương tâm khối)',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'circle',
          id: 'e1',
          cx: 100,
          cy: 90,
          r: 4.5,
          fill: 'accent',
          keyframes: [
            {
              atMs: 0,
              dx: 0,
              dy: 0,
            },
            {
              atMs: 2000,
              dx: 60,
              dy: 26,
            },
            {
              atMs: 4000,
              dx: 20,
              dy: 66,
            },
            {
              atMs: 6000,
              dx: 80,
              dy: -20,
            },
            {
              atMs: 8000,
              dx: 0,
              dy: 0,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'e2',
          cx: 160,
          cy: 130,
          r: 4.5,
          fill: 'accent',
          keyframes: [
            {
              atMs: 0,
              dx: 0,
              dy: 0,
            },
            {
              atMs: 2400,
              dx: -50,
              dy: -40,
            },
            {
              atMs: 4800,
              dx: 30,
              dy: -70,
            },
            {
              atMs: 8000,
              dx: 0,
              dy: 0,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'e3',
          cx: 130,
          cy: 70,
          r: 4.5,
          fill: 'accent',
          keyframes: [
            {
              atMs: 0,
              dx: 0,
              dy: 0,
            },
            {
              atMs: 1800,
              dx: 50,
              dy: 60,
            },
            {
              atMs: 4200,
              dx: -40,
              dy: 40,
            },
            {
              atMs: 6400,
              dx: 10,
              dy: -20,
            },
            {
              atMs: 8000,
              dx: 0,
              dy: 0,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'e4',
          cx: 190,
          cy: 100,
          r: 4.5,
          fill: 'accent',
          keyframes: [
            {
              atMs: 0,
              dx: 0,
              dy: 0,
            },
            {
              atMs: 2200,
              dx: -70,
              dy: 30,
            },
            {
              atMs: 5000,
              dx: -20,
              dy: -50,
            },
            {
              atMs: 8000,
              dx: 0,
              dy: 0,
            },
          ],
        },
        {
          kind: 'label',
          id: 'et',
          x: 145,
          y: 220,
          text: 'electron tự do chạy khắp khối — biển electron',
          size: 11,
          anchor: 'middle',
          fill: 'accent',
        },
        {
          kind: 'label',
          id: 'h1',
          x: 300,
          y: 70,
          text: 'Electron chạy được',
          size: 11,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 2000,
              opacity: 0,
            },
            {
              atMs: 2500,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'h1b',
          x: 310,
          y: 90,
          text: '→ dẫn điện, dẫn nhiệt',
          size: 11,
          anchor: 'start',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 2000,
              opacity: 0,
            },
            {
              atMs: 2500,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'h2',
          x: 300,
          y: 120,
          text: 'Electron phản xạ ánh sáng',
          size: 11,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 3600,
              opacity: 0,
            },
            {
              atMs: 4100,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'h2b',
          x: 310,
          y: 140,
          text: '→ có ánh kim',
          size: 11,
          anchor: 'start',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 3600,
              opacity: 0,
            },
            {
              atMs: 4100,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'h3',
          x: 300,
          y: 170,
          text: 'Các lớp ion trượt được',
          size: 11,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 5200,
              opacity: 0,
            },
            {
              atMs: 5700,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'h3b',
          x: 310,
          y: 190,
          text: '→ dẻo, dát mỏng được',
          size: 11,
          anchor: 'start',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 5200,
              opacity: 0,
            },
            {
              atMs: 5700,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
      ],
      captions: [
        {
          atMs: 0,
          text: 'Nút mạng là các ion dương, không phải nguyên tử trung hoà.',
        },
        {
          atMs: 1600,
          text: 'Electron hoá trị tách ra, chạy tự do khắp khối: biển electron.',
        },
        {
          atMs: 3600,
          text: 'Liên kết kim loại = lực hút giữa biển electron chung và mọi ion dương.',
        },
        {
          atMs: 5200,
          text: 'Từ mô hình này suy ra đủ tính dẫn điện, ánh kim và tính dẻo.',
        },
      ],
    },
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'hoa12-c6-b19',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Đại cương về kim loại',
    lessonNumber: 19,
    title: 'Tính chất vật lí và tính chất hoá học của kim loại',
    hook:
      'Đồng dẫn điện tốt, vàng óng ánh sang trọng, sắt cứng cáp làm khung nhà. ' +
      'Các electron tự do không chỉ liên kết mạng tinh thể mà còn quyết định các tính chất vật lí kỳ diệu của kim loại.',
    theory:
      'TÍNH CHẤT VẬT LÍ CHUNG (Do electron tự do gây ra):\n' +
      '— Tính dẻo: Vàng (Au) dẻo nhất (có thể dát mỏng đến mức ánh sáng đi qua được).\n' +
      '— Tính dẫn điện: Ag > Cu > Au > Al > Fe. Nhiệt độ càng tăng thì tính dẫn điện càng giảm (do mạng tinh thể dao động mạnh cản trở electron di chuyển).\n' +
      '— Tính dẫn nhiệt: cũng do electron tự do đảm nhận, nên kim loại dẫn điện tốt thì thường cũng dẫn nhiệt tốt (thứ tự gần như trùng nhau).\n' +
      '— Ánh kim: Phản xạ hầu hết ánh sáng nhìn thấy.\n\n' +
      'TÍNH CHẤT VẬT LÍ RIÊNG (Do nguyên tử và mạng tinh thể quyết định):\n' +
      '— Khối lượng riêng: Nhỏ nhất là Li (0,5 g/cm³), lớn nhất là Os (22,6 g/cm³).\n' +
      '— Nhiệt độ nóng chảy: Thấp nhất là Hg (−39 °C), cao nhất là W (Tungsten, 3410 °C - làm dây tóc bóng đèn).\n' +
      '— Độ cứng: Mềm nhất là Cs (có thể cắt bằng dao), cứng nhất là Cr (Chromium - rạch được thuỷ tinh).\n\n' +
      'TÍNH CHẤT HOÁ HỌC CHUNG:\n' +
      '— Kim loại có tính KHỬ đặc trưng (dễ nhường electron để tạo cation): M → Mⁿ⁺ + ne.\n' +
      '— Phản ứng đặc trưng: Tác dụng với phi kim (O₂, Cl₂, S); tác dụng với dung dịch acid (HCl, H₂SO₄ loãng giải phóng H₂; HNO₃, H₂SO₄ đặc tạo sản phẩm khử); tác dụng với nước (kim loại kiềm/kiềm thổ); tác dụng với muối của kim loại yếu hơn (thế kim loại).',
    workedExample: {
      problem: 'Sắp xếp khả năng dẫn điện giảm dần của các kim loại sau: Al, Ag, Cu, Fe.',
      steps: [
        'Khả năng dẫn điện của kim loại phụ thuộc vào mật độ electron tự do và cấu trúc tinh thể.',
        'Thứ tự dẫn điện giảm dần chuẩn xác của các kim loại phổ biến là: Bạc (Ag) > Đồng (Cu) > Vàng (Au) > Nhôm (Al) > Sắt (Fe).',
        'Áp dụng vào các kim loại đề bài cho: Ag > Cu > Al > Fe.',
      ],
      answer: 'Ag > Cu > Al > Fe',
    },
    checkQuestions: [
      {
        prompt: 'Kim loại nào sau đây dẫn điện tốt nhất ở điều kiện thường?',
        choices: [
          { id: 'cu', label: 'Copper (Cu)' },
          { id: 'al', label: 'Aluminium (Al)' },
          { id: 'ag', label: 'Silver (Ag)' },
          { id: 'fe', label: 'Iron (Fe)' },
        ],
        answer: { kind: 'choice', correctIds: ['ag'] },
        explain: 'Bạc (Ag) là kim loại dẫn điện và dẫn nhiệt tốt nhất, tiếp theo là Đồng (Cu).',
      },
      {
        prompt:
          'Kim loại có độ cứng lớn nhất (rạch được thuỷ tinh) dùng làm thành phần thép không gỉ là kim loại nào?',
        choices: [
          { id: 'fe', label: 'Iron (Fe)' },
          { id: 'cr', label: 'Chromium (Cr)' },
          { id: 'w', label: 'Tungsten (W)' },
        ],
        answer: { kind: 'choice', correctIds: ['cr'] },
        explain:
          'Chromium (Cr) là kim loại cứng nhất, khoảng 8,5 trên thang Mohs (thang 10 bậc), nên rạch được thuỷ tinh. Iron mềm hơn nhiều; tungsten nổi bật ở nhiệt độ nóng chảy cao nhất chứ không phải ở độ cứng.',
      },
    ],
    srsCards: [
      {
        hoi: 'Bốn tính chất vật lí chung của kim loại?',
        dap: 'Tính dẻo, dẫn điện, dẫn nhiệt, và ánh kim.',
      },
      {
        hoi: 'Nguyên nhân gây ra tính chất vật lí chung của kim loại?',
        dap: 'Do các electron tự do trong mạng tinh thể kim loại gây ra.',
      },
      {
        hoi: 'Kim loại có nhiệt độ nóng chảy cao nhất dùng làm dây tóc bóng đèn?',
        dap: 'Tungsten (W).',
      },
    ],
    animation: {
      title: 'Vì sao kim loại dát mỏng được còn tinh thể muối thì vỡ vụn',
      description:
        'Hai khối tinh thể cùng chịu một cú gõ làm lớp trên trượt sang đúng một ô. Bên trái là kim loại: các ion dương (dấu +) nằm chìm trong biển electron chung (vùng tô nhạt và các chấm). Lớp trên trượt thì biển electron trượt theo và vẫn gắn lớp trên với lớp dưới, nên khối chỉ biến dạng chứ không tách ra — kim loại dát mỏng, kéo sợi được. Bên phải là tinh thể ion như NaCl: ion dương (+) và ion âm (−) xếp xen kẽ. Trượt một ô xong, các ion cùng dấu nằm ngay đối diện nhau, lực hút thành lực đẩy, hai lớp bật ra và tinh thể nứt theo đúng mặt phẳng đó. Khác biệt nằm ở chỗ: biển electron không gắn với vị trí nào nên trượt tới đâu liên kết vẫn còn, còn mỗi ion chỉ bền khi quanh nó là các ion trái dấu.',
      viewBoxWidth: 470,
      viewBoxHeight: 240,
      durationMs: 8000,
      loop: true,
      shapes: [
        {
          kind: 'rect',
          id: 'bien-duoi',
          x: 46,
          y: 103,
          w: 120,
          h: 35,
          fill: 'accent',
          opacity: 0.22,
        },
        {
          kind: 'rect',
          id: 'bien-tren',
          x: 46,
          y: 68,
          w: 120,
          h: 35,
          fill: 'accent',
          opacity: 0.22,
          keyframes: [
            { atMs: 2200, dx: 0, dy: 0 },
            { atMs: 4000, dx: 40 },
          ],
        },
        {
          kind: 'arrow',
          id: 'luc1',
          x1: 118,
          y1: 26,
          x2: 118,
          y2: 58,
          stroke: 'accent',
          strokeWidth: 2.5,
          keyframes: [
            { atMs: 4000, opacity: 1 },
            { atMs: 4400, opacity: 0 },
          ],
        },
        {
          kind: 'line',
          id: 'chia',
          x1: 236,
          y1: 40,
          x2: 236,
          y2: 224,
          stroke: 'muted',
          strokeWidth: 1.5,
          dash: '5 5',
        },
        {
          kind: 'arrow',
          id: 'luc2',
          x1: 352,
          y1: 26,
          x2: 352,
          y2: 58,
          stroke: 'accent',
          strokeWidth: 2.5,
          keyframes: [
            { atMs: 4000, opacity: 1 },
            { atMs: 4400, opacity: 0 },
          ],
        },
        {
          kind: 'line',
          id: 'nut',
          x1: 270,
          y1: 94,
          x2: 440,
          y2: 94,
          stroke: 'danger',
          strokeWidth: 2.5,
          dash: '6 4',
          opacity: 0,
          keyframes: [
            { atMs: 5300, opacity: 0 },
            { atMs: 5600, opacity: 1 },
          ],
        },
        {
          kind: 'circle',
          id: 'ma1',
          cx: 66,
          cy: 84,
          r: 12,
          fill: 'primary',
          keyframes: [
            { atMs: 2200, dx: 0, dy: 0 },
            { atMs: 4000, dx: 40 },
          ],
        },
        { kind: 'circle', id: 'mb1', cx: 66, cy: 122, r: 12, fill: 'primary' },
        {
          kind: 'circle',
          id: 'ma2',
          cx: 106,
          cy: 84,
          r: 12,
          fill: 'primary',
          keyframes: [
            { atMs: 2200, dx: 0, dy: 0 },
            { atMs: 4000, dx: 40 },
          ],
        },
        { kind: 'circle', id: 'mb2', cx: 106, cy: 122, r: 12, fill: 'primary' },
        {
          kind: 'circle',
          id: 'ma3',
          cx: 146,
          cy: 84,
          r: 12,
          fill: 'primary',
          keyframes: [
            { atMs: 2200, dx: 0, dy: 0 },
            { atMs: 4000, dx: 40 },
          ],
        },
        { kind: 'circle', id: 'mb3', cx: 146, cy: 122, r: 12, fill: 'primary' },
        {
          kind: 'circle',
          id: 'me1',
          cx: 86,
          cy: 103,
          r: 3.5,
          fill: 'accent',
          keyframes: [
            { atMs: 2200, dx: 0 },
            { atMs: 4000, dx: 20 },
          ],
        },
        {
          kind: 'circle',
          id: 'me2',
          cx: 106,
          cy: 103,
          r: 3.5,
          fill: 'accent',
          keyframes: [
            { atMs: 2200, dx: 0 },
            { atMs: 4000, dx: 20 },
          ],
        },
        {
          kind: 'circle',
          id: 'me3',
          cx: 126,
          cy: 103,
          r: 3.5,
          fill: 'accent',
          keyframes: [
            { atMs: 2200, dx: 0 },
            { atMs: 4000, dx: 20 },
          ],
        },
        {
          kind: 'circle',
          id: 'ia1',
          cx: 300,
          cy: 84,
          r: 12,
          fill: 'primary',
          keyframes: [
            { atMs: 2200, dx: 0, dy: 0 },
            { atMs: 4000, dx: 40 },
            { atMs: 5000, dy: 0 },
            { atMs: 5600, dy: -18 },
          ],
        },
        {
          kind: 'circle',
          id: 'ia2',
          cx: 340,
          cy: 84,
          r: 12,
          fill: 'muted',
          keyframes: [
            { atMs: 2200, dx: 0, dy: 0 },
            { atMs: 4000, dx: 40 },
            { atMs: 5000, dy: 0 },
            { atMs: 5600, dy: -18 },
          ],
        },
        {
          kind: 'circle',
          id: 'ia3',
          cx: 380,
          cy: 84,
          r: 12,
          fill: 'primary',
          keyframes: [
            { atMs: 2200, dx: 0, dy: 0 },
            { atMs: 4000, dx: 40 },
            { atMs: 5000, dy: 0 },
            { atMs: 5600, dy: -18 },
          ],
        },
        { kind: 'circle', id: 'ib1', cx: 300, cy: 122, r: 12, fill: 'muted' },
        { kind: 'circle', id: 'ib2', cx: 340, cy: 122, r: 12, fill: 'primary' },
        { kind: 'circle', id: 'ib3', cx: 380, cy: 122, r: 12, fill: 'muted' },
        {
          kind: 'arrow',
          id: 'day-len340',
          x1: 340,
          y1: 70,
          x2: 340,
          y2: 54,
          stroke: 'danger',
          strokeWidth: 1.5,
          opacity: 0,
          keyframes: [
            { atMs: 4100, dy: 0, opacity: 0 },
            { atMs: 4400, opacity: 1 },
            { atMs: 5000, dy: 0 },
            { atMs: 5600, dy: -18 },
          ],
        },
        {
          kind: 'arrow',
          id: 'day-xuong340',
          x1: 340,
          y1: 136,
          x2: 340,
          y2: 152,
          stroke: 'danger',
          strokeWidth: 1.5,
          opacity: 0,
          keyframes: [
            { atMs: 4100, opacity: 0 },
            { atMs: 4400, opacity: 1 },
          ],
        },
        {
          kind: 'arrow',
          id: 'day-len380',
          x1: 380,
          y1: 70,
          x2: 380,
          y2: 54,
          stroke: 'danger',
          strokeWidth: 1.5,
          opacity: 0,
          keyframes: [
            { atMs: 4100, dy: 0, opacity: 0 },
            { atMs: 4400, opacity: 1 },
            { atMs: 5000, dy: 0 },
            { atMs: 5600, dy: -18 },
          ],
        },
        {
          kind: 'arrow',
          id: 'day-xuong380',
          x1: 380,
          y1: 136,
          x2: 380,
          y2: 152,
          stroke: 'danger',
          strokeWidth: 1.5,
          opacity: 0,
          keyframes: [
            { atMs: 4100, opacity: 0 },
            { atMs: 4400, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'ma1-d',
          x: 66,
          y: 88.5,
          text: '+',
          size: 14,
          anchor: 'middle',
          fill: 'surface',
          keyframes: [
            { atMs: 2200, dx: 0, dy: 0 },
            { atMs: 4000, dx: 40 },
          ],
        },
        {
          kind: 'label',
          id: 'mb1-d',
          x: 66,
          y: 126.5,
          text: '+',
          size: 14,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'ma2-d',
          x: 106,
          y: 88.5,
          text: '+',
          size: 14,
          anchor: 'middle',
          fill: 'surface',
          keyframes: [
            { atMs: 2200, dx: 0, dy: 0 },
            { atMs: 4000, dx: 40 },
          ],
        },
        {
          kind: 'label',
          id: 'mb2-d',
          x: 106,
          y: 126.5,
          text: '+',
          size: 14,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'ma3-d',
          x: 146,
          y: 88.5,
          text: '+',
          size: 14,
          anchor: 'middle',
          fill: 'surface',
          keyframes: [
            { atMs: 2200, dx: 0, dy: 0 },
            { atMs: 4000, dx: 40 },
          ],
        },
        {
          kind: 'label',
          id: 'mb3-d',
          x: 146,
          y: 126.5,
          text: '+',
          size: 14,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'ia1-d',
          x: 300,
          y: 88.5,
          text: '+',
          size: 14,
          anchor: 'middle',
          fill: 'surface',
          keyframes: [
            { atMs: 2200, dx: 0, dy: 0 },
            { atMs: 4000, dx: 40 },
            { atMs: 5000, dy: 0 },
            { atMs: 5600, dy: -18 },
          ],
        },
        {
          kind: 'label',
          id: 'ia2-d',
          x: 340,
          y: 88.5,
          text: '−',
          size: 14,
          anchor: 'middle',
          fill: 'surface',
          keyframes: [
            { atMs: 2200, dx: 0, dy: 0 },
            { atMs: 4000, dx: 40 },
            { atMs: 5000, dy: 0 },
            { atMs: 5600, dy: -18 },
          ],
        },
        {
          kind: 'label',
          id: 'ia3-d',
          x: 380,
          y: 88.5,
          text: '+',
          size: 14,
          anchor: 'middle',
          fill: 'surface',
          keyframes: [
            { atMs: 2200, dx: 0, dy: 0 },
            { atMs: 4000, dx: 40 },
            { atMs: 5000, dy: 0 },
            { atMs: 5600, dy: -18 },
          ],
        },
        {
          kind: 'label',
          id: 'ib1-d',
          x: 300,
          y: 126.5,
          text: '−',
          size: 14,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'ib2-d',
          x: 340,
          y: 126.5,
          text: '+',
          size: 14,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'ib3-d',
          x: 380,
          y: 126.5,
          text: '−',
          size: 14,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'luc1t',
          x: 118,
          y: 20,
          text: 'lực gõ',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
          keyframes: [
            { atMs: 4000, opacity: 1 },
            { atMs: 4400, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'luc2t',
          x: 352,
          y: 20,
          text: 'lực gõ',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
          keyframes: [
            { atMs: 4000, opacity: 1 },
            { atMs: 4400, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'mt',
          x: 118,
          y: 172,
          text: 'Kim loại: biển electron trượt theo',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 4300, opacity: 0 },
            { atMs: 4600, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'mt2',
          x: 118,
          y: 190,
          text: 'liên kết vẫn giữ — chỉ biến dạng',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 4300, opacity: 0 },
            { atMs: 4600, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'mt3',
          x: 118,
          y: 214,
          text: 'dát mỏng, kéo sợi được',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 5300, opacity: 0 },
            { atMs: 5600, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'it',
          x: 352,
          y: 172,
          text: 'Tinh thể ion: ion cùng dấu đối diện',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 4300, opacity: 0 },
            { atMs: 4600, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'it2',
          x: 352,
          y: 190,
          text: 'lực hút thành lực đẩy',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 4300, opacity: 0 },
            { atMs: 4600, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'it3',
          x: 352,
          y: 214,
          text: 'tinh thể nứt và vỡ vụn',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 5300, opacity: 0 },
            { atMs: 5600, opacity: 1 },
          ],
        },
      ],
      captions: [
        { atMs: 0, text: 'Cùng một cú gõ tác dụng lên khối kim loại và khối tinh thể ion.' },
        { atMs: 2200, text: 'Lực gõ làm lớp ion phía trên trượt sang đúng một ô.' },
        {
          atMs: 4000,
          text: 'Kim loại: biển electron trượt theo, vẫn gắn lớp trên với lớp dưới — khối chỉ biến dạng.',
        },
        { atMs: 4400, text: 'Tinh thể ion: ion cùng dấu nằm đối diện nhau và đẩy nhau.' },
        { atMs: 5600, text: 'Lực đẩy tách hai lớp — tinh thể nứt vỡ. Kim loại dẻo, muối giòn.' },
      ],
    },
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'hoa12-c6-b20',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Đại cương về kim loại',
    lessonNumber: 20,
    title: 'Kim loại trong tự nhiên và phương pháp tách kim loại',
    hook:
      'Trong vỏ Trái Đất, hầu hết kim loại nằm sẵn trong quặng dưới dạng hợp chất oxide hoặc sulfide. ' +
      'Muốn có kim loại để dùng, con người phải tách nó ra khỏi hợp chất — đó là công việc của ngành luyện kim.',
    theory:
      'TRẠNG THÁI TỰ NHIÊN:\n' +
      '— Hầu hết kim loại tồn tại dưới dạng hợp chất (quặng bauxite Al₂O₃, quặng hematite Fe₂O₃, quặng pyrite FeS₂...). Chỉ một số ít kim loại có tính khử rất yếu mới tồn tại ở dạng đơn chất trong tự nhiên (như Au, Pt).\n\n' +
      'PHƯƠNG PHÁP TÁCH (ĐIỀU CHẾ KIM LOẠI):\n' +
      'Nguyên tắc chung: Khử ion kim loại thành nguyên tử: Mⁿ⁺ + ne → M.\n' +
      '1. Phương pháp thuỷ luyện (Hydrometallurgy):\n' +
      '   — Dùng kim loại mạnh đẩy kim loại yếu ra khỏi dung dịch muối (điều chế kim loại hoạt động yếu như Cu, Ag, Au).\n' +
      '   — Ví dụ: Fe + CuSO₄ → FeSO₄ + Cu.\n' +
      '2. Phương pháp nhiệt luyện (Pyrometallurgy):\n' +
      '   — Dùng chất khử mạnh như CO, C, H₂, Al để khử ion kim loại trong oxide ở nhiệt độ cao (điều chế kim loại hoạt động trung bình như Fe, Cr, Zn, Cu).\n' +
      '   — Ví dụ: Fe₂O₃ + 3CO → 2Fe + 3CO₂ (t°).\n' +
      '3. Phương pháp điện phân (Electrolysis):\n' +
      '   — Điện phân nóng chảy: Điều chế các kim loại có tính khử rất mạnh (nhóm IA, IIA, Al) từ muối chloride hoặc oxide nóng chảy.\n' +
      '   — Điện phân dung dịch: Điều chế kim loại trung bình và yếu.',
    workedExample: {
      problem:
        'Cần dùng bao nhiêu lít khí CO (ở điều kiện chuẩn: 25 °C, 1 bar, thể tích mol 24,79 L/mol) ' +
        'để khử hoàn toàn 8,0 gam oxide sắt Fe₂O₃ (M = 160) thành kim loại sắt Fe?',
      steps: [
        'Tính số mol Fe₂O₃: n = 8,0 / 160 = 0,05 mol.',
        'Viết phương trình phản ứng nhiệt luyện: Fe₂O₃ + 3CO → 2Fe + 3CO₂ (t°).',
        'Theo tỉ lệ phản ứng, 1 mol Fe₂O₃ cần 3 mol CO để phản ứng.',
        'Tính số mol khí CO cần dùng: nCO = 3 * n(Fe₂O₃) = 3 * 0,05 = 0,15 mol.',
        'Tính thể tích khí CO ở đkc: V = nCO * 24,79 = 0,15 * 24,79 = 3,7185 L.',
      ],
      answer: '3,7185 L',
    },
    checkQuestions: [
      {
        prompt: 'Nguyên tắc chung của quá trình điều chế kim loại là gì?',
        choices: [
          { id: 'oxi', label: 'Oxi hoá nguyên tử kim loại thành ion' },
          { id: 'khu', label: 'Khử ion kim loại trong hợp chất thành nguyên tử tự do' },
          { id: 'trunghoa', label: 'Trung hoà điện tích ion kim loại' },
        ],
        answer: { kind: 'choice', correctIds: ['khu'] },
        explain:
          'Điều chế kim loại là quá trình khử ion kim loại (Mⁿ⁺) bằng cách cho nó nhận electron để trở thành nguyên tử tự do (M).',
      },
      {
        prompt:
          'Để điều chế kim loại kiềm Sodium (Na) trong công nghiệp, người ta dùng phương pháp nào?',
        choices: [
          { id: 'nhiet', label: 'Nhiệt luyện quặng oxide' },
          { id: 'thuy', label: 'Thuỷ luyện muối chloride' },
          { id: 'dien_nongchay', label: 'Điện phân nóng chảy muối NaCl' },
        ],
        answer: { kind: 'choice', correctIds: ['dien_nongchay'] },
        explain:
          'Sodium là kim loại kiềm hoạt động hoá học cực mạnh, ion Na⁺ rất khó bị khử. Cách duy nhất trong công nghiệp là điện phân nóng chảy muối chloride NaCl.',
      },
    ],
    srsCards: [
      {
        hoi: 'Nguyên tắc điều chế kim loại?',
        dap: 'Khử ion kim loại thành nguyên tử tự do (Mⁿ⁺ + ne → M).',
      },
      {
        hoi: 'Phương pháp nhiệt luyện dùng chất khử nào ở nhiệt độ cao?',
        dap: 'Các chất khử mạnh như C, CO, H₂, Al.',
      },
      {
        hoi: 'Phương pháp thuỷ luyện dùng cho kim loại nào?',
        dap: 'Kim loại hoạt động yếu (Cu, Ag, Au...).',
      },
    ],
    animation: {
      title: 'Dãy hoạt động hoá học chọn phương pháp tách kim loại',
      description:
        'Một trục ngang xếp các kim loại theo chiều giảm dần tính khử, từ K, Na, Mg, Al bên trái tới Zn, Fe, Cu ở giữa và Hg, Ag bên phải. Con trỏ chạy dọc trục và mỗi lần dừng lại thì vùng tương ứng sáng lên cùng phương pháp tách phù hợp. Vùng trái: hợp chất của các kim loại mạnh này rất bền, không chất khử thông thường nào giật nổi oxygen ra, phải dùng điện phân nóng chảy — nhôm được tách từ Al₂O₃ nóng chảy trong cryolite. Vùng giữa: oxide kim loại trung bình bị khử bằng CO, C hoặc H₂ ở nhiệt độ cao, đây là phương pháp nhiệt luyện dùng trong lò cao luyện gang. Vùng phải: kim loại yếu chỉ cần đốt nóng quặng hoặc dùng kim loại mạnh hơn đẩy ra khỏi dung dịch muối. Kim loại càng hoạt động thì càng tốn năng lượng để tách ra khỏi hợp chất.',
      viewBoxWidth: 470,
      viewBoxHeight: 230,
      durationMs: 9000,
      loop: true,
      shapes: [
        {
          kind: 'arrow',
          id: 'truc',
          x1: 40,
          y1: 70,
          x2: 440,
          y2: 70,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'k1',
          x: 70,
          y: 56,
          text: 'K',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'k2',
          x: 110,
          y: 56,
          text: 'Na',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'k3',
          x: 150,
          y: 56,
          text: 'Mg',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'k4',
          x: 190,
          y: 56,
          text: 'Al',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'k5',
          x: 240,
          y: 56,
          text: 'Zn',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'k6',
          x: 280,
          y: 56,
          text: 'Fe',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'k7',
          x: 320,
          y: 56,
          text: 'Cu',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'k8',
          x: 370,
          y: 56,
          text: 'Hg',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'k9',
          x: 410,
          y: 56,
          text: 'Ag',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'truct',
          x: 235,
          y: 32,
          text: 'tính khử giảm dần →',
          size: 11,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'rect',
          id: 'v1',
          x: 50,
          y: 92,
          w: 160,
          h: 46,
          fill: 'primary',
          rx: 4,
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 600,
              opacity: 0.22,
            },
            {
              atMs: 9000,
              opacity: 0.22,
            },
          ],
        },
        {
          kind: 'label',
          id: 'v1t',
          x: 130,
          y: 112,
          text: 'Điện phân nóng chảy',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 600,
              opacity: 0,
            },
            {
              atMs: 1100,
              opacity: 1,
            },
            {
              atMs: 9000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'v1b',
          x: 130,
          y: 130,
          text: 'Al₂O₃ nóng chảy trong cryolite',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 1200,
              opacity: 0,
            },
            {
              atMs: 1700,
              opacity: 1,
            },
            {
              atMs: 9000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'rect',
          id: 'v2',
          x: 218,
          y: 92,
          w: 130,
          h: 46,
          fill: 'primary',
          rx: 4,
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 3200,
              opacity: 0,
            },
            {
              atMs: 3600,
              opacity: 0.22,
            },
            {
              atMs: 9000,
              opacity: 0.22,
            },
          ],
        },
        {
          kind: 'label',
          id: 'v2t',
          x: 283,
          y: 112,
          text: 'Nhiệt luyện',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 3600,
              opacity: 0,
            },
            {
              atMs: 4100,
              opacity: 1,
            },
            {
              atMs: 9000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'v2b',
          x: 283,
          y: 130,
          text: 'khử oxide bằng CO, C, H₂',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 4200, opacity: 0 },
            { atMs: 4700, opacity: 1 },
            { atMs: 9000, opacity: 1 },
          ],
        },
        {
          kind: 'rect',
          id: 'v3',
          x: 356,
          y: 92,
          w: 84,
          h: 46,
          fill: 'primary',
          rx: 4,
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 6000,
              opacity: 0,
            },
            {
              atMs: 6400,
              opacity: 0.22,
            },
            {
              atMs: 9000,
              opacity: 0.22,
            },
          ],
        },
        {
          kind: 'label',
          id: 'v3t',
          x: 398,
          y: 112,
          text: 'Nhiệt phân',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 6400,
              opacity: 0,
            },
            {
              atMs: 6900,
              opacity: 1,
            },
            {
              atMs: 9000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'v3b',
          x: 398,
          y: 130,
          text: 'hoặc thuỷ luyện',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 6400,
              opacity: 0,
            },
            {
              atMs: 6900,
              opacity: 1,
            },
            {
              atMs: 9000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'troi',
          cx: 130,
          cy: 70,
          r: 8,
          fill: 'accent',
          keyframes: [
            {
              atMs: 0,
              dx: 0,
            },
            {
              atMs: 3200,
              dx: 0,
            },
            {
              atMs: 4000,
              dx: 153,
            },
            {
              atMs: 6000,
              dx: 153,
            },
            {
              atMs: 6800,
              dx: 268,
            },
            {
              atMs: 9000,
              dx: 268,
            },
          ],
        },
        {
          kind: 'label',
          id: 'vd1',
          x: 130,
          y: 164,
          text: 'ví dụ: 2Al₂O₃ → 4Al + 3O₂',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 1800, opacity: 0 },
            { atMs: 2300, opacity: 1 },
            { atMs: 9000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'vd2',
          x: 283,
          y: 184,
          text: 'ví dụ: Fe₂O₃ + 3CO → 2Fe + 3CO₂',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 4800, opacity: 0 },
            { atMs: 5300, opacity: 1 },
            { atMs: 9000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'vd3',
          x: 398,
          y: 164,
          text: 'ví dụ: 2HgO → 2Hg + O₂',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 7000, opacity: 0 },
            { atMs: 7500, opacity: 1 },
            { atMs: 9000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'kl',
          x: 235,
          y: 214,
          text: 'Kim loại càng hoạt động, tách ra càng tốn năng lượng',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 7600, opacity: 0 },
            { atMs: 8100, opacity: 1 },
            { atMs: 9000, opacity: 1 },
          ],
        },
      ],
      captions: [
        {
          atMs: 600,
          text: 'K, Na, Mg, Al: hợp chất rất bền, phải điện phân nóng chảy.',
        },
        {
          atMs: 3600,
          text: 'Zn, Fe, Cu: khử oxide bằng CO, C hoặc H₂ ở nhiệt độ cao — nhiệt luyện.',
        },
        {
          atMs: 6400,
          text: 'Hg, Ag: chỉ cần nhiệt phân hợp chất, hoặc dùng kim loại mạnh hơn đẩy ra.',
        },
        {
          atMs: 7600,
          text: 'Vị trí trong dãy hoạt động quyết định phương pháp tách.',
        },
      ],
    },
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'hoa12-c6-b21',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Đại cương về kim loại',
    lessonNumber: 21,
    title: 'Hợp kim',
    hook:
      'Sắt nguyên chất khá mềm và dễ gỉ sét. Nhưng khi pha thêm một chút carbon và chromium, ' +
      'ta thu được thép không gỉ vững chãi kiến tạo nên những toà nhà chọc trời.',
    theory:
      'KHÁI NIỆM HỢP KIM:\n' +
      '— Hợp kim là vật liệu kim loại có chứa một kim loại cơ bản và một số kim loại hoặc phi kim khác (như carbon, silicon).\n\n' +
      'TÍNH CHẤT CỦA HỢP KIM:\n' +
      '— Tính chất hoá học: Tương tự như tính chất của các đơn chất tham gia tạo thành hợp kim.\n' +
      '— Tính chất vật lí và cơ học (khác biệt nhiều so với kim loại thành phần):\n' +
      '  1. Độ dẫn điện và dẫn nhiệt của hợp kim kém hơn kim loại thành phần tinh khiết (do sự xáo trộn mạng tinh thể cản trở electron di chuyển).\n' +
      '  2. Độ cứng của hợp kim thường cao hơn kim loại thành phần (do các nguyên tử có kích thước khác nhau chèn vào mạng tinh thể làm các lớp tinh thể khó trượt lên nhau hơn).\n' +
      '  3. Nhiệt độ nóng chảy của hợp kim thường thấp hơn nhiệt độ nóng chảy của kim loại thành phần.\n\n' +
      'HỢP KIM PHỔ BIẾN:\n' +
      '— Gang (Cast iron): Hợp kim Fe−C (hàm lượng C từ 2% đến 5%), giòn, cứng.\n' +
      '— Thép (Steel): Hợp kim Fe−C (C < 2%), dẻo, bền dai. Thép không gỉ (Inox) chứa Fe−C−Cr−Ni.\n' +
      '— Đồng thau (Brass): Hợp kim Cu−Zn; Đồng bạch: Cu−Ni.',
    workedExample: {
      problem: 'Vì sao hợp kim thường cứng hơn kim loại thành phần tinh khiết cấu tạo nên nó?',
      steps: [
        'Trong kim loại tinh khiết, các nguyên tử đồng đều về kích thước xếp khít nhau thành các lớp mạng phẳng dễ trượt lên nhau khi chịu lực.',
        'Khi tạo hợp kim, các nguyên tử kim loại hoặc phi kim khác loại (có kích thước khác biệt) chèn vào các kẽ hở hoặc nút mạng tinh thể kim loại cơ bản.',
        'Sự chênh lệch kích thước này làm biến dạng mạng tinh thể, tạo ra các rào cản ngăn cản các lớp nguyên tử trượt lên nhau một cách dễ dàng.',
        'Do đó, cấu trúc trở nên khóa chặt hơn và làm tăng đáng kể độ cứng của vật liệu.',
      ],
      answer: 'Do nguyên tử khác kích thước cản trở các lớp tinh thể trượt lên nhau',
    },
    checkQuestions: [
      {
        prompt:
          'Thép là hợp kim của sắt (Fe) với phi kim nào sau đây, trong đó tỉ lệ phi kim này nhỏ hơn 2%?',
        choices: [
          { id: 'si', label: 'Silicon (Si)' },
          { id: 'p', label: 'Phosphorus (P)' },
          { id: 'c', label: 'Carbon (C)' },
          { id: 's', label: 'Sulfur (S)' },
        ],
        answer: { kind: 'choice', correctIds: ['c'] },
        explain:
          'Thép và gang đều là hợp kim của sắt và carbon (C). Thép có hàm lượng C < 2%, gang có hàm lượng C từ 2% đến 5%.',
      },
      {
        prompt: 'Đồng thau (brass) là hợp kim của đồng với kim loại nào sau đây?',
        choices: [
          { id: 'sn', label: 'Tin (Thiếc, Sn)' },
          { id: 'zn', label: 'Zinc (Kẽm, Zn)' },
          { id: 'ni', label: 'Nickel (Ni)' },
        ],
        answer: { kind: 'choice', correctIds: ['zn'] },
        explain:
          'Đồng thau là hợp kim của Đồng (Cu) và Kẽm (Zn). Đồng thiếc (bronze) là hợp kim của Đồng và Thiếc (Sn).',
      },
    ],
    srsCards: [
      { hoi: 'Thành phần chính của gang và thép?', dap: 'Sắt (Fe) và Carbon (C).' },
      { hoi: 'Nhiệt độ nóng chảy của hợp kim so với kim loại gốc?', dap: 'Thường thấp hơn.' },
      {
        hoi: 'Độ dẫn điện của hợp kim so với kim loại gốc?',
        dap: 'Kém hơn (do mạng tinh thể bị xáo trộn làm electron tự do khó di chuyển).',
      },
    ],
    animation: {
      title: 'Vì sao thép cứng hơn sắt nguyên chất: nguyên tử lạ chặn mặt trượt',
      description:
        'Bên trái là sắt nguyên chất: các nguyên tử cùng cỡ xếp thành hàng lối đều tăm tắp. Khi có lực tác dụng, cả một lớp nguyên tử trượt trơn tru sang bên — đường trượt được vẽ bằng nét đứt — nên sắt nguyên chất khá mềm và dễ biến dạng. Bên phải là thép, tức sắt có chen thêm những nguyên tử carbon nhỏ hơn nhiều nằm lọt vào khe giữa các nguyên tử sắt. Khi lực tác dụng, lớp nguyên tử vừa trượt được một đoạn ngắn đã vấp phải các nguyên tử lạ đó và khựng lại: mạng bị méo cục bộ, mặt trượt không đi tiếp được. Kết quả là thép cứng hơn và bền hơn hẳn sắt nguyên chất, dù thành phần chỉ thêm dưới 2% carbon. Hợp kim cứng hơn kim loại thành phần không phải vì chất mới cứng, mà vì trật tự mạng bị phá vỡ.',
      viewBoxWidth: 470,
      viewBoxHeight: 230,
      durationMs: 8000,
      loop: true,
      shapes: [
        {
          kind: 'label',
          id: 't1',
          x: 118,
          y: 34,
          text: 'Sắt nguyên chất',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'circle',
          id: 'f1',
          cx: 50,
          cy: 70,
          r: 13,
          fill: 'primary',
          keyframes: [
            {
              atMs: 0,
              dx: 0,
            },
            {
              atMs: 2000,
              dx: 0,
            },
            {
              atMs: 4000,
              dx: 40,
            },
            {
              atMs: 8000,
              dx: 40,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'f2',
          cx: 90,
          cy: 70,
          r: 13,
          fill: 'primary',
          keyframes: [
            {
              atMs: 0,
              dx: 0,
            },
            {
              atMs: 2000,
              dx: 0,
            },
            {
              atMs: 4000,
              dx: 40,
            },
            {
              atMs: 8000,
              dx: 40,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'f3',
          cx: 130,
          cy: 70,
          r: 13,
          fill: 'primary',
          keyframes: [
            {
              atMs: 0,
              dx: 0,
            },
            {
              atMs: 2000,
              dx: 0,
            },
            {
              atMs: 4000,
              dx: 40,
            },
            {
              atMs: 8000,
              dx: 40,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'f4',
          cx: 170,
          cy: 70,
          r: 13,
          fill: 'primary',
          keyframes: [
            {
              atMs: 0,
              dx: 0,
            },
            {
              atMs: 2000,
              dx: 0,
            },
            {
              atMs: 4000,
              dx: 40,
            },
            {
              atMs: 8000,
              dx: 40,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'f5',
          cx: 50,
          cy: 110,
          r: 13,
          fill: 'primary',
        },
        {
          kind: 'circle',
          id: 'f6',
          cx: 90,
          cy: 110,
          r: 13,
          fill: 'primary',
        },
        {
          kind: 'circle',
          id: 'f7',
          cx: 130,
          cy: 110,
          r: 13,
          fill: 'primary',
        },
        {
          kind: 'circle',
          id: 'f8',
          cx: 170,
          cy: 110,
          r: 13,
          fill: 'primary',
        },
        {
          kind: 'line',
          id: 'truot1',
          x1: 30,
          y1: 90,
          x2: 206,
          y2: 90,
          stroke: 'accent',
          strokeWidth: 2,
          dash: '5 4',
        },
        {
          kind: 'arrow',
          id: 'l1',
          x1: 30,
          y1: 56,
          x2: 62,
          y2: 56,
          stroke: 'accent',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'kq1',
          x: 118,
          y: 156,
          text: 'lớp trên trượt trơn tru',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 4000,
              opacity: 0,
            },
            {
              atMs: 4500,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'kq1b',
          x: 118,
          y: 178,
          text: 'sắt nguyên chất mềm, dễ biến dạng',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 4000,
              opacity: 0,
            },
            {
              atMs: 4500,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'line',
          id: 'chia',
          x1: 236,
          y1: 40,
          x2: 236,
          y2: 190,
          stroke: 'muted',
          strokeWidth: 1.5,
          dash: '5 5',
        },
        {
          kind: 'label',
          id: 't2',
          x: 352,
          y: 34,
          text: 'Thép (Fe + dưới 2% C)',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'circle',
          id: 'g1',
          cx: 284,
          cy: 70,
          r: 13,
          fill: 'primary',
          keyframes: [
            {
              atMs: 0,
              dx: 0,
            },
            {
              atMs: 2000,
              dx: 0,
            },
            {
              atMs: 3400,
              dx: 9,
            },
            {
              atMs: 8000,
              dx: 9,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'g2',
          cx: 324,
          cy: 70,
          r: 13,
          fill: 'primary',
          keyframes: [
            {
              atMs: 0,
              dx: 0,
            },
            {
              atMs: 2000,
              dx: 0,
            },
            {
              atMs: 3400,
              dx: 9,
            },
            {
              atMs: 8000,
              dx: 9,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'g3',
          cx: 364,
          cy: 70,
          r: 13,
          fill: 'primary',
          keyframes: [
            {
              atMs: 0,
              dx: 0,
            },
            {
              atMs: 2000,
              dx: 0,
            },
            {
              atMs: 3400,
              dx: 9,
            },
            {
              atMs: 8000,
              dx: 9,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'g4',
          cx: 404,
          cy: 70,
          r: 13,
          fill: 'primary',
          keyframes: [
            {
              atMs: 0,
              dx: 0,
            },
            {
              atMs: 2000,
              dx: 0,
            },
            {
              atMs: 3400,
              dx: 9,
            },
            {
              atMs: 8000,
              dx: 9,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'g5',
          cx: 284,
          cy: 110,
          r: 13,
          fill: 'primary',
        },
        {
          kind: 'circle',
          id: 'g6',
          cx: 324,
          cy: 110,
          r: 13,
          fill: 'primary',
        },
        {
          kind: 'circle',
          id: 'g7',
          cx: 364,
          cy: 110,
          r: 13,
          fill: 'primary',
        },
        {
          kind: 'circle',
          id: 'g8',
          cx: 404,
          cy: 110,
          r: 13,
          fill: 'primary',
        },
        {
          kind: 'circle',
          id: 'c1',
          cx: 344,
          cy: 90,
          r: 6,
          fill: 'accent',
        },
        {
          kind: 'circle',
          id: 'c2',
          cx: 424,
          cy: 90,
          r: 6,
          fill: 'accent',
        },
        {
          kind: 'label',
          id: 'ct',
          x: 384,
          y: 132,
          text: 'nguyên tử carbon nhỏ chen vào khe',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'line',
          id: 'truot2',
          x1: 264,
          y1: 90,
          x2: 336,
          y2: 90,
          stroke: 'accent',
          strokeWidth: 2,
          dash: '5 4',
        },
        {
          kind: 'arrow',
          id: 'l2',
          x1: 264,
          y1: 56,
          x2: 296,
          y2: 56,
          stroke: 'accent',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'kq2',
          x: 352,
          y: 156,
          text: 'mặt trượt vấp nguyên tử lạ, khựng lại',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 3800,
              opacity: 0,
            },
            {
              atMs: 4300,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'kq2b',
          x: 352,
          y: 178,
          text: 'thép cứng hơn, bền hơn hẳn',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 3800,
              opacity: 0,
            },
            {
              atMs: 4300,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'kl',
          x: 235,
          y: 208,
          text: 'Hợp kim cứng hơn vì trật tự mạng bị phá, không phải vì có chất mới cứng',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 5600,
              opacity: 0,
            },
            {
              atMs: 6100,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
      ],
      captions: [
        {
          atMs: 0,
          text: 'Sắt nguyên chất: các nguyên tử cùng cỡ xếp đều, có mặt trượt trơn.',
        },
        {
          atMs: 3400,
          text: 'Thép: nguyên tử carbon nhỏ chen vào khe giữa các nguyên tử sắt.',
        },
        {
          atMs: 4000,
          text: 'Lớp trượt vấp phải nguyên tử lạ và khựng lại — mạng bị méo cục bộ.',
        },
        {
          atMs: 5600,
          text: 'Chỉ thêm dưới 2% carbon mà thép cứng hơn sắt nguyên chất rất nhiều.',
        },
      ],
    },
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'hoa12-c6-b22',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Đại cương về kim loại',
    lessonNumber: 22,
    title: 'Sự ăn mòn kim loại',
    hook:
      'Gỉ sét tàn phá cầu đường và tàu biển, gây thiệt hại hàng tỷ USD mỗi năm. ' +
      'Đây không chỉ là phản ứng hoá học đơn thuần mà là một quá trình điện hoá tinh vi.',
    theory:
      'KHÁI NIỆM ĂN MÒN KIM LOẠI:\n' +
      '— Là sự phá huỷ kim loại hoặc hợp kim do tác dụng hoá học của các chất trong môi trường xung quanh: M → Mⁿ⁺ + ne.\n\n' +
      'PHÂN LOẠI ĂN MÒN:\n' +
      '1. Ăn mòn hoá học: Kim loại phản ứng trực tiếp với chất oxi hoá trong môi trường (không phát sinh dòng điện, thường gặp ở các chi tiết máy làm việc ở nhiệt độ cao, như van động cơ).\n' +
      '2. Ăn mòn điện hoá (phổ biến và nguy hiểm nhất): Quá trình ăn mòn kim loại do tác dụng của dung dịch chất điện li và tạo ra dòng điện.\n' +
      '   — Điều kiện xảy ra ăn mòn điện hoá (đồng thời cả 3 điều kiện):\n' +
      '     1. Hai điện cực khác chất nhau (kim loại - kim loại, kim loại - phi kim như Fe−C).\n' +
      '     2. Các điện cực tiếp xúc trực tiếp hoặc gián tiếp qua dây dẫn.\n' +
      '     3. Các điện cực cùng tiếp xúc với dung dịch chất điện li (nước mưa, không khí ẩm chứa khí tan).\n' +
      '   — Cơ chế cực: Cực âm (Anode) là kim loại mạnh hơn, bị ăn mòn; Cực dương (Cathode) là kim loại yếu hơn/phi kim, được bảo vệ.\n\n' +
      'PHƯƠNG PHÁP BẢO VỆ KIM LOẠI KHÔNG BỊ ĂN MÒN:\n' +
      '— Phương pháp cách li môi trường: Sơn, mạ, bôi dầu mỡ, tráng men... lên bề mặt kim loại.\n' +
      '— Phương pháp bảo vệ điện hoá: Dùng kim loại hoạt động mạnh hơn làm "vật hi sinh" để bảo vệ kim loại yếu hơn. Ví dụ: Gắn các khối kẽm (Zn) vào vỏ tàu biển bằng thép (Fe). Kẽm bị ăn mòn trước, thép của tàu được bảo vệ.',
    workedExample: {
      problem:
        'Một sợi dây đồng (Cu) được nối với một sợi dây sắt (Fe) rồi để ngoài không khí ẩm. ' +
        'Xác định loại ăn mòn xảy ra, cực âm, cực dương và chất nào bị ăn mòn.',
      steps: [
        'Xét điều kiện ăn mòn: hai điện cực khác nhau (Fe và Cu), tiếp xúc trực tiếp, cùng đặt trong không khí ẩm (chất điện li) ⇒ Thoả mãn ăn mòn điện hoá học.',
        'Xác định tính chất kim loại: Fe hoạt động hoá học mạnh hơn Cu.',
        'Cực âm (Anode): Fe. Quá trình oxi hoá xảy ra tại đây: Fe → Fe²⁺ + 2e. Sắt bị ăn mòn.',
        'Cực dương (Cathode): Cu. Quá trình khử của môi trường xảy ra tại đây (như khử O₂ hoặc H⁺). Đồng được bảo vệ, không bị ăn mòn.',
        'Kết luận: Xảy ra ăn mòn điện hoá; Fe là anode và bị ăn mòn; Cu là cathode và được bảo vệ.',
      ],
      answer: 'Fe bị ăn mòn điện hoá',
    },
    checkQuestions: [
      {
        prompt:
          'Để bảo vệ vỏ tàu biển bằng thép (thành phần chính là sắt) khỏi bị ăn mòn điện hoá bởi nước biển, người ta gắn vào vỏ tàu khối kim loại nào sau đây làm vật hi sinh?',
        choices: [
          { id: 'cu', label: 'Copper (Đồng, Cu)' },
          { id: 'ag', label: 'Silver (Bạc, Ag)' },
          { id: 'zn', label: 'Zinc (Kẽm, Zn)' },
          { id: 'pb', label: 'Lead (Chì, Pb)' },
        ],
        answer: { kind: 'choice', correctIds: ['zn'] },
        explain:
          'Kẽm (Zn) hoạt động mạnh hơn Sắt (Fe). Khi gắn vào vỏ tàu, Zn đóng vai trò cực âm (anode) và bị ăn mòn trước, bảo vệ sắt không bị oxi hoá.',
      },
      {
        prompt:
          'Điều kiện nào sau đây KHÔNG bắt buộc để xảy ra quá trình ăn mòn điện hoá học của kim loại?',
        choices: [
          { id: 'a', label: 'Hai điện cực phải tiếp xúc trực tiếp với nhau' },
          { id: 'b', label: 'Phải có dòng điện bên ngoài truyền vào' },
          { id: 'c', label: 'Các điện cực phải cùng tiếp xúc với một dung dịch chất điện li' },
        ],
        answer: { kind: 'choice', correctIds: ['b'] },
        explain:
          'Ăn mòn điện hoá tự sinh ra dòng điện từ phản ứng bên trong, nên không cần nguồn điện ngoài. Hai điều kiện kia thì bắt buộc: có tiếp xúc thì electron mới chuyển từ cực này sang cực kia, và có dung dịch điện li thì mạch mới khép kín nhờ ion di chuyển.',
      },
    ],
    srsCards: [
      { hoi: 'Hai loại ăn mòn kim loại thường gặp?', dap: 'Ăn mòn hoá học và Ăn mòn điện hoá.' },
      {
        hoi: 'Trong ăn mòn điện hoá, điện cực nào bị ăn mòn?',
        dap: 'Cực âm (anode), làm bằng kim loại hoạt động mạnh hơn.',
      },
      {
        hoi: 'Bảo vệ điện hoá là phương pháp gì?',
        dap: 'Gắn một kim loại mạnh hơn làm vật hi sinh bị ăn mòn trước để bảo vệ kim loại chính.',
      },
    ],
    animation: {
      title: 'Ăn mòn điện hoá: vì sao chỗ sắt tiếp xúc đồng lại gỉ nhanh hơn',
      description:
        'Một thanh sắt gắn liền với một thanh đồng, cả hai cùng nhúng trong màng nước có hoà tan chất điện li (nước mưa, không khí ẩm). Ba điều kiện của ăn mòn điện hoá đủ cả: hai điện cực khác chất, tiếp xúc trực tiếp, cùng nằm trong dung dịch điện li. Kết quả là một pin điện hoá tí hon ngay trên bề mặt vật: sắt hoạt động mạnh hơn nên làm anode, bị oxi hoá Fe → Fe²⁺ + 2e, ion Fe²⁺ tan vào màng nước (chỗ này gỉ, lõm dần). Electron chạy trong kim loại qua chỗ tiếp xúc sang thanh đồng — cathode — và ở mặt đồng, oxygen hoà tan nhận electron: O₂ + 2H₂O + 4e → 4OH⁻. Electron bị kéo đi liên tục nên sắt tan nhanh hơn hẳn so với khi đứng một mình. Cũng nguyên lí đó dùng để bảo vệ vỏ tàu: gắn khối kẽm (hoạt động mạnh hơn sắt) để kẽm làm anode và bị ăn mòn thay cho sắt.',
      viewBoxWidth: 440,
      viewBoxHeight: 230,
      durationMs: 6000,
      loop: true,
      shapes: [
        {
          kind: 'rect',
          id: 'dung-dich',
          x: 30,
          y: 90,
          w: 380,
          h: 110,
          rx: 4,
          fill: 'primary',
          opacity: 0.15,
        },
        { kind: 'rect', id: 'fe', x: 90, y: 70, w: 130, h: 46, rx: 3, fill: 'muted' },
        { kind: 'rect', id: 'cu', x: 220, y: 70, w: 130, h: 46, rx: 3, fill: 'warn' },
        {
          kind: 'arrow',
          id: 'huong-e',
          x1: 176,
          y1: 44,
          x2: 304,
          y2: 44,
          stroke: 'muted',
          strokeWidth: 1.5,
        },
        {
          kind: 'circle',
          id: 'e1',
          cx: 185,
          cy: 104,
          r: 4,
          fill: 'correct',
          opacity: 0,
          keyframes: [
            { atMs: 500, dx: 0, opacity: 0 },
            { atMs: 600, opacity: 1 },
            { atMs: 1800, dx: 105 },
            { atMs: 2000, opacity: 0 },
          ],
        },
        {
          kind: 'circle',
          id: 'e2',
          cx: 185,
          cy: 104,
          r: 4,
          fill: 'correct',
          opacity: 0,
          keyframes: [
            { atMs: 1300, dx: 0, opacity: 0 },
            { atMs: 1400, opacity: 1 },
            { atMs: 2600, dx: 105 },
            { atMs: 2800, opacity: 0 },
          ],
        },
        {
          kind: 'circle',
          id: 'e3',
          cx: 185,
          cy: 104,
          r: 4,
          fill: 'correct',
          opacity: 0,
          keyframes: [
            { atMs: 2100, dx: 0, opacity: 0 },
            { atMs: 2200, opacity: 1 },
            { atMs: 3400, dx: 105 },
            { atMs: 3600, opacity: 0 },
          ],
        },
        {
          kind: 'circle',
          id: 'fe-ion1',
          cx: 130,
          cy: 124,
          r: 7,
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 500, dy: 0, opacity: 0 },
            { atMs: 750, opacity: 1 },
            { atMs: 2600, dy: 50 },
          ],
        },
        {
          kind: 'circle',
          id: 'fe-ion2',
          cx: 185,
          cy: 124,
          r: 7,
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 2100, dy: 0, opacity: 0 },
            { atMs: 2350, opacity: 1 },
            { atMs: 4200, dy: 44 },
          ],
        },
        {
          kind: 'circle',
          id: 'o2',
          cx: 300,
          cy: 162,
          r: 6,
          fill: 'primary',
          keyframes: [
            { atMs: 1500, dy: 0 },
            { atMs: 2800, dy: -36, opacity: 1 },
            { atMs: 3100, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'fe-t',
          x: 155,
          y: 62,
          text: 'Fe (anode)',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'cu-t',
          x: 285,
          y: 62,
          text: 'Cu (cathode)',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'e-t',
          x: 240,
          y: 34,
          text: 'electron qua chỗ tiếp xúc',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'fe-ion-t',
          x: 118,
          y: 128,
          text: 'Fe²⁺',
          size: 10,
          anchor: 'end',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 500, dy: 0, opacity: 0 },
            { atMs: 750, opacity: 1 },
            { atMs: 2600, dy: 50 },
          ],
        },
        {
          kind: 'label',
          id: 'o2-t',
          x: 290,
          y: 166,
          text: 'O₂',
          size: 10,
          anchor: 'end',
          fill: 'neutral',
          keyframes: [
            { atMs: 1500, dy: 0 },
            { atMs: 2800, dy: -36, opacity: 1 },
            { atMs: 3100, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'oh-t',
          x: 300,
          y: 140,
          text: 'OH⁻',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 3100, opacity: 0 },
            { atMs: 3400, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'dd-t',
          x: 404,
          y: 194,
          text: 'màng nước có chất điện li (không khí ẩm)',
          size: 10,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'pt-anode',
          x: 120,
          y: 220,
          text: 'Fe → Fe²⁺ + 2e (sắt tan, gỉ)',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'pt-cathode',
          x: 320,
          y: 220,
          text: 'O₂ + 2H₂O + 4e → 4OH⁻',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
      ],
      captions: [
        {
          atMs: 0,
          text: 'Đủ 3 điều kiện: hai kim loại khác nhau, tiếp xúc trực tiếp, cùng nằm trong dung dịch điện li.',
        },
        {
          atMs: 700,
          text: 'Sắt (hoạt động mạnh hơn) làm anode: Fe → Fe²⁺ + 2e, ion Fe²⁺ tan vào màng nước.',
        },
        { atMs: 1500, text: 'Electron chạy trong kim loại, qua chỗ tiếp xúc sang đồng.' },
        {
          atMs: 2800,
          text: 'Ở mặt đồng (cathode), oxygen hoà tan nhận electron thành OH⁻ — electron bị kéo đi liên tục nên sắt tan nhanh hơn.',
        },
      ],
    },
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'hoa12-c6-b23',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Đại cương về kim loại',
    lessonNumber: 23,
    title: 'Ôn tập chương 6 — Đại cương về kim loại',
    hook:
      'Chương 6 gom lại những quy luật chung của mọi kim loại: cấu trúc tinh thể, tính chất vật lí và hoá học, cách tách ra khỏi quặng, ' +
      'hợp kim và sự ăn mòn.',
    theory:
      'HỆ THỐNG HOÁ KIẾN THỨC CHƯƠNG 6:\n' +
      '1. Cấu trúc kim loại: Liên kết kim loại (hút cation - electron tự do). 3 kiểu mạng tinh thể: lập phương tâm khối, lập phương tâm diện, lục phương.\n' +
      '2. Tính chất vật lí: Dẫn điện (Ag>Cu>Au>Al>Fe), dẫn nhiệt, tính dẻo, ánh kim do electron tự do. Độ cứng (Cr nhất), nhiệt độ nóng chảy (W nhất), khối lượng riêng (Os lớn nhất) do khối lượng và cách sắp xếp nguyên tử quyết định.\n' +
      '3. Tính chất hoá học: tính khử là tính chất đặc trưng. Dãy điện hoá cho biết chiều phản ứng: chất oxi hoá mạnh hơn tác dụng với chất khử mạnh hơn, tạo ra chất oxi hoá yếu hơn và chất khử yếu hơn.\n' +
      '4. Điều chế kim loại: Khử ion kim loại. Thuỷ luyện (yếu), Nhiệt luyện (dùng C, CO, H₂, Al khử oxide của kim loại trung bình/yếu), Điện phân (nóng chảy cho IA, IIA, Al; dung dịch cho trung bình/yếu).\n' +
      '5. Hợp kim: vật liệu gồm một kim loại cơ bản trộn thêm kim loại hoặc phi kim khác (không phải hợp chất). So với kim loại thành phần: cứng hơn, dẫn điện kém hơn, thường nóng chảy ở nhiệt độ thấp hơn.\n' +
      '6. Ăn mòn: Ăn mòn hoá học và ăn mòn điện hoá (3 điều kiện). Cực âm (anode) bị ăn mòn. Bảo vệ bằng sơn/mạ hoặc gắn kim loại mạnh hi sinh.',
    workedExample: {
      problem:
        'Sắt bị ăn mòn điện hoá học khi tiếp xúc với kim loại nào sau đây trong không khí ẩm: Mg, Cu, Zn?',
      steps: [
        'Để sắt (Fe) bị ăn mòn điện hoá học khi tiếp xúc với kim loại khác trong không khí ẩm, sắt phải đóng vai trò cực âm (anode) của cặp điện cực.',
        'Muốn sắt là cực âm, sắt phải hoạt động hoá học mạnh hơn kim loại tiếp xúc cùng.',
        'So sánh hoạt động hoá học: Mg > Zn > Fe > Cu.',
        'Do đó, Fe chỉ mạnh hơn Cu. Trong cặp Fe-Cu, Fe bị ăn mòn điện hoá học. Trong cặp Mg-Fe và Zn-Fe, Mg và Zn bị ăn mòn trước để bảo vệ Fe.',
        'Kết luận: Sắt bị ăn mòn khi tiếp xúc với Cu.',
      ],
      answer: 'Cu',
    },
    checkQuestions: [
      {
        prompt:
          'Kim loại nào sau đây có tính khử yếu hơn sắt (Fe) nhưng mạnh hơn đồng (Cu) trong dãy hoạt động hoá học?',
        choices: [
          { id: 'mg', label: 'Magnesium (Mg)' },
          { id: 'pb', label: 'Lead (Chì, Pb)' },
          { id: 'al', label: 'Aluminium (Al)' },
          { id: 'na', label: 'Sodium (Na)' },
        ],
        answer: { kind: 'choice', correctIds: ['pb'] },
        explain:
          'Theo dãy hoạt động hoá học: Mg > Al > Zn > Fe > Ni > Sn > Pb > H > Cu. Do đó Chì (Pb) nằm giữa Fe và Cu.',
      },
      {
        prompt: 'Đặc điểm nào sau đây là của hợp kim so với kim loại gốc cấu tạo nên nó?',
        choices: [
          { id: 'a', label: 'Dẫn điện tốt hơn, cứng hơn' },
          { id: 'b', label: 'Dẫn điện kém hơn, cứng hơn, nhiệt độ nóng chảy thấp hơn' },
          { id: 'c', label: 'Dẫn điện tốt hơn, dẻo hơn' },
        ],
        answer: { kind: 'choice', correctIds: ['b'] },
        explain:
          'Sự xáo trộn mạng tinh thể của hợp kim cản trở chuyển động của electron tự do (dẫn điện kém hơn) và cản trở sự trượt của các lớp nguyên tử (cứng hơn).',
      },
    ],
    srsCards: [
      { hoi: 'Kim loại dẻo nhất có thể dát mỏng cực độ?', dap: 'Vàng (Au).' },
      { hoi: 'Kim loại có khối lượng riêng lớn nhất (nặng nhất)?', dap: 'Osmium (Os).' },
      {
        hoi: 'Trong chương trình phổ thông, sắt đạt số oxi hoá cao nhất là bao nhiêu?',
        dap: '+3, khi tác dụng với chất oxi hoá mạnh như Cl₂ hoặc HNO₃.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
]
