// lessons/hoa10c2.ts — Hoá học 10, Chương 2: Bảng tuần hoàn các nguyên tố hoá học (4 bài).
// Đối chiếu mục lục thật: tai-lieu-sgk/SGK-Hoa/10/page_0004.png (OCR 2026-08-31).
// reviewStatus='draft' — nội dung soạn từ docs/research/kho-kien-thuc-hoa-gdpt2018.md §3,
// CHƯA qua giáo viên Hoá duyệt. Xem docs/goals/2026-08-31-mon-hoc-toan-ly-hoa-sinh.md.
import type { ChemLesson } from '../lessonTypes.js'

export const HOA10_C2_LESSONS: ChemLesson[] = [
  {
    id: 'hoa10-c2-b5',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Bảng tuần hoàn các nguyên tố hoá học',
    lessonNumber: 5,
    title: 'Cấu tạo của bảng tuần hoàn các nguyên tố hoá học',
    hook:
      'Mendeleev năm 1869 xếp các nguyên tố theo khối lượng nguyên tử tăng dần và dự đoán ' +
      'chính xác tính chất của những nguyên tố CHƯA TỪNG được tìm ra — bí quyết nằm ở quy ' +
      'luật lặp lại tính chất theo chu kì.',
    theory:
      'Bảng tuần hoàn hiện đại sắp xếp các nguyên tố theo CHIỀU TĂNG DẦN của điện tích hạt ' +
      'nhân (số hiệu nguyên tử Z).\n\n' +
      'Ô NGUYÊN TỐ: mỗi nguyên tố chiếm một ô, chứa số hiệu nguyên tử, kí hiệu hoá học, tên ' +
      'nguyên tố, nguyên tử khối.\n\n' +
      'CHU KÌ: dãy nguyên tố có CÙNG SỐ LỚP ELECTRON, xếp theo hàng ngang. Số thứ tự chu kì = ' +
      'số lớp electron. Bảng tuần hoàn có 7 chu kì (chu kì 1, 2, 3 là chu kì nhỏ; 4, 5, 6, 7 là ' +
      'chu kì lớn).\n\n' +
      'NHÓM: tập hợp nguyên tố có tính chất hoá học TƯƠNG TỰ nhau, xếp theo cột dọc — thường ' +
      'do CÙNG SỐ ELECTRON LỚP NGOÀI CÙNG. Có nhóm A (nguyên tố s, p) và nhóm B (nguyên tố d, ' +
      'chuyển tiếp).\n\n' +
      'Số thứ tự nhóm A = số electron lớp ngoài cùng (với nhóm chính).',
    workedExample: {
      problem:
        'Nguyên tử X có cấu hình electron 1s²2s²2p⁶3s²3p⁴. Xác định X thuộc chu kì mấy, nhóm ' +
        'nào?',
      steps: [
        'Đếm số lớp electron: lớp 1 (1s), lớp 2 (2s,2p), lớp 3 (3s,3p) — có 3 lớp ⇒ X thuộc ' +
          'CHU KÌ 3.',
        'Đếm electron lớp ngoài cùng (lớp 3): 3s²3p⁴ = 2+4 = 6 electron.',
        'Số electron lớp ngoài cùng = 6 ⇒ X thuộc NHÓM VIA.',
        'Kết luận: X ở chu kì 3, nhóm VIA (đây là nguyên tử Sulfur — S, Z=16).',
      ],
      answer: 'Chu kì 3, nhóm VIA.',
    },
    checkQuestions: [
      {
        prompt: 'Số thứ tự chu kì trong bảng tuần hoàn ứng với đại lượng nào của nguyên tử?',
        choices: [
          { id: 'a', label: 'Số lớp electron' },
          { id: 'b', label: 'Số electron lớp ngoài cùng' },
          { id: 'c', label: 'Số proton' },
          { id: 'd', label: 'Số neutron' },
        ],
        answer: { kind: 'choice', correctIds: ['a'] },
        explain:
          'Chu kì = dãy nguyên tố có CÙNG SỐ LỚP ELECTRON. Số thứ tự chu kì chính là số lớp electron.',
      },
      {
        prompt: 'Nguyên tử Y có cấu hình 1s²2s²2p⁶3s²3p¹. Y thuộc nhóm nào trong các nhóm sau?',
        choices: [
          { id: 'IA', label: 'IA' },
          { id: 'IIA', label: 'IIA' },
          { id: 'IIIA', label: 'IIIA' },
          { id: 'IVA', label: 'IVA' },
        ],
        answer: { kind: 'choice', correctIds: ['IIIA'] },
        explain: 'Electron lớp ngoài cùng (lớp 3): 3s²3p¹ = 3 electron ⇒ nhóm IIIA (đây là Al).',
      },
    ],
    srsCards: [
      {
        hoi: 'Nguyên tố xếp trong bảng tuần hoàn theo chiều tăng dần đại lượng gì?',
        dap: 'Điện tích hạt nhân (Z).',
      },
      { hoi: 'Số thứ tự chu kì bằng gì?', dap: 'Số lớp electron.' },
      { hoi: 'Số thứ tự nhóm A (nguyên tố chính) bằng gì?', dap: 'Số electron lớp ngoài cùng.' },
    ],
    animation: {
      title: 'Từ cấu hình electron đọc ra ô, chu kì và nhóm trong bảng tuần hoàn',
      description:
        'Cấu hình electron của sulfur hiện ra từng lớp một: 1s² rồi 2s²2p⁶ rồi 3s²3p⁴. Đếm số lớp được 3 lớp — đó chính là số chu kì, nên hàng thứ 3 của lưới sáng lên. Đếm số electron ở lớp ngoài cùng được 2 + 4 = 6 — đó chính là số thứ tự nhóm A, nên cột VIA sáng lên. Lưới là phần đầu bảng tuần hoàn với đủ tám nhóm A từ IA đến VIIIA: chu kì 1 chỉ có hai ô (H và He), còn khoảng trống giữa IIA và IIIA là chỗ của các nhóm B, chỉ bắt đầu có từ chu kì 4. Ô sáng mang chữ S đi từ góc trên bên trái xuống hàng 3 rồi sang phải, dừng đúng ở giao điểm của hàng 3 và cột VIA. Điều cần thấy: vị trí trong bảng không phải học thuộc, nó đọc thẳng ra từ cấu hình electron.',
      viewBoxWidth: 440,
      viewBoxHeight: 246,
      durationMs: 7000,
      loop: true,
      shapes: [
        {
          kind: 'rect',
          id: 'o1-1',
          x: 40,
          y: 90,
          w: 42,
          h: 36,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.2,
        },
        {
          kind: 'rect',
          id: 'o1-8',
          x: 368,
          y: 90,
          w: 42,
          h: 36,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.2,
        },
        {
          kind: 'rect',
          id: 'o2-1',
          x: 40,
          y: 126,
          w: 42,
          h: 36,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.2,
        },
        {
          kind: 'rect',
          id: 'o2-2',
          x: 82,
          y: 126,
          w: 42,
          h: 36,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.2,
        },
        {
          kind: 'rect',
          id: 'o2-3',
          x: 158,
          y: 126,
          w: 42,
          h: 36,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.2,
        },
        {
          kind: 'rect',
          id: 'o2-4',
          x: 200,
          y: 126,
          w: 42,
          h: 36,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.2,
        },
        {
          kind: 'rect',
          id: 'o2-5',
          x: 242,
          y: 126,
          w: 42,
          h: 36,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.2,
        },
        {
          kind: 'rect',
          id: 'o2-6',
          x: 284,
          y: 126,
          w: 42,
          h: 36,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.2,
        },
        {
          kind: 'rect',
          id: 'o2-7',
          x: 326,
          y: 126,
          w: 42,
          h: 36,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.2,
        },
        {
          kind: 'rect',
          id: 'o2-8',
          x: 368,
          y: 126,
          w: 42,
          h: 36,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.2,
        },
        {
          kind: 'rect',
          id: 'o3-1',
          x: 40,
          y: 162,
          w: 42,
          h: 36,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.2,
        },
        {
          kind: 'rect',
          id: 'o3-2',
          x: 82,
          y: 162,
          w: 42,
          h: 36,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.2,
        },
        {
          kind: 'rect',
          id: 'o3-3',
          x: 158,
          y: 162,
          w: 42,
          h: 36,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.2,
        },
        {
          kind: 'rect',
          id: 'o3-4',
          x: 200,
          y: 162,
          w: 42,
          h: 36,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.2,
        },
        {
          kind: 'rect',
          id: 'o3-5',
          x: 242,
          y: 162,
          w: 42,
          h: 36,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.2,
        },
        {
          kind: 'rect',
          id: 'o3-6',
          x: 284,
          y: 162,
          w: 42,
          h: 36,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.2,
        },
        {
          kind: 'rect',
          id: 'o3-7',
          x: 326,
          y: 162,
          w: 42,
          h: 36,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.2,
        },
        {
          kind: 'rect',
          id: 'o3-8',
          x: 368,
          y: 162,
          w: 42,
          h: 36,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.2,
        },
        {
          kind: 'rect',
          id: 'dai-hang',
          x: 12,
          y: 162,
          w: 398,
          h: 36,
          fill: 'accent',
          opacity: 0,
          keyframes: [
            { atMs: 2600, opacity: 0 },
            { atMs: 3100, opacity: 0.2 },
          ],
        },
        {
          kind: 'rect',
          id: 'dai-cot',
          x: 284,
          y: 70,
          w: 42,
          h: 128,
          fill: 'accent',
          opacity: 0,
          keyframes: [
            { atMs: 3600, opacity: 0 },
            { atMs: 4100, opacity: 0.2 },
          ],
        },
        {
          kind: 'rect',
          id: 'o',
          x: 42,
          y: 92,
          w: 38,
          h: 32,
          rx: 3,
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 2300, opacity: 0, dx: 0, dy: 0 },
            { atMs: 2700, opacity: 0.9 },
            { atMs: 2900, dx: 0, dy: 0 },
            { atMs: 3700, dx: 0, dy: 72 },
            { atMs: 4300, dx: 0, dy: 72 },
            { atMs: 5500, dx: 244, dy: 72 },
          ],
        },
        {
          kind: 'label',
          id: 'cf1',
          x: 30,
          y: 30,
          text: '1s²',
          size: 14,
          anchor: 'start',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 200, opacity: 0 },
            { atMs: 700, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'cf2',
          x: 70,
          y: 30,
          text: '2s²2p⁶',
          size: 14,
          anchor: 'start',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 900, opacity: 0 },
            { atMs: 1400, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'cf3',
          x: 140,
          y: 30,
          text: '3s²3p⁴',
          size: 14,
          anchor: 'start',
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 1600, opacity: 0 },
            { atMs: 2100, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'ghi1',
          x: 30,
          y: 54,
          text: '3 lớp → chu kì 3',
          size: 12,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 2600, opacity: 0 },
            { atMs: 3100, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'ghi2',
          x: 190,
          y: 54,
          text: '2 + 4 = 6 e lớp ngoài → nhóm VIA',
          size: 12,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 3600, opacity: 0 },
            { atMs: 4100, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'cIA',
          x: 61,
          y: 82,
          text: 'IA',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'cIIA',
          x: 103,
          y: 82,
          text: 'IIA',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'cIIIA',
          x: 179,
          y: 82,
          text: 'IIIA',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'cIVA',
          x: 221,
          y: 82,
          text: 'IVA',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'cVA',
          x: 263,
          y: 82,
          text: 'VA',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'cVIA',
          x: 305,
          y: 82,
          text: 'VIA',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'cVIIA',
          x: 347,
          y: 82,
          text: 'VIIA',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'cVIIIA',
          x: 389,
          y: 82,
          text: 'VIIIA',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'ck1',
          x: 24,
          y: 112,
          text: '1',
          size: 11,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'ck2',
          x: 24,
          y: 148,
          text: '2',
          size: 11,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'ck3',
          x: 24,
          y: 184,
          text: '3',
          size: 11,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'oS',
          x: 61,
          y: 114,
          text: 'S',
          size: 16,
          anchor: 'middle',
          fill: 'surface',
          opacity: 0,
          keyframes: [
            { atMs: 2300, opacity: 0, dx: 0, dy: 0 },
            { atMs: 2700, opacity: 1 },
            { atMs: 2900, dx: 0, dy: 0 },
            { atMs: 3700, dx: 0, dy: 72 },
            { atMs: 4300, dx: 0, dy: 72 },
            { atMs: 5500, dx: 244, dy: 72 },
          ],
        },
        {
          kind: 'label',
          id: 'nhomB',
          x: 225,
          y: 214,
          text: 'khoảng trống giữa IIA và IIIA: chỗ các nhóm B, chỉ có từ chu kì 4',
          size: 9,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'zs',
          x: 225,
          y: 236,
          text: 'S (Z = 16): ô số 16, chu kì 3, nhóm VIA',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 5600, opacity: 0 },
            { atMs: 6100, opacity: 1 },
          ],
        },
      ],
      captions: [
        { atMs: 0, text: 'Viết cấu hình electron của sulfur: 1s²2s²2p⁶3s²3p⁴.' },
        { atMs: 2600, text: 'Số lớp electron = số thứ tự chu kì → 3 lớp, chu kì 3.' },
        {
          atMs: 3600,
          text: 'Số electron lớp ngoài cùng = số thứ tự nhóm A → 2 + 4 = 6, nhóm VIA.',
        },
        { atMs: 5500, text: 'Giao của hàng 3 và cột VIA chính là ô của sulfur.' },
      ],
    },
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'hoa10-c2-b6',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Bảng tuần hoàn các nguyên tố hoá học',
    lessonNumber: 6,
    title: 'Xu hướng biến đổi một số tính chất của nguyên tử trong một chu kì và một nhóm',
    hook:
      'Vì sao kim loại kiềm (như Na, K) phản ứng mạnh với nước ngay ở nhiệt độ thường, còn ' +
      'khí hiếm gần như trơ tuyệt đối? Xu hướng biến đổi tuần hoàn giải thích được điều này ' +
      'mà không cần học thuộc từng nguyên tố.',
    theory:
      'BÁN KÍNH NGUYÊN TỬ:\n' +
      '— Trong MỘT CHU KÌ (trái → phải): điện tích hạt nhân tăng, lực hút electron mạnh hơn ' +
      '⇒ bán kính GIẢM DẦN.\n' +
      '— Trong MỘT NHÓM (trên → dưới): số lớp electron tăng ⇒ bán kính TĂNG DẦN.\n\n' +
      'ĐỘ ÂM ĐIỆN (khả năng hút electron về mình khi tạo liên kết):\n' +
      '— Trong một chu kì (trái → phải): độ âm điện TĂNG DẦN (ngược xu hướng bán kính).\n' +
      '— Trong một nhóm (trên → dưới): độ âm điện GIẢM DẦN.\n\n' +
      'TÍNH KIM LOẠI / PHI KIM:\n' +
      '— Trong một chu kì (trái → phải): tính kim loại GIẢM, tính phi kim TĂNG.\n' +
      '— Trong một nhóm (trên → dưới): tính kim loại TĂNG, tính phi kim GIẢM.\n\n' +
      'Nguyên tố có độ âm điện lớn nhất trong bảng tuần hoàn là Fluorine (F). Nguyên tố có ' +
      'tính kim loại mạnh nhất là Francium (Fr, nhóm IA, chu kì 7); nhưng Fr phóng xạ và cực ' +
      'hiếm, nên khi xét các kim loại bền người ta lấy Caesium (Cs) làm mốc mạnh nhất.',
    workedExample: {
      problem: 'So sánh bán kính nguyên tử của Na (Z=11) và Mg (Z=12) — cả hai đều thuộc chu kì 3.',
      steps: [
        'Cả Na và Mg đều thuộc CHU KÌ 3 (cùng số lớp electron).',
        'Trong cùng một chu kì, đi từ trái sang phải (Z tăng), bán kính nguyên tử GIẢM DẦN.',
        'Na có Z=11 nhỏ hơn Mg có Z=12 ⇒ Na đứng trước Mg trong chu kì.',
        'Kết luận: bán kính nguyên tử Na LỚN HƠN bán kính nguyên tử Mg.',
      ],
      answer: 'Bán kính Na > bán kính Mg.',
    },
    checkQuestions: [
      {
        prompt: 'Trong một chu kì, đi từ trái sang phải, bán kính nguyên tử biến đổi như thế nào?',
        choices: [
          { id: 'tang', label: 'Tăng dần' },
          { id: 'giam', label: 'Giảm dần' },
        ],
        answer: { kind: 'choice', correctIds: ['giam'] },
        explain:
          'Điện tích hạt nhân tăng dần trong khi số lớp electron không đổi ⇒ lực hút electron mạnh hơn ⇒ bán kính giảm.',
      },
      {
        prompt: 'Trong một nhóm A, đi từ trên xuống dưới, tính kim loại biến đổi như thế nào?',
        choices: [
          { id: 'tang', label: 'Tăng dần' },
          { id: 'giam', label: 'Giảm dần' },
        ],
        answer: { kind: 'choice', correctIds: ['tang'] },
        explain:
          'Số lớp electron tăng, electron ngoài cùng ở xa hạt nhân hơn, dễ bị mất hơn ⇒ tính kim loại tăng.',
      },
    ],
    srsCards: [
      {
        hoi: 'Bán kính nguyên tử biến đổi thế nào trong một chu kì (trái→phải)?',
        dap: 'Giảm dần.',
      },
      { hoi: 'Bán kính nguyên tử biến đổi thế nào trong một nhóm (trên→dưới)?', dap: 'Tăng dần.' },
      { hoi: 'Nguyên tố có độ âm điện lớn nhất bảng tuần hoàn?', dap: 'Fluorine (F).' },
    ],
    animation: {
      title: 'Bán kính nguyên tử giảm, độ âm điện tăng dọc chu kì 3',
      description:
        'Hàng trên là bảy nguyên tử của chu kì 3 hiện ra lần lượt từ Na đến Cl, vòng tròn mỗi lần một nhỏ hơn: bán kính đi từ 186 pm ở Na xuống 99 pm ở Cl. Điều gây bất ngờ là số electron lại TĂNG dần — thêm electron mà nguyên tử vẫn co lại, vì các electron mới đều rơi vào cùng lớp thứ 3 trong khi điện tích hạt nhân tăng từ +11 lên +17 và kéo cả lớp vỏ vào gần hơn. Hàng dưới là đường độ âm điện đi lên đều đặn từ 0,93 (Na) tới 3,16 (Cl): hạt nhân càng kéo mạnh thì khả năng hút electron liên kết càng lớn. Hai xu hướng này là hai mặt của một nguyên nhân.',
      viewBoxWidth: 460,
      viewBoxHeight: 250,
      durationMs: 8000,
      loop: true,
      shapes: [
        {
          kind: 'circle',
          id: 'a1',
          cx: 55,
          cy: 60,
          r: 27,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 400,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'a2',
          cx: 118,
          cy: 60,
          r: 23,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 500,
              opacity: 0,
            },
            {
              atMs: 900,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'a3',
          cx: 178,
          cy: 60,
          r: 20,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 1000,
              opacity: 0,
            },
            {
              atMs: 1400,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'a4',
          cx: 235,
          cy: 60,
          r: 17,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 1500,
              opacity: 0,
            },
            {
              atMs: 1900,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'a5',
          cx: 290,
          cy: 60,
          r: 16,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 2000,
              opacity: 0,
            },
            {
              atMs: 2400,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'a6',
          cx: 343,
          cy: 60,
          r: 15,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 2500,
              opacity: 0,
            },
            {
              atMs: 2900,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'a7',
          cx: 395,
          cy: 60,
          r: 14,
          fill: 'surface',
          stroke: 'primary',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 3000,
              opacity: 0,
            },
            {
              atMs: 3400,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'n1',
          x: 55,
          y: 64,
          text: 'Na',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 0, opacity: 0 },
            { atMs: 400, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'n2',
          x: 118,
          y: 64,
          text: 'Mg',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 500, opacity: 0 },
            { atMs: 900, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'n3',
          x: 178,
          y: 64,
          text: 'Al',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 1000, opacity: 0 },
            { atMs: 1400, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'n4',
          x: 235,
          y: 64,
          text: 'Si',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 1500, opacity: 0 },
            { atMs: 1900, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'n5',
          x: 290,
          y: 64,
          text: 'P',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 2000, opacity: 0 },
            { atMs: 2400, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'n6',
          x: 343,
          y: 64,
          text: 'S',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 2500, opacity: 0 },
            { atMs: 2900, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'n7',
          x: 395,
          y: 64,
          text: 'Cl',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 3000, opacity: 0 },
            { atMs: 3400, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'bk',
          x: 55,
          y: 100,
          text: 'bán kính 186 pm',
          size: 10,
          anchor: 'start',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 400, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'bk2',
          x: 440,
          y: 100,
          text: '99 pm',
          size: 10,
          anchor: 'end',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 3000, opacity: 0 },
            { atMs: 3400, opacity: 1 },
            { atMs: 8000, opacity: 1 },
          ],
        },
        {
          kind: 'line',
          id: 'trucx',
          x1: 40,
          y1: 225,
          x2: 440,
          y2: 225,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'line',
          id: 'trucy',
          x1: 40,
          y1: 225,
          x2: 40,
          y2: 130,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'yd',
          x: 44,
          y: 126,
          text: 'độ âm điện',
          size: 10,
          anchor: 'start',
          fill: 'muted',
        },
        {
          kind: 'polyline',
          id: 'dam',
          points: [
            [55, 206],
            [118, 191],
            [178, 179],
            [235, 168],
            [290, 157],
            [343, 142],
            [395, 120],
          ],
          stroke: 'accent',
          strokeWidth: 2.5,
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 3800,
              opacity: 0,
            },
            {
              atMs: 4600,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'd1',
          x: 55,
          y: 220,
          text: '0,93',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 4600,
              opacity: 0,
            },
            {
              atMs: 5100,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'd7',
          x: 400,
          y: 112,
          text: '3,16',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 4600,
              opacity: 0,
            },
            {
              atMs: 5100,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'kl',
          x: 240,
          y: 245,
          text: 'Cùng một lớp vỏ, hạt nhân mạnh dần: bán kính giảm — độ âm điện tăng',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 5600,
              opacity: 0,
            },
            {
              atMs: 6200,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
      ],
      captions: [
        {
          atMs: 0,
          text: 'Đi từ Na sang Cl, mỗi nguyên tử thêm một proton và một electron.',
        },
        {
          atMs: 2000,
          text: 'Electron mới vẫn ở lớp 3, nhưng hạt nhân mạnh dần nên vỏ bị kéo vào: bán kính giảm.',
        },
        {
          atMs: 4600,
          text: 'Cùng nguyên nhân đó làm độ âm điện tăng từ 0,93 lên 3,16.',
        },
      ],
    },
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'hoa10-c2-b7',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Bảng tuần hoàn các nguyên tố hoá học',
    lessonNumber: 7,
    title: 'Xu hướng biến đổi thành phần và một số tính chất của hợp chất trong một chu kì',
    hook:
      'Oxide của Sodium (Na₂O) tan trong nước tạo dung dịch base mạnh, còn oxide của Chlorine ' +
      '(Cl₂O₇) tan trong nước lại tạo acid mạnh — cùng là oxide, nhưng tính chất đối lập hoàn ' +
      'toàn tuỳ vị trí trong chu kì.',
    theory:
      'HOÁ TRỊ CAO NHẤT VỚI OXYGEN của các nguyên tố trong MỘT CHU KÌ tăng dần từ trái sang ' +
      'phải, đúng bằng số thứ tự nhóm A (với các nhóm IA đến VIIA): nhóm IA hoá trị I, nhóm ' +
      'IIA hoá trị II... nhóm VIIA hoá trị VII.\n\n' +
      'Ví dụ chu kì 3: Na₂O (hoá trị I) → MgO (II) → Al₂O₃ (III) → SiO₂ (IV) → P₂O₅ (V) → SO₃ ' +
      '(VI) → Cl₂O₇ (VII).\n\n' +
      'TÍNH ACID – BASE của oxide và hydroxide tương ứng biến đổi trong một chu kì (trái → ' +
      'phải): TỪ BASE MẠNH DẦN SANG ACID MẠNH — khớp với xu hướng tính kim loại giảm, tính ' +
      'phi kim tăng đã học ở bài trước.\n\n' +
      'Ví dụ: NaOH (base mạnh) → Mg(OH)₂ (base yếu) → Al(OH)₃ (lưỡng tính) → H₂SiO₃ (acid rất ' +
      'yếu) → H₃PO₄ (acid trung bình) → H₂SO₄ (acid mạnh) → HClO₄ (acid rất mạnh).',
    workedExample: {
      problem:
        'Trong chu kì 3, hợp chất oxide cao nhất của nguyên tố nhóm VA có công thức dạng ' +
        'tổng quát nào? (biết nguyên tố nhóm VA chu kì 3 là Phosphorus, P).',
      steps: [
        'Hoá trị cao nhất với oxygen = số thứ tự nhóm A. Nhóm VA ⇒ hoá trị cao nhất = V.',
        'Oxide cao nhất có dạng X₂Oy, với quy tắc hoá trị: 2 × (hoá trị của X) = y × (hoá ' +
          'trị của O).',
        'Với hoá trị X = V (5), oxygen hoá trị II: 5×2 = 2×y ⇒ y = 5.',
        'Công thức: P₂O₅.',
      ],
      answer: 'P₂O₅',
    },
    checkQuestions: [
      {
        prompt:
          'Hoá trị cao nhất với oxygen của nguyên tố nhóm VIA (chu kì 3, là Sulfur) là bao ' +
          'nhiêu? (chỉ nhập số)',
        answer: { kind: 'numeric', value: 6 },
        explain:
          'Hoá trị cao nhất với oxygen = số thứ tự nhóm A. Nhóm VIA ⇒ hoá trị VI, tức nhập 6.',
      },
      {
        prompt:
          'Trong một chu kì, đi từ trái sang phải, tính acid của oxide/hydroxide cao nhất biến đổi ra sao?',
        choices: [
          { id: 'tang', label: 'Tăng dần (từ base mạnh sang acid mạnh)' },
          { id: 'giam', label: 'Giảm dần (từ acid mạnh sang base mạnh)' },
        ],
        answer: { kind: 'choice', correctIds: ['tang'] },
        explain:
          'Khớp xu hướng tính kim loại giảm/phi kim tăng: oxide/hydroxide chuyển từ base mạnh (đầu chu kì) sang acid mạnh (cuối chu kì).',
      },
    ],
    srsCards: [
      {
        hoi: 'Hoá trị cao nhất với oxygen của nguyên tố nhóm A bằng gì?',
        dap: 'Bằng số thứ tự nhóm A.',
      },
      {
        hoi: 'Tính acid-base của oxide/hydroxide biến đổi thế nào trong một chu kì?',
        dap: 'Từ base mạnh (đầu chu kì) sang acid mạnh (cuối chu kì).',
      },
    ],
    animation: {
      title: 'Oxide và hydroxide cao nhất chu kì 3: từ base mạnh sang acid mạnh',
      description:
        'Một dải nằm ngang xếp bảy oxide cao nhất của chu kì 3 theo đúng thứ tự Na₂O, MgO, Al₂O₃, SiO₂, P₂O₅, SO₃, Cl₂O₇, và bên dưới là hydroxide tương ứng NaOH, Mg(OH)₂, Al(OH)₃, H₂SiO₃, H₃PO₄, H₂SO₄, HClO₄. Một con trỏ chạy từ trái sang phải: đầu dải là base mạnh, giữa dải dừng lại ở Al₂O₃ và Al(OH)₃ — chất lưỡng tính, tan được cả trong acid lẫn trong kiềm — rồi tiếp tục sang phải vào vùng acid, mạnh dần tới HClO₄ là một trong những acid mạnh nhất. Tính base giảm và tính acid tăng là cùng một chuyển động chứ không phải hai quy tắc rời nhau.',
      viewBoxWidth: 470,
      viewBoxHeight: 210,
      durationMs: 8000,
      loop: true,
      shapes: [
        {
          kind: 'rect',
          id: 'dai',
          x: 30,
          y: 70,
          w: 410,
          h: 30,
          fill: 'surface',
          stroke: 'muted',
          strokeWidth: 1.5,
          rx: 4,
        },
        {
          kind: 'label',
          id: 'o1',
          x: 60,
          y: 90,
          text: 'Na₂O',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'o2',
          x: 118,
          y: 90,
          text: 'MgO',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'o3',
          x: 176,
          y: 90,
          text: 'Al₂O₃',
          size: 11,
          anchor: 'middle',
          fill: 'primary',
        },
        {
          kind: 'label',
          id: 'o4',
          x: 234,
          y: 90,
          text: 'SiO₂',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'o5',
          x: 292,
          y: 90,
          text: 'P₂O₅',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'o6',
          x: 350,
          y: 90,
          text: 'SO₃',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'o7',
          x: 410,
          y: 90,
          text: 'Cl₂O₇',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'h1',
          x: 60,
          y: 126,
          text: 'NaOH',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'h2',
          x: 118,
          y: 126,
          text: 'Mg(OH)₂',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'h3',
          x: 176,
          y: 126,
          text: 'Al(OH)₃',
          size: 10,
          anchor: 'middle',
          fill: 'primary',
        },
        {
          kind: 'label',
          id: 'h4',
          x: 234,
          y: 126,
          text: 'H₂SiO₃',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'h5',
          x: 292,
          y: 126,
          text: 'H₃PO₄',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'h6',
          x: 350,
          y: 126,
          text: 'H₂SO₄',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'h7',
          x: 410,
          y: 126,
          text: 'HClO₄',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'tbase',
          x: 60,
          y: 56,
          text: 'base mạnh',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'tluong',
          x: 176,
          y: 56,
          text: 'lưỡng tính',
          size: 11,
          anchor: 'middle',
          fill: 'primary',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 3000,
              opacity: 0,
            },
            {
              atMs: 3500,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'tacid',
          x: 410,
          y: 56,
          text: 'acid rất mạnh',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'arrow',
          id: 'mui',
          x1: 30,
          y1: 158,
          x2: 440,
          y2: 158,
          stroke: 'accent',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'mt',
          x: 235,
          y: 176,
          text: 'tính base giảm dần — tính acid tăng dần',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'circle',
          id: 'troi',
          cx: 60,
          cy: 70,
          r: 9,
          fill: 'accent',
          opacity: 0.9,
          keyframes: [
            {
              atMs: 0,
              dx: 0,
            },
            {
              atMs: 2600,
              dx: 116,
            },
            {
              atMs: 4200,
              dx: 116,
            },
            {
              atMs: 7000,
              dx: 350,
            },
            {
              atMs: 8000,
              dx: 350,
            },
          ],
        },
      ],
      captions: [
        {
          atMs: 0,
          text: 'Đầu chu kì: Na₂O và NaOH là oxide base, hydroxide base mạnh.',
        },
        {
          atMs: 2800,
          text: 'Giữa chu kì: Al₂O₃ và Al(OH)₃ lưỡng tính — tan cả trong acid lẫn trong kiềm.',
        },
        {
          atMs: 4400,
          text: 'Cuối chu kì: SO₃, Cl₂O₇ là oxide acid; H₂SO₄, HClO₄ là acid mạnh.',
        },
      ],
    },
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'hoa10-c2-b8',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Bảng tuần hoàn các nguyên tố hoá học',
    lessonNumber: 8,
    title: 'Định luật tuần hoàn và ý nghĩa của bảng tuần hoàn các nguyên tố hoá học',
    hook:
      'Trước khi biết cấu tạo nguyên tử, Mendeleev chỉ dựa vào tính chất LẶP LẠI theo chu kì ' +
      'đã sắp xếp đúng gần như toàn bộ bảng tuần hoàn — quy luật đó giờ có tên: định luật ' +
      'tuần hoàn.',
    theory:
      'ĐỊNH LUẬT TUẦN HOÀN: tính chất của các nguyên tố và đơn chất, cũng như thành phần và ' +
      'tính chất của các hợp chất tạo nên từ các nguyên tố đó, biến đổi TUẦN HOÀN theo chiều ' +
      'tăng của điện tích hạt nhân.\n\n' +
      '"Tuần hoàn" nghĩa là LẶP LẠI có quy luật sau mỗi chu kì — không phải giống hệt, mà ' +
      'giống về XU HƯỚNG (ví dụ mọi nhóm IA đều là kim loại hoạt động mạnh, mọi nhóm VIIA ' +
      'đều là phi kim hoạt động mạnh).\n\n' +
      'Ý NGHĨA của bảng tuần hoàn: biết vị trí (ô, chu kì, nhóm) của một nguyên tố, ta suy ra ' +
      'được cấu hình electron và ngược lại; từ đó DỰ ĐOÁN được tính chất hoá học cơ bản mà ' +
      'không cần nhớ riêng từng nguyên tố — đây chính là công cụ hệ thống hoá quan trọng ' +
      'nhất của Hoá học.',
    workedExample: {
      problem:
        'Nguyên tố X ở ô số 20 trong bảng tuần hoàn, thuộc chu kì 4, nhóm IIA. Dự đoán X là ' +
        'kim loại hay phi kim, và hoá trị cao nhất với oxygen.',
      steps: [
        'X ở nhóm IIA ⇒ có 2 electron lớp ngoài cùng, dễ NHƯỜNG electron ⇒ X là KIM LOẠI.',
        'Nhóm IIA nằm ở phía đầu bảng tuần hoàn, ngay cạnh nhóm IA ⇒ tính kim loại khá mạnh ' +
          '(Ca thuộc nhóm kim loại kiềm thổ).',
        'Hoá trị cao nhất với oxygen = số thứ tự nhóm A = II.',
        'Kết luận: X là kim loại (thực tế là Calcium — Ca), hoá trị cao nhất với oxygen là II ' +
          '(oxide CaO).',
      ],
      answer: 'X là kim loại, hoá trị cao nhất với oxygen là II.',
    },
    checkQuestions: [
      {
        prompt:
          'Định luật tuần hoàn phát biểu: tính chất các nguyên tố biến đổi theo quy luật gì khi Z tăng dần?',
        choices: [
          { id: 'a', label: 'Biến đổi tuần hoàn (lặp lại có quy luật)' },
          { id: 'b', label: 'Biến đổi ngẫu nhiên, không quy luật' },
          { id: 'c', label: 'Luôn tăng liên tục, không lặp lại' },
          { id: 'd', label: 'Không đổi' },
        ],
        answer: { kind: 'choice', correctIds: ['a'] },
        explain:
          'Định luật tuần hoàn: tính chất biến đổi TUẦN HOÀN (lặp lại theo chu kì) theo chiều tăng điện tích hạt nhân.',
      },
      {
        prompt:
          'Biết vị trí của một nguyên tố trong bảng tuần hoàn (ô, chu kì, nhóm), ta có thể suy ra được điều gì?',
        choices: [
          { id: 'a', label: 'Cấu hình electron và tính chất hoá học cơ bản' },
          { id: 'b', label: 'Chỉ tên gọi, không suy ra được gì khác' },
          { id: 'c', label: 'Chỉ khối lượng riêng' },
        ],
        answer: { kind: 'choice', correctIds: ['a'] },
        explain:
          'Vị trí ô cho biết Z, số thứ tự chu kì cho biết số lớp electron, số thứ tự nhóm A ' +
          'cho biết số electron lớp ngoài cùng — đủ để viết cấu hình electron rồi suy ra tính ' +
          'chất hoá học cơ bản. Các phương án còn lại đều bó hẹp bảng tuần hoàn vào một mẩu ' +
          'thông tin rời rạc (tên gọi, khối lượng riêng), bỏ mất giá trị dự đoán của nó.',
      },
    ],
    srsCards: [
      {
        hoi: 'Định luật tuần hoàn phát biểu gì?',
        dap: 'Tính chất nguyên tố biến đổi TUẦN HOÀN theo chiều tăng điện tích hạt nhân.',
      },
      {
        hoi: 'Ý nghĩa quan trọng nhất của bảng tuần hoàn?',
        dap: 'Từ vị trí suy ra cấu hình electron và dự đoán tính chất hoá học.',
      },
    ],
    animation: {
      title: 'Bán kính nguyên tử lặp lại theo chu kì — hình răng cưa của định luật tuần hoàn',
      description:
        'Trục ngang xếp các nguyên tố theo chiều tăng của điện tích hạt nhân, trục dọc là bán kính nguyên tử tính bằng pm. Một chấm chạy dọc đường gấp khúc: trong chu kì 2 nó tụt từ Li (152 pm) xuống F (71 pm), rồi tới Na nó nhảy vọt lên 186 pm — cao hơn cả Li; qua chu kì 3 nó lại tụt đều xuống Cl (99 pm), rồi tới K lại nhảy lên 227 pm. Hình răng cưa đó chính là định luật tuần hoàn nhìn thấy được: tính chất không tăng hay giảm một mạch theo số hiệu nguyên tử, mà lặp lại có chu kì mỗi khi bắt đầu một lớp electron mới.',
      viewBoxWidth: 470,
      viewBoxHeight: 240,
      durationMs: 8000,
      loop: true,
      shapes: [
        {
          kind: 'line',
          id: 'tx',
          x1: 45,
          y1: 210,
          x2: 450,
          y2: 210,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'line',
          id: 'ty',
          x1: 45,
          y1: 210,
          x2: 45,
          y2: 40,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'ty-t',
          x: 50,
          y: 36,
          text: 'bán kính (pm)',
          size: 10,
          anchor: 'start',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'tx-t',
          x: 250,
          y: 232,
          text: 'điện tích hạt nhân tăng dần →',
          size: 11,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'polyline',
          id: 'duong',
          points: [
            [60, 119],
            [86, 143],
            [112, 159],
            [138, 164],
            [164, 165],
            [190, 166],
            [216, 167],
            [242, 98],
            [268, 114],
            [294, 124],
            [320, 140],
            [346, 144],
            [372, 148],
            [398, 151],
            [424, 74],
          ],
          stroke: 'primary',
          strokeWidth: 2.5,
        },
        {
          kind: 'label',
          id: 'li',
          x: 60,
          y: 110,
          text: 'Li',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'f',
          x: 216,
          y: 182,
          text: 'F',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'na',
          x: 242,
          y: 89,
          text: 'Na',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'cl',
          x: 398,
          y: 166,
          text: 'Cl',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'k',
          x: 424,
          y: 64,
          text: 'K',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'line',
          id: 'mocck2',
          x1: 229,
          y1: 55,
          x2: 229,
          y2: 210,
          stroke: 'muted',
          strokeWidth: 1.5,
          dash: '4 3',
        },
        {
          kind: 'line',
          id: 'mocck3',
          x1: 411,
          y1: 55,
          x2: 411,
          y2: 210,
          stroke: 'muted',
          strokeWidth: 1.5,
          dash: '4 3',
        },
        {
          kind: 'label',
          id: 'ck2',
          x: 138,
          y: 50,
          text: 'chu kì 2',
          size: 11,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'ck3',
          x: 320,
          y: 50,
          text: 'chu kì 3',
          size: 11,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'circle',
          id: 'cham',
          cx: 60,
          cy: 119,
          r: 7,
          fill: 'accent',
          keyframes: [
            { atMs: 0, dx: 0, dy: 0 },
            { atMs: 433, dx: 26, dy: 24 },
            { atMs: 867, dx: 52, dy: 40 },
            { atMs: 1300, dx: 78, dy: 45 },
            { atMs: 1733, dx: 104, dy: 46 },
            { atMs: 2167, dx: 130, dy: 47 },
            { atMs: 2600, dx: 156, dy: 48 },
            { atMs: 3200, dx: 182, dy: -21 },
            { atMs: 3667, dx: 208, dy: -5 },
            { atMs: 4133, dx: 234, dy: 5 },
            { atMs: 4600, dx: 260, dy: 21 },
            { atMs: 5067, dx: 286, dy: 25 },
            { atMs: 5533, dx: 312, dy: 29 },
            { atMs: 6000, dx: 338, dy: 32 },
            { atMs: 6600, dx: 364, dy: -45 },
            { atMs: 8000, dx: 364, dy: -45 },
          ],
        },
      ],
      captions: [
        {
          atMs: 0,
          text: 'Trong chu kì 2, bán kính tụt đều từ Li xuống F.',
        },
        {
          atMs: 3000,
          text: 'Sang Na — mở lớp electron thứ 3 — bán kính nhảy vọt lên 186 pm.',
        },
        {
          atMs: 6200,
          text: 'Sang K lại nhảy lên lần nữa: tính chất lặp lại tuần hoàn, không đơn điệu.',
        },
      ],
    },
    track: 'core',
    reviewStatus: 'draft',
  },
]
