// lessons/hoa12c2.ts — Hoá học 12, Chương 2: Carbohydrate (4 bài).
// Đối chiếu mục lục thật: tai-lieu-sgk/SGK-Hoa/12/page_0004.png (OCR 2026-08-31).
// reviewStatus='draft' — soạn từ docs/research/kho-kien-thuc-hoa-gdpt2018.md §3, chưa duyệt.
import type { ChemLesson } from '../lessonTypes.js'

export const HOA12_C2_LESSONS: ChemLesson[] = [
  {
    id: 'hoa12-c2-b4',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Carbohydrate',
    lessonNumber: 4,
    title: 'Glucose và fructose',
    hook:
      'Nho chín có vị ngọt đậm đà nhờ đường glucose. Mật ong ngọt sắc lịm là do đường fructose. ' +
      'Đây là hai nguồn năng lượng carbohydrate đơn giản nhất nuôi sống tế bào.',
    theory:
      'PHÂN LOẠI CARBOHYDRATE:\n' +
      '— Carbohydrate (tên gọi cũ: gluxit, saccarit) là những hợp chất hữu cơ tạp chức, thường có công thức chung Cₙ(H₂O)ₘ.\n' +
      '— Chia làm 3 nhóm chính: Monosaccharide (không bị thuỷ phân, vd: glucose, fructose); Disaccharide (thuỷ phân tạo 2 monosaccharide, vd: saccharose, maltose); Polysaccharide (thuỷ phân tạo nhiều monosaccharide, vd: tinh bột, cellulose).\n\n' +
      'GLUCOSE VÀ FRUCTOSE (C₆H₁₂O₆ = 180):\n' +
      '— Glucose và fructose là hai chất đồng phân của nhau.\n' +
      '— Cấu trúc glucose: Là hợp chất tạp chức, dạng mạch hở là polyhydroxy aldehyde (có 5 nhóm −OH và 1 nhóm −CHO). Trong dung dịch, glucose tồn tại chủ yếu ở hai dạng vòng: α-glucose và β-glucose.\n' +
      '— Cấu trúc fructose: Dạng mạch hở là polyhydroxy ketone (có 5 nhóm −OH và 1 nhóm ketone C=O ở vị trí C số 2).\n\n' +
      'TÍNH CHẤT HOÁ HỌC CỦA GLUCOSE:\n' +
      '1. Tính chất của polyalcohol: Hoà tan Cu(OH)₂ ở nhiệt độ thường tạo dung dịch màu xanh lam thẫm (do có nhiều nhóm −OH kề nhau).\n' +
      '2. Tính chất của aldehyde: Phản ứng tráng bạc với thuốc thử Tollens (tạo gương Ag); phản ứng với Cu(OH)₂/NaOH nóng tạo kết tủa đỏ gạch Cu₂O.\n' +
      '   * Lưu ý: Fructose không có nhóm −CHO nhưng vẫn có phản ứng tráng bạc vì trong môi trường kiềm (NH₃), fructose chuyển hoá thuận nghịch thành glucose.\n' +
      '3. Phản ứng cộng hydrogen: C₆H₁₂O₆ + H₂ → C₆H₁₄O₆ (Sorbitol) (t°, Ni).\n' +
      '4. Phản ứng lên men rượu: C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂↑ (men rượu, 30 - 35 °C).',
    workedExample: {
      problem:
        'Thực hiện phản ứng tráng bạc hoàn toàn 1,8 gam glucose (C₆H₁₂O₆, M=180) với lượng dư ' +
        'thuốc thử Tollens. Tính khối lượng bạc (Ag, M=108) tạo thành.',
      steps: [
        'Tính số mol glucose: n = 1,8 / 180 = 0,01 mol.',
        'Vì glucose có 1 nhóm −CHO tự do nên 1 mol glucose phản ứng tạo ra 2 mol Ag.',
        'Tính số mol bạc tạo thành: nAg = 2 * n(glucose) = 2 * 0,01 = 0,02 mol.',
        'Tính khối lượng bạc kết tủa: mAg = 0,02 * 108 = 2,16 gam.',
      ],
      answer: '2,16 gam',
    },
    checkQuestions: [
      {
        prompt: 'Glucose và fructose có cùng công thức phân tử nào sau đây?',
        choices: [
          { id: 'c6h12o6', label: 'C₆H₁₂O₆' },
          { id: 'c12h22o11', label: 'C₁₂H₂₂O₁₁' },
          { id: 'c6h10o5', label: 'C₆H₁₀O₅' },
        ],
        answer: { kind: 'choice', correctIds: ['c6h12o6'] },
        explain:
          'Glucose và fructose là đồng phân cấu tạo của nhau, có cùng công thức phân tử C₆H₁₂O₆.',
      },
      {
        prompt:
          'Khi hydrogen hoá hoàn toàn glucose bằng khí H₂ (xúc tác Ni, đun nóng), sản phẩm hữu cơ thu được là gì?',
        choices: [
          { id: 'gluconic', label: 'Gluconic acid' },
          { id: 'sorbitol', label: 'Sorbitol' },
          { id: 'ethanol', label: 'Ethanol' },
        ],
        answer: { kind: 'choice', correctIds: ['sorbitol'] },
        explain:
          'Nhóm −CHO của glucose bị hydrogen khử thành nhóm −CH₂OH, cho sorbitol C₆H₁₄O₆ — một polyalcohol 6 chức. Gluconic acid là sản phẩm khi OXI HOÁ nhóm −CHO, còn ethanol là sản phẩm của phản ứng lên men, không phải của phản ứng cộng H₂.',
      },
    ],
    srsCards: [
      { hoi: 'Glucose thuộc loại carbohydrate nào?', dap: 'Monosaccharide (đường đơn).' },
      {
        hoi: 'Tại sao fructose vẫn tham gia phản ứng tráng bạc dù không có nhóm −CHO?',
        dap: 'Vì trong môi trường kiềm của phản ứng tráng bạc, fructose chuyển hoá thành glucose.',
      },
      {
        hoi: 'Sản phẩm của phản ứng lên men glucose?',
        dap: 'Ethanol (C₂H₅OH) và khí carbon dioxide (CO₂).',
      },
    ],
    animation: {
      title: 'Glucose: mạch hở có nhóm CHO cuộn lại thành vòng sáu cạnh',
      description:
        'Bên trái là glucose dạng mạch hở: sáu carbon đánh số 1 đến 6, carbon số 1 là nhóm CHO (aldehyde), năm nhóm OH gắn ở carbon số 2 đến số 6. Mũi tên cong cho thấy cách mạch khép vòng: oxygen của nhóm OH ở carbon số 5 cộng vào carbon của nhóm CHO. Bên phải là dạng vòng sáu cạnh gồm năm carbon và một oxygen; oxygen trong vòng chính là oxygen của nhóm OH ở C5, còn oxygen của nhóm CHO cũ trở thành nhóm OH mới ở C1 (tô cùng màu). Tuỳ nhóm OH mới này nằm phía nào của vòng mà có hai dạng α và β. Mũi tên hai chiều ở giữa: các dạng chuyển hoá qua lại liên tục; dạng vòng chiếm gần như toàn bộ, mạch hở chỉ rất ít. Nhóm CHO chỉ có ở mạch hở, nhưng khi nó bị oxi hoá hết thì cân bằng lại sinh thêm mạch hở, nên glucose vẫn tráng bạc hoàn toàn.',
      viewBoxWidth: 460,
      viewBoxHeight: 240,
      durationMs: 8000,
      loop: true,
      shapes: [
        {
          kind: 'line',
          id: 'lk1',
          x1: 96,
          y1: 62,
          x2: 96,
          y2: 74,
          stroke: 'muted',
          strokeWidth: 1.6,
        },
        {
          kind: 'line',
          id: 'lk2',
          x1: 96,
          y1: 90,
          x2: 96,
          y2: 100,
          stroke: 'muted',
          strokeWidth: 1.6,
        },
        {
          kind: 'line',
          id: 'lk3',
          x1: 96,
          y1: 116,
          x2: 96,
          y2: 126,
          stroke: 'muted',
          strokeWidth: 1.6,
        },
        {
          kind: 'line',
          id: 'lk4',
          x1: 96,
          y1: 142,
          x2: 96,
          y2: 152,
          stroke: 'muted',
          strokeWidth: 1.6,
        },
        {
          kind: 'line',
          id: 'lk5',
          x1: 96,
          y1: 168,
          x2: 96,
          y2: 178,
          stroke: 'muted',
          strokeWidth: 1.6,
        },
        {
          kind: 'polyline',
          id: 'cuon',
          points: [
            [116, 160],
            [123.6, 159.2],
            [131, 157],
            [138, 153.3],
            [144.3, 148.3],
            [149.7, 142.1],
            [154.1, 135],
            [157.3, 127.1],
            [159.3, 118.7],
            [160, 110],
            [159.3, 101.3],
            [157.3, 92.9],
            [154.1, 85],
            [149.7, 77.9],
            [144.3, 71.7],
            [138, 66.7],
          ],
          stroke: 'accent',
          strokeWidth: 2,
          dash: '4 3',
          opacity: 0,
          keyframes: [
            { atMs: 1700, opacity: 0 },
            { atMs: 2200, opacity: 1 },
          ],
        },
        {
          kind: 'arrow',
          id: 'cuon-dau',
          x1: 138,
          y1: 66.7,
          x2: 121.3,
          y2: 55.7,
          stroke: 'accent',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 1700, opacity: 0 },
            { atMs: 2200, opacity: 1 },
          ],
        },
        {
          kind: 'polyline',
          id: 'vong',
          points: [
            [372, 93.8],
            [386, 118],
            [368, 149.2],
            [332, 149.2],
            [314, 118],
            [332, 86.8],
            [360, 86.8],
          ],
          stroke: 'primary',
          strokeWidth: 2.5,
          opacity: 0,
          keyframes: [
            { atMs: 3000, opacity: 0 },
            { atMs: 3500, opacity: 1 },
          ],
        },
        {
          kind: 'line',
          id: 'nt-C1',
          x1: 386,
          y1: 118,
          x2: 400,
          y2: 118,
          stroke: 'muted',
          strokeWidth: 1.6,
          opacity: 0,
          keyframes: [
            { atMs: 3400, opacity: 0 },
            { atMs: 3900, opacity: 1 },
          ],
        },
        {
          kind: 'line',
          id: 'nt-C2',
          x1: 368,
          y1: 149.2,
          x2: 375,
          y2: 161.3,
          stroke: 'muted',
          strokeWidth: 1.6,
          opacity: 0,
          keyframes: [
            { atMs: 3400, opacity: 0 },
            { atMs: 3900, opacity: 1 },
          ],
        },
        {
          kind: 'line',
          id: 'nt-C3',
          x1: 332,
          y1: 149.2,
          x2: 325,
          y2: 161.3,
          stroke: 'muted',
          strokeWidth: 1.6,
          opacity: 0,
          keyframes: [
            { atMs: 3400, opacity: 0 },
            { atMs: 3900, opacity: 1 },
          ],
        },
        {
          kind: 'line',
          id: 'nt-C4',
          x1: 314,
          y1: 118,
          x2: 300,
          y2: 118,
          stroke: 'muted',
          strokeWidth: 1.6,
          opacity: 0,
          keyframes: [
            { atMs: 3400, opacity: 0 },
            { atMs: 3900, opacity: 1 },
          ],
        },
        {
          kind: 'line',
          id: 'nt-C5',
          x1: 332,
          y1: 86.8,
          x2: 325,
          y2: 74.7,
          stroke: 'muted',
          strokeWidth: 1.6,
          opacity: 0,
          keyframes: [
            { atMs: 3400, opacity: 0 },
            { atMs: 3900, opacity: 1 },
          ],
        },
        {
          kind: 'arrow',
          id: 'cb1',
          x1: 190,
          y1: 104,
          x2: 262,
          y2: 104,
          stroke: 'muted',
          strokeWidth: 1.8,
          opacity: 0,
          keyframes: [
            { atMs: 3800, opacity: 0 },
            { atMs: 4300, opacity: 1 },
          ],
        },
        {
          kind: 'arrow',
          id: 'cb2',
          x1: 262,
          y1: 116,
          x2: 190,
          y2: 116,
          stroke: 'muted',
          strokeWidth: 1.8,
          opacity: 0,
          keyframes: [
            { atMs: 3800, opacity: 0 },
            { atMs: 4300, opacity: 1 },
          ],
        },
        {
          kind: 'rect',
          id: 'khung-cho',
          x: 78,
          y: 44,
          w: 36,
          h: 19,
          rx: 4,
          stroke: 'accent',
          strokeWidth: 1.5,
          opacity: 0,
          keyframes: [
            { atMs: 5500, opacity: 0 },
            { atMs: 6000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'm1',
          x: 96,
          y: 58,
          text: 'CHO',
          size: 13,
          anchor: 'middle',
          fill: 'accent',
        },
        {
          kind: 'label',
          id: 'so1',
          x: 68,
          y: 58,
          text: '1',
          size: 9,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'm2',
          x: 96,
          y: 86,
          text: 'CHOH',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'so2',
          x: 68,
          y: 86,
          text: '2',
          size: 9,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'm3',
          x: 96,
          y: 112,
          text: 'CHOH',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'so3',
          x: 68,
          y: 112,
          text: '3',
          size: 9,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'm4',
          x: 96,
          y: 138,
          text: 'CHOH',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'so4',
          x: 68,
          y: 138,
          text: '4',
          size: 9,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'm5',
          x: 96,
          y: 164,
          text: 'CHOH',
          size: 12,
          anchor: 'middle',
          fill: 'accent',
        },
        {
          kind: 'label',
          id: 'so5',
          x: 68,
          y: 164,
          text: '5',
          size: 9,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'm6',
          x: 96,
          y: 190,
          text: 'CH₂OH',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'so6',
          x: 68,
          y: 190,
          text: '6',
          size: 9,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'o-vong',
          x: 368,
          y: 91,
          text: 'O',
          size: 12,
          anchor: 'middle',
          fill: 'accent',
          opacity: 0,
          keyframes: [
            { atMs: 3000, opacity: 0 },
            { atMs: 3500, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'tt-C1',
          x: 403,
          y: 122,
          text: 'OH',
          size: 10,
          anchor: 'start',
          fill: 'accent',
          opacity: 0,
          keyframes: [
            { atMs: 3400, opacity: 0 },
            { atMs: 3900, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'tt-C2',
          x: 377,
          y: 171.3,
          text: 'OH',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 3400, opacity: 0 },
            { atMs: 3900, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'tt-C3',
          x: 323,
          y: 171.3,
          text: 'OH',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 3400, opacity: 0 },
            { atMs: 3900, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'tt-C4',
          x: 297,
          y: 122,
          text: 'HO',
          size: 10,
          anchor: 'end',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 3400, opacity: 0 },
            { atMs: 3900, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'tt-C5',
          x: 322,
          y: 68.7,
          text: 'CH₂OH',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 3400, opacity: 0 },
            { atMs: 3900, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'sv1',
          x: 373,
          y: 121,
          text: '1',
          size: 8,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 3400, opacity: 0 },
            { atMs: 3900, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'sv2',
          x: 361.5,
          y: 141,
          text: '2',
          size: 8,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 3400, opacity: 0 },
            { atMs: 3900, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'sv3',
          x: 338.5,
          y: 141,
          text: '3',
          size: 8,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 3400, opacity: 0 },
            { atMs: 3900, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'sv4',
          x: 327,
          y: 121,
          text: '4',
          size: 8,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 3400, opacity: 0 },
            { atMs: 3900, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'sv5',
          x: 338.5,
          y: 101,
          text: '5',
          size: 8,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 3400, opacity: 0 },
            { atMs: 3900, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'cuont1',
          x: 166,
          y: 150,
          text: 'O của nhóm OH ở C5 cộng vào',
          size: 9.5,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 1700, opacity: 0 },
            { atMs: 2200, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'cuont2',
          x: 166,
          y: 163,
          text: 'C của nhóm CHO → khép vòng',
          size: 9.5,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 1700, opacity: 0 },
            { atMs: 2200, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'cbt',
          x: 226,
          y: 94,
          text: 'chuyển hoá qua lại',
          size: 9.5,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 3800, opacity: 0 },
            { atMs: 4300, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'mht',
          x: 96,
          y: 214,
          text: 'dạng mạch hở',
          size: 10.5,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'mht2',
          x: 96,
          y: 228,
          text: 'chỉ một phần rất nhỏ',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 4300, opacity: 0 },
            { atMs: 4800, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'vongt',
          x: 350,
          y: 200,
          text: 'dạng mạch vòng 6 cạnh (α và β)',
          size: 10.5,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 4300, opacity: 0 },
            { atMs: 4800, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'vongt2',
          x: 350,
          y: 214,
          text: 'chiếm gần như toàn bộ',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            { atMs: 4300, opacity: 0 },
            { atMs: 4800, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'trangbac',
          x: 16,
          y: 24,
          text: 'Nhóm –CHO chỉ có ở mạch hở → tráng bạc, khử Cu(OH)₂ khi đun nóng',
          size: 10,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 5500, opacity: 0 },
            { atMs: 6000, opacity: 1 },
          ],
        },
      ],
      captions: [
        {
          atMs: 0,
          text: 'Dạng mạch hở: mạch 6 carbon, C1 là nhóm –CHO, còn 5 nhóm OH nằm ở C2 đến C6.',
        },
        {
          atMs: 1700,
          text: 'Oxygen của nhóm OH ở C5 cộng vào carbon của nhóm CHO: mạch khép lại thành vòng 6 cạnh (5 C và 1 O).',
        },
        {
          atMs: 3000,
          text: 'Oxygen của nhóm CHO cũ trở thành nhóm OH mới ở C1; tuỳ nhóm OH này nằm phía nào mà có dạng α hay β.',
        },
        {
          atMs: 3800,
          text: 'Các dạng chuyển hoá qua lại liên tục; trong dung dịch, dạng vòng chiếm gần như toàn bộ.',
        },
        {
          atMs: 5500,
          text: 'Nhóm –CHO chỉ có ở mạch hở. Khi nó phản ứng hết, cân bằng lại sinh thêm mạch hở — nên glucose vẫn tráng bạc hoàn toàn.',
        },
      ],
    },
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'hoa12-c2-b5',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Carbohydrate',
    lessonNumber: 5,
    title: 'Saccharose và maltose',
    hook:
      'Đường mía chúng ta ăn hằng ngày chứa chủ yếu saccharose. Mầm lúa mạch dùng để ủ bia ' +
      'chứa nhiều maltose. Đây là hai disaccharide phổ biến nhất.',
    theory:
      'SACCHAROSE (C₁₂H₂₂O₁₁ = 342):\n' +
      '— Trạng thái: Chất rắn kết tinh, không màu, vị ngọt, tan tốt trong nước (có nhiều trong cây mía, củ cải đường, hoa thốt nốt).\n' +
      '— Cấu trúc phân tử: Là disaccharide được cấu tạo từ 1 gốc α-glucose và 1 gốc β-fructose liên kết qua nguyên tử oxygen. Phân tử không có nhóm aldehyde (−CHO) tự do nên KHÔNG có phản ứng tráng bạc (được gọi là đường không khử).\n\n' +
      'TÍNH CHẤT HOÁ HỌC CỦA SACCHAROSE:\n' +
      '1. Tính chất của polyalcohol: Hoà tan Cu(OH)₂ ở nhiệt độ thường tạo dung dịch màu xanh lam thẫm.\n' +
      '2. Phản ứng thuỷ phân (tính chất quan trọng nhất, xúc tác acid hoặc enzyme):\n' +
      '   C₁₂H₂₂O₁₁ + H₂O → C₆H₁₂O₆ (glucose) + C₆H₁₂O₆ (fructose).\n\n' +
      'MALTOSE (ĐỒNG PHÂN CỦA SACCHAROSE):\n' +
      '— Cấu tạo từ 2 gốc α-glucose. Ở dạng mạch hở có chứa nhóm aldehyde tự do nên có tính khử (có phản ứng tráng bạc, hoà tan Cu(OH)₂ nóng tạo kết tủa đỏ gạch).',
    workedExample: {
      problem:
        'Thuỷ phân hoàn toàn 3,42 gam saccharose (C₁₂H₂₂O₁₁, M=342) trong môi trường acid. ' +
        'Lấy toàn bộ sản phẩm thu được cho tác dụng hoàn toàn với dung dịch Tollens dư. ' +
        'Tính số mol bạc (Ag) kết tủa thu được.',
      steps: [
        'Tính số mol saccharose: n = 3,42 / 342 = 0,01 mol.',
        'Viết phương trình thuỷ phân: Saccharose + H₂O → Glucose + Fructose.',
        'Số mol sản phẩm: n(glucose) = 0,01 mol; n(fructose) = 0,01 mol.',
        'Cho sản phẩm tác dụng với thuốc thử Tollens: cả glucose và fructose đều tráng bạc, mỗi mol đường cho 2 mol Ag.',
        'Tổng số mol Ag sinh ra: nAg = 2 * n(glucose) + 2 * n(fructose) = 2 * 0,01 + 2 * 0,01 = 0,04 mol.',
      ],
      answer: '0,04 mol',
    },
    checkQuestions: [
      {
        prompt: 'Saccharose trực tiếp phản ứng được với chất nào sau đây ở nhiệt độ thường?',
        choices: [
          { id: 'tollens', label: 'Thuốc thử Tollens' },
          { id: 'cuoh2', label: 'Cu(OH)₂ (tạo dung dịch xanh lam)' },
          { id: 'h2', label: 'Khí hydrogen (Ni, t°)' },
        ],
        answer: { kind: 'choice', correctIds: ['cuoh2'] },
        explain:
          'Saccharose có nhiều nhóm −OH kề nhau nên hoà tan được Cu(OH)₂ tạo dung dịch xanh lam ở nhiệt độ thường. Nó không tráng bạc trực tiếp do không có nhóm −CHO tự do.',
      },
      {
        prompt:
          'Khi thuỷ phân hoàn toàn saccharose trong môi trường acid, thu được hỗn hợp monosaccharide nào?',
        choices: [
          { id: 'hai_glu', label: 'Hai phân tử glucose' },
          { id: 'glu_fru', label: 'Một phân tử glucose và một phân tử fructose' },
          { id: 'hai_fru', label: 'Hai phân tử fructose' },
        ],
        answer: { kind: 'choice', correctIds: ['glu_fru'] },
        explain:
          'Saccharose cấu tạo từ gốc glucose và fructose nên khi thuỷ phân sinh ra cả glucose và fructose với tỉ lệ mol 1:1.',
      },
    ],
    srsCards: [
      { hoi: 'Saccharose thuộc loại carbohydrate nào?', dap: 'Disaccharide (đường đôi).' },
      {
        hoi: 'Tại sao saccharose không có phản ứng tráng bạc trực tiếp?',
        dap: 'Vì phân tử không có nhóm aldehyde (−CHO) tự do.',
      },
      { hoi: 'Sản phẩm thuỷ phân saccharose gồm những gì?', dap: 'Glucose và fructose.' },
    ],
    animation: {
      title: 'Thuỷ phân saccharose: liên kết glycoside đứt, nhóm CHO được giải phóng',
      description:
        'Phân tử saccharose gồm một đơn vị glucose và một đơn vị fructose nối nhau qua một cầu oxygen — liên kết glycoside. Cầu nối này chiếm đúng vị trí nhóm chức khử của cả hai đơn vị, nên saccharose nguyên vẹn KHÔNG tráng được gương bạc: ống nghiệm bên trái vẫn trong suốt. Khi đun với dung dịch acid loãng, một phân tử nước cắt đứt cầu oxygen: nhóm OH và nguyên tử H của nước gắn vào hai đầu vừa cắt, tách saccharose thành một phân tử glucose và một phân tử fructose. Glucose tự do mở vòng được nên nhóm CHO lộ ra, và thử lại phản ứng tráng bạc thì lớp bạc sáng bám lên thành ống nghiệm bên phải. Cùng một chất mà trước và sau thuỷ phân cho kết quả thử nghiệm trái ngược nhau.',
      viewBoxWidth: 470,
      viewBoxHeight: 230,
      durationMs: 8000,
      loop: true,
      shapes: [
        {
          kind: 'polyline',
          id: 'g1',
          points: [
            [114, 96],
            [99, 122],
            [69, 122],
            [54, 96],
            [69, 70],
            [99, 70],
          ],
          closed: true,
          stroke: 'primary',
          strokeWidth: 2,
          keyframes: [
            { atMs: 4000, dx: 0 },
            { atMs: 4600, dx: -22 },
          ],
        },
        {
          kind: 'polyline',
          id: 'f1',
          points: [
            [170, 96],
            [188, 71.3],
            [217, 80.7],
            [217, 111.3],
            [188, 120.7],
          ],
          closed: true,
          stroke: 'accent',
          strokeWidth: 2,
          keyframes: [
            { atMs: 4000, dx: 0 },
            { atMs: 4600, dx: 22 },
          ],
        },
        {
          kind: 'line',
          id: 'cl',
          x1: 114,
          y1: 96,
          x2: 135,
          y2: 96,
          stroke: 'primary',
          strokeWidth: 2,
          keyframes: [
            { atMs: 3400, opacity: 1 },
            { atMs: 4000, opacity: 0 },
          ],
        },
        {
          kind: 'line',
          id: 'cr',
          x1: 149,
          y1: 96,
          x2: 170,
          y2: 96,
          stroke: 'accent',
          strokeWidth: 2,
          keyframes: [
            { atMs: 3400, opacity: 1 },
            { atMs: 4000, opacity: 0 },
          ],
        },
        {
          kind: 'line',
          id: 'oh-g',
          x1: 92,
          y1: 96,
          x2: 102,
          y2: 96,
          stroke: 'muted',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 4600, opacity: 0 },
            { atMs: 5000, opacity: 1 },
          ],
        },
        {
          kind: 'line',
          id: 'oh-f',
          x1: 192,
          y1: 96,
          x2: 182,
          y2: 96,
          stroke: 'muted',
          strokeWidth: 2,
          opacity: 0,
          keyframes: [
            { atMs: 4600, opacity: 0 },
            { atMs: 5000, opacity: 1 },
          ],
        },
        {
          kind: 'polyline',
          id: 'dd1',
          points: [
            [292.5, 84],
            [292.5, 128],
            [292.8, 131],
            [293.6, 134],
            [294.8, 136.8],
            [296.6, 139.2],
            [298.8, 141.4],
            [301.2, 143.2],
            [304, 144.4],
            [307, 145.2],
            [310, 145.5],
            [313, 145.2],
            [316, 144.4],
            [318.8, 143.2],
            [321.2, 141.4],
            [323.4, 139.2],
            [325.2, 136.8],
            [326.4, 134],
            [327.2, 131],
            [327.5, 128],
            [327.5, 84],
          ],
          closed: true,
          fill: 'primary',
          opacity: 0.18,
        },
        {
          kind: 'polyline',
          id: 'o1',
          points: [
            [290, 46],
            [290, 128],
            [290.3, 131.5],
            [291.2, 134.8],
            [292.7, 138],
            [294.7, 140.9],
            [297.1, 143.3],
            [300, 145.3],
            [303.2, 146.8],
            [306.5, 147.7],
            [310, 148],
            [313.5, 147.7],
            [316.8, 146.8],
            [320, 145.3],
            [322.9, 143.3],
            [325.3, 140.9],
            [327.3, 138],
            [328.8, 134.8],
            [329.7, 131.5],
            [330, 128],
            [330, 46],
          ],
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'polyline',
          id: 'dd2',
          points: [
            [392.5, 84],
            [392.5, 128],
            [392.8, 131],
            [393.6, 134],
            [394.8, 136.8],
            [396.6, 139.2],
            [398.8, 141.4],
            [401.2, 143.2],
            [404, 144.4],
            [407, 145.2],
            [410, 145.5],
            [413, 145.2],
            [416, 144.4],
            [418.8, 143.2],
            [421.2, 141.4],
            [423.4, 139.2],
            [425.2, 136.8],
            [426.4, 134],
            [427.2, 131],
            [427.5, 128],
            [427.5, 84],
          ],
          closed: true,
          fill: 'primary',
          opacity: 0.18,
        },
        {
          kind: 'polyline',
          id: 'bac',
          points: [
            [393, 70],
            [393, 128],
            [393.3, 131],
            [394, 133.8],
            [395.3, 136.5],
            [397, 138.9],
            [399.1, 141],
            [401.5, 142.7],
            [404.2, 144],
            [407, 144.7],
            [410, 145],
            [413, 144.7],
            [415.8, 144],
            [418.5, 142.7],
            [420.9, 141],
            [423, 138.9],
            [424.7, 136.5],
            [426, 133.8],
            [426.7, 131],
            [427, 128],
            [427, 70],
          ],
          stroke: 'muted',
          strokeWidth: 3.5,
          opacity: 0,
          keyframes: [
            { atMs: 5400, opacity: 0 },
            { atMs: 6600, opacity: 0.9 },
          ],
        },
        {
          kind: 'polyline',
          id: 'o2',
          points: [
            [390, 46],
            [390, 128],
            [390.3, 131.5],
            [391.2, 134.8],
            [392.7, 138],
            [394.7, 140.9],
            [397.1, 143.3],
            [400, 145.3],
            [403.2, 146.8],
            [406.5, 147.7],
            [410, 148],
            [413.5, 147.7],
            [416.8, 146.8],
            [420, 145.3],
            [422.9, 143.3],
            [425.3, 140.9],
            [427.3, 138],
            [428.8, 134.8],
            [429.7, 131.5],
            [430, 128],
            [430, 46],
          ],
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'g1t',
          x: 84,
          y: 100,
          text: 'glucose',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
          keyframes: [
            { atMs: 4000, dx: 0 },
            { atMs: 4600, dx: -22 },
          ],
        },
        {
          kind: 'label',
          id: 'f1t',
          x: 196,
          y: 100,
          text: 'fructose',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
          keyframes: [
            { atMs: 4000, dx: 0 },
            { atMs: 4600, dx: 22 },
          ],
        },
        {
          kind: 'label',
          id: 'cau',
          x: 142,
          y: 100,
          text: 'O',
          size: 13,
          anchor: 'middle',
          fill: 'accent',
          keyframes: [
            { atMs: 3400, opacity: 1 },
            { atMs: 4000, opacity: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'caut',
          x: 142,
          y: 44,
          text: 'liên kết glycoside',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'h2o',
          x: 142,
          y: 146,
          text: 'H₂O (H⁺, t°)',
          size: 12,
          anchor: 'middle',
          fill: 'accent',
          opacity: 0,
          keyframes: [
            { atMs: 2600, opacity: 0, dy: 30 },
            { atMs: 3400, opacity: 1, dy: 0 },
          ],
        },
        {
          kind: 'label',
          id: 'oh-gt',
          x: 104,
          y: 100,
          text: 'OH',
          size: 10,
          anchor: 'start',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 4600, opacity: 0 },
            { atMs: 5000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'oh-ft',
          x: 180,
          y: 100,
          text: 'HO',
          size: 10,
          anchor: 'end',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 4600, opacity: 0 },
            { atMs: 5000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'o1t',
          x: 310,
          y: 170,
          text: 'saccharose',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'o1k',
          x: 310,
          y: 186,
          text: 'không tráng bạc',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'o2t',
          x: 410,
          y: 170,
          text: 'sau thuỷ phân',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'o2k',
          x: 410,
          y: 186,
          text: 'có gương bạc',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 6600, opacity: 0 },
            { atMs: 7000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'kl',
          x: 235,
          y: 216,
          text: 'Nhóm CHO của glucose chỉ lộ ra sau khi cầu oxygen bị cắt',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            { atMs: 5100, opacity: 0 },
            { atMs: 5500, opacity: 1 },
          ],
        },
      ],
      captions: [
        {
          atMs: 0,
          text: 'Saccharose = glucose + fructose nối qua cầu oxygen (liên kết glycoside).',
        },
        { atMs: 1400, text: 'Cầu nối khoá mất nhóm chức khử nên saccharose không tráng bạc.' },
        {
          atMs: 3400,
          text: 'Đun với acid loãng: nước cắt đứt cầu, OH và H của nước gắn vào hai đầu — tách thành glucose và fructose.',
        },
        {
          atMs: 6600,
          text: 'Nhóm CHO tự do trở lại — thử tráng bạc lần này cho lớp gương bạc bám thành ống.',
        },
      ],
    },
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'hoa12-c2-b6',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Carbohydrate',
    lessonNumber: 6,
    title: 'Tinh bột và cellulose',
    hook:
      'Gạo tẻ chứa tinh bột — nguồn dự trữ năng lượng của cây lúa. Bông nõn chứa cellulose tinh khiết ' +
      '— bộ khung vách tế bào thực vật dai bền. Cả hai đều là những polysaccharide khổng lồ.',
    theory:
      'TINH BỘT ((C₆H₁₀O₅)ₙ):\n' +
      '— Cấu trúc: Là polymer của các gốc α-glucose liên kết α-1,4-glycoside và α-1,6-glycoside. Gồm 2 dạng chính:\n' +
      '  1. Amylose: mạch không phân nhánh, xoắn lại thành hình lò xo.\n' +
      '  2. Amylopectin: mạch phân nhánh nhiều.\n' +
      '— Phản ứng đặc trưng: Tác dụng với Iodine (I₂) tạo phức màu xanh tím đặc trưng (ở nhiệt độ thường, đun nóng mất màu, nguội hiện lại). Phản ứng thuỷ phân đến cùng tạo glucose.\n\n' +
      'CELLULOSE ((C₆H₁₀O₅)ₙ):\n' +
      '— Cấu trúc: Là polymer của các gốc β-glucose liên kết β-1,4-glycoside tạo mạch thẳng, kéo sợi bền vững, không xoắn, không phân nhánh.\n' +
      '— Công thức cấu tạo: [C₆H₇O₂(OH)₃]ₙ (mỗi mắt xích có 3 nhóm −OH tự do).\n' +
      '— Phản ứng hoá học đặc trưng:\n' +
      '  1. Tác dụng với HNO₃ đặc (xúc tác H₂SO₄ đặc nóng): tạo cellulose trinitrate dùng làm thuốc súng không khói: [C₆H₇O₂(OH)₃]ₙ + 3n HNO₃ → [C₆H₇O₂(ONO₂)₃]ₙ + 3n H₂O.\n' +
      '  2. Phản ứng thuỷ phân: Bị thuỷ phân đến cùng trong dung dịch acid đặc nóng tạo thành glucose.',
    workedExample: {
      problem:
        'Nhận biết dung dịch hồ tinh bột và dung dịch glucose đựng trong hai lọ mất nhãn bằng một thuốc thử ' +
        'đơn giản ở nhiệt độ thường.',
      steps: [
        'Lấy một ít mỗi dung dịch ra hai ống nghiệm làm mẫu thử.',
        'Nhỏ vài giọt dung dịch iodine (I₂) vào hai mẫu thử.',
        'Mẫu xuất hiện màu xanh tím đặc trưng là hồ tinh bột (do cấu trúc lò xo của amylose hấp phụ iodine).',
        'Mẫu không có hiện tượng gì ở nhiệt độ thường là glucose.',
      ],
      answer: 'Dùng dung dịch iodine',
    },
    checkQuestions: [
      {
        prompt: 'Thuốc thử đặc trưng dùng để nhận biết nhanh hồ tinh bột là chất nào?',
        choices: [
          { id: 'cuoh2', label: 'Cu(OH)₂' },
          { id: 'iodine', label: 'Dung dịch Iodine (I₂)' },
          { id: 'tollens', label: 'Thuốc thử Tollens' },
        ],
        answer: { kind: 'choice', correctIds: ['iodine'] },
        explain:
          'Phân tử iodine chui vào lòng xoắn lò xo của amylose và bị hấp phụ ở đó, cho màu xanh tím đặc trưng. Cu(OH)₂ và thuốc thử Tollens đều không cho dấu hiệu gì với tinh bột, vì tinh bột không có nhóm −CHO tự do.',
      },
      {
        prompt: 'Cellulose trinitrate được sản xuất từ phản ứng giữa cellulose và chất nào?',
        choices: [
          { id: 'hno3', label: 'HNO₃ đặc (xúc tác H₂SO₄ đặc)' },
          { id: 'hcl', label: 'HCl đặc' },
          { id: 'ch3cooh', label: 'CH₃COOH khan' },
        ],
        answer: { kind: 'choice', correctIds: ['hno3'] },
        explain:
          'Ba nhóm −OH tự do trên mỗi mắt xích của cellulose phản ứng ester hoá với HNO₃ tạo cellulose trinitrate [C₆H₇O₂(ONO₂)₃]ₙ.',
      },
    ],
    srsCards: [
      {
        hoi: 'Công thức cấu tạo thu gọn của cellulose biểu diễn các nhóm −OH tự do?',
        dap: '[C₆H₇O₂(OH)₃]ₙ.',
      },
      {
        hoi: 'Hiện tượng tinh bột tác dụng với iodine?',
        dap: 'Xuất hiện màu xanh tím ở nhiệt độ thường.',
      },
      {
        hoi: 'Sản phẩm thuỷ phân đến cùng của cả tinh bột và cellulose là gì?',
        dap: 'Glucose (C₆H₁₂O₆).',
      },
    ],
    animation: {
      title: 'Tinh bột xoắn lò xo, cellulose duỗi thẳng — hai kiểu nối từ cùng một glucose',
      description:
        'Cả hai polymer đều làm từ đúng một loại mắt xích glucose, khác nhau chỉ ở kiểu liên kết glycoside. Bên trái là amylose của tinh bột: nối kiểu α-1,4 làm mạch bẻ góc đều đặn và cuộn lại thành hình lò xo; khoang giữa lò xo vừa vặn nhốt phân tử iodine, nên hồ tinh bột gặp iodine cho màu xanh tím — chấm iodine trong hình chui vào lòng xoắn và cả vùng đổi màu. Bên phải là cellulose: nối kiểu β-1,4 làm mỗi mắt xích lật ngược so với mắt xích trước, mạch duỗi thẳng tắp; nhiều mạch thẳng nằm song song rồi được liên kết hydrogen ghép thành bó sợi rất bền — đó là lý do sợi bông và gỗ chắc. Cùng viên gạch, cách xếp khác nhau cho hai vật liệu khác hẳn: một cái để ăn, một cái để dệt.',
      viewBoxWidth: 470,
      viewBoxHeight: 240,
      durationMs: 8000,
      loop: true,
      shapes: [
        {
          kind: 'label',
          id: 'tt',
          x: 120,
          y: 32,
          text: 'Tinh bột (amylose) — liên kết α-1,4',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'rect',
          id: 'vung-mau',
          x: 30,
          y: 80,
          w: 190,
          h: 64,
          rx: 12,
          fill: 'primary',
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 3000, opacity: 0 },
            { atMs: 3600, opacity: 0.18 },
            { atMs: 8000, opacity: 0.18 },
          ],
        },
        {
          kind: 'polyline',
          id: 'xoan',
          points: [
            [40, 90],
            [37.4, 90.4],
            [34.9, 91.7],
            [32.8, 93.7],
            [31.1, 96.4],
            [30.1, 99.8],
            [29.7, 103.6],
            [30.1, 107.7],
            [31.4, 112],
            [33.4, 116.3],
            [36.4, 120.4],
            [40.1, 124.2],
            [44.5, 127.6],
            [49.5, 130.3],
            [54.9, 132.3],
            [60.7, 133.6],
            [66.7, 134],
            [72.7, 133.6],
            [78.5, 132.3],
            [83.9, 130.3],
            [88.9, 127.6],
            [93.3, 124.2],
            [97, 120.4],
            [100, 116.3],
            [102.1, 112],
            [103.3, 107.7],
            [103.7, 103.6],
            [103.4, 99.8],
            [102.3, 96.4],
            [100.6, 93.7],
            [98.5, 91.7],
            [96, 90.4],
            [93.4, 90],
            [90.8, 90.4],
            [88.3, 91.7],
            [86.2, 93.7],
            [84.5, 96.4],
            [83.5, 99.8],
            [83.1, 103.6],
            [83.5, 107.7],
            [84.8, 112],
            [86.9, 116.3],
            [89.8, 120.4],
            [93.5, 124.2],
            [97.9, 127.6],
            [102.9, 130.3],
            [108.4, 132.3],
            [114.1, 133.6],
            [120.1, 134],
            [126.1, 133.6],
            [131.9, 132.3],
            [137.3, 130.3],
            [142.3, 127.6],
            [146.7, 124.2],
            [150.4, 120.4],
            [153.4, 116.3],
            [155.5, 112],
            [156.7, 107.7],
            [157.1, 103.6],
            [156.8, 99.8],
            [155.7, 96.4],
            [154, 93.7],
            [151.9, 91.7],
            [149.4, 90.4],
            [146.8, 90],
            [144.2, 90.4],
            [141.7, 91.7],
            [139.6, 93.7],
            [137.9, 96.4],
            [136.9, 99.8],
            [136.5, 103.6],
            [136.9, 107.7],
            [138.2, 112],
            [140.3, 116.3],
            [143.2, 120.4],
            [146.9, 124.2],
            [151.3, 127.6],
            [156.3, 130.3],
            [161.8, 132.3],
            [167.6, 133.6],
            [173.5, 134],
            [179.5, 133.6],
            [185.3, 132.3],
            [190.7, 130.3],
            [195.7, 127.6],
            [200.2, 124.2],
            [203.9, 120.4],
            [206.8, 116.3],
            [208.9, 112],
            [210.1, 107.7],
            [210.5, 103.6],
            [210.2, 99.8],
            [209.1, 96.4],
            [207.4, 93.7],
            [205.3, 91.7],
            [202.8, 90.4],
            [200.2, 90],
          ],
          stroke: 'primary',
          strokeWidth: 2.5,
        },
        {
          kind: 'circle',
          id: 'iot',
          cx: 120,
          cy: 112,
          r: 8,
          fill: 'accent',
          keyframes: [
            { atMs: 0, dx: -70, dy: 80, opacity: 0 },
            { atMs: 1200, dx: -70, dy: 80, opacity: 1 },
            { atMs: 3000, dx: 0, dy: 0, opacity: 1 },
            { atMs: 8000, dx: 0, dy: 0, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'iott',
          x: 120,
          y: 202,
          text: 'iodine lọt vào lòng xoắn → xanh tím',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 3000,
              opacity: 0,
            },
            {
              atMs: 3600,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'ttv',
          x: 120,
          y: 222,
          text: 'dễ bị enzyme thuỷ phân — làm thức ăn',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 3600,
              opacity: 0,
            },
            {
              atMs: 4200,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'line',
          id: 'chia',
          x1: 236,
          y1: 40,
          x2: 236,
          y2: 220,
          stroke: 'muted',
          strokeWidth: 1.5,
          dash: '5 5',
        },
        {
          kind: 'label',
          id: 'cel',
          x: 356,
          y: 32,
          text: 'Cellulose — liên kết β-1,4',
          size: 11,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'polyline',
          id: 's1',
          points: [
            [266, 70],
            [306, 62],
            [346, 70],
            [386, 62],
            [426, 70],
            [446, 66],
          ],
          stroke: 'primary',
          strokeWidth: 2.5,
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 4400,
              opacity: 0,
            },
            {
              atMs: 4900,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'polyline',
          id: 's2',
          points: [
            [266, 100],
            [306, 92],
            [346, 100],
            [386, 92],
            [426, 100],
            [446, 96],
          ],
          stroke: 'primary',
          strokeWidth: 2.5,
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 4900,
              opacity: 0,
            },
            {
              atMs: 5400,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'polyline',
          id: 's3',
          points: [
            [266, 130],
            [306, 122],
            [346, 130],
            [386, 122],
            [426, 130],
            [446, 126],
          ],
          stroke: 'primary',
          strokeWidth: 2.5,
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 5400,
              opacity: 0,
            },
            {
              atMs: 5900,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'line',
          id: 'hb1',
          x1: 306,
          y1: 64,
          x2: 306,
          y2: 92,
          stroke: 'accent',
          strokeWidth: 1.8,
          dash: '3 3',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 6000,
              opacity: 0,
            },
            {
              atMs: 6500,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'line',
          id: 'hb2',
          x1: 386,
          y1: 64,
          x2: 386,
          y2: 92,
          stroke: 'accent',
          strokeWidth: 1.8,
          dash: '3 3',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 6000,
              opacity: 0,
            },
            {
              atMs: 6500,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'line',
          id: 'hb3',
          x1: 306,
          y1: 94,
          x2: 306,
          y2: 122,
          stroke: 'accent',
          strokeWidth: 1.8,
          dash: '3 3',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 6000,
              opacity: 0,
            },
            {
              atMs: 6500,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'line',
          id: 'hb4',
          x1: 386,
          y1: 94,
          x2: 386,
          y2: 122,
          stroke: 'accent',
          strokeWidth: 1.8,
          dash: '3 3',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 6000,
              opacity: 0,
            },
            {
              atMs: 6500,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'celt',
          x: 356,
          y: 168,
          text: 'mạch thẳng xếp song song',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 5400,
              opacity: 0,
            },
            {
              atMs: 5900,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'celt2',
          x: 356,
          y: 188,
          text: 'liên kết hydrogen ghép thành bó sợi bền',
          size: 10,
          anchor: 'middle',
          fill: 'neutral',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 6000,
              opacity: 0,
            },
            {
              atMs: 6500,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'celt3',
          x: 356,
          y: 214,
          text: 'người không tiêu hoá được — làm sợi, giấy',
          size: 10,
          anchor: 'middle',
          fill: 'muted',
          opacity: 0,
          keyframes: [
            {
              atMs: 0,
              opacity: 0,
            },
            {
              atMs: 6600,
              opacity: 0,
            },
            {
              atMs: 7100,
              opacity: 1,
            },
            {
              atMs: 8000,
              opacity: 1,
            },
          ],
        },
      ],
      captions: [
        {
          atMs: 0,
          text: 'Cả hai đều làm từ mắt xích glucose, khác nhau ở kiểu liên kết glycoside.',
        },
        {
          atMs: 1400,
          text: 'α-1,4 làm mạch amylose cuộn thành lò xo.',
        },
        {
          atMs: 3000,
          text: 'Iodine lọt vào lòng xoắn — hồ tinh bột hoá xanh tím.',
        },
        {
          atMs: 4400,
          text: 'β-1,4 làm mỗi mắt xích lật ngược, mạch cellulose duỗi thẳng.',
        },
        {
          atMs: 6000,
          text: 'Các mạch thẳng ghép bằng liên kết hydrogen thành bó sợi rất bền.',
        },
      ],
    },
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'hoa12-c2-b7',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Carbohydrate',
    lessonNumber: 7,
    title: 'Ôn tập chương 2 — Carbohydrate',
    hook:
      'Chương 2 dựng lại bức tranh toàn cảnh về carbohydrate — vừa là nguồn năng lượng chính của cơ thể, ' +
      'vừa là vật liệu dựng nên thân cây, sợi bông và trang giấy.',
    theory:
      'TỔNG KẾT SO SÁNH CÁC CARBOHYDRATE THƯỜNG GẶP:\n' +
      '1. Monosaccharide: Glucose và Fructose (C₆H₁₂O₆). Đều hoà tan Cu(OH)₂ xanh lam, đều tráng bạc (fructose tráng bạc trong môi trường kiềm).\n' +
      '2. Disaccharide: Saccharose (C₁₂H₂₂O₁₁). Hoà tan Cu(OH)₂ xanh lam. Không tráng bạc trực tiếp, thuỷ phân ra glucose + fructose.\n' +
      '3. Polysaccharide: Tinh bột và Cellulose ((C₆H₁₀O₅)ₙ). Thuỷ phân đến cùng đều tạo glucose. Tinh bột làm xanh tím iodine. Cellulose có 3 nhóm −OH tự do, phản ứng HNO₃ tạo thuốc súng không khói.',
    workedExample: {
      problem:
        'Nhận biết 4 dung dịch mất nhãn sau bằng phương pháp hoá học: glycerol, glucose, saccharose, và hồ tinh bột.',
      steps: [
        'Lấy một ít mỗi dung dịch ra bốn ống nghiệm làm mẫu thử.',
        'Dùng dung dịch iodine ở nhiệt độ thường: mẫu hoá xanh tím là hồ tinh bột.',
        'Với 3 mẫu còn lại, nhỏ dung dịch Cu(OH)₂ ở nhiệt độ thường: cả 3 đều hoà tan tạo dung dịch xanh lam thẫm.',
        'Đun nóng nhẹ 3 ống nghiệm xanh lam: chỉ có mẫu glucose xuất hiện kết tủa đỏ gạch Cu₂O (do có nhóm −CHO). Hai mẫu kia không đổi màu.',
        'Để phân biệt glycerol và saccharose: thực hiện thuỷ phân 2 mẫu thử bằng acid, rồi trung hoà và thử Tollens. Mẫu saccharose sau khi thuỷ phân cho phản ứng tráng gương (do sinh ra glucose và fructose). Glycerol không phản ứng.',
      ],
      answer: 'Dùng Iodine, Cu(OH)₂ thường và đun nóng',
    },
    checkQuestions: [
      {
        prompt: 'Chất nào sau đây KHÔNG bị thuỷ phân trong môi trường acid?',
        choices: [
          { id: 'glu', label: 'Glucose' },
          { id: 'sac', label: 'Saccharose' },
          { id: 'starch', label: 'Tinh bột' },
        ],
        answer: { kind: 'choice', correctIds: ['glu'] },
        explain:
          'Glucose là monosaccharide — đường đơn, không ghép từ các gốc đường nhỏ hơn, nên không thuỷ phân được. Saccharose ghép từ hai gốc đường, còn tinh bột ghép từ rất nhiều gốc glucose, nên cả hai đều bị thuỷ phân.',
      },
      {
        prompt:
          'Phương pháp hoá học nhanh nhất để phát hiện vết tinh bột có trong nước giò chả là gì?',
        choices: [
          { id: 'a', label: 'Nhỏ vài giọt dung dịch Iodine (I₂)' },
          { id: 'b', label: 'Thử bằng thuốc thử Tollens' },
          { id: 'c', label: 'Thử bằng dung dịch NaOH' },
        ],
        answer: { kind: 'choice', correctIds: ['a'] },
        explain:
          'Chỉ cần nhỏ vài giọt dung dịch iodine: nếu trong nước giò chả có tinh bột thì lập tức xuất hiện màu xanh tím đặc trưng. Thuốc thử Tollens chỉ phát hiện nhóm −CHO, còn NaOH không cho dấu hiệu nào nhìn thấy được.',
      },
    ],
    srsCards: [
      { hoi: 'Đường nho là tên gọi của loại đường nào?', dap: 'Glucose.' },
      { hoi: 'Đường mía là tên gọi của loại đường nào?', dap: 'Saccharose.' },
      {
        hoi: 'Maltose có tráng bạc được không?',
        dap: 'Có (vì cấu trúc mạch hở có chứa nhóm −CHO tự do).',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
]
