// lessonsLazy.ts — TỆP SINH TỰ ĐỘNG, ĐỪNG SỬA TAY.
// Sinh bởi `npm run gen:stem-lesson-index` (scripts/gen-stem-lesson-index.ts).
// Thêm hoặc sửa bài học xong PHẢI chạy lại lệnh đó, nếu không chỉ mục lệch với nội dung thật.
import type { StemLessonSummary } from '@dhcb/core-contracts/stemLesson'
import type { BiologyLesson } from './lessonTypes.js'

export const LESSON_INDEX: StemLessonSummary[] = [
  {
    id: 'sinh10-c1-b1',
    grade: '10',
    chapterNumber: 1,
    chapterTitle: 'Phần mở đầu',
    lessonNumber: 1,
    title: 'Giới thiệu khái quát môn Sinh học',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c1',
  },
  {
    id: 'sinh10-c1-b2',
    grade: '10',
    chapterNumber: 1,
    chapterTitle: 'Phần mở đầu',
    lessonNumber: 2,
    title: 'Phương pháp nghiên cứu và học tập môn Sinh học',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c1',
  },
  {
    id: 'sinh10-c1-b3',
    grade: '10',
    chapterNumber: 1,
    chapterTitle: 'Phần mở đầu',
    lessonNumber: 3,
    title: 'Các cấp độ tổ chức của thế giới sống',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c1',
  },
  {
    id: 'sinh10-c2-b4',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Thành phần hoá học của tế bào',
    lessonNumber: 4,
    title: 'Các nguyên tố hoá học và nước',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c1',
  },
  {
    id: 'sinh10-c2-b5',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Thành phần hoá học của tế bào',
    lessonNumber: 5,
    title: 'Các phân tử sinh học',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c1',
  },
  {
    id: 'sinh10-c2-b6',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Thành phần hoá học của tế bào',
    lessonNumber: 6,
    title: 'Thực hành: Nhận biết một số phân tử sinh học',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c1',
  },
  {
    id: 'sinh10-c3-b7',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Cấu trúc tế bào',
    lessonNumber: 7,
    title: 'Tế bào nhân sơ',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c2',
  },
  {
    id: 'sinh10-c3-b8',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Cấu trúc tế bào',
    lessonNumber: 8,
    title: 'Tế bào nhân thực',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c2',
  },
  {
    id: 'sinh10-c3-b9',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Cấu trúc tế bào',
    lessonNumber: 9,
    title: 'Thực hành: Quan sát tế bào',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c2',
  },
  {
    id: 'sinh10-c4-b10',
    grade: '10',
    chapterNumber: 4,
    chapterTitle: 'Trao đổi chất qua màng và truyền tin tế bào',
    lessonNumber: 10,
    title: 'Trao đổi chất qua màng tế bào',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c2',
  },
  {
    id: 'sinh10-c4-b11',
    grade: '10',
    chapterNumber: 4,
    chapterTitle: 'Trao đổi chất qua màng và truyền tin tế bào',
    lessonNumber: 11,
    title: 'Thực hành: Thí nghiệm co và phản co nguyên sinh',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c2',
  },
  {
    id: 'sinh10-c4-b12',
    grade: '10',
    chapterNumber: 4,
    chapterTitle: 'Trao đổi chất qua màng và truyền tin tế bào',
    lessonNumber: 12,
    title: 'Truyền tin tế bào',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c2',
  },
  {
    id: 'sinh10-c5-b13',
    grade: '10',
    chapterNumber: 5,
    chapterTitle: 'Chuyển hoá năng lượng trong tế bào',
    lessonNumber: 13,
    title: 'Khái quát về chuyển hoá vật chất và năng lượng',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c3',
  },
  {
    id: 'sinh10-c5-b14',
    grade: '10',
    chapterNumber: 5,
    chapterTitle: 'Chuyển hoá năng lượng trong tế bào',
    lessonNumber: 14,
    title: 'Phân giải và tổng hợp các chất trong tế bào',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c3',
  },
  {
    id: 'sinh10-c5-b15',
    grade: '10',
    chapterNumber: 5,
    chapterTitle: 'Chuyển hoá năng lượng trong tế bào',
    lessonNumber: 15,
    title:
      'Thực hành: Thí nghiệm phân tích ảnh hưởng của một số yếu tố đến hoạt tính của enzyme và kiểm tra hoạt tính của enzyme amylase',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c3',
  },
  {
    id: 'sinh10-c6-b16',
    grade: '10',
    chapterNumber: 6,
    chapterTitle: 'Chu kì tế bào và phân bào',
    lessonNumber: 16,
    title: 'Chu kì tế bào và nguyên phân',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c3',
  },
  {
    id: 'sinh10-c6-b17',
    grade: '10',
    chapterNumber: 6,
    chapterTitle: 'Chu kì tế bào và phân bào',
    lessonNumber: 17,
    title: 'Giảm phân',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c3',
  },
  {
    id: 'sinh10-c6-b18',
    grade: '10',
    chapterNumber: 6,
    chapterTitle: 'Chu kì tế bào và phân bào',
    lessonNumber: 18,
    title: 'Thực hành: Làm và quan sát tiêu bản quá trình nguyên phân và giảm phân',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c3',
  },
  {
    id: 'sinh10-c6-b19',
    grade: '10',
    chapterNumber: 6,
    chapterTitle: 'Chu kì tế bào và phân bào',
    lessonNumber: 19,
    title: 'Công nghệ tế bào',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c3',
  },
  {
    id: 'sinh10-c7-b20',
    grade: '10',
    chapterNumber: 7,
    chapterTitle: 'Sinh học vi sinh vật',
    lessonNumber: 20,
    title: 'Khái quát về vi sinh vật',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c4',
  },
  {
    id: 'sinh10-c7-b21',
    grade: '10',
    chapterNumber: 7,
    chapterTitle: 'Sinh học vi sinh vật',
    lessonNumber: 21,
    title: 'Trao đổi chất, sinh trưởng và sinh sản ở vi sinh vật',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c4',
  },
  {
    id: 'sinh10-c7-b22',
    grade: '10',
    chapterNumber: 7,
    chapterTitle: 'Sinh học vi sinh vật',
    lessonNumber: 22,
    title: 'Vai trò và ứng dụng của vi sinh vật',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c4',
  },
  {
    id: 'sinh10-c7-b23',
    grade: '10',
    chapterNumber: 7,
    chapterTitle: 'Sinh học vi sinh vật',
    lessonNumber: 23,
    title: 'Thực hành: Một số phương pháp nghiên cứu vi sinh vật',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c4',
  },
  {
    id: 'sinh10-c8-b24',
    grade: '10',
    chapterNumber: 8,
    chapterTitle: 'Virus và các ứng dụng',
    lessonNumber: 24,
    title: 'Khái quát về virus',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c4',
  },
  {
    id: 'sinh10-c8-b25',
    grade: '10',
    chapterNumber: 8,
    chapterTitle: 'Virus và các ứng dụng',
    lessonNumber: 25,
    title: 'Một số bệnh do virus và các thành tựu nghiên cứu ứng dụng virus',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c4',
  },
  {
    id: 'sinh10-c8-b26',
    grade: '10',
    chapterNumber: 8,
    chapterTitle: 'Virus và các ứng dụng',
    lessonNumber: 26,
    title:
      'Thực hành: Điều tra một số bệnh do virus gây ra và nhân giống cây trồng bằng nuôi cấy mô',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh10c4',
  },
  {
    id: 'sinh11-c1-b1',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Trao đổi chất và chuyển hoá năng lượng ở sinh vật',
    lessonNumber: 1,
    title: 'Khái quát về trao đổi chất và chuyển hóa năng lượng ở sinh vật',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c1',
  },
  {
    id: 'sinh11-c1-b2',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Trao đổi chất và chuyển hoá năng lượng ở sinh vật',
    lessonNumber: 2,
    title: 'Trao đổi nước và khoáng ở thực vật',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c1',
  },
  {
    id: 'sinh11-c1-b3',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Trao đổi chất và chuyển hoá năng lượng ở sinh vật',
    lessonNumber: 3,
    title: 'Thực hành: Một số thí nghiệm về trao đổi nước và khoáng ở thực vật',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c1',
  },
  {
    id: 'sinh11-c1-b4',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Trao đổi chất và chuyển hoá năng lượng ở sinh vật',
    lessonNumber: 4,
    title: 'Quang hợp ở thực vật',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c1',
  },
  {
    id: 'sinh11-c1-b5',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Trao đổi chất và chuyển hoá năng lượng ở sinh vật',
    lessonNumber: 5,
    title: 'Thực hành: Một số thí nghiệm về quang hợp ở thực vật',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c1',
  },
  {
    id: 'sinh11-c1-b6',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Trao đổi chất và chuyển hoá năng lượng ở sinh vật',
    lessonNumber: 6,
    title: 'Hô hấp ở thực vật',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c1',
  },
  {
    id: 'sinh11-c1-b7',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Trao đổi chất và chuyển hoá năng lượng ở sinh vật',
    lessonNumber: 7,
    title: 'Thực hành: Một số thí nghiệm về hô hấp ở thực vật',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c1',
  },
  {
    id: 'sinh11-c1-b8',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Trao đổi chất và chuyển hoá năng lượng ở sinh vật',
    lessonNumber: 8,
    title: 'Dinh dưỡng và tiêu hóa ở động vật',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c1',
  },
  {
    id: 'sinh11-c1-b9',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Trao đổi chất và chuyển hoá năng lượng ở sinh vật',
    lessonNumber: 9,
    title: 'Hô hấp ở động vật',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c1',
  },
  {
    id: 'sinh11-c1-b10',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Trao đổi chất và chuyển hoá năng lượng ở sinh vật',
    lessonNumber: 10,
    title: 'Tuần hoàn ở động vật',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c1',
  },
  {
    id: 'sinh11-c1-b11',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Trao đổi chất và chuyển hoá năng lượng ở sinh vật',
    lessonNumber: 11,
    title: 'Thực hành: Một số thí nghiệm về tuần hoàn ở động vật',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c1',
  },
  {
    id: 'sinh11-c1-b12',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Trao đổi chất và chuyển hoá năng lượng ở sinh vật',
    lessonNumber: 12,
    title: 'Bài tiết và cân bằng nội môi',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c1',
  },
  {
    id: 'sinh11-c2-b13',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Cảm ứng ở sinh vật',
    lessonNumber: 13,
    title: 'Cảm ứng ở thực vật',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c2',
  },
  {
    id: 'sinh11-c2-b14',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Cảm ứng ở sinh vật',
    lessonNumber: 14,
    title: 'Thực hành: Một số thí nghiệm về cảm ứng ở thực vật',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c2',
  },
  {
    id: 'sinh11-c2-b15',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Cảm ứng ở sinh vật',
    lessonNumber: 15,
    title: 'Cảm ứng ở động vật',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c2',
  },
  {
    id: 'sinh11-c2-b16',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Cảm ứng ở sinh vật',
    lessonNumber: 16,
    title: 'Thực hành: Một số thí nghiệm về cảm ứng ở động vật',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c2',
  },
  {
    id: 'sinh11-c3-b17',
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Sinh trưởng và phát triển ở sinh vật',
    lessonNumber: 17,
    title: 'Sinh trưởng và phát triển ở thực vật',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c2',
  },
  {
    id: 'sinh11-c3-b18',
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Sinh trưởng và phát triển ở sinh vật',
    lessonNumber: 18,
    title: 'Thực hành: Một số thí nghiệm về sinh trưởng và phát triển ở thực vật',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c2',
  },
  {
    id: 'sinh11-c3-b19',
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Sinh trưởng và phát triển ở sinh vật',
    lessonNumber: 19,
    title: 'Sinh trưởng và phát triển ở động vật',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c2',
  },
  {
    id: 'sinh11-c3-b20',
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Sinh trưởng và phát triển ở sinh vật',
    lessonNumber: 20,
    title: 'Thực hành: Quan sát các giai đoạn sinh trưởng, phát triển ở động vật và vẽ vòng đời',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c2',
  },
  {
    id: 'sinh11-c4-b21',
    grade: '11',
    chapterNumber: 4,
    chapterTitle: 'Sinh sản ở sinh vật',
    lessonNumber: 21,
    title: 'Sinh sản ở thực vật',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c2',
  },
  {
    id: 'sinh11-c4-b22',
    grade: '11',
    chapterNumber: 4,
    chapterTitle: 'Sinh sản ở sinh vật',
    lessonNumber: 22,
    title: 'Thực hành: Nhân giống vô tính ở thực vật và thụ phấn nhân tạo',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c2',
  },
  {
    id: 'sinh11-c4-b23',
    grade: '11',
    chapterNumber: 4,
    chapterTitle: 'Sinh sản ở sinh vật',
    lessonNumber: 23,
    title: 'Sinh sản ở động vật',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c2',
  },
  {
    id: 'sinh11-c4-b24',
    grade: '11',
    chapterNumber: 4,
    chapterTitle: 'Sinh sản ở sinh vật',
    lessonNumber: 24,
    title:
      'Thực hành: Khảo sát hiện tượng thụ tinh ở động vật và tìm hiểu các biện pháp tránh thai',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c2',
  },
  {
    id: 'sinh11-c5-b25',
    grade: '11',
    chapterNumber: 5,
    chapterTitle:
      'Mối quan hệ giữa các quá trình sinh lý trong cơ thể sinh vật và ngành nghề liên quan',
    lessonNumber: 25,
    title: 'Mối quan hệ giữa các quá trình sinh lý trong cơ thể sinh vật',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c2',
  },
  {
    id: 'sinh11-c5-b26',
    grade: '11',
    chapterNumber: 5,
    chapterTitle:
      'Mối quan hệ giữa các quá trình sinh lý trong cơ thể sinh vật và ngành nghề liên quan',
    lessonNumber: 26,
    title: 'Một số ngành nghề liên quan đến sinh học cơ thể',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh11c2',
  },
  {
    id: 'sinh12-c1-b1',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Cơ chế di truyền và biến dị',
    lessonNumber: 1,
    title: 'Gen, mã di truyền và nhân đôi ADN',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c1-b2',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Cơ chế di truyền và biến dị',
    lessonNumber: 2,
    title: 'Phiên mã và dịch mã',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c1-b3',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Cơ chế di truyền và biến dị',
    lessonNumber: 3,
    title: 'Điều hòa biểu hiện gen',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c1-b4',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Cơ chế di truyền và biến dị',
    lessonNumber: 4,
    title: 'Đột biến gen',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c1-b5',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Cơ chế di truyền và biến dị',
    lessonNumber: 5,
    title: 'Nhiễm sắc thể và đột biến cấu trúc nhiễm sắc thể',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c1-b6',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Cơ chế di truyền và biến dị',
    lessonNumber: 6,
    title: 'Đột biến số lượng nhiễm sắc thể',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c1-b7',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Cơ chế di truyền và biến dị',
    lessonNumber: 7,
    title: 'Thực hành: Quan sát tiêu bản nhiễm sắc thể và đột biến nhiễm sắc thể',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c2-b8',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Tính quy luật của hiện tượng di truyền',
    lessonNumber: 8,
    title: 'Học thuyết di truyền của Mendel',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c2-b9',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Tính quy luật của hiện tượng di truyền',
    lessonNumber: 9,
    title: 'Tương tác gen và tác động đa hiệu của gen',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c2-b10',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Tính quy luật của hiện tượng di truyền',
    lessonNumber: 10,
    title: 'Liên kết gen và hoán vị gen',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c2-b11',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Tính quy luật của hiện tượng di truyền',
    lessonNumber: 11,
    title: 'Di truyền liên kết giới tính và di truyền ngoài nhân',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c2-b12',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Tính quy luật của hiện tượng di truyền',
    lessonNumber: 12,
    title: 'Ảnh hưởng của môi trường lên sự biểu hiện của gen',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c2-b13',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Tính quy luật của hiện tượng di truyền',
    lessonNumber: 13,
    title: 'Thực hành: Lai giống',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c3-b14',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Di truyền học quần thể',
    lessonNumber: 14,
    title: 'Cấu trúc di truyền của quần thể',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c3-b15',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Di truyền học quần thể',
    lessonNumber: 15,
    title: 'Trạng thái cân bằng di truyền của quần thể ngẫu phối',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c4-b16',
    grade: '12',
    chapterNumber: 4,
    chapterTitle: 'Ứng dụng di truyền học',
    lessonNumber: 16,
    title: 'Chọn giống vật nuôi và cây trồng bằng phương pháp truyền thống',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c4-b17',
    grade: '12',
    chapterNumber: 4,
    chapterTitle: 'Ứng dụng di truyền học',
    lessonNumber: 17,
    title: 'Chọn giống bằng công nghệ tế bào',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c4-b18',
    grade: '12',
    chapterNumber: 4,
    chapterTitle: 'Ứng dụng di truyền học',
    lessonNumber: 18,
    title: 'Chọn giống bằng công nghệ gen',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c5-b19',
    grade: '12',
    chapterNumber: 5,
    chapterTitle: 'Di truyền học người',
    lessonNumber: 19,
    title: 'Di truyền y học và bảo vệ vốn gen loài người',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c1',
  },
  {
    id: 'sinh12-c6-b20',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Bằng chứng và cơ chế tiến hoá',
    lessonNumber: 20,
    title: 'Bằng chứng tiến hoá',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c2',
  },
  {
    id: 'sinh12-c6-b21',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Bằng chứng và cơ chế tiến hoá',
    lessonNumber: 21,
    title: 'Học thuyết tiến hoá của Darwin',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c2',
  },
  {
    id: 'sinh12-c6-b22',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Bằng chứng và cơ chế tiến hoá',
    lessonNumber: 22,
    title: 'Thuyết tiến hoá tổng hợp hiện đại và các nhân tố tiến hoá',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c2',
  },
  {
    id: 'sinh12-c6-b23',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Bằng chứng và cơ chế tiến hoá',
    lessonNumber: 23,
    title: 'Hình thành loài và tiến hoá lớn',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c2',
  },
  {
    id: 'sinh12-c7-b24',
    grade: '12',
    chapterNumber: 7,
    chapterTitle: 'Sự phát sinh và phát triển sự sống trên Trái Đất',
    lessonNumber: 24,
    title: 'Nguồn gốc sự sống và tiến hoá của sinh giới qua các đại địa chất',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c2',
  },
  {
    id: 'sinh12-c8-b25',
    grade: '12',
    chapterNumber: 8,
    chapterTitle: 'Sinh thái học cá thể và quần thể',
    lessonNumber: 25,
    title: 'Sinh thái học và sinh thái học cá thể',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c2',
  },
  {
    id: 'sinh12-c8-b26',
    grade: '12',
    chapterNumber: 8,
    chapterTitle: 'Sinh thái học cá thể và quần thể',
    lessonNumber: 26,
    title: 'Quần thể sinh vật và các đặc trưng cơ bản',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c2',
  },
  {
    id: 'sinh12-c9-b27',
    grade: '12',
    chapterNumber: 9,
    chapterTitle: 'Quần xã sinh vật',
    lessonNumber: 27,
    title: 'Quần xã sinh vật và các mối quan hệ trong quần xã',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c2',
  },
  {
    id: 'sinh12-c10-b28',
    grade: '12',
    chapterNumber: 10,
    chapterTitle: 'Hệ sinh thái, sinh quyển và bảo vệ môi trường',
    lessonNumber: 28,
    title: 'Hệ sinh thái',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c2',
  },
  {
    id: 'sinh12-c10-b29',
    grade: '12',
    chapterNumber: 10,
    chapterTitle: 'Hệ sinh thái, sinh quyển và bảo vệ môi trường',
    lessonNumber: 29,
    title: 'Chu trình sinh địa hoá và sinh quyển',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c2',
  },
  {
    id: 'sinh12-c10-b30',
    grade: '12',
    chapterNumber: 10,
    chapterTitle: 'Hệ sinh thái, sinh quyển và bảo vệ môi trường',
    lessonNumber: 30,
    title: 'Bảo vệ đa dạng sinh học và môi trường',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c2',
  },
  {
    id: 'sinh12-c11-b31',
    grade: '12',
    chapterNumber: 11,
    chapterTitle: 'Sinh thái học phục hồi, bảo tồn và phát triển bền vững',
    lessonNumber: 31,
    title: 'Sinh thái học phục hồi và bảo tồn',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c3',
  },
  {
    id: 'sinh12-c11-b32',
    grade: '12',
    chapterNumber: 11,
    chapterTitle: 'Sinh thái học phục hồi, bảo tồn và phát triển bền vững',
    lessonNumber: 32,
    title: 'Phát triển bền vững và dấu chân sinh thái',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'sinh12c3',
  },
]

export const CHAPTER_LOADERS: Record<string, () => Promise<BiologyLesson[]>> = {
  sinh10c1: () => import('./lessons/sinh10c1.js').then((m) => m.SINH10_C1_LESSONS),
  sinh10c2: () => import('./lessons/sinh10c2.js').then((m) => m.SINH10_C2_LESSONS),
  sinh10c3: () => import('./lessons/sinh10c3.js').then((m) => m.SINH10_C3_LESSONS),
  sinh10c4: () => import('./lessons/sinh10c4.js').then((m) => m.SINH10_C4_LESSONS),
  sinh11c1: () => import('./lessons/sinh11c1.js').then((m) => m.SINH11_C1_LESSONS),
  sinh11c2: () => import('./lessons/sinh11c2.js').then((m) => m.SINH11_C2_LESSONS),
  sinh12c1: () => import('./lessons/sinh12c1.js').then((m) => m.SINH12_C1_LESSONS),
  sinh12c2: () => import('./lessons/sinh12c2.js').then((m) => m.SINH12_C2_LESSONS),
  sinh12c3: () => import('./lessons/sinh12c3.js').then((m) => m.SINH12_C3_LESSONS),
}
