import type { ShortCourse } from './types.js'

export const AIREL_COURSE: ShortCourse = {
  id: 'airel',
  title: 'AI Evals & Reliability Engineer',
  canDo:
    'Xây evaluation harness, quality gate, tracing, giám sát, fallback và SLO cho hệ thống LLM/RAG/Agent; kết thúc bằng một portfolio production-grade có bằng chứng đo lường.',
  duration: '24 tuần · 12 giai đoạn · 26 lượt học thực hành có bộ chạy code',
  prerequisites: [
    'Python căn bản (biến, hàm, list/dict)',
    'Biết dùng terminal và Git ở mức nhập môn',
  ],
  chapters: [
    {
      id: 'airel-c1',
      title: 'Nền tảng Python & kiểm thử tự động',
      weeks: 'Tuần 1–2',
      summary: 'Chuẩn hoá JSON/JSONL, dữ liệu bảng và tư duy kiểm thử trước khi đánh giá AI.',
      focus: [
        'pytest: fixture, parametrize, mock',
        'Pydantic v2 và schema JSONL',
        'pandas pass-rate',
        'GitHub Actions chạy khi mở PR',
      ],
      lab: 'Dựng pipeline kiểm định output JSON: thiếu field hoặc sai kiểu phải làm test đỏ.',
      deliverable: 'Repo có CI tự chạy pytest trên mỗi commit và Pull Request.',
      lessonIds: ['p3-u2-l1', 'p3-u3-l1'],
    },
    {
      id: 'airel-c2',
      title: 'LLM internals & cơ chế lấy mẫu',
      weeks: 'Tuần 3–4',
      summary: 'Hiểu token, sampling, độ bất định và ảnh hưởng trực tiếp tới chi phí/độ trễ.',
      focus: [
        'BPE và token length',
        'temperature, top_p, top_k',
        'penalty và seed',
        'giới hạn tái lập trên inference phân tán',
      ],
      lab: 'Chạy 100 request ở temperature 0.0, 0.7, 1.2; đo semantic variance bằng cosine similarity.',
      deliverable: 'Báo cáo giải thích vì sao temperature=0 vẫn có thể cho output khác nhau.',
      lessonIds: ['llmagent-u1-l1', 'llmagent-u1-l4'],
    },
    {
      id: 'airel-c3',
      title: 'Đánh giá AI & LLM-as-a-Judge',
      weeks: 'Tuần 5–6',
      summary: 'Từ metric tất định đến rubric judge, hiệu chuẩn và đo độ đồng thuận với con người.',
      focus: [
        'Exact/regex/Levenshtein/BLEU/ROUGE',
        'Rubric binary và thang 1–5',
        'Position, verbosity, self-enhancement bias',
        'Swap-position và Cohen’s Kappa',
      ],
      lab: 'Tạo golden set 50 câu, chấm mù và đảo vị trí hai câu trả lời để giảm bias.',
      deliverable: 'Benchmark AI–human đạt Cohen’s Kappa > 0,75 hoặc có phân tích lỗi rõ ràng.',
      lessonIds: ['p6-u95-l1', 'p6-u64-l1'],
    },
    {
      id: 'airel-c4',
      title: 'Đánh giá hệ thống RAG',
      weeks: 'Tuần 7–9',
      summary: 'Tách lỗi retrieval khỏi lỗi generation và kiểm chứng trích dẫn tới từng câu.',
      focus: [
        'Hit Rate@K, MRR, NDCG',
        'RAG Triad',
        'Groundedness và answer relevance',
        'Citation verification',
      ],
      lab: 'Benchmark 100 tài liệu, chèn context nhiễu và so Dense với Hybrid BM25 + Vector.',
      deliverable: 'Dashboard so sánh hai chiến lược retrieval và các ca hallucination.',
      lessonIds: ['llmagent-u2-l3', 'llmagent-u2-l4'],
    },
    {
      id: 'airel-c5',
      title: 'AI Agent & multi-step execution',
      weeks: 'Tuần 10–12',
      summary: 'Chấm đúng tool, đúng schema và đúng cả quỹ đạo thay vì chỉ nhìn câu trả lời cuối.',
      focus: [
        'Tool selection accuracy',
        'Argument schema validation',
        'Multi-turn goal adherence',
        'Step-level và trajectory-level scoring',
      ],
      lab: 'Tạo mock database/weather/calculator rồi chạy 30 tình huống agent nhiều bước.',
      deliverable: 'Harness báo Success Rate, Tool Accuracy và Efficiency Score.',
      lessonIds: ['llmagent-u3-l2', 'llmagent-u3-l4'],
    },
    {
      id: 'airel-c6',
      title: 'CI/CD cho AI — Evals-as-Code',
      weeks: 'Tuần 13–14',
      summary: 'Biến benchmark thành quality gate có thể chặn regression ngay trong PR.',
      focus: [
        'promptfoo và DeepEval',
        'Quality gate theo baseline',
        'Ma trận model × prompt',
        'Negative control',
      ],
      lab: 'Cấu hình promptfoo.yaml chạy khi thư mục prompts/ thay đổi.',
      deliverable: 'PR mẫu bị chặn khi faithfulness giảm quá 3% hoặc tool-call fail tăng.',
      lessonIds: ['p6-u64-l2', 'git-u5-l1'],
    },
    {
      id: 'airel-c7',
      title: 'Tracing & observability',
      weeks: 'Tuần 15–16',
      summary: 'Nhìn được chuỗi request từ input tới retrieval, prompt, model và hậu xử lý.',
      focus: [
        'Trace, span và metadata',
        'Langfuse/LangSmith/Phoenix',
        'OpenTelemetry',
        'Latency breakdown',
      ],
      lab: 'Tự host Langfuse local và instrument một pipeline RAG từ đầu đến cuối.',
      deliverable: 'Trace waterfall có latency từng node và tag lỗi tra cứu được.',
      lessonIds: ['p6-u63-l1', 'p4-u4-l1'],
    },
    {
      id: 'airel-c8',
      title: 'Giám sát production & online evals',
      weeks: 'Tuần 17–18',
      summary:
        'Phát hiện drift và suy giảm chất lượng trên traffic thật bằng sampling có kiểm soát.',
      focus: [
        'Online judge sampling 5–10%',
        'Data/concept drift',
        'Shadow và canary deployment',
        'p50/p95/p99 và safety rate',
      ],
      lab: 'Bắn cảnh báo khi thumbs-down >5%/giờ hoặc latency p99 vượt 5 giây.',
      deliverable: 'Dashboard realtime cho latency, throughput, hallucination và safety.',
      lessonIds: ['p6-u107-l2', 'llmagent-u3-l5'],
    },
    {
      id: 'airel-c9',
      title: 'Chịu tải & phục hồi',
      weeks: 'Tuần 19–20',
      summary: 'Giữ hệ thống phản hồi khi provider chậm, 429, 5xx hoặc ngừng hoàn toàn.',
      focus: [
        'Exponential backoff + jitter',
        'Fallback cascade',
        'Circuit breaker',
        'Graceful degradation',
      ],
      lab: 'Viết gateway đổi provider sau 3 lỗi 429/503 liên tiếp.',
      deliverable: 'Test chứng minh fallback vẫn trả 200 khi provider chính bị ngắt.',
      lessonIds: ['p6-u107-l1', 'p6-u14-l2'],
    },
    {
      id: 'airel-c10',
      title: 'Durable execution & chaos engineering',
      weeks: 'Tuần 21–22',
      summary: 'Cho workflow dài tự tiếp tục sau crash và kiểm thử lỗi biên một cách chủ động.',
      focus: [
        'Temporal workflow',
        'Checkpoint và replay',
        'Fault injection',
        'Hard-cap cost/step và loop detection',
      ],
      lab: 'Kill worker ở bước 3/5, khởi động lại và xác nhận không gọi lại API đã hoàn tất.',
      deliverable: 'Chaos suite gồm 5 kịch bản và báo cáo tỷ lệ tự phục hồi.',
      lessonIds: ['p6-u105-l2', 'p6-u14-l2'],
    },
    {
      id: 'airel-c11',
      title: 'Tối ưu & kiểm soát chi phí',
      weeks: 'Tuần 23',
      summary: 'Tối ưu theo cost-per-success thay vì chỉ nhìn giá mỗi token.',
      focus: [
        'Unit economics',
        'Exact và semantic cache',
        'Prompt caching',
        'Model routing theo độ khó',
      ],
      lab: 'Mô phỏng 1.000 truy vấn qua Redis semantic cache và đo hit-rate/latency/cost.',
      deliverable:
        'Báo cáo ROI chứng minh mức tiết kiệm mục tiêu 40–60% hoặc giải thích chênh lệch.',
      lessonIds: ['p6-u95-l2', 'p6-u103-l1', 'p6-u99-l2'],
    },
    {
      id: 'airel-c12',
      title: 'SRE & portfolio production-grade',
      weeks: 'Tuần 24',
      summary: 'Chốt SLI/SLO/SLA, viết post-mortem và đóng gói toàn bộ bằng chứng thành portfolio.',
      focus: [
        'SLI/SLO/SLA cho chất lượng AI',
        'Error budget',
        'RCA và post-mortem không đổ lỗi',
        'ADR và runbook',
      ],
      lab: 'Viết post-mortem sự cố RAG rò dữ liệu do prompt injection trong tài liệu nội bộ.',
      deliverable: 'Template GitHub gồm CI eval, tracing, fallback gateway và ADR kiến trúc.',
      lessonIds: ['p6-u107-l2', 'p6-u101-l1', 'p6-u101-l2'],
    },
  ],
}
