// lessonsLazy.ts — TỆP SINH TỰ ĐỘNG, ĐỪNG SỬA TAY.
// Sinh bởi `npm run gen:stem-lesson-index` (scripts/gen-stem-lesson-index.ts).
// Thêm hoặc sửa bài học xong PHẢI chạy lại lệnh đó, nếu không chỉ mục lệch với nội dung thật.
import type { StemLessonSummary } from '@dhcb/core-contracts/stemLesson'
import type { ChemLesson } from './lessonTypes.js'

export const LESSON_INDEX: StemLessonSummary[] = [
  {
    id: 'hoa11-c90-b1',
    grade: '11',
    chapterNumber: 90,
    chapterTitle: 'Chuyên đề HSG — Cân bằng ion trong dung dịch',
    lessonNumber: 1,
    title: 'HSG cấp trường: Acid yếu, hằng số Ka và độ điện li',
    track: 'advanced',
    advancedTier: 'hsg-truong',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa-hsg-dung-dich',
  },
  {
    id: 'hoa11-c91-b1',
    grade: '11',
    chapterNumber: 91,
    chapterTitle: 'Chuyên đề HSG — Cân bằng ion trong dung dịch',
    lessonNumber: 1,
    title: 'HSG cấp tỉnh: Dung dịch đệm và bước nhảy pH khi chuẩn độ',
    track: 'advanced',
    advancedTier: 'hsg-tinh',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa-hsg-dung-dich',
  },
  {
    id: 'hoa11-c92-b1',
    grade: '11',
    chapterNumber: 92,
    chapterTitle: 'Chuyên đề HSG — Cân bằng ion trong dung dịch',
    lessonNumber: 1,
    title: 'HSG cấp quốc gia: Tích số tan và kết tủa phân đoạn',
    track: 'advanced',
    advancedTier: 'hsg-quoc-gia',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa-hsg-dung-dich',
  },
  {
    id: 'hoa11-c93-b1',
    grade: '11',
    chapterNumber: 93,
    chapterTitle: 'Chuyên đề HSG — Xác định công thức hợp chất hữu cơ',
    lessonNumber: 1,
    title: 'HSG cấp trường: Lập công thức phân tử từ dữ kiện đốt cháy',
    track: 'advanced',
    advancedTier: 'hsg-truong',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa-hsg-huu-co-va-hon-hop',
  },
  {
    id: 'hoa11-c94-b1',
    grade: '11',
    chapterNumber: 94,
    chapterTitle: 'Chuyên đề HSG — Bài toán hỗn hợp nhiều phản ứng',
    lessonNumber: 1,
    title: 'HSG cấp tỉnh: Hỗn hợp kim loại tác dụng HNO₃ và ba định luật bảo toàn',
    track: 'advanced',
    advancedTier: 'hsg-tinh',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa-hsg-huu-co-va-hon-hop',
  },
  {
    id: 'hoa11-c95-b1',
    grade: '11',
    chapterNumber: 95,
    chapterTitle: 'Chuyên đề HSG — Cơ chế phản ứng hữu cơ',
    lessonNumber: 1,
    title: 'HSG cấp quốc gia: Cơ chế SN1, SN2, E1, E2 và hệ quả hoá lập thể',
    track: 'advanced',
    advancedTier: 'hsg-quoc-gia',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa-hsg-huu-co-va-hon-hop',
  },
  {
    id: 'hoa10-c90-b1',
    grade: '10',
    chapterNumber: 90,
    chapterTitle: 'Chuyên đề HSG — Nhiệt hoá học',
    lessonNumber: 1,
    title: 'HSG cấp trường: Định luật Hess và các cách tính nhiệt phản ứng',
    track: 'advanced',
    advancedTier: 'hsg-truong',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa-hsg-nhiet-dong-hoc',
  },
  {
    id: 'hoa10-c91-b1',
    grade: '10',
    chapterNumber: 91,
    chapterTitle: 'Chuyên đề HSG — Động hoá học',
    lessonNumber: 1,
    title: 'HSG cấp tỉnh: Bậc phản ứng, phương trình tốc độ và chu kì bán huỷ',
    track: 'advanced',
    advancedTier: 'hsg-tinh',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa-hsg-nhiet-dong-hoc',
  },
  {
    id: 'hoa10-c92-b1',
    grade: '10',
    chapterNumber: 92,
    chapterTitle: 'Chuyên đề HSG — Nhiệt động học',
    lessonNumber: 1,
    title: 'HSG cấp quốc gia: ΔG = ΔH − TΔS, chiều tự diễn biến và hằng số cân bằng',
    track: 'advanced',
    advancedTier: 'hsg-quoc-gia',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa-hsg-nhiet-dong-hoc',
  },
  {
    id: 'hoa12-c90-b1',
    grade: '12',
    chapterNumber: 90,
    chapterTitle: 'Chuyên đề HSG — Điện hoá học',
    lessonNumber: 1,
    title: 'HSG cấp trường: Thế điện cực chuẩn và sức điện động của pin',
    track: 'advanced',
    advancedTier: 'hsg-truong',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa-hsg-dien-hoa',
  },
  {
    id: 'hoa12-c91-b1',
    grade: '12',
    chapterNumber: 91,
    chapterTitle: 'Chuyên đề HSG — Điện hoá học',
    lessonNumber: 1,
    title: 'HSG cấp tỉnh: Điện phân, định luật Faraday và thứ tự phóng điện',
    track: 'advanced',
    advancedTier: 'hsg-tinh',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa-hsg-dien-hoa',
  },
  {
    id: 'hoa12-c92-b1',
    grade: '12',
    chapterNumber: 92,
    chapterTitle: 'Chuyên đề HSG — Điện hoá học',
    lessonNumber: 1,
    title: 'HSG cấp quốc gia: Phương trình Nernst, ΔG° = −nFE° và ăn mòn điện hoá',
    track: 'advanced',
    advancedTier: 'hsg-quoc-gia',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa-hsg-dien-hoa',
  },
  {
    id: 'hoa12-c93-b1',
    grade: '12',
    chapterNumber: 93,
    chapterTitle: 'Chuyên đề HSG — Hữu cơ lớp 12',
    lessonNumber: 1,
    title: 'HSG cấp trường: Thuỷ phân ester, chất béo và chỉ số xà phòng hoá',
    track: 'advanced',
    advancedTier: 'hsg-truong',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa-hsg-huu-co-12',
  },
  {
    id: 'hoa12-c94-b1',
    grade: '12',
    chapterNumber: 94,
    chapterTitle: 'Chuyên đề HSG — Hữu cơ lớp 12',
    lessonNumber: 1,
    title: 'HSG cấp tỉnh: Amine, amino acid, peptide và điểm đẳng điện',
    track: 'advanced',
    advancedTier: 'hsg-tinh',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa-hsg-huu-co-12',
  },
  {
    id: 'hoa12-c95-b1',
    grade: '12',
    chapterNumber: 95,
    chapterTitle: 'Chuyên đề HSG — Hữu cơ lớp 12',
    lessonNumber: 1,
    title: 'HSG cấp quốc gia: Bài toán hỗn hợp, quy đổi và biện luận polymer',
    track: 'advanced',
    advancedTier: 'hsg-quoc-gia',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa-hsg-huu-co-12',
  },
  {
    id: 'hoa10-c1-b1',
    grade: '10',
    chapterNumber: 1,
    chapterTitle: 'Nhập môn Hoá học & Thành phần nguyên tử',
    lessonNumber: 1,
    title: 'Nhập môn Hoá học',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa10c1',
  },
  {
    id: 'hoa10-c1-b2',
    grade: '10',
    chapterNumber: 1,
    chapterTitle: 'Nhập môn Hoá học & Thành phần nguyên tử',
    lessonNumber: 2,
    title: 'Thành phần của nguyên tử',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa10c1',
  },
  {
    id: 'hoa10-c1-b3',
    grade: '10',
    chapterNumber: 1,
    chapterTitle: 'Nhập môn Hoá học & Thành phần nguyên tử',
    lessonNumber: 3,
    title: 'Nguyên tố hoá học',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa10c1',
  },
  {
    id: 'hoa10-c1-b4',
    grade: '10',
    chapterNumber: 1,
    chapterTitle: 'Nhập môn Hoá học & Thành phần nguyên tử',
    lessonNumber: 4,
    title: 'Cấu trúc lớp vỏ electron nguyên tử',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa10c1',
  },
  {
    id: 'hoa10-c2-b5',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Bảng tuần hoàn các nguyên tố hoá học',
    lessonNumber: 5,
    title: 'Cấu tạo của bảng tuần hoàn các nguyên tố hoá học',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa10c2',
  },
  {
    id: 'hoa10-c2-b6',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Bảng tuần hoàn các nguyên tố hoá học',
    lessonNumber: 6,
    title: 'Xu hướng biến đổi một số tính chất của nguyên tử trong một chu kì và một nhóm',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa10c2',
  },
  {
    id: 'hoa10-c2-b7',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Bảng tuần hoàn các nguyên tố hoá học',
    lessonNumber: 7,
    title: 'Xu hướng biến đổi thành phần và một số tính chất của hợp chất trong một chu kì',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa10c2',
  },
  {
    id: 'hoa10-c2-b8',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Bảng tuần hoàn các nguyên tố hoá học',
    lessonNumber: 8,
    title: 'Định luật tuần hoàn và ý nghĩa của bảng tuần hoàn các nguyên tố hoá học',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa10c2',
  },
  {
    id: 'hoa10-c3-b9',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Liên kết hoá học',
    lessonNumber: 9,
    title: 'Quy tắc octet',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa10c3',
  },
  {
    id: 'hoa10-c3-b10',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Liên kết hoá học',
    lessonNumber: 10,
    title: 'Liên kết ion',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa10c3',
  },
  {
    id: 'hoa10-c3-b11',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Liên kết hoá học',
    lessonNumber: 11,
    title: 'Liên kết cộng hoá trị',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa10c3',
  },
  {
    id: 'hoa10-c3-b12',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Liên kết hoá học',
    lessonNumber: 12,
    title: 'Liên kết hydrogen và tương tác van der Waals',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa10c3',
  },
  {
    id: 'hoa10-c4-b13',
    grade: '10',
    chapterNumber: 4,
    chapterTitle: 'Phản ứng oxi hoá - khử',
    lessonNumber: 13,
    title: 'Phản ứng oxi hoá - khử',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa10c4',
  },
  {
    id: 'hoa10-c5-b14',
    grade: '10',
    chapterNumber: 5,
    chapterTitle: 'Năng lượng hoá học',
    lessonNumber: 14,
    title: 'Biến thiên enthalpy trong các phản ứng hoá học',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa10c5',
  },
  {
    id: 'hoa10-c6-b15',
    grade: '10',
    chapterNumber: 6,
    chapterTitle: 'Tốc độ phản ứng hoá học',
    lessonNumber: 15,
    title: 'Tốc độ phản ứng',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa10c6',
  },
  {
    id: 'hoa10-c7-b16',
    grade: '10',
    chapterNumber: 7,
    chapterTitle: 'Nhóm halogen',
    lessonNumber: 16,
    title: 'Nhóm halogen',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa10c7',
  },
  {
    id: 'hoa10-c7-b17',
    grade: '10',
    chapterNumber: 7,
    chapterTitle: 'Nhóm halogen',
    lessonNumber: 17,
    title: 'Hydrogen halide và một số phản ứng của ion halide',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa10c7',
  },
  {
    id: 'hoa11-c1-b1',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Cân bằng hoá học',
    lessonNumber: 1,
    title: 'Khái niệm về cân bằng hoá học',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c1',
  },
  {
    id: 'hoa11-c1-b2',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Cân bằng hoá học',
    lessonNumber: 2,
    title: 'Cân bằng trong dung dịch nước',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c1',
  },
  {
    id: 'hoa11-c1-b3',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Cân bằng hoá học',
    lessonNumber: 3,
    title: 'Ôn tập chương 1 — Cân bằng hoá học',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c1',
  },
  {
    id: 'hoa11-c2-b4',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Nitrogen - Sulfur',
    lessonNumber: 4,
    title: 'Nitrogen',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c2',
  },
  {
    id: 'hoa11-c2-b5',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Nitrogen - Sulfur',
    lessonNumber: 5,
    title: 'Ammonia - Muối ammonium',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c2',
  },
  {
    id: 'hoa11-c2-b6',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Nitrogen - Sulfur',
    lessonNumber: 6,
    title: 'Một số hợp chất của nitrogen với oxygen',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c2',
  },
  {
    id: 'hoa11-c2-b7',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Nitrogen - Sulfur',
    lessonNumber: 7,
    title: 'Sulfur và sulfur dioxide',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c2',
  },
  {
    id: 'hoa11-c2-b8',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Nitrogen - Sulfur',
    lessonNumber: 8,
    title: 'Sulfuric acid và muối sulfate',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c2',
  },
  {
    id: 'hoa11-c2-b9',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Nitrogen - Sulfur',
    lessonNumber: 9,
    title: 'Ôn tập chương 2 — Nitrogen - Sulfur',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c2',
  },
  {
    id: 'hoa11-c3-b10',
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Đại cương hoá học hữu cơ',
    lessonNumber: 10,
    title: 'Hợp chất hữu cơ và hoá học hữu cơ',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c3',
  },
  {
    id: 'hoa11-c3-b11',
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Đại cương hoá học hữu cơ',
    lessonNumber: 11,
    title: 'Phương pháp tách biệt và tinh chế hợp chất hữu cơ',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c3',
  },
  {
    id: 'hoa11-c3-b12',
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Đại cương hoá học hữu cơ',
    lessonNumber: 12,
    title: 'Công thức phân tử hợp chất hữu cơ',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c3',
  },
  {
    id: 'hoa11-c3-b13',
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Đại cương hoá học hữu cơ',
    lessonNumber: 13,
    title: 'Cấu tạo hoá học hợp chất hữu cơ',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c3',
  },
  {
    id: 'hoa11-c3-b14',
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Đại cương hoá học hữu cơ',
    lessonNumber: 14,
    title: 'Ôn tập chương 3 — Đại cương hoá học hữu cơ',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c3',
  },
  {
    id: 'hoa11-c4-b15',
    grade: '11',
    chapterNumber: 4,
    chapterTitle: 'Hydrocarbon',
    lessonNumber: 15,
    title: 'Alkane',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c4',
  },
  {
    id: 'hoa11-c4-b16',
    grade: '11',
    chapterNumber: 4,
    chapterTitle: 'Hydrocarbon',
    lessonNumber: 16,
    title: 'Hydrocarbon không no',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c4',
  },
  {
    id: 'hoa11-c4-b17',
    grade: '11',
    chapterNumber: 4,
    chapterTitle: 'Hydrocarbon',
    lessonNumber: 17,
    title: 'Arene (Hydrocarbon thơm)',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c4',
  },
  {
    id: 'hoa11-c4-b18',
    grade: '11',
    chapterNumber: 4,
    chapterTitle: 'Hydrocarbon',
    lessonNumber: 18,
    title: 'Ôn tập chương 4 — Hydrocarbon',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c4',
  },
  {
    id: 'hoa11-c5-b19',
    grade: '11',
    chapterNumber: 5,
    chapterTitle: 'Dẫn xuất halogen - Alcohol - Phenol',
    lessonNumber: 19,
    title: 'Dẫn xuất halogen',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c5',
  },
  {
    id: 'hoa11-c5-b20',
    grade: '11',
    chapterNumber: 5,
    chapterTitle: 'Dẫn xuất halogen - Alcohol - Phenol',
    lessonNumber: 20,
    title: 'Alcohol',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c5',
  },
  {
    id: 'hoa11-c5-b21',
    grade: '11',
    chapterNumber: 5,
    chapterTitle: 'Dẫn xuất halogen - Alcohol - Phenol',
    lessonNumber: 21,
    title: 'Phenol',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c5',
  },
  {
    id: 'hoa11-c5-b22',
    grade: '11',
    chapterNumber: 5,
    chapterTitle: 'Dẫn xuất halogen - Alcohol - Phenol',
    lessonNumber: 22,
    title: 'Ôn tập chương 5 — Dẫn xuất halogen - Alcohol - Phenol',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c5',
  },
  {
    id: 'hoa11-c6-b23',
    grade: '11',
    chapterNumber: 6,
    chapterTitle: 'Hợp chất carbonyl - Carboxylic acid',
    lessonNumber: 23,
    title: 'Hợp chất carbonyl',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c6',
  },
  {
    id: 'hoa11-c6-b24',
    grade: '11',
    chapterNumber: 6,
    chapterTitle: 'Hợp chất carbonyl - Carboxylic acid',
    lessonNumber: 24,
    title: 'Carboxylic acid',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c6',
  },
  {
    id: 'hoa11-c6-b25',
    grade: '11',
    chapterNumber: 6,
    chapterTitle: 'Hợp chất carbonyl - Carboxylic acid',
    lessonNumber: 25,
    title: 'Ôn tập chương 6 — Hợp chất carbonyl - Carboxylic acid',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa11c6',
  },
  {
    id: 'hoa12-c1-b1',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Ester - Lipid',
    lessonNumber: 1,
    title: 'Ester - Lipid',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c1',
  },
  {
    id: 'hoa12-c1-b2',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Ester - Lipid',
    lessonNumber: 2,
    title: 'Xà phòng và chất giặt rửa',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c1',
  },
  {
    id: 'hoa12-c1-b3',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Ester - Lipid',
    lessonNumber: 3,
    title: 'Ôn tập chương 1 — Ester - Lipid',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c1',
  },
  {
    id: 'hoa12-c2-b4',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Carbohydrate',
    lessonNumber: 4,
    title: 'Glucose và fructose',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c2',
  },
  {
    id: 'hoa12-c2-b5',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Carbohydrate',
    lessonNumber: 5,
    title: 'Saccharose và maltose',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c2',
  },
  {
    id: 'hoa12-c2-b6',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Carbohydrate',
    lessonNumber: 6,
    title: 'Tinh bột và cellulose',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c2',
  },
  {
    id: 'hoa12-c2-b7',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Carbohydrate',
    lessonNumber: 7,
    title: 'Ôn tập chương 2 — Carbohydrate',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c2',
  },
  {
    id: 'hoa12-c3-b8',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Hợp chất chứa nitrogen',
    lessonNumber: 8,
    title: 'Amine',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c3',
  },
  {
    id: 'hoa12-c3-b9',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Hợp chất chứa nitrogen',
    lessonNumber: 9,
    title: 'Amino acid và peptide',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c3',
  },
  {
    id: 'hoa12-c3-b10',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Hợp chất chứa nitrogen',
    lessonNumber: 10,
    title: 'Protein và enzyme',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c3',
  },
  {
    id: 'hoa12-c3-b11',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Hợp chất chứa nitrogen',
    lessonNumber: 11,
    title: 'Ôn tập chương 3 — Hợp chất chứa nitrogen',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c3',
  },
  {
    id: 'hoa12-c4-b12',
    grade: '12',
    chapterNumber: 4,
    chapterTitle: 'Polymer',
    lessonNumber: 12,
    title: 'Đại cương về polymer',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c4',
  },
  {
    id: 'hoa12-c4-b13',
    grade: '12',
    chapterNumber: 4,
    chapterTitle: 'Polymer',
    lessonNumber: 13,
    title: 'Vật liệu polymer',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c4',
  },
  {
    id: 'hoa12-c4-b14',
    grade: '12',
    chapterNumber: 4,
    chapterTitle: 'Polymer',
    lessonNumber: 14,
    title: 'Ôn tập chương 4 — Polymer',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c4',
  },
  {
    id: 'hoa12-c5-b15',
    grade: '12',
    chapterNumber: 5,
    chapterTitle: 'Pin điện và điện phân',
    lessonNumber: 15,
    title: 'Thế điện cực và nguồn điện hoá học',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c5',
  },
  {
    id: 'hoa12-c5-b16',
    grade: '12',
    chapterNumber: 5,
    chapterTitle: 'Pin điện và điện phân',
    lessonNumber: 16,
    title: 'Điện phân',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c5',
  },
  {
    id: 'hoa12-c5-b17',
    grade: '12',
    chapterNumber: 5,
    chapterTitle: 'Pin điện và điện phân',
    lessonNumber: 17,
    title: 'Ôn tập chương 5 — Pin điện và điện phân',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c5',
  },
  {
    id: 'hoa12-c6-b18',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Đại cương về kim loại',
    lessonNumber: 18,
    title: 'Cấu tạo và liên kết trong tinh thể kim loại',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c6',
  },
  {
    id: 'hoa12-c6-b19',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Đại cương về kim loại',
    lessonNumber: 19,
    title: 'Tính chất vật lí và tính chất hoá học của kim loại',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c6',
  },
  {
    id: 'hoa12-c6-b20',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Đại cương về kim loại',
    lessonNumber: 20,
    title: 'Kim loại trong tự nhiên và phương pháp tách kim loại',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c6',
  },
  {
    id: 'hoa12-c6-b21',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Đại cương về kim loại',
    lessonNumber: 21,
    title: 'Hợp kim',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c6',
  },
  {
    id: 'hoa12-c6-b22',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Đại cương về kim loại',
    lessonNumber: 22,
    title: 'Sự ăn mòn kim loại',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c6',
  },
  {
    id: 'hoa12-c6-b23',
    grade: '12',
    chapterNumber: 6,
    chapterTitle: 'Đại cương về kim loại',
    lessonNumber: 23,
    title: 'Ôn tập chương 6 — Đại cương về kim loại',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c6',
  },
  {
    id: 'hoa12-c7-b24',
    grade: '12',
    chapterNumber: 7,
    chapterTitle: 'Nguyên tố nhóm IA và nhóm IIA',
    lessonNumber: 24,
    title: 'Nguyên tố nhóm IA',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c7',
  },
  {
    id: 'hoa12-c7-b25',
    grade: '12',
    chapterNumber: 7,
    chapterTitle: 'Nguyên tố nhóm IA và nhóm IIA',
    lessonNumber: 25,
    title: 'Nguyên tố nhóm IIA',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c7',
  },
  {
    id: 'hoa12-c7-b26',
    grade: '12',
    chapterNumber: 7,
    chapterTitle: 'Nguyên tố nhóm IA và nhóm IIA',
    lessonNumber: 26,
    title: 'Ôn tập chương 7 — Nguyên tố nhóm IA và nhóm IIA',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c7',
  },
  {
    id: 'hoa12-c8-b27',
    grade: '12',
    chapterNumber: 8,
    chapterTitle: 'Sơ lược về kim loại chuyển tiếp d và phức chất',
    lessonNumber: 27,
    title: 'Đại cương về kim loại chuyển tiếp dãy thứ nhất',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c8',
  },
  {
    id: 'hoa12-c8-b28',
    grade: '12',
    chapterNumber: 8,
    chapterTitle: 'Sơ lược về kim loại chuyển tiếp d và phức chất',
    lessonNumber: 28,
    title: 'Sơ lược về phức chất',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c8',
  },
  {
    id: 'hoa12-c8-b29',
    grade: '12',
    chapterNumber: 8,
    chapterTitle: 'Sơ lược về kim loại chuyển tiếp d và phức chất',
    lessonNumber: 29,
    title: 'Một số tính chất và ứng dụng của phức chất',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c8',
  },
  {
    id: 'hoa12-c8-b30',
    grade: '12',
    chapterNumber: 8,
    chapterTitle: 'Sơ lược về kim loại chuyển tiếp d và phức chất',
    lessonNumber: 30,
    title: 'Ôn tập chương 8 — Sơ lược về kim loại chuyển tiếp d và phức chất',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'hoa12c8',
  },
]

export const CHAPTER_LOADERS: Record<string, () => Promise<ChemLesson[]>> = {
  'hoa-hsg-dung-dich': () =>
    import('./lessons/hoa-hsg-dung-dich.js').then((m) => m.HOA_HSG_DUNG_DICH_LESSONS),
  'hoa-hsg-huu-co-va-hon-hop': () =>
    import('./lessons/hoa-hsg-huu-co-va-hon-hop.js').then((m) => m.HOA_HSG_HUU_CO_LESSONS),
  'hoa-hsg-nhiet-dong-hoc': () =>
    import('./lessons/hoa-hsg-nhiet-dong-hoc.js').then((m) => m.HOA_HSG_NHIET_DONG_LESSONS),
  'hoa-hsg-dien-hoa': () =>
    import('./lessons/hoa-hsg-dien-hoa.js').then((m) => m.HOA_HSG_DIEN_HOA_LESSONS),
  'hoa-hsg-huu-co-12': () =>
    import('./lessons/hoa-hsg-huu-co-12.js').then((m) => m.HOA_HSG_HUU_CO_12_LESSONS),
  hoa10c1: () => import('./lessons/hoa10c1.js').then((m) => m.HOA10_C1_LESSONS),
  hoa10c2: () => import('./lessons/hoa10c2.js').then((m) => m.HOA10_C2_LESSONS),
  hoa10c3: () => import('./lessons/hoa10c3.js').then((m) => m.HOA10_C3_LESSONS),
  hoa10c4: () => import('./lessons/hoa10c4.js').then((m) => m.HOA10_C4_LESSONS),
  hoa10c5: () => import('./lessons/hoa10c5.js').then((m) => m.HOA10_C5_LESSONS),
  hoa10c6: () => import('./lessons/hoa10c6.js').then((m) => m.HOA10_C6_LESSONS),
  hoa10c7: () => import('./lessons/hoa10c7.js').then((m) => m.HOA10_C7_LESSONS),
  hoa11c1: () => import('./lessons/hoa11c1.js').then((m) => m.HOA11_C1_LESSONS),
  hoa11c2: () => import('./lessons/hoa11c2.js').then((m) => m.HOA11_C2_LESSONS),
  hoa11c3: () => import('./lessons/hoa11c3.js').then((m) => m.HOA11_C3_LESSONS),
  hoa11c4: () => import('./lessons/hoa11c4.js').then((m) => m.HOA11_C4_LESSONS),
  hoa11c5: () => import('./lessons/hoa11c5.js').then((m) => m.HOA11_C5_LESSONS),
  hoa11c6: () => import('./lessons/hoa11c6.js').then((m) => m.HOA11_C6_LESSONS),
  hoa12c1: () => import('./lessons/hoa12c1.js').then((m) => m.HOA12_C1_LESSONS),
  hoa12c2: () => import('./lessons/hoa12c2.js').then((m) => m.HOA12_C2_LESSONS),
  hoa12c3: () => import('./lessons/hoa12c3.js').then((m) => m.HOA12_C3_LESSONS),
  hoa12c4: () => import('./lessons/hoa12c4.js').then((m) => m.HOA12_C4_LESSONS),
  hoa12c5: () => import('./lessons/hoa12c5.js').then((m) => m.HOA12_C5_LESSONS),
  hoa12c6: () => import('./lessons/hoa12c6.js').then((m) => m.HOA12_C6_LESSONS),
  hoa12c7: () => import('./lessons/hoa12c7.js').then((m) => m.HOA12_C7_LESSONS),
  hoa12c8: () => import('./lessons/hoa12c8.js').then((m) => m.HOA12_C8_LESSONS),
}
