// details/algo-s3.ts — Chi tiết chặng S3 hướng THUẬT TOÁN
// ("Quy hoạch động và kỹ thuật nâng cao").
import type { SpecStageDetail } from '../stageDetailTypes.js'

export const ALGO_S3_DETAIL: SpecStageDetail = {
  stageId: 'algo-s3',
  modules: [
    {
      moduleId: 'algo-s3-m1',
      // Cảnh cho thấy VÌ SAO quy hoạch động phải tính từ trái sang phải: mỗi ô dp[i] chỉ tính
      // được sau khi mọi ô j < i mà nó có thể phụ thuộc đã có kết quả. Bảng dp cho bài dãy con
      // tăng dài nhất (LIS) trên mảng 3, 1, 4, 1, 5, 9 — dp = [1, 1, 2, 1, 3, 4].
      animation: {
        title: 'Quy hoạch động: bảng dp cho dãy con tăng dài nhất',
        description:
          'Hàng trên là mảng sáu số 3, 1, 4, 1, 5, 9; hàng dưới là bảng dp điền dần từ trái sang phải, mỗi ô lưu độ dài dãy con tăng dài nhất kết thúc tại vị trí đó. Trước khi điền một ô, khung màu nhấn quét lần lượt các ô bên trái có giá trị nhỏ hơn giá trị hiện tại; nếu tìm được ô tốt nhất, một mũi tên nối ô đó tới ô đang xét và giá trị dp được cộng thêm một. Ô nào không tìm được ô nào nhỏ hơn thì giữ dp bằng một. Kết quả cuối cùng, dp ở ô cuối bằng 4, ứng với dãy 3, 4, 5, 9, được đánh dấu bằng viền báo chốt. Điểm cốt lõi: mỗi ô chỉ tính được sau khi mọi ô nó phụ thuộc đã có kết quả, nên thứ tự tính từ trái sang phải là bắt buộc.',
        viewBoxWidth: 480,
        viewBoxHeight: 220,
        durationMs: 12000,
        loop: true,
        shapes: [
          // Sáu ô mảng gốc, tĩnh, không di chuyển.
          {
            kind: 'rect',
            id: 'a0',
            x: 40,
            y: 40,
            w: 60,
            h: 50,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'rect',
            id: 'a1',
            x: 110,
            y: 40,
            w: 60,
            h: 50,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'rect',
            id: 'a2',
            x: 180,
            y: 40,
            w: 60,
            h: 50,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'rect',
            id: 'a3',
            x: 250,
            y: 40,
            w: 60,
            h: 50,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'rect',
            id: 'a4',
            x: 320,
            y: 40,
            w: 60,
            h: 50,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'rect',
            id: 'a5',
            x: 390,
            y: 40,
            w: 60,
            h: 50,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'label',
            id: 'av0',
            x: 70,
            y: 72,
            text: '3',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'av1',
            x: 140,
            y: 72,
            text: '1',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'av2',
            x: 210,
            y: 72,
            text: '4',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'av3',
            x: 280,
            y: 72,
            text: '1',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'av4',
            x: 350,
            y: 72,
            text: '5',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'av5',
            x: 420,
            y: 72,
            text: '9',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
          },
          // Sáu ô dp, ẩn ban đầu, hiện dần đúng lúc được tính (trái sang phải).
          {
            kind: 'rect',
            id: 'd0',
            x: 40,
            y: 130,
            w: 60,
            h: 50,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 500, opacity: 0 },
              { atMs: 600, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'd1',
            x: 110,
            y: 130,
            w: 60,
            h: 50,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 1300, opacity: 0 },
              { atMs: 1400, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'd2',
            x: 180,
            y: 130,
            w: 60,
            h: 50,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 3200, opacity: 0 },
              { atMs: 3300, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'd3',
            x: 250,
            y: 130,
            w: 60,
            h: 50,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 5100, opacity: 0 },
              { atMs: 5200, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'd4',
            x: 320,
            y: 130,
            w: 60,
            h: 50,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 7500, opacity: 0 },
              { atMs: 7600, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'd5',
            x: 390,
            y: 130,
            w: 60,
            h: 50,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 10300, opacity: 0 },
              { atMs: 10400, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'dv0',
            x: 70,
            y: 162,
            text: '1',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 500, opacity: 0 },
              { atMs: 600, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'dv1',
            x: 140,
            y: 162,
            text: '1',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 1300, opacity: 0 },
              { atMs: 1400, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'dv2',
            x: 210,
            y: 162,
            text: '2',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 3200, opacity: 0 },
              { atMs: 3300, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'dv3',
            x: 280,
            y: 162,
            text: '1',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 5100, opacity: 0 },
              { atMs: 5200, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'dv4',
            x: 350,
            y: 162,
            text: '3',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 7500, opacity: 0 },
              { atMs: 7600, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'dv5',
            x: 420,
            y: 162,
            text: '4',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 10300, opacity: 0 },
              { atMs: 10400, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          // Khung màu nhấn quét qua các ô bên trái đang được so để tìm ô tốt nhất cho dp hiện tại.
          {
            kind: 'rect',
            id: 'scan',
            x: 40,
            y: 40,
            w: 60,
            h: 50,
            rx: 6,
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0, dx: 0 },
              { atMs: 2000, opacity: 1, dx: 0 },
              { atMs: 2500, dx: 70 },
              { atMs: 3000, opacity: 0, dx: 70 },
              { atMs: 4000, opacity: 1, dx: 0 },
              { atMs: 4400, dx: 70 },
              { atMs: 4800, dx: 140 },
              { atMs: 5200, opacity: 0, dx: 140 },
              { atMs: 5800, opacity: 1, dx: 0 },
              { atMs: 6200, dx: 70 },
              { atMs: 6600, dx: 140 },
              { atMs: 7000, dx: 210 },
              { atMs: 7300, opacity: 0, dx: 210 },
              { atMs: 8200, opacity: 1, dx: 0 },
              { atMs: 8600, dx: 70 },
              { atMs: 9000, dx: 140 },
              { atMs: 9400, dx: 210 },
              { atMs: 9800, dx: 280 },
              { atMs: 10100, opacity: 0, dx: 280 },
              { atMs: 12000, opacity: 0, dx: 280 },
            ],
          },
          // Mũi tên nối ô nguồn tốt nhất tới ô đang tính dp, xuất hiện đúng lúc tìm ra và giữ
          // nguyên tới hết cảnh để lộ dần cả dãy con tăng dài nhất tìm được.
          {
            kind: 'arrow',
            id: 'arr02',
            x1: 70,
            y1: 112,
            x2: 210,
            y2: 112,
            stroke: 'correct',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 3000, opacity: 0 },
              { atMs: 3050, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          {
            kind: 'arrow',
            id: 'arr24',
            x1: 210,
            y1: 110,
            x2: 350,
            y2: 110,
            stroke: 'correct',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 7300, opacity: 0 },
              { atMs: 7350, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          {
            kind: 'arrow',
            id: 'arr45',
            x1: 350,
            y1: 108,
            x2: 420,
            y2: 108,
            stroke: 'correct',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 10100, opacity: 0 },
              { atMs: 10150, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          // Viền báo chốt quanh ô dp cuối cùng — kết quả bài toán.
          {
            kind: 'rect',
            id: 'chot-dp5',
            x: 390,
            y: 130,
            w: 60,
            h: 50,
            rx: 6,
            stroke: 'correct',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 10800, opacity: 0 },
              { atMs: 10850, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
        ],
        captions: [
          {
            atMs: 0,
            text: 'Mảng sáu số 3, 1, 4, 1, 5, 9 nằm ở hàng trên; hàng dưới là bảng dp sẽ điền dần từ trái sang phải, mỗi ô là độ dài dãy con tăng dài nhất kết thúc tại vị trí đó.',
          },
          {
            atMs: 600,
            text: 'dp ở ô đầu bằng 1: một phần tử luôn tự tạo thành dãy tăng độ dài 1.',
          },
          {
            atMs: 1400,
            text: 'dp ở ô thứ hai bằng 1: số 1 nhỏ hơn số 3 đứng trước nên không nối dài được.',
          },
          {
            atMs: 2000,
            text: 'Đang tính ô thứ ba: khung màu nhấn quét các ô bên trái có giá trị nhỏ hơn 4.',
          },
          {
            atMs: 3050,
            text: '3 nhỏ hơn 4 nên nối được — mũi tên nối hai ô, dp ô thứ ba bằng dp ô đầu cộng một, tức 2.',
          },
          {
            atMs: 4000,
            text: 'Đang tính ô thứ tư: quét cả ba ô bên trái nhưng không ô nào nhỏ hơn 1, nên dp vẫn là 1.',
          },
          {
            atMs: 5800,
            text: 'Đang tính ô thứ năm: quét bốn ô bên trái để tìm ô tốt nhất nhỏ hơn 5.',
          },
          {
            atMs: 7350,
            text: 'Ô mang giá trị 4 cho dp lớn nhất — mũi tên nối tới ô đang xét, dp ô thứ năm bằng 3.',
          },
          {
            atMs: 8200,
            text: 'Đang tính ô cuối: quét năm ô bên trái để tìm ô tốt nhất nhỏ hơn 9.',
          },
          {
            atMs: 10150,
            text: 'Ô mang giá trị 5 cho dp lớn nhất — mũi tên nối tới ô cuối, dp ô cuối bằng 4.',
          },
          {
            atMs: 10850,
            text: 'Viền báo chốt quanh ô cuối: dãy con tăng dài nhất là 3, 4, 5, 9, độ dài 4. Mỗi ô chỉ tính được sau khi mọi ô nó phụ thuộc đã có kết quả.',
          },
        ],
      },
      objective:
        'Nhận ra được bài quy hoạch động và phát biểu trạng thái cùng công thức chuyển trước khi viết dòng code nào.',
      practice: [
        'Giải 20 bài quy hoạch động thuộc bốn họ khác nhau, mỗi bài ghi trạng thái và chuyển trong năm dòng.',
        'Chuyển một lời giải đệ quy có nhớ sang bản lặp và giảm bộ nhớ xuống một chiều.',
        'Tự đặt lại một bài đã giải theo trạng thái khác để thấy cách chọn trạng thái đổi độ phức tạp ra sao.',
      ],
      selfCheck: [
        {
          q: 'Trạng thái trong quy hoạch động phải thoả tính chất gì?',
          a: 'Phải đủ thông tin để tính bước sau mà không cần nhớ lại cách đi tới trạng thái đó.',
        },
        {
          q: 'Vì sao thứ tự tính lại quan trọng?',
          a: 'Mỗi trạng thái chỉ tính được khi các trạng thái nó phụ thuộc đã có kết quả.',
        },
      ],
      doneSignals: [
        'Đọc đề xong bạn phát biểu được trạng thái trước khi gõ code.',
        'Bạn ước lượng độ phức tạp trước và số đo thực tế khớp với ước lượng.',
      ],
    },
    {
      moduleId: 'algo-s3-m2',
      // Cảnh cho thấy VÌ SAO KMP chạy tuyến tính: bảng thất bại cho phép mẫu dịch nhiều hơn một
      // ô mỗi khi lệch, giữ lại phần đã khớp trước đó, nên con trỏ văn bản không bao giờ lùi lại.
      // Văn bản "ABABCABABA" (10 ký tự), mẫu "ABAB" (4 ký tự), bảng thất bại [0, 0, 1, 2].
      animation: {
        title: 'KMP: bảng thất bại giúp con trỏ văn bản chỉ tiến',
        description:
          'Văn bản mười ký tự A B A B C A B A B A nằm ở hàng trên, mẫu bốn ký tự A B A B trượt bên dưới cùng bảng thất bại 0, 0, 1, 2 của từng vị trí trong mẫu. Một mũi tên nhỏ phía trên đánh dấu vị trí con trỏ văn bản đang xét, chỉ di chuyển về phía trước. Khi khớp đủ bốn ký tự, khung viền báo đúng xuất hiện quanh đoạn văn bản vừa khớp. Khi lệch, thay vì dịch mẫu sang phải đúng một ô như cách ngây thơ, mẫu dịch theo bảng thất bại, giữ lại phần đã khớp trước đó nếu có thể, nên con trỏ văn bản không bao giờ phải lùi lại để so sánh lại từ đầu. Nhờ vậy tổng số phép so sánh chỉ tỉ lệ thuận với tổng độ dài văn bản và mẫu, không phải tích của hai độ dài.',
        viewBoxWidth: 460,
        viewBoxHeight: 210,
        durationMs: 10000,
        loop: true,
        shapes: [
          {
            kind: 'label',
            id: 't0',
            x: 39,
            y: 65,
            text: 'A',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 't1',
            x: 79,
            y: 65,
            text: 'B',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 't2',
            x: 119,
            y: 65,
            text: 'A',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 't3',
            x: 159,
            y: 65,
            text: 'B',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 't4',
            x: 199,
            y: 65,
            text: 'C',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 't5',
            x: 239,
            y: 65,
            text: 'A',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 't6',
            x: 279,
            y: 65,
            text: 'B',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 't7',
            x: 319,
            y: 65,
            text: 'A',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 't8',
            x: 359,
            y: 65,
            text: 'B',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 't9',
            x: 399,
            y: 65,
            text: 'A',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'p0',
            x: 39,
            y: 125,
            text: 'A',
            size: 22,
            anchor: 'middle',
            fill: 'accent',
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 2500, dx: 0 },
              { atMs: 2650, dx: 80 },
              { atMs: 3000, dx: 80 },
              { atMs: 3150, dx: 160 },
              { atMs: 3500, dx: 160 },
              { atMs: 3650, dx: 200 },
              { atMs: 5900, dx: 200 },
              { atMs: 6050, dx: 280 },
              { atMs: 10000, dx: 280 },
            ],
          },
          {
            kind: 'label',
            id: 'p1',
            x: 79,
            y: 125,
            text: 'B',
            size: 22,
            anchor: 'middle',
            fill: 'accent',
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 2500, dx: 0 },
              { atMs: 2650, dx: 80 },
              { atMs: 3000, dx: 80 },
              { atMs: 3150, dx: 160 },
              { atMs: 3500, dx: 160 },
              { atMs: 3650, dx: 200 },
              { atMs: 5900, dx: 200 },
              { atMs: 6050, dx: 280 },
              { atMs: 10000, dx: 280 },
            ],
          },
          {
            kind: 'label',
            id: 'p2',
            x: 119,
            y: 125,
            text: 'A',
            size: 22,
            anchor: 'middle',
            fill: 'accent',
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 2500, dx: 0 },
              { atMs: 2650, dx: 80 },
              { atMs: 3000, dx: 80 },
              { atMs: 3150, dx: 160 },
              { atMs: 3500, dx: 160 },
              { atMs: 3650, dx: 200 },
              { atMs: 5900, dx: 200 },
              { atMs: 6050, dx: 280 },
              { atMs: 10000, dx: 280 },
            ],
          },
          {
            kind: 'label',
            id: 'p3',
            x: 159,
            y: 125,
            text: 'B',
            size: 22,
            anchor: 'middle',
            fill: 'accent',
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 2500, dx: 0 },
              { atMs: 2650, dx: 80 },
              { atMs: 3000, dx: 80 },
              { atMs: 3150, dx: 160 },
              { atMs: 3500, dx: 160 },
              { atMs: 3650, dx: 200 },
              { atMs: 5900, dx: 200 },
              { atMs: 6050, dx: 280 },
              { atMs: 10000, dx: 280 },
            ],
          },
          {
            kind: 'rect',
            id: 'pbox0',
            x: 22,
            y: 105,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'accent',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 2500, dx: 0 },
              { atMs: 2650, dx: 80 },
              { atMs: 3000, dx: 80 },
              { atMs: 3150, dx: 160 },
              { atMs: 3500, dx: 160 },
              { atMs: 3650, dx: 200 },
              { atMs: 5900, dx: 200 },
              { atMs: 6050, dx: 280 },
              { atMs: 10000, dx: 280 },
            ],
          },
          {
            kind: 'rect',
            id: 'pbox1',
            x: 62,
            y: 105,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'accent',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 2500, dx: 0 },
              { atMs: 2650, dx: 80 },
              { atMs: 3000, dx: 80 },
              { atMs: 3150, dx: 160 },
              { atMs: 3500, dx: 160 },
              { atMs: 3650, dx: 200 },
              { atMs: 5900, dx: 200 },
              { atMs: 6050, dx: 280 },
              { atMs: 10000, dx: 280 },
            ],
          },
          {
            kind: 'rect',
            id: 'pbox2',
            x: 102,
            y: 105,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'accent',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 2500, dx: 0 },
              { atMs: 2650, dx: 80 },
              { atMs: 3000, dx: 80 },
              { atMs: 3150, dx: 160 },
              { atMs: 3500, dx: 160 },
              { atMs: 3650, dx: 200 },
              { atMs: 5900, dx: 200 },
              { atMs: 6050, dx: 280 },
              { atMs: 10000, dx: 280 },
            ],
          },
          {
            kind: 'rect',
            id: 'pbox3',
            x: 142,
            y: 105,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'accent',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 2500, dx: 0 },
              { atMs: 2650, dx: 80 },
              { atMs: 3000, dx: 80 },
              { atMs: 3150, dx: 160 },
              { atMs: 3500, dx: 160 },
              { atMs: 3650, dx: 200 },
              { atMs: 5900, dx: 200 },
              { atMs: 6050, dx: 280 },
              { atMs: 10000, dx: 280 },
            ],
          },
          // Bảng thất bại của mẫu ABAB: 0, 0, 1, 2 — tĩnh, đặt ngay dưới mẫu.
          {
            kind: 'label',
            id: 'f0',
            x: 39,
            y: 175,
            text: '0',
            size: 18,
            anchor: 'middle',
            fill: 'muted',
          },
          {
            kind: 'label',
            id: 'f1',
            x: 79,
            y: 175,
            text: '0',
            size: 18,
            anchor: 'middle',
            fill: 'muted',
          },
          {
            kind: 'label',
            id: 'f2',
            x: 119,
            y: 175,
            text: '1',
            size: 18,
            anchor: 'middle',
            fill: 'muted',
          },
          {
            kind: 'label',
            id: 'f3',
            x: 159,
            y: 175,
            text: '2',
            size: 18,
            anchor: 'middle',
            fill: 'muted',
          },
          // Con trỏ văn bản: mũi tên nhỏ chỉ di chuyển về phía trước, không bao giờ lùi.
          {
            kind: 'arrow',
            id: 'con-tro-i',
            x1: 39,
            y1: 15,
            x2: 39,
            y2: 38,
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 600, dx: 40 },
              { atMs: 1100, dx: 80 },
              { atMs: 1600, dx: 120 },
              { atMs: 2100, dx: 160 },
              { atMs: 3500, dx: 160 },
              { atMs: 3650, dx: 200 },
              { atMs: 4150, dx: 240 },
              { atMs: 4650, dx: 280 },
              { atMs: 5150, dx: 320 },
              { atMs: 5650, dx: 360 },
              { atMs: 5900, dx: 360 },
              { atMs: 6550, dx: 400 },
              { atMs: 10000, dx: 400 },
            ],
          },
          // Khung viền báo đúng, xuất hiện đúng lúc khớp đủ bốn ký tự và giữ nguyên đến hết cảnh.
          {
            kind: 'rect',
            id: 'khop-1',
            x: 22,
            y: 47,
            w: 156,
            h: 36,
            rx: 6,
            stroke: 'correct',
            strokeWidth: 3,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 2100, opacity: 0 },
              { atMs: 2200, opacity: 1 },
              { atMs: 10000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'khop-2',
            x: 222,
            y: 47,
            w: 156,
            h: 36,
            rx: 6,
            stroke: 'correct',
            strokeWidth: 3,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 5500, opacity: 0 },
              { atMs: 5600, opacity: 1 },
              { atMs: 10000, opacity: 1 },
            ],
          },
        ],
        captions: [
          {
            atMs: 0,
            text: 'Văn bản 10 ký tự A B A B C A B A B A ở hàng trên; mẫu 4 ký tự A B A B ở hàng dưới, kèm bảng thất bại của từng vị trí trong mẫu: 0, 0, 1, 2.',
          },
          {
            atMs: 2200,
            text: 'Con trỏ văn bản đi tới ký tự thứ năm và khớp đủ bốn ký tự — tìm thấy mẫu ở đầu văn bản, khung viền báo đúng xuất hiện.',
          },
          {
            atMs: 2650,
            text: 'Nhờ bảng thất bại, mẫu không dịch về đầu mà dịch sao cho hai ký tự A, B đã khớp trước đó được giữ nguyên, không so lại.',
          },
          {
            atMs: 3150,
            text: 'Ký tự tiếp theo của văn bản là C, không khớp; bảng thất bại lại rút gọn phần khớp còn giữ được về 0.',
          },
          {
            atMs: 3650,
            text: 'Không còn phần khớp nào giữ lại được nên mẫu dịch tiếp; con trỏ văn bản chỉ tiến thêm một bước, không lùi lại.',
          },
          {
            atMs: 4150,
            text: 'Từ đây các ký tự A, B, A, B của mẫu lần lượt khớp mà không cần so lại từ đầu mẫu.',
          },
          {
            atMs: 5600,
            text: 'Khớp đủ bốn ký tự lần nữa — tìm thấy mẫu lần hai, khung viền báo đúng thứ hai xuất hiện.',
          },
          {
            atMs: 6050,
            text: 'Bảng thất bại lại dịch mẫu tiếp mà không lùi con trỏ văn bản.',
          },
          {
            atMs: 6550,
            text: 'Con trỏ văn bản chạm hết mười ký tự, thuật toán dừng. Suốt quá trình con trỏ văn bản chỉ đi tới, không bao giờ lùi lại — đó là lý do KMP chạy trong thời gian tuyến tính, tỉ lệ với độ dài văn bản cộng độ dài mẫu.',
          },
        ],
      },
      objective:
        'Cài và kiểm chứng được các thuật toán chuỗi kinh điển thay vì chỉ gọi thư viện có sẵn.',
      practice: [
        'Cài ba thuật toán chuỗi từ đầu và kiểm mỗi cài đặt bằng đối chứng vét cạn trên dữ liệu ngẫu nhiên.',
        'Dùng băm chuỗi cho một bài rồi tự tạo trường hợp va chạm để thấy giới hạn của cách này.',
        'Áp dụng khoảng cách chỉnh sửa vào một bài toán thực tế như gợi ý sửa lỗi chính tả.',
      ],
      selfCheck: [
        {
          q: 'Vì sao băm chuỗi cần cẩn thận khi dùng trong thi đấu?',
          a: 'Có thể bị dựng dữ liệu gây va chạm, nên phải chọn mô-đun và cơ số đủ tốt hoặc dùng hai bộ băm.',
        },
        {
          q: 'Cấu trúc Aho-Corasick giải bài toán gì?',
          a: 'Tìm đồng thời nhiều mẫu trong một văn bản chỉ với một lần duyệt.',
        },
      ],
      doneSignals: [
        'Bạn kiểm cài đặt bằng đối chứng vét cạn trước khi tin nó đúng.',
        'Bạn chọn thuật toán chuỗi theo ràng buộc đề bài, không theo thói quen.',
      ],
    },
    {
      moduleId: 'algo-s3-m3',
      // Cảnh cho thấy VÌ SAO sàng Eratosthenes chỉ cần gạch bội của các số nguyên tố không lớn
      // hơn căn bậc hai của giới hạn trên. Phạm vi rút gọn còn 2..21 (thay vì 2..30) để tổng số
      // hình vẽ nằm trong giới hạn của hoạt ảnh — √21 ≈ 4,6 nên chỉ cần sàng với 2 và 3.
      animation: {
        title: 'Sàng Eratosthenes: chỉ cần gạch tới căn bậc hai',
        description:
          'Lưới hai hàng liệt kê các số từ 2 đến 21. Khung màu nhấn quét lần lượt tới từng số: lấy 2 làm số nguyên tố đầu tiên rồi gạch hết bội của 2 — mỗi số bị gạch mờ đi và có viền cảnh báo; lấy tiếp 3 làm số nguyên tố rồi chỉ cần gạch từ 3 nhân 3 trở đi vì các bội nhỏ hơn đã bị gạch từ trước. Vì căn bậc hai của 21 xấp xỉ 4,6, nhỏ hơn số nguyên tố kế tiếp là 5, nên sàng dừng lại: mọi số chưa từng bị gạch được viền xanh lá đánh dấu là số nguyên tố. Điểm cốt lõi: chỉ cần sàng các bội của những số nguyên tố không lớn hơn căn bậc hai của giới hạn trên là đủ liệt kê hết số nguyên tố trong đoạn.',
        viewBoxWidth: 460,
        viewBoxHeight: 150,
        durationMs: 9000,
        loop: true,
        shapes: [
          // Hàng 1: số 2..11 ở cột 0..9. Hàng 2: số 12..21 ở cột 0..9.
          {
            kind: 'label',
            id: 'n2',
            x: 40,
            y: 55,
            text: '2',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'n3',
            x: 80,
            y: 55,
            text: '3',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'n4',
            x: 120,
            y: 55,
            text: '4',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            opacity: 1,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 1350, opacity: 1 },
              { atMs: 1450, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'label',
            id: 'n5',
            x: 160,
            y: 55,
            text: '5',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'n6',
            x: 200,
            y: 55,
            text: '6',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            opacity: 1,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 1750, opacity: 1 },
              { atMs: 1850, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'label',
            id: 'n7',
            x: 240,
            y: 55,
            text: '7',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'n8',
            x: 280,
            y: 55,
            text: '8',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            opacity: 1,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 2150, opacity: 1 },
              { atMs: 2250, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'label',
            id: 'n9',
            x: 320,
            y: 55,
            text: '9',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            opacity: 1,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 5550, opacity: 1 },
              { atMs: 5650, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'label',
            id: 'n10',
            x: 360,
            y: 55,
            text: '10',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            opacity: 1,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 2550, opacity: 1 },
              { atMs: 2650, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'label',
            id: 'n11',
            x: 400,
            y: 55,
            text: '11',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'n12',
            x: 40,
            y: 105,
            text: '12',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            opacity: 1,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 2950, opacity: 1 },
              { atMs: 3050, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'label',
            id: 'n13',
            x: 80,
            y: 105,
            text: '13',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'n14',
            x: 120,
            y: 105,
            text: '14',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            opacity: 1,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 3350, opacity: 1 },
              { atMs: 3450, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'label',
            id: 'n15',
            x: 160,
            y: 105,
            text: '15',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            opacity: 1,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 5950, opacity: 1 },
              { atMs: 6050, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'label',
            id: 'n16',
            x: 200,
            y: 105,
            text: '16',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            opacity: 1,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 3750, opacity: 1 },
              { atMs: 3850, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'label',
            id: 'n17',
            x: 240,
            y: 105,
            text: '17',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'n18',
            x: 280,
            y: 105,
            text: '18',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            opacity: 1,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 4150, opacity: 1 },
              { atMs: 4250, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'label',
            id: 'n19',
            x: 320,
            y: 105,
            text: '19',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'n20',
            x: 360,
            y: 105,
            text: '20',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            opacity: 1,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 4550, opacity: 1 },
              { atMs: 4650, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'label',
            id: 'n21',
            x: 400,
            y: 105,
            text: '21',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            opacity: 1,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 6350, opacity: 1 },
              { atMs: 6450, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          // Khung màu nhấn quét tới từng số theo thứ tự gạch bội của 2 rồi bội của 3.
          {
            kind: 'rect',
            id: 'sweep',
            x: 22,
            y: 32,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'accent',
            strokeWidth: 3,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0, dx: 0, dy: 0 },
              { atMs: 400, opacity: 1, dx: 0, dy: 0 },
              { atMs: 1200, dx: 80, dy: 0 },
              { atMs: 1600, dx: 160, dy: 0 },
              { atMs: 2000, dx: 240, dy: 0 },
              { atMs: 2400, dx: 320, dy: 0 },
              { atMs: 2800, dx: 0, dy: 50 },
              { atMs: 3200, dx: 80, dy: 50 },
              { atMs: 3600, dx: 160, dy: 50 },
              { atMs: 4000, dx: 240, dy: 50 },
              { atMs: 4400, dx: 320, dy: 50 },
              { atMs: 4800, opacity: 0, dx: 320, dy: 50 },
              { atMs: 5000, opacity: 1, dx: 40, dy: 0 },
              { atMs: 5400, dx: 280, dy: 0 },
              { atMs: 5800, dx: 120, dy: 50 },
              { atMs: 6200, dx: 360, dy: 50 },
              { atMs: 6600, opacity: 0, dx: 360, dy: 50 },
              { atMs: 9000, opacity: 0, dx: 360, dy: 50 },
            ],
          },
          // Viền cảnh báo cho mỗi hợp số, xuất hiện đúng lúc bị gạch, giữ nguyên tới hết cảnh.
          {
            kind: 'rect',
            id: 'w4',
            x: 102,
            y: 32,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'warn',
            strokeWidth: 2,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 1350, opacity: 0 },
              { atMs: 1450, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'w6',
            x: 182,
            y: 32,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'warn',
            strokeWidth: 2,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 1750, opacity: 0 },
              { atMs: 1850, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'w8',
            x: 262,
            y: 32,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'warn',
            strokeWidth: 2,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 2150, opacity: 0 },
              { atMs: 2250, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'w10',
            x: 342,
            y: 32,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'warn',
            strokeWidth: 2,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 2550, opacity: 0 },
              { atMs: 2650, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'w12',
            x: 22,
            y: 82,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'warn',
            strokeWidth: 2,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 2950, opacity: 0 },
              { atMs: 3050, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'w14',
            x: 102,
            y: 82,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'warn',
            strokeWidth: 2,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 3350, opacity: 0 },
              { atMs: 3450, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'w16',
            x: 182,
            y: 82,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'warn',
            strokeWidth: 2,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 3750, opacity: 0 },
              { atMs: 3850, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'w18',
            x: 262,
            y: 82,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'warn',
            strokeWidth: 2,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 4150, opacity: 0 },
              { atMs: 4250, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'w20',
            x: 342,
            y: 82,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'warn',
            strokeWidth: 2,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 4550, opacity: 0 },
              { atMs: 4650, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'w9',
            x: 302,
            y: 32,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'warn',
            strokeWidth: 2,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 5550, opacity: 0 },
              { atMs: 5650, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'w15',
            x: 142,
            y: 82,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'warn',
            strokeWidth: 2,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 5950, opacity: 0 },
              { atMs: 6050, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'w21',
            x: 382,
            y: 82,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'warn',
            strokeWidth: 2,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 6350, opacity: 0 },
              { atMs: 6450, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          // Viền xanh lá cho từng số nguyên tố. 2 và 3 chốt ngay khi được chọn làm cơ số sàng;
          // các số còn lại (5, 7, 11, 13, 17, 19) chốt cùng lúc ở cuối vì chưa từng bị gạch.
          {
            kind: 'rect',
            id: 'ok2',
            x: 22,
            y: 32,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'correct',
            strokeWidth: 3,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 650, opacity: 0 },
              { atMs: 700, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'ok3',
            x: 62,
            y: 32,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'correct',
            strokeWidth: 3,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 5150, opacity: 0 },
              { atMs: 5200, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'ok-rest',
            x: 142,
            y: 32,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'correct',
            strokeWidth: 3,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 7000, opacity: 0 },
              { atMs: 7150, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'ok-rest2',
            x: 222,
            y: 32,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'correct',
            strokeWidth: 3,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 7000, opacity: 0 },
              { atMs: 7150, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'ok-rest3',
            x: 382,
            y: 32,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'correct',
            strokeWidth: 3,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 7000, opacity: 0 },
              { atMs: 7150, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'ok-rest4',
            x: 62,
            y: 82,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'correct',
            strokeWidth: 3,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 7000, opacity: 0 },
              { atMs: 7150, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'ok-rest5',
            x: 222,
            y: 82,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'correct',
            strokeWidth: 3,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 7000, opacity: 0 },
              { atMs: 7150, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'ok-rest6',
            x: 302,
            y: 82,
            w: 36,
            h: 36,
            rx: 6,
            stroke: 'correct',
            strokeWidth: 3,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 7000, opacity: 0 },
              { atMs: 7150, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
        ],
        captions: [
          {
            atMs: 0,
            text: 'Lưới hai hàng chứa các số từ 2 đến 21. Khung màu nhấn sẽ lần lượt quét qua từng số để đánh dấu số nguyên tố hay hợp số.',
          },
          {
            atMs: 700,
            text: 'Lấy số 2, số nhỏ nhất chưa bị gạch, làm số nguyên tố đầu tiên — viền xanh lá xuất hiện.',
          },
          {
            atMs: 1450,
            text: 'Gạch lần lượt các bội của 2: 4, 6, 8, 10, 12, 14, 16, 18, 20 — mỗi số bị gạch mờ đi kèm viền cảnh báo.',
          },
          {
            atMs: 5200,
            text: 'Bội của 2 gạch xong. Lấy số 3, số nhỏ nhất còn lại chưa bị gạch, làm số nguyên tố tiếp theo.',
          },
          {
            atMs: 5650,
            text: 'Chỉ cần gạch từ 3 nhân 3 bằng 9 trở đi vì các bội nhỏ hơn đã bị 2 gạch rồi: 9, 15, 21 lần lượt mờ đi.',
          },
          {
            atMs: 6600,
            text: 'Căn bậc hai của 21 xấp xỉ 4,6, nhỏ hơn số nguyên tố tiếp theo là 5, nên sàng dừng lại ở đây.',
          },
          {
            atMs: 7150,
            text: 'Mọi số còn lại — 5, 7, 11, 13, 17, 19 — chưa từng bị gạch nên đều là số nguyên tố, viền xanh lá xuất hiện đồng loạt.',
          },
        ],
      },
      objective:
        'Xử lý được các bài toán rời rạc và hình học cơ bản mà không mắc lỗi tràn số hay sai số dấu phẩy động.',
      practice: [
        'Giải mười bài số học mô-đun, tổ hợp và hình học, trong đó ít nhất ba bài dễ tràn số.',
        'Ghi lại ba chỗ suýt tràn số hoặc sai số và cách đã xử lý.',
        'Cài sàng nguyên tố rồi đo thời gian trên giới hạn lớn nhất của đề.',
      ],
      selfCheck: [
        {
          q: 'Vì sao so sánh số thực bằng dấu bằng là bẫy?',
          a: 'Sai số dấu phẩy động làm hai giá trị đáng lẽ bằng nhau lại lệch một chút, nên phải so theo ngưỡng.',
        },
        {
          q: 'Nhân hai số lớn theo mô-đun cần lưu ý gì?',
          a: 'Tích trung gian có thể vượt kiểu số đang dùng, nên phải chọn kiểu đủ rộng hoặc nhân theo cách an toàn.',
        },
      ],
      doneSignals: [
        'Bạn kiểm giới hạn số trước khi chọn kiểu dữ liệu.',
        'Bạn dùng số nguyên thay cho số thực bất cứ khi nào bài toán cho phép.',
      ],
    },
    {
      moduleId: 'algo-s3-m4',
      // Cảnh cho thấy VÌ SAO cây phân đoạn trả lời truy vấn tổng khoảng trong thời gian lôgarit:
      // chỉ cần chạm tới các nút mà khoảng của nó nằm TRỌN VẸN trong khoảng cần hỏi, không cần
      // xuống tới lá. Mảng đáy 3, 1, 4, 1, 5, 9, 2, 6; truy vấn tổng khoảng chỉ số 2 tới 5 (= 19).
      animation: {
        title: 'Cây phân đoạn: mỗi truy vấn chỉ chạm log n nút',
        description:
          'Mảng đáy có tám số 3, 1, 4, 1, 5, 9, 2, 6; phía trên là cây tổng ba tầng, mỗi nút lưu tổng của đúng một khoảng con liên tiếp trong mảng, nút gốc lưu tổng của cả tám số. Khi truy vấn tổng khoảng chỉ số 2 tới 5, phép tính đi từ gốc xuống: mỗi khi khoảng của một nút nằm trọn vẹn trong khoảng cần hỏi, nút đó được dùng thẳng mà không cần xuống tới tận lá — ở đây chỉ hai nút như vậy được tô sáng, một nút bao khoảng chỉ số 2 tới 3 và một nút bao khoảng chỉ số 4 tới 5, cộng lại đúng bằng tổng bốn số cần hỏi. Điểm cốt lõi: mỗi truy vấn chỉ chạm một số lượng nút tỉ lệ với chiều cao cây, tức lôgarit của kích thước mảng, chứ không phải duyệt qua từng phần tử.',
        viewBoxWidth: 460,
        viewBoxHeight: 245,
        durationMs: 8000,
        loop: true,
        shapes: [
          // Tám lá đáy, giữ nguyên giá trị mảng gốc.
          {
            kind: 'rect',
            id: 'l0',
            x: 25,
            y: 170,
            w: 40,
            h: 34,
            rx: 5,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'rect',
            id: 'l1',
            x: 75,
            y: 170,
            w: 40,
            h: 34,
            rx: 5,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'rect',
            id: 'l2',
            x: 125,
            y: 170,
            w: 40,
            h: 34,
            rx: 5,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'rect',
            id: 'l3',
            x: 175,
            y: 170,
            w: 40,
            h: 34,
            rx: 5,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'rect',
            id: 'l4',
            x: 225,
            y: 170,
            w: 40,
            h: 34,
            rx: 5,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'rect',
            id: 'l5',
            x: 275,
            y: 170,
            w: 40,
            h: 34,
            rx: 5,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'rect',
            id: 'l6',
            x: 325,
            y: 170,
            w: 40,
            h: 34,
            rx: 5,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'rect',
            id: 'l7',
            x: 375,
            y: 170,
            w: 40,
            h: 34,
            rx: 5,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'label',
            id: 'lv0',
            x: 45,
            y: 191,
            text: '3',
            size: 16,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'lv1',
            x: 95,
            y: 191,
            text: '1',
            size: 16,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'lv2',
            x: 145,
            y: 191,
            text: '4',
            size: 16,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'lv3',
            x: 195,
            y: 191,
            text: '1',
            size: 16,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'lv4',
            x: 245,
            y: 191,
            text: '5',
            size: 16,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'lv5',
            x: 295,
            y: 191,
            text: '9',
            size: 16,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'lv6',
            x: 345,
            y: 191,
            text: '2',
            size: 16,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'lv7',
            x: 395,
            y: 191,
            text: '6',
            size: 16,
            anchor: 'middle',
            fill: 'primary',
          },
          // Tầng cha trực tiếp của lá: mỗi nút gộp tổng của hai lá liền kề.
          {
            kind: 'rect',
            id: 'n4',
            x: 50,
            y: 118,
            w: 40,
            h: 34,
            rx: 5,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'rect',
            id: 'n5',
            x: 150,
            y: 118,
            w: 40,
            h: 34,
            rx: 5,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'rect',
            id: 'n6',
            x: 250,
            y: 118,
            w: 40,
            h: 34,
            rx: 5,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'rect',
            id: 'n7',
            x: 350,
            y: 118,
            w: 40,
            h: 34,
            rx: 5,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'label',
            id: 'nv4',
            x: 70,
            y: 139,
            text: '4',
            size: 16,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'nv5',
            x: 170,
            y: 139,
            text: '5',
            size: 16,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'nv6',
            x: 270,
            y: 139,
            text: '14',
            size: 16,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'nv7',
            x: 370,
            y: 139,
            text: '8',
            size: 16,
            anchor: 'middle',
            fill: 'primary',
          },
          // Tầng thứ ba: mỗi nút gộp tổng của bốn lá.
          {
            kind: 'rect',
            id: 'n2',
            x: 100,
            y: 66,
            w: 40,
            h: 34,
            rx: 5,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'rect',
            id: 'n3',
            x: 300,
            y: 66,
            w: 40,
            h: 34,
            rx: 5,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'label',
            id: 'nv2',
            x: 120,
            y: 87,
            text: '9',
            size: 16,
            anchor: 'middle',
            fill: 'primary',
          },
          {
            kind: 'label',
            id: 'nv3',
            x: 320,
            y: 87,
            text: '22',
            size: 16,
            anchor: 'middle',
            fill: 'primary',
          },
          // Nút gốc: tổng cả tám số.
          {
            kind: 'rect',
            id: 'n1',
            x: 200,
            y: 16,
            w: 40,
            h: 34,
            rx: 5,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          {
            kind: 'label',
            id: 'nv1',
            x: 220,
            y: 37,
            text: '31',
            size: 16,
            anchor: 'middle',
            fill: 'primary',
          },
          // Cạnh nối cha-con, chỉ để dẫn mắt, không mang trạng thái.
          {
            kind: 'line',
            id: 'e-1-2',
            x1: 220,
            y1: 50,
            x2: 120,
            y2: 66,
            stroke: 'muted',
            strokeWidth: 1,
          },
          {
            kind: 'line',
            id: 'e-1-3',
            x1: 220,
            y1: 50,
            x2: 320,
            y2: 66,
            stroke: 'muted',
            strokeWidth: 1,
          },
          {
            kind: 'line',
            id: 'e-2-4',
            x1: 120,
            y1: 100,
            x2: 70,
            y2: 118,
            stroke: 'muted',
            strokeWidth: 1,
          },
          {
            kind: 'line',
            id: 'e-2-5',
            x1: 120,
            y1: 100,
            x2: 170,
            y2: 118,
            stroke: 'muted',
            strokeWidth: 1,
          },
          {
            kind: 'line',
            id: 'e-3-6',
            x1: 320,
            y1: 100,
            x2: 270,
            y2: 118,
            stroke: 'muted',
            strokeWidth: 1,
          },
          {
            kind: 'line',
            id: 'e-3-7',
            x1: 320,
            y1: 100,
            x2: 370,
            y2: 118,
            stroke: 'muted',
            strokeWidth: 1,
          },
          {
            kind: 'line',
            id: 'e-4-l0',
            x1: 70,
            y1: 152,
            x2: 45,
            y2: 170,
            stroke: 'muted',
            strokeWidth: 1,
          },
          {
            kind: 'line',
            id: 'e-4-l1',
            x1: 70,
            y1: 152,
            x2: 95,
            y2: 170,
            stroke: 'muted',
            strokeWidth: 1,
          },
          {
            kind: 'line',
            id: 'e-5-l2',
            x1: 170,
            y1: 152,
            x2: 145,
            y2: 170,
            stroke: 'muted',
            strokeWidth: 1,
          },
          {
            kind: 'line',
            id: 'e-5-l3',
            x1: 170,
            y1: 152,
            x2: 195,
            y2: 170,
            stroke: 'muted',
            strokeWidth: 1,
          },
          {
            kind: 'line',
            id: 'e-6-l4',
            x1: 270,
            y1: 152,
            x2: 245,
            y2: 170,
            stroke: 'muted',
            strokeWidth: 1,
          },
          {
            kind: 'line',
            id: 'e-6-l5',
            x1: 270,
            y1: 152,
            x2: 295,
            y2: 170,
            stroke: 'muted',
            strokeWidth: 1,
          },
          {
            kind: 'line',
            id: 'e-7-l6',
            x1: 370,
            y1: 152,
            x2: 345,
            y2: 170,
            stroke: 'muted',
            strokeWidth: 1,
          },
          {
            kind: 'line',
            id: 'e-7-l7',
            x1: 370,
            y1: 152,
            x2: 395,
            y2: 170,
            stroke: 'muted',
            strokeWidth: 1,
          },
          // Viền đánh dấu đúng khoảng chỉ số 2 tới 5 cần hỏi, ngay trên hàng lá.
          {
            kind: 'rect',
            id: 'khoang-hoi',
            x: 125,
            y: 206,
            w: 190,
            h: 4,
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 1000, opacity: 0 },
              { atMs: 1100, opacity: 1 },
              { atMs: 8000, opacity: 1 },
            ],
          },
          // Gốc được xét trước, tô sáng thoáng qua rồi tắt vì khoảng của nó không nằm trọn vẹn
          // trong khoảng cần hỏi.
          {
            kind: 'rect',
            id: 'xet-n1',
            x: 200,
            y: 16,
            w: 40,
            h: 34,
            rx: 5,
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 500, opacity: 0 },
              { atMs: 600, opacity: 1 },
              { atMs: 1300, opacity: 1 },
              { atMs: 1400, opacity: 0 },
              { atMs: 8000, opacity: 0 },
            ],
          },
          // Hai nút con của gốc cũng chỉ trùng một phần với khoảng cần hỏi nên chỉ tô sáng thoáng
          // qua trước khi xét tiếp xuống dưới.
          {
            kind: 'rect',
            id: 'xet-n2',
            x: 100,
            y: 66,
            w: 40,
            h: 34,
            rx: 5,
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 1500, opacity: 0 },
              { atMs: 1600, opacity: 1 },
              { atMs: 2400, opacity: 1 },
              { atMs: 2500, opacity: 0 },
              { atMs: 8000, opacity: 0 },
            ],
          },
          {
            kind: 'rect',
            id: 'xet-n3',
            x: 300,
            y: 66,
            w: 40,
            h: 34,
            rx: 5,
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 1500, opacity: 0 },
              { atMs: 1600, opacity: 1 },
              { atMs: 2400, opacity: 1 },
              { atMs: 2500, opacity: 0 },
              { atMs: 8000, opacity: 0 },
            ],
          },
          // Hai nút bao khoảng trọn vẹn trong khoảng cần hỏi — dùng thẳng, tô sáng và giữ nguyên.
          {
            kind: 'rect',
            id: 'dung-n5',
            x: 150,
            y: 118,
            w: 40,
            h: 34,
            rx: 5,
            stroke: 'correct',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 2600, opacity: 0 },
              { atMs: 2700, opacity: 1 },
              { atMs: 8000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'dung-n6',
            x: 250,
            y: 118,
            w: 40,
            h: 34,
            rx: 5,
            stroke: 'correct',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 3000, opacity: 0 },
              { atMs: 3100, opacity: 1 },
              { atMs: 8000, opacity: 1 },
            ],
          },
          // Kết quả cộng hai nút vừa chọn, hiện ra sau khi cả hai đã được tô sáng.
          {
            kind: 'label',
            id: 'ket-qua',
            x: 220,
            y: 236,
            text: '5 + 14 = 19',
            size: 16,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 4400, opacity: 0 },
              { atMs: 4500, opacity: 1 },
              { atMs: 8000, opacity: 1 },
            ],
          },
        ],
        captions: [
          {
            atMs: 0,
            text: 'Mảng đáy tám số 3, 1, 4, 1, 5, 9, 2, 6; phía trên là cây tổng ba tầng, mỗi nút lưu tổng của một khoảng con liên tiếp, nút gốc lưu tổng cả tám số.',
          },
          {
            atMs: 600,
            text: 'Truy vấn bắt đầu từ nút gốc, so khoảng nó phụ trách với khoảng chỉ số 2 tới 5 cần hỏi — viền dưới cùng đánh dấu đúng đoạn này trên mảng đáy.',
          },
          {
            atMs: 1600,
            text: 'Gốc chia khoảng cho hai nút con; cả hai chỉ trùng một phần với khoảng cần hỏi nên phải xét tiếp xuống dưới.',
          },
          {
            atMs: 2700,
            text: 'Một nút con bao trọn vẹn khoảng chỉ số 2 tới 3, tổng bằng 5, được dùng thẳng mà không cần xuống tới lá.',
          },
          {
            atMs: 3100,
            text: 'Nút còn lại bao trọn vẹn khoảng chỉ số 4 tới 5, tổng bằng 14, cũng được dùng thẳng.',
          },
          {
            atMs: 4500,
            text: 'Cộng hai nút đã chọn: 5 cộng 14 bằng 19, đúng bằng tổng bốn số 4, 1, 5, 9. Truy vấn chỉ chạm vài nút theo chiều cao cây, không phải duyệt hết tám phần tử.',
          },
        ],
      },
      objective:
        'Dùng thành thạo cấu trúc dữ liệu truy vấn khoảng và biết khi nào một cấu trúc phức tạp là thừa.',
      practice: [
        'Cài cây phân đoạn có cập nhật lười rồi dùng lại đúng bản cài đó cho năm bài khác nhau.',
        'So cây phân đoạn với cây chỉ số nhị phân trên cùng một bài để thấy khi nào bản đơn giản là đủ.',
        'Đo thời gian truy vấn trên dữ liệu lớn nhất của đề để xác nhận độ phức tạp thực tế.',
      ],
      selfCheck: [
        {
          q: 'Cập nhật lười giải quyết vấn đề gì?',
          a: 'Cho phép cập nhật cả một khoảng trong thời gian logarit thay vì sửa từng phần tử.',
        },
        {
          q: 'Khi nào cây chỉ số nhị phân là lựa chọn tốt hơn?',
          a: 'Khi chỉ cần tổng tiền tố và cập nhật điểm: mã ngắn hơn, hằng số nhỏ hơn và ít lỗi hơn.',
        },
      ],
      doneSignals: [
        'Bạn dùng lại một bản cài đặt đã kiểm kỹ thay vì viết lại mỗi lần.',
        'Bạn chọn cấu trúc đơn giản nhất còn đáp ứng được ràng buộc đề bài.',
      ],
    },
  ],
  rubric: [
    {
      id: 'algo-s3-r1',
      text: 'Có nhật ký ít nhất 10 kỳ thi, mỗi kỳ ghi rõ sai ở đâu và thiếu mảng kiến thức nào.',
      howToProve: 'Nộp nhật ký theo từng kỳ kèm liên kết tới bài đã nộp trong kỳ đó.',
    },
    {
      id: 'algo-s3-r2',
      text: 'Toàn bộ bài không giải được trong kỳ thi đều được giải lại trong vòng 7 ngày kèm ghi chú.',
      howToProve:
        'Đối chiếu danh sách bài chưa giải với thời điểm nộp lại thành công của từng bài.',
    },
    {
      id: 'algo-s3-r3',
      text: 'Số bài giải được trong hai giờ hoặc mức xếp hạng tăng ít nhất 30% sau ba tháng luyện.',
      howToProve: 'Nộp số liệu của kỳ đầu và kỳ cuối trong quãng ba tháng, cùng định dạng thi.',
    },
    {
      id: 'algo-s3-r4',
      text: 'Ít nhất 80% bài nộp có bộ sinh dữ liệu ngẫu nhiên đối chứng chạy trước khi nộp.',
      howToProve: 'Nộp kịch bản sinh dữ liệu và nhật ký đối chứng của các bài đã làm.',
    },
  ],
  specBrief: {
    scopeDo: [
      'Luyện thi đấu có nhật ký và giải lại toàn bộ bài chưa làm được.',
      'Xây bộ cài đặt chuẩn dùng lại được cho các cấu trúc dữ liệu nâng cao.',
    ],
    scopeDont: [
      'Không học thuộc lời giải mẫu, vì mục tiêu là nhận ra dạng bài chứ không phải nhớ đáp án.',
      'Không chỉ làm bài trong vùng dễ chịu để tăng số lượng bài đã giải.',
    ],
    touchpoints: [
      'Kho mã chứa các bản cài đặt chuẩn và bộ sinh dữ liệu đối chứng.',
      'Nhật ký thi đấu và danh sách bài cần giải lại.',
    ],
    contracts: [
      'Mỗi bản cài đặt chuẩn ghi rõ độ phức tạp và giới hạn dữ liệu áp dụng được.',
      'Mỗi bài nộp có bộ sinh dữ liệu và bản giải vét cạn để đối chứng.',
    ],
    acceptance: [
      'Đạt đủ bốn tiêu chí rubric với số liệu thi đấu thật.',
      'Bộ cài đặt chuẩn đã được dùng lại ở ít nhất năm bài khác nhau.',
    ],
    invariants: [
      'Không nộp bài khi chưa kiểm ca biên nhỏ nhất và lớn nhất.',
      'Không bỏ qua bài khó sau kỳ thi; mọi bài chưa làm được đều phải quay lại.',
    ],
    conventions: [
      'Mỗi bản cài đặt lưu kèm một bài đã dùng nó để có ví dụ chạy thật.',
      'Ghi chú sau mỗi kỳ thi viết ngay trong ngày, khi còn nhớ mình nghĩ gì lúc làm bài.',
    ],
  },
}
