// details/algo-s1.ts — Chi tiết chặng S1 hướng THUẬT TOÁN ("Nền tảng và độ phức tạp").
// Bản đồ chặng nằm ở ../algo.ts; file này bổ sung phần THI HÀNH ĐƯỢC.
//
// Hướng này mang cờ `crossCutting`: học SONG SONG với hướng chính, không thay thế nó.
// Đặc thù S1: thứ đáng đo không phải số bài đã giải mà là bài giải LẠI được sau hai tuần —
// nên rubric ở đây đo trí nhớ dài hạn và kỷ luật kiểm thử, không đo số lượng.
import type { SpecStageDetail } from '../stageDetailTypes.js'

export const ALGO_S1_DETAIL: SpecStageDetail = {
  stageId: 'algo-s1',
  modules: [
    {
      moduleId: 'algo-s1-m1',
      // Cảnh cho thấy VÌ SAO sắp xếp nổi bọt có chi phí bậc hai: mỗi vòng quét chỉ chốt đúng
      // MỘT số (ô viền xanh lá), nên cần gần n vòng × n phép so sánh mới sắp xong cả mảng.
      animation: {
        title: 'Sắp xếp nổi bọt: so từng cặp liền kề rồi hoán đổi',
        description:
          'Một mảng sáu số 5, 2, 8, 1, 9, 3 nằm trong sáu ô vuông. Khung viền màu nhấn (sáng hơn viền các ô) chạy từ trái sang phải, mỗi lúc ôm lấy đúng hai ô liền kề đang được so sánh: nếu số bên trái lớn hơn số bên phải thì hai ô đổi chỗ cho nhau, còn không thì khung đi tiếp. Vòng quét thứ nhất đẩy số lớn nhất là 9 về sát ô cuối và ô đó được viền xanh lá báo đã đúng vị trí vĩnh viễn; vòng thứ hai chốt số 8 vào ô kế cuối; vòng thứ ba chốt nốt phần còn lại và mảng thành 1, 2, 3, 5, 8, 9. Điểm cần thấy: mỗi vòng quét tốn gần n phép so sánh mà chỉ chốt thêm được một số, nên tổng chi phí tăng theo bình phương kích thước mảng.',
        viewBoxWidth: 440,
        viewBoxHeight: 180,
        durationMs: 9000,
        loop: true,
        shapes: [
          // Sáu ô giá trị. dx = (vị trí mới - vị trí ban đầu) x 60 (mỗi ô rộng 50, cách nhau 10).
          {
            kind: 'rect',
            id: 'o-5',
            x: 40,
            y: 60,
            w: 50,
            h: 50,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 700, dx: 0 },
              { atMs: 1000, dx: 60 },
              { atMs: 3700, dx: 60 },
              { atMs: 4000, dx: 120 },
              { atMs: 6700, dx: 120 },
              { atMs: 7000, dx: 180 },
              { atMs: 9000, dx: 180 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-2',
            x: 100,
            y: 60,
            w: 50,
            h: 50,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 700, dx: 0 },
              { atMs: 1000, dx: -60 },
              { atMs: 5700, dx: -60 },
              { atMs: 6000, dx: 0 },
              { atMs: 9000, dx: 0 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-8',
            x: 160,
            y: 60,
            w: 50,
            h: 50,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 1700, dx: 0 },
              { atMs: 2000, dx: 60 },
              { atMs: 4700, dx: 60 },
              { atMs: 5000, dx: 120 },
              { atMs: 9000, dx: 120 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-1',
            x: 220,
            y: 60,
            w: 50,
            h: 50,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 1700, dx: 0 },
              { atMs: 2000, dx: -60 },
              { atMs: 3700, dx: -60 },
              { atMs: 4000, dx: -120 },
              { atMs: 5700, dx: -120 },
              { atMs: 6000, dx: -180 },
              { atMs: 9000, dx: -180 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-9',
            x: 280,
            y: 60,
            w: 50,
            h: 50,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 2700, dx: 0 },
              { atMs: 3000, dx: 60 },
              { atMs: 9000, dx: 60 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-3',
            x: 340,
            y: 60,
            w: 50,
            h: 50,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 2700, dx: 0 },
              { atMs: 3000, dx: -60 },
              { atMs: 4700, dx: -60 },
              { atMs: 5000, dx: -120 },
              { atMs: 6700, dx: -120 },
              { atMs: 7000, dx: -180 },
              { atMs: 9000, dx: -180 },
            ],
          },
          // Số bên trong ô: đi kèm đúng ô của nó nên dùng lại y hệt bộ keyframes ở trên.
          {
            kind: 'label',
            id: 'so-5',
            x: 65,
            y: 93,
            text: '5',
            size: 24,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 700, dx: 0 },
              { atMs: 1000, dx: 60 },
              { atMs: 3700, dx: 60 },
              { atMs: 4000, dx: 120 },
              { atMs: 6700, dx: 120 },
              { atMs: 7000, dx: 180 },
              { atMs: 9000, dx: 180 },
            ],
          },
          {
            kind: 'label',
            id: 'so-2',
            x: 125,
            y: 93,
            text: '2',
            size: 24,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 700, dx: 0 },
              { atMs: 1000, dx: -60 },
              { atMs: 5700, dx: -60 },
              { atMs: 6000, dx: 0 },
              { atMs: 9000, dx: 0 },
            ],
          },
          {
            kind: 'label',
            id: 'so-8',
            x: 185,
            y: 93,
            text: '8',
            size: 24,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 1700, dx: 0 },
              { atMs: 2000, dx: 60 },
              { atMs: 4700, dx: 60 },
              { atMs: 5000, dx: 120 },
              { atMs: 9000, dx: 120 },
            ],
          },
          {
            kind: 'label',
            id: 'so-1',
            x: 245,
            y: 93,
            text: '1',
            size: 24,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 1700, dx: 0 },
              { atMs: 2000, dx: -60 },
              { atMs: 3700, dx: -60 },
              { atMs: 4000, dx: -120 },
              { atMs: 5700, dx: -120 },
              { atMs: 6000, dx: -180 },
              { atMs: 9000, dx: -180 },
            ],
          },
          {
            kind: 'label',
            id: 'so-9',
            x: 305,
            y: 93,
            text: '9',
            size: 24,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 2700, dx: 0 },
              { atMs: 3000, dx: 60 },
              { atMs: 9000, dx: 60 },
            ],
          },
          {
            kind: 'label',
            id: 'so-3',
            x: 365,
            y: 93,
            text: '3',
            size: 24,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, dx: 0 },
              { atMs: 2700, dx: 0 },
              { atMs: 3000, dx: -60 },
              { atMs: 4700, dx: -60 },
              { atMs: 5000, dx: -120 },
              { atMs: 6700, dx: -120 },
              { atMs: 7000, dx: -180 },
              { atMs: 9000, dx: -180 },
            ],
          },
          // Khung màu nhấn (vai trò `accent`, đổi theo theme — KHÔNG gọi tên màu cụ thể) ôm CẶP đang được so sánh, chạy lại từ đầu mảng ở mỗi vòng quét.
          {
            kind: 'rect',
            id: 'khung-so-sanh',
            x: 36,
            y: 56,
            w: 118,
            h: 58,
            rx: 8,
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, dx: 0, opacity: 1 },
              { atMs: 700, dx: 0 },
              { atMs: 1200, dx: 60 },
              { atMs: 1700, dx: 120 },
              { atMs: 2200, dx: 180 },
              { atMs: 2700, dx: 240 },
              { atMs: 3300, dx: 0 },
              { atMs: 3700, dx: 60 },
              { atMs: 4300, dx: 120 },
              { atMs: 4700, dx: 180 },
              { atMs: 5700, dx: 0 },
              { atMs: 6300, dx: 60 },
              { atMs: 6700, dx: 120 },
              { atMs: 7200, dx: 120, opacity: 0 },
              { atMs: 9000, dx: 120, opacity: 0 },
            ],
          },
          // Viền xanh lá = ô đã chắc chắn đúng vị trí cuối cùng, không phải so lại nữa.
          {
            kind: 'rect',
            id: 'chot-o-cuoi',
            x: 336,
            y: 56,
            w: 58,
            h: 58,
            rx: 8,
            stroke: 'correct',
            strokeWidth: 3,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 3000, opacity: 0 },
              { atMs: 3200, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'chot-o-ke-cuoi',
            x: 276,
            y: 56,
            w: 58,
            h: 58,
            rx: 8,
            stroke: 'correct',
            strokeWidth: 3,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 5000, opacity: 0 },
              { atMs: 5200, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'chot-phan-con-lai',
            x: 36,
            y: 56,
            w: 238,
            h: 58,
            rx: 8,
            stroke: 'correct',
            strokeWidth: 3,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 7000, opacity: 0 },
              { atMs: 7200, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
        ],
        captions: [
          {
            atMs: 0,
            text: 'Sắp xếp nổi bọt: quét từ trái sang phải, so từng cặp ô liền kề; trái lớn hơn phải thì đổi chỗ.',
          },
          { atMs: 700, text: 'Vòng 1 — so 5 với 2: 5 > 2 nên hai ô đổi chỗ cho nhau.' },
          {
            atMs: 1700,
            text: 'So 8 với 1: 8 > 1, đổi chỗ. Số lớn cứ thế bị đẩy dần về phía bên phải.',
          },
          {
            atMs: 2700,
            text: 'So 9 với 3: đổi chỗ. Hết vòng 1, số lớn nhất là 9 đã nằm đúng ô cuối — viền xanh lá đánh dấu chốt.',
          },
          {
            atMs: 3300,
            text: 'Vòng 2 chỉ cần quét tới ô kế cuối, vì ô cuối đã chắc chắn đúng rồi.',
          },
          { atMs: 3700, text: 'So 5 với 1: 5 > 1 nên đổi chỗ.' },
          { atMs: 4700, text: 'So 8 với 3: đổi chỗ. Hết vòng 2, số 8 vào đúng ô kế cuối.' },
          { atMs: 5700, text: 'Vòng 3 — so 2 với 1: đổi chỗ, số nhỏ nhất về được ô đầu tiên.' },
          { atMs: 6700, text: 'So 5 với 3: đổi chỗ — đây là lần hoán đổi cuối cùng.' },
          {
            atMs: 7200,
            text: 'Mảng đã sắp xong: 1 2 3 5 8 9. Mỗi vòng quét chỉ chốt thêm một số mà tốn gần n phép so sánh, nên chi phí tăng theo bình phương kích thước mảng.',
          },
        ],
      },
      objective:
        'Đọc ràng buộc của đề bài là suy ra được lớp thuật toán nào chấp nhận được, và kiểm lại lý thuyết bằng đo thời gian thật.',
      practice: [
        'Với năm đề có ràng buộc khác nhau, viết ra lớp độ phức tạp tối đa được phép trước khi nghĩ lời giải.',
        'Chạy một thuật toán bậc hai trên dữ liệu tăng gấp đôi nhiều lần, vẽ đồ thị thời gian và đối chiếu lý thuyết.',
        'Tìm một đoạn mã có vòng lặp lồng nhưng thực ra chỉ chạy tuyến tính, giải thích vì sao.',
      ],
      selfCheck: [
        {
          q: 'Ràng buộc kích thước dữ liệu cho biết điều gì về thuật toán cần dùng?',
          a: 'Nó chặn trên số phép tính chấp nhận được, nên loại thẳng những lớp thuật toán quá chậm trước khi nghĩ.',
        },
        {
          q: 'Phân tích khấu hao khác phân tích trường hợp xấu nhất ở chỗ nào?',
          a: 'Khấu hao chia đều chi phí một thao tác đắt hiếm gặp cho cả dãy thao tác, nên phản ánh chi phí thật hơn.',
        },
        {
          q: 'Vì sao đo thời gian thật vẫn cần dù đã phân tích được big-O?',
          a: 'Hằng số ẩn và tính cục bộ của bộ nhớ ảnh hưởng lớn ở kích thước thật, big-O không nói gì về chúng.',
        },
      ],
      doneSignals: [
        'Bạn loại được phương án quá chậm trước khi viết dòng mã nào.',
        'Đồ thị thời gian đo được khớp với hình dạng bạn dự đoán.',
      ],
    },
    {
      moduleId: 'algo-s1-m2',
      // Cảnh cho thấy VÌ SAO mảng động vẫn thêm phần tử với chi phí O(1) khấu hao dù thỉnh
      // thoảng phải sao chép toàn bộ: dung lượng nhân đôi 2 → 4 → 8, ô cũ mờ đi lúc sao chép
      // rồi mờ dần xong thì phần tử mới cứ thế được thêm vào bình thường.
      animation: {
        title: 'Mảng động: nhân đôi dung lượng khi đầy, chi phí sao chép khấu hao dần',
        description:
          'Tám ô vuông nối tiếp biểu diễn một mảng động. Ban đầu chỉ hai ô đầu hiện ra (dung lượng 2), lần lượt nhận số 1 rồi số 2 và đầy chỗ. Khi cần thêm số 3, mảng cấp một vùng nhớ mới gấp đôi: hai ô kế tiếp xuất hiện với khung màu nhấn nhấp nháy, đồng thời hai ô cũ mờ đi một nhịp để biểu thị đang sao chép giá trị cũ sang vùng mới. Số 3, 4 được thêm vào và dung lượng 4 lại đầy, mảng nhân đôi tiếp lên 8: bốn ô mới xuất hiện, bốn ô cũ mờ đi trong lúc sao chép, rồi số 5, 6, 7, 8 lần lượt được thêm cho tới khi đầy 8/8. Điểm cần thấy: mỗi lần nhân đôi tốn sao chép toàn bộ phần tử cũ, nhưng việc này càng lúc càng hiếm xảy ra, nên tính trung bình mỗi lần thêm một phần tử vẫn chỉ tốn thời gian hằng số.',
        viewBoxWidth: 440,
        viewBoxHeight: 180,
        durationMs: 9500,
        loop: true,
        shapes: [
          // Tám ô của mảng động, x tính theo công thức 20 + i*50 (ô rộng 42, cách nhau 8).
          {
            kind: 'rect',
            id: 'o-cap-0',
            x: 20,
            y: 70,
            w: 42,
            h: 42,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 2000, opacity: 1 },
              { atMs: 2200, opacity: 0.4 },
              { atMs: 2600, opacity: 1 },
              { atMs: 4400, opacity: 1 },
              { atMs: 4600, opacity: 0.4 },
              { atMs: 5000, opacity: 1 },
              { atMs: 9500, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-cap-1',
            x: 70,
            y: 70,
            w: 42,
            h: 42,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 2000, opacity: 1 },
              { atMs: 2200, opacity: 0.4 },
              { atMs: 2600, opacity: 1 },
              { atMs: 4400, opacity: 1 },
              { atMs: 4600, opacity: 0.4 },
              { atMs: 5000, opacity: 1 },
              { atMs: 9500, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-cap-2',
            x: 120,
            y: 70,
            w: 42,
            h: 42,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 2000, opacity: 0 },
              { atMs: 2300, opacity: 1 },
              { atMs: 4400, opacity: 1 },
              { atMs: 4600, opacity: 0.4 },
              { atMs: 5000, opacity: 1 },
              { atMs: 9500, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-cap-3',
            x: 170,
            y: 70,
            w: 42,
            h: 42,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 2000, opacity: 0 },
              { atMs: 2300, opacity: 1 },
              { atMs: 4400, opacity: 1 },
              { atMs: 4600, opacity: 0.4 },
              { atMs: 5000, opacity: 1 },
              { atMs: 9500, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-cap-4',
            x: 220,
            y: 70,
            w: 42,
            h: 42,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 4400, opacity: 0 },
              { atMs: 4700, opacity: 1 },
              { atMs: 9500, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-cap-5',
            x: 270,
            y: 70,
            w: 42,
            h: 42,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 4400, opacity: 0 },
              { atMs: 4700, opacity: 1 },
              { atMs: 9500, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-cap-6',
            x: 320,
            y: 70,
            w: 42,
            h: 42,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 4400, opacity: 0 },
              { atMs: 4700, opacity: 1 },
              { atMs: 9500, opacity: 1 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-cap-7',
            x: 370,
            y: 70,
            w: 42,
            h: 42,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 4400, opacity: 0 },
              { atMs: 4700, opacity: 1 },
              { atMs: 9500, opacity: 1 },
            ],
          },
          // Số bên trong từng ô, xuất hiện đúng lúc phần tử được thêm vào.
          {
            kind: 'label',
            id: 'so-1',
            x: 41,
            y: 98,
            text: '1',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 400, opacity: 0 },
              { atMs: 600, opacity: 1 },
              { atMs: 2000, opacity: 1 },
              { atMs: 2200, opacity: 0.4 },
              { atMs: 2600, opacity: 1 },
              { atMs: 4400, opacity: 1 },
              { atMs: 4600, opacity: 0.4 },
              { atMs: 5000, opacity: 1 },
              { atMs: 9500, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'so-2',
            x: 91,
            y: 98,
            text: '2',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 1000, opacity: 0 },
              { atMs: 1200, opacity: 1 },
              { atMs: 2000, opacity: 1 },
              { atMs: 2200, opacity: 0.4 },
              { atMs: 2600, opacity: 1 },
              { atMs: 4400, opacity: 1 },
              { atMs: 4600, opacity: 0.4 },
              { atMs: 5000, opacity: 1 },
              { atMs: 9500, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'so-3',
            x: 141,
            y: 98,
            text: '3',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 2800, opacity: 0 },
              { atMs: 3000, opacity: 1 },
              { atMs: 4400, opacity: 1 },
              { atMs: 4600, opacity: 0.4 },
              { atMs: 5000, opacity: 1 },
              { atMs: 9500, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'so-4',
            x: 191,
            y: 98,
            text: '4',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 3400, opacity: 0 },
              { atMs: 3600, opacity: 1 },
              { atMs: 4400, opacity: 1 },
              { atMs: 4600, opacity: 0.4 },
              { atMs: 5000, opacity: 1 },
              { atMs: 9500, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'so-5',
            x: 241,
            y: 98,
            text: '5',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 5200, opacity: 0 },
              { atMs: 5400, opacity: 1 },
              { atMs: 9500, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'so-6',
            x: 291,
            y: 98,
            text: '6',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 5800, opacity: 0 },
              { atMs: 6000, opacity: 1 },
              { atMs: 9500, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'so-7',
            x: 341,
            y: 98,
            text: '7',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 6400, opacity: 0 },
              { atMs: 6600, opacity: 1 },
              { atMs: 9500, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'so-8',
            x: 391,
            y: 98,
            text: '8',
            size: 22,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 7000, opacity: 0 },
              { atMs: 7200, opacity: 1 },
              { atMs: 9500, opacity: 1 },
            ],
          },
          // Khung màu nhấn nhấp nháy quanh ô vừa cấp mới, báo hiệu vùng nhớ vừa được cấp thêm.
          {
            kind: 'rect',
            id: 'khung-cap-moi-4',
            x: 118,
            y: 68,
            w: 96,
            h: 46,
            rx: 8,
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 2000, opacity: 0 },
              { atMs: 2100, opacity: 1 },
              { atMs: 2600, opacity: 1 },
              { atMs: 2900, opacity: 0 },
              { atMs: 9500, opacity: 0 },
            ],
          },
          {
            kind: 'rect',
            id: 'khung-cap-moi-8',
            x: 218,
            y: 68,
            w: 196,
            h: 46,
            rx: 8,
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 4400, opacity: 0 },
              { atMs: 4500, opacity: 1 },
              { atMs: 5000, opacity: 1 },
              { atMs: 5300, opacity: 0 },
              { atMs: 9500, opacity: 0 },
            ],
          },
          // Khung màu nhấn phủ lên các ô CŨ đang được sao chép, cùng nhịp với việc chúng mờ đi.
          {
            kind: 'rect',
            id: 'khung-dang-sao-chep-4',
            x: 18,
            y: 68,
            w: 96,
            h: 46,
            rx: 8,
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 2000, opacity: 0 },
              { atMs: 2100, opacity: 1 },
              { atMs: 2600, opacity: 1 },
              { atMs: 2900, opacity: 0 },
              { atMs: 9500, opacity: 0 },
            ],
          },
          {
            kind: 'rect',
            id: 'khung-dang-sao-chep-8',
            x: 18,
            y: 68,
            w: 196,
            h: 46,
            rx: 8,
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 4400, opacity: 0 },
              { atMs: 4500, opacity: 1 },
              { atMs: 5000, opacity: 1 },
              { atMs: 5300, opacity: 0 },
              { atMs: 9500, opacity: 0 },
            ],
          },
          // Nhãn dung lượng hiện tại, đổi bằng cách hiện/ẩn ba nhãn khác nhau theo mốc thời gian.
          {
            kind: 'label',
            id: 'nhan-dung-luong-2',
            x: 220,
            y: 30,
            text: 'Dung lượng: 2',
            size: 15,
            anchor: 'middle',
            fill: 'neutral',
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 1900, opacity: 1 },
              { atMs: 2000, opacity: 0 },
              { atMs: 9500, opacity: 0 },
            ],
          },
          {
            kind: 'label',
            id: 'nhan-dung-luong-4',
            x: 220,
            y: 30,
            text: 'Dung lượng: 4',
            size: 15,
            anchor: 'middle',
            fill: 'neutral',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 2000, opacity: 0 },
              { atMs: 2100, opacity: 1 },
              { atMs: 4300, opacity: 1 },
              { atMs: 4400, opacity: 0 },
              { atMs: 9500, opacity: 0 },
            ],
          },
          {
            kind: 'label',
            id: 'nhan-dung-luong-8',
            x: 220,
            y: 30,
            text: 'Dung lượng: 8',
            size: 15,
            anchor: 'middle',
            fill: 'neutral',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 4400, opacity: 0 },
              { atMs: 4500, opacity: 1 },
              { atMs: 9500, opacity: 1 },
            ],
          },
        ],
        captions: [
          {
            atMs: 0,
            text: 'Mảng động bắt đầu với dung lượng 2 ô, còn trống.',
          },
          { atMs: 600, text: 'Thêm phần tử 1 vào ô đầu tiên.' },
          { atMs: 1200, text: 'Thêm phần tử 2 — mảng đầy 2/2, không còn chỗ trống.' },
          {
            atMs: 2100,
            text: 'Cấp một vùng nhớ mới gấp đôi (dung lượng 4) và sao chép hai phần tử cũ sang đó — ô cũ mờ đi trong lúc sao chép.',
          },
          { atMs: 3000, text: 'Sao chép xong, thêm phần tử 3 vào ô mới.' },
          { atMs: 3600, text: 'Thêm phần tử 4 — mảng lại đầy, lần này là 4/4.' },
          {
            atMs: 4500,
            text: 'Đầy lần nữa: nhân đôi dung lượng lên 8 và sao chép bốn phần tử cũ sang vùng nhớ mới.',
          },
          {
            atMs: 5400,
            text: 'Sao chép xong, lần lượt thêm phần tử 5, 6, 7, 8 cho tới khi đầy 8/8.',
          },
          {
            atMs: 7200,
            text: 'Việc sao chép tốn thời gian tuyến tính nhưng chỉ xảy ra khi mảng đầy — càng lúc càng hiếm khi kích thước phải tăng.',
          },
          {
            atMs: 8200,
            text: 'Tính trung bình cộng dồn, mỗi lần thêm phần tử chỉ tốn thời gian hằng số — gọi là chi phí O(1) khấu hao.',
          },
        ],
      },
      objective:
        'Chọn đúng cấu trúc dữ liệu tuyến tính cho từng bài toán dựa trên chi phí thật của thao tác chính, không theo thói quen.',
      practice: [
        'Tự cài mảng động có nhân đôi dung lượng, đếm số lần sao chép khi thêm một triệu phần tử.',
        'So thời gian chèn vào giữa của mảng động và danh sách liên kết ở nhiều kích thước khác nhau.',
        'Cố tình tạo va chạm hàng loạt trong bảng băm và quan sát thời gian tra cứu xấu đi thế nào.',
      ],
      selfCheck: [
        {
          q: 'Vì sao mảng động thường nhanh hơn danh sách liên kết dù cùng độ phức tạp lý thuyết?',
          a: 'Phần tử nằm liền nhau trong bộ nhớ nên bộ đệm của bộ xử lý hoạt động hiệu quả, còn con trỏ thì nhảy lung tung.',
        },
        {
          q: 'Bảng băm có chi phí tra cứu hằng số trong điều kiện nào?',
          a: 'Khi hàm băm phân tán đều; va chạm nhiều thì tra cứu thoái hoá về tuyến tính trong nhóm va chạm.',
        },
        {
          q: 'Nhân đôi dung lượng khi mảng đầy mang lại lợi ích gì?',
          a: 'Chi phí sao chép được khấu hao thành hằng số cho mỗi lần thêm, thay vì tuyến tính nếu tăng từng ô.',
        },
      ],
      doneSignals: [
        'Bạn giải thích được vì sao chọn cấu trúc này thay vì cấu trúc kia bằng chi phí thao tác.',
        'Bạn nhận ra ngay khi một bài đang dùng sai cấu trúc dữ liệu.',
      ],
    },
    {
      moduleId: 'algo-s1-m3',
      // Cảnh cho thấy VÌ SAO tìm kiếm nhị phân chỉ tốn log n bước: mỗi lần so mid với giá trị
      // cần tìm, cả một nửa khoảng đang xét bị loại (mờ đi) ngay lập tức, không phải quét qua.
      animation: {
        title: 'Tìm kiếm nhị phân: mỗi bước bỏ đi một nửa khoảng đang xét',
        description:
          'Một mảng chín số đã sắp tăng dần: 2, 5, 9, 12, 17, 23, 30, 38, 45, cần tìm số 23. Hai đường kẻ đứt nét đánh dấu biên trái (lo) và biên phải (hi) của khoảng đang xét, khung màu nhấn bao quanh ô giữa (mid). Bước một: mid ở ô thứ 5 (giá trị 17), nhỏ hơn 23 nên cả nửa trái từ lo tới mid mờ đi và bị loại, lo dời sang phải. Bước hai: mid mới ở ô thứ 7 (giá trị 30), lớn hơn 23 nên cả nửa phải từ mid tới hi mờ đi và bị loại, hi dời sang trái. Bước ba: mid trùng đúng ô còn lại (giá trị 23), bằng số cần tìm — viền báo đúng hiện quanh ô đó. Điểm cần thấy: chỉ ba bước cho chín phần tử, vì mỗi bước loại hẳn một nửa khoảng đang xét thay vì quét từng ô, nên số bước tăng theo logarit chứ không theo kích thước mảng.',
        viewBoxWidth: 440,
        viewBoxHeight: 180,
        durationMs: 9000,
        loop: true,
        shapes: [
          // Chín ô giá trị đã sắp, x = 20 + i*44 (ô rộng 38, cách nhau 6).
          {
            kind: 'rect',
            id: 'o-0',
            x: 20,
            y: 70,
            w: 38,
            h: 42,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 1200, opacity: 1 },
              { atMs: 1400, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-1',
            x: 64,
            y: 70,
            w: 38,
            h: 42,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 1200, opacity: 1 },
              { atMs: 1400, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-2',
            x: 108,
            y: 70,
            w: 38,
            h: 42,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 1200, opacity: 1 },
              { atMs: 1400, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-3',
            x: 152,
            y: 70,
            w: 38,
            h: 42,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 1200, opacity: 1 },
              { atMs: 1400, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-4',
            x: 196,
            y: 70,
            w: 38,
            h: 42,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 1200, opacity: 1 },
              { atMs: 1400, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-5',
            x: 240,
            y: 70,
            w: 38,
            h: 42,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [{ atMs: 0, opacity: 1 }],
          },
          {
            kind: 'rect',
            id: 'o-6',
            x: 284,
            y: 70,
            w: 38,
            h: 42,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 2800, opacity: 1 },
              { atMs: 3000, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-7',
            x: 328,
            y: 70,
            w: 38,
            h: 42,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 2800, opacity: 1 },
              { atMs: 3000, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'rect',
            id: 'o-8',
            x: 372,
            y: 70,
            w: 38,
            h: 42,
            rx: 6,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 2800, opacity: 1 },
              { atMs: 3000, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          // Số bên trong ô, đi kèm y hệt keyframes mờ/loại của ô chứa nó.
          {
            kind: 'label',
            id: 'so-2',
            x: 39,
            y: 98,
            text: '2',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 1200, opacity: 1 },
              { atMs: 1400, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'label',
            id: 'so-5',
            x: 83,
            y: 98,
            text: '5',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 1200, opacity: 1 },
              { atMs: 1400, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'label',
            id: 'so-9',
            x: 127,
            y: 98,
            text: '9',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 1200, opacity: 1 },
              { atMs: 1400, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'label',
            id: 'so-12',
            x: 171,
            y: 98,
            text: '12',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 1200, opacity: 1 },
              { atMs: 1400, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'label',
            id: 'so-17',
            x: 215,
            y: 98,
            text: '17',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 1200, opacity: 1 },
              { atMs: 1400, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'label',
            id: 'so-23',
            x: 259,
            y: 98,
            text: '23',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [{ atMs: 0, opacity: 1 }],
          },
          {
            kind: 'label',
            id: 'so-30',
            x: 303,
            y: 98,
            text: '30',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 2800, opacity: 1 },
              { atMs: 3000, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'label',
            id: 'so-38',
            x: 347,
            y: 98,
            text: '38',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 2800, opacity: 1 },
              { atMs: 3000, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          {
            kind: 'label',
            id: 'so-45',
            x: 391,
            y: 98,
            text: '45',
            size: 20,
            anchor: 'middle',
            fill: 'primary',
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 2800, opacity: 1 },
              { atMs: 3000, opacity: 0.4 },
              { atMs: 9000, opacity: 0.4 },
            ],
          },
          // Đường kẻ đứt nét đánh dấu biên trái (lo) và biên phải (hi) của khoảng đang xét.
          {
            kind: 'line',
            id: 'bien-lo',
            x1: 20,
            y1: 58,
            x2: 20,
            y2: 124,
            stroke: 'primary',
            strokeWidth: 3,
            dash: '4 2',
            keyframes: [
              { atMs: 0, dx: 0, opacity: 1 },
              { atMs: 1300, dx: 0 },
              { atMs: 1400, dx: 220 },
              { atMs: 4300, dx: 220 },
              { atMs: 4400, dx: 220, opacity: 0 },
              { atMs: 9000, dx: 220, opacity: 0 },
            ],
          },
          {
            kind: 'line',
            id: 'bien-hi',
            x1: 410,
            y1: 58,
            x2: 410,
            y2: 124,
            stroke: 'primary',
            strokeWidth: 3,
            dash: '4 2',
            keyframes: [
              { atMs: 0, dx: 0, opacity: 1 },
              { atMs: 2700, dx: 0 },
              { atMs: 3000, dx: -132 },
              { atMs: 4300, dx: -132 },
              { atMs: 4400, dx: -132, opacity: 0 },
              { atMs: 9000, dx: -132, opacity: 0 },
            ],
          },
          // Khung màu nhấn bao quanh ô mid, dời chỗ theo từng bước rồi mờ đi khi đã tìm thấy.
          {
            kind: 'rect',
            id: 'khung-mid',
            x: 193,
            y: 67,
            w: 44,
            h: 48,
            rx: 8,
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, dx: 0, opacity: 1 },
              { atMs: 1500, dx: 0 },
              { atMs: 1600, dx: 88 },
              { atMs: 2900, dx: 88 },
              { atMs: 3000, dx: 44 },
              { atMs: 4200, dx: 44 },
              { atMs: 4400, dx: 44, opacity: 0 },
              { atMs: 9000, dx: 44, opacity: 0 },
            ],
          },
          // Viền báo đúng, chỉ hiện ra khi mid trùng đúng ô mang giá trị cần tìm.
          {
            kind: 'rect',
            id: 'vien-bao-dung',
            x: 237,
            y: 67,
            w: 44,
            h: 48,
            rx: 8,
            stroke: 'correct',
            strokeWidth: 3,
            opacity: 0,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 4200, opacity: 0 },
              { atMs: 4400, opacity: 1 },
              { atMs: 9000, opacity: 1 },
            ],
          },
        ],
        captions: [
          {
            atMs: 0,
            text: 'Mảng đã sắp: 2, 5, 9, 12, 17, 23, 30, 38, 45. Tìm số 23. lo ở ô 0, hi ở ô 8, mid = ô 4 (khung màu nhấn).',
          },
          { atMs: 600, text: 'So giá trị ở mid (17) với 23.' },
          {
            atMs: 1400,
            text: '17 nhỏ hơn 23 nên đáp án nằm nửa bên phải — nửa trái (ô 0 tới ô 4) bị loại, mờ đi. lo dời tới ô 5.',
          },
          { atMs: 1600, text: 'Tính lại mid = (5+8)/2 = ô 6.' },
          { atMs: 2800, text: 'So giá trị ở mid (30) với 23.' },
          {
            atMs: 3000,
            text: '30 lớn hơn 23 nên đáp án nằm nửa bên trái — nửa phải (ô 6 tới ô 8) bị loại, mờ đi. hi dời tới ô 5.',
          },
          { atMs: 3200, text: 'Tính lại mid = (5+5)/2 = ô 5.' },
          {
            atMs: 4400,
            text: 'So giá trị ở mid (23) với 23: bằng nhau — tìm thấy! Viền báo đúng xuất hiện quanh ô 5.',
          },
          {
            atMs: 6000,
            text: 'Chỉ 3 bước cho 9 phần tử: mỗi bước bỏ đi một nửa khoảng đang xét, nên số bước tăng theo logarit, không theo tuyến tính.',
          },
        ],
      },
      objective:
        'Nhận ra được dạng bài phù hợp với hai con trỏ, cửa sổ trượt, tổng tiền tố hay tìm kiếm nhị phân trên đáp án.',
      practice: [
        'Giải một bài bằng cách vét cạn trước, rồi tối ưu bằng cửa sổ trượt và so kết quả hai bản.',
        'Dùng tổng tiền tố để trả lời nhiều truy vấn đoạn con, đo lại thời gian so với cộng lại từng lần.',
        'Giải một bài tối ưu hoá bằng cách nhị phân trên đáp án, viết rõ hàm kiểm tính khả thi.',
      ],
      selfCheck: [
        {
          q: 'Dấu hiệu nào cho biết một bài dùng được cửa sổ trượt?',
          a: 'Đáp án tính trên đoạn liên tiếp và khi cửa sổ dịch một bước thì cập nhật được mà không tính lại từ đầu.',
        },
        {
          q: 'Nhị phân trên đáp án dùng được khi nào?',
          a: 'Khi tính khả thi đơn điệu theo đáp án: khả thi với giá trị nào thì cũng khả thi với mọi giá trị dễ hơn.',
        },
        {
          q: 'Tổng tiền tố đánh đổi cái gì để lấy tốc độ truy vấn?',
          a: 'Tốn thêm bộ nhớ và phải dựng lại khi dữ liệu đổi, đổi lấy mỗi truy vấn chỉ còn một phép trừ.',
        },
      ],
      doneSignals: [
        'Đọc đề xong bạn nhận ra dạng quen thuộc trong vài phút.',
        'Bản tối ưu của bạn luôn cho cùng kết quả với bản vét cạn trên mọi dữ liệu thử.',
      ],
    },
    {
      moduleId: 'algo-s1-m4',
      objective:
        'Giữ kỷ luật giải bài: nghĩ ca biên trước khi viết mã và dùng kiểm thử ngẫu nhiên đối chiếu với bản đơn giản chắc đúng.',
      practice: [
        'Trước mỗi bài, viết ra danh sách ca biên rồi mới viết mã, sau đó đếm bao nhiêu ca bạn đã đoán trúng.',
        'Viết bản vét cạn chắc đúng làm chuẩn rồi sinh dữ liệu ngẫu nhiên so hai bản cho tới khi tìm ra ca lệch.',
        'Ghi nhật ký cho mỗi bài gồm ý tưởng, độ phức tạp và ca biên, rồi giải lại bài đó sau hai tuần.',
      ],
      selfCheck: [
        {
          q: 'Vì sao viết bản vét cạn chắc đúng lại đáng công dù nó chậm?',
          a: 'Nó là thước đo để phát hiện lời giải nhanh sai ở đâu, thứ mà đọc mã bằng mắt gần như không tìm ra.',
        },
        {
          q: 'Kiểm thử ngẫu nhiên mạnh hơn tự nghĩ ca kiểm ở điểm nào?',
          a: 'Nó tìm ra những tổ hợp bạn không nghĩ tới, đúng chỗ trực giác của bạn đang có điểm mù.',
        },
        {
          q: 'Vì sao giải lại bài cũ sau hai tuần lại là bài kiểm tra tốt?',
          a: 'Nó phân biệt hiểu thật với nhớ tạm; nhớ tạm thì hai tuần sau đã bay mất.',
        },
      ],
      doneSignals: [
        'Bạn tìm ra lỗi của mình bằng kiểm thử ngẫu nhiên chứ không bằng đọc lại mã.',
        'Bài đã giải cách đây hai tuần bạn làm lại được mà không nhìn lời giải cũ.',
      ],
    },
  ],
  rubric: [
    {
      id: 'algo-s1-r1',
      text: 'Đủ 80 bài mức dễ tới trung bình, mỗi bài có nhật ký ghi ý tưởng, độ phức tạp và ca biên đã nghĩ.',
      howToProve:
        'Dán mục lục nhật ký kèm ba mục bất kỳ đầy đủ ba phần để soát chất lượng ghi chép.',
    },
    {
      id: 'algo-s1-r2',
      text: 'Ít nhất 15 bài đã được giải lại sau hai tuần mà không nhìn lời giải cũ, có ghi ngày cả hai lần.',
      howToProve:
        'Dán bảng 15 bài kèm ngày giải lần đầu và ngày giải lại, cùng kết quả nộp của lần hai.',
    },
    {
      id: 'algo-s1-r3',
      text: 'Có bộ kiểm thử ngẫu nhiên đối chiếu hai lời giải cho ít nhất năm bài, chạy được bằng một lệnh.',
      howToProve:
        'Chạy bộ kiểm thử và dán kết quả, kèm một ca lệch mà nó từng tìm ra trong lúc bạn làm.',
    },
    {
      id: 'algo-s1-r4',
      text: 'Có ít nhất một bài kèm đồ thị đo thời gian thật đối chiếu với độ phức tạp lý thuyết đã phân tích.',
      howToProve:
        'Dán bảng số liệu đo ở nhiều kích thước đầu vào cùng đồ thị và nhận xét về hằng số ẩn.',
    },
  ],
  specBrief: {
    scopeDo: [
      'Giải 80 bài mức dễ tới trung bình phủ đủ bốn module của chặng, mỗi bài kèm nhật ký cách nghĩ.',
      'Bộ kiểm thử ngẫu nhiên đối chiếu lời giải nhanh với bản vét cạn cho ít nhất năm bài.',
      'Một lượt giải lại 15 bài cũ sau hai tuần để kiểm tra trí nhớ dài hạn.',
    ],
    scopeDont: [
      'KHÔNG đụng tới quy hoạch động hay đồ thị, vì đó là nội dung chặng sau và học sớm sẽ hổng phần nền.',
      'KHÔNG chạy đua số lượng bài, 80 bài có nhật ký tốt hơn 300 bài giải xong quên ngay.',
      'KHÔNG chép lời giải rồi ghi nhật ký theo, nhật ký phải phản ánh cách bạn thật sự nghĩ.',
    ],
    touchpoints: [
      'Thư mục lời giải: mỗi bài một tệp, tên tệp có mã bài để tra lại.',
      'Tệp nhật ký: mỗi bài một mục gồm ý tưởng, độ phức tạp, ca biên và ngày giải.',
      'Thư mục kiểm thử ngẫu nhiên: bộ sinh dữ liệu, bản vét cạn và kịch bản so kết quả.',
    ],
    contracts: [
      'Mỗi lời giải ghi rõ độ phức tạp thời gian và bộ nhớ ngay đầu tệp.',
      'Bản vét cạn và bản tối ưu nhận cùng định dạng đầu vào để so trực tiếp được.',
      'Bộ sinh dữ liệu nhận một hạt giống để tái hiện lại đúng ca lệch đã tìm ra.',
    ],
    acceptance: [
      'Bốn tiêu chí rubric ở trên đều đạt và có bằng chứng kèm theo.',
      'Người khác chạy bộ kiểm thử ngẫu nhiên của bạn với cùng hạt giống và ra cùng kết quả.',
    ],
    invariants: [
      'Không bài nào vào nhật ký mà chưa tự giải được ít nhất một lần.',
      'Mọi lời giải tối ưu đều đã được đối chiếu với một bản chắc đúng hoặc với bộ ca kiểm chính thức.',
      'Ngày giải ghi đúng thời điểm thật, không ghi lùi để cho đủ khoảng hai tuần.',
    ],
    conventions: [
      'Nhật ký viết bằng tiếng Việt, đủ để chính bạn hai tuần sau đọc lại hiểu được.',
      'Đặt tên biến theo ý nghĩa trong bài toán, không dùng một chữ cái trừ chỉ số vòng lặp.',
      'Commit nhỏ theo conventional commits, mỗi commit một thay đổi logic.',
    ],
  },
}
