// details/algo-s2.ts — Chi tiết chặng S2 hướng THUẬT TOÁN (cây, đồ thị, đệ quy, tham lam).
import type { SpecStageDetail } from '../stageDetailTypes.js'

export const ALGO_S2_DETAIL: SpecStageDetail = {
  stageId: 'algo-s2',
  modules: [
    {
      moduleId: 'algo-s2-m1',
      // Cảnh cho thấy VÌ SAO cắt tỉa sớm tiết kiệm cả nhánh con: một khung nhỏ đi DFS từ gốc
      // xuống ba nhánh; nhánh giữa vi phạm ràng buộc ngay khi vừa tới nơi nên bị cắt hẳn,
      // không cần xét hai lá bên dưới nó.
      animation: {
        title: 'Đệ quy quay lui: cắt tỉa bỏ cả một nhánh con',
        description:
          'Một cây quyết định ba tầng: gốc có ba nhánh, mỗi nhánh dẫn tới hai lá. Một khung nhỏ đi từ gốc xuống theo chiều sâu: nó thăm nhánh thứ nhất, lần lượt xét cả hai lá của nhánh đó — cả hai đều không phải nghiệm nên quay lại gốc. Sang nhánh thứ hai, ngay khi vừa tới nơi đã phát hiện vi phạm ràng buộc nên toàn bộ nhánh con của nó (mờ đi, có viền báo đã cắt) bị bỏ qua hoàn toàn, không cần xét từng lá bên trong. Sang nhánh thứ ba, lá đầu không phải nghiệm nhưng lá thứ hai thoả điều kiện — toàn bộ đường từ gốc tới lá đó được đánh dấu viền báo đã tìm thấy nghiệm. Điểm mấu chốt: cắt tỉa sớm giúp bỏ qua cả một nhánh con lớn mà không cần duyệt từng phần tử bên trong nó.',
        viewBoxWidth: 440,
        viewBoxHeight: 230,
        durationMs: 12000,
        loop: true,
        shapes: [
          // Cạnh nối gốc với ba nhánh, và mỗi nhánh với hai lá của nó. Hai cạnh dẫn tới nhánh
          // bị cắt vẽ nét đứt + mờ sẵn: chúng không bao giờ thật sự được đi qua.
          { kind: 'line', id: 'e-goc-n1', x1: 220, y1: 30, x2: 90, y2: 100, stroke: 'primary' },
          { kind: 'line', id: 'e-goc-n2', x1: 220, y1: 30, x2: 220, y2: 100, stroke: 'primary' },
          { kind: 'line', id: 'e-goc-n3', x1: 220, y1: 30, x2: 350, y2: 100, stroke: 'primary' },
          { kind: 'line', id: 'e-n1-l1a', x1: 90, y1: 100, x2: 50, y2: 175, stroke: 'primary' },
          { kind: 'line', id: 'e-n1-l1b', x1: 90, y1: 100, x2: 130, y2: 175, stroke: 'primary' },
          {
            kind: 'line',
            id: 'e-n2-l2a',
            x1: 220,
            y1: 100,
            x2: 185,
            y2: 175,
            stroke: 'muted',
            dash: '4 3',
            opacity: 0.35,
          },
          {
            kind: 'line',
            id: 'e-n2-l2b',
            x1: 220,
            y1: 100,
            x2: 255,
            y2: 175,
            stroke: 'muted',
            dash: '4 3',
            opacity: 0.35,
          },
          { kind: 'line', id: 'e-n3-l3a', x1: 350, y1: 100, x2: 315, y2: 175, stroke: 'primary' },
          { kind: 'line', id: 'e-n3-l3b', x1: 350, y1: 100, x2: 390, y2: 175, stroke: 'primary' },
          // Các nút của cây — mỗi nút một hình nền cố định, cộng một lớp "kết quả" phủ lên
          // xuất hiện đúng lúc khung đi qua nó (vì màu một hình không đổi được theo thời gian,
          // trạng thái "đã xét/đã cắt/đã tìm thấy" phải là một hình riêng fade dần vào).
          { kind: 'circle', id: 'goc', cx: 220, cy: 30, r: 16, fill: 'surface', stroke: 'primary' },
          {
            kind: 'circle',
            id: 'goc-thanh-cong',
            cx: 220,
            cy: 30,
            r: 16,
            fill: 'surface',
            stroke: 'correct',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 6600, opacity: 0 },
              { atMs: 6800, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          { kind: 'circle', id: 'n1', cx: 90, cy: 100, r: 14, fill: 'surface', stroke: 'primary' },
          {
            kind: 'circle',
            id: 'n1-da-xet',
            cx: 90,
            cy: 100,
            r: 14,
            fill: 'surface',
            stroke: 'muted',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 3100, opacity: 0 },
              { atMs: 3300, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          { kind: 'circle', id: 'n2', cx: 220, cy: 100, r: 14, fill: 'surface', stroke: 'primary' },
          {
            kind: 'circle',
            id: 'n2-bi-cat',
            cx: 220,
            cy: 100,
            r: 14,
            fill: 'surface',
            stroke: 'warn',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 3900, opacity: 0 },
              { atMs: 4100, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          { kind: 'circle', id: 'n3', cx: 350, cy: 100, r: 14, fill: 'surface', stroke: 'primary' },
          {
            kind: 'circle',
            id: 'n3-thanh-cong',
            cx: 350,
            cy: 100,
            r: 14,
            fill: 'surface',
            stroke: 'correct',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 6600, opacity: 0 },
              { atMs: 6800, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          { kind: 'circle', id: 'l1a', cx: 50, cy: 175, r: 12, fill: 'surface', stroke: 'primary' },
          {
            kind: 'circle',
            id: 'l1a-da-xet',
            cx: 50,
            cy: 175,
            r: 12,
            fill: 'surface',
            stroke: 'muted',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 2100, opacity: 0 },
              { atMs: 2300, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          {
            kind: 'circle',
            id: 'l1b',
            cx: 130,
            cy: 175,
            r: 12,
            fill: 'surface',
            stroke: 'primary',
          },
          {
            kind: 'circle',
            id: 'l1b-da-xet',
            cx: 130,
            cy: 175,
            r: 12,
            fill: 'surface',
            stroke: 'muted',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 2900, opacity: 0 },
              { atMs: 3100, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          // Hai lá của nhánh bị cắt: không bao giờ được khung ghé qua, vẽ mờ sẵn từ đầu.
          {
            kind: 'circle',
            id: 'l2a',
            cx: 185,
            cy: 175,
            r: 12,
            fill: 'surface',
            stroke: 'muted',
            opacity: 0.35,
          },
          {
            kind: 'circle',
            id: 'l2b',
            cx: 255,
            cy: 175,
            r: 12,
            fill: 'surface',
            stroke: 'muted',
            opacity: 0.35,
          },
          {
            kind: 'circle',
            id: 'l3a',
            cx: 315,
            cy: 175,
            r: 12,
            fill: 'surface',
            stroke: 'primary',
          },
          {
            kind: 'circle',
            id: 'l3a-da-xet',
            cx: 315,
            cy: 175,
            r: 12,
            fill: 'surface',
            stroke: 'muted',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 5600, opacity: 0 },
              { atMs: 5800, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          {
            kind: 'circle',
            id: 'l3b',
            cx: 390,
            cy: 175,
            r: 12,
            fill: 'surface',
            stroke: 'primary',
          },
          {
            kind: 'circle',
            id: 'l3b-nghiem',
            cx: 390,
            cy: 175,
            r: 12,
            fill: 'surface',
            stroke: 'correct',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 6600, opacity: 0 },
              { atMs: 6800, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          // Khung nhỏ đi DFS — dx/dy là toạ độ tuyệt đối tính từ gốc, TÍCH LUỸ theo mỗi mốc.
          {
            kind: 'circle',
            id: 'khung',
            cx: 220,
            cy: 30,
            r: 8,
            fill: 'accent',
            stroke: 'accent',
            keyframes: [
              { atMs: 0, dx: 0, dy: 0 },
              { atMs: 500, dx: 0, dy: 0 },
              { atMs: 900, dx: -130, dy: 70 },
              { atMs: 1300, dx: -130, dy: 70 },
              { atMs: 1700, dx: -170, dy: 145 },
              { atMs: 2100, dx: -170, dy: 145 },
              { atMs: 2500, dx: -90, dy: 145 },
              { atMs: 2900, dx: -90, dy: 145 },
              { atMs: 3400, dx: 0, dy: 70 },
              { atMs: 3900, dx: 0, dy: 70 },
              { atMs: 4400, dx: 130, dy: 70 },
              { atMs: 4800, dx: 130, dy: 70 },
              { atMs: 5200, dx: 95, dy: 145 },
              { atMs: 5600, dx: 95, dy: 145 },
              { atMs: 6000, dx: 170, dy: 145 },
              { atMs: 6600, dx: 170, dy: 145 },
              { atMs: 9500, dx: 170, dy: 145 },
              { atMs: 12000, dx: 170, dy: 145 },
            ],
          },
          {
            kind: 'label',
            id: 'nhan-cat',
            x: 220,
            y: 128,
            text: 'cắt tỉa',
            size: 12,
            anchor: 'middle',
            fill: 'neutral',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 3900, opacity: 0 },
              { atMs: 4100, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'nhan-nghiem',
            x: 390,
            y: 203,
            text: 'nghiệm',
            size: 12,
            anchor: 'middle',
            fill: 'neutral',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 6600, opacity: 0 },
              { atMs: 6800, opacity: 1 },
              { atMs: 12000, opacity: 1 },
            ],
          },
        ],
        captions: [
          { atMs: 900, text: 'Bắt đầu từ gốc, đi xuống nhánh thứ nhất.' },
          { atMs: 1700, text: 'Thăm lá đầu tiên của nhánh 1 — hợp lệ nhưng chưa phải nghiệm.' },
          {
            atMs: 2500,
            text: 'Quay lại, thăm lá thứ hai của nhánh 1 — vẫn không phải nghiệm, cả nhánh 1 coi như xong.',
          },
          { atMs: 3400, text: 'Sang nhánh thứ hai: kiểm tra điều kiện ngay khi vừa tới.' },
          {
            atMs: 3900,
            text: 'Nhánh thứ hai vi phạm ràng buộc — cắt bỏ toàn bộ nhánh con, không cần đi xuống hai lá còn lại.',
          },
          { atMs: 4400, text: 'Sang nhánh thứ ba, đi xuống lá đầu tiên.' },
          { atMs: 5200, text: 'Lá đầu của nhánh 3 không phải nghiệm, quay lại thử lá thứ hai.' },
          {
            atMs: 6000,
            text: 'Lá thứ hai của nhánh 3 thoả điều kiện — tìm thấy nghiệm! Đường đi từ gốc được đánh dấu.',
          },
        ],
      },
      objective:
        'Thiết kế được lời giải đệ quy có chứng minh dừng và biết khi nào phải chuyển sang lặp.',
      practice: [
        'Giải mười bài quay lui, mỗi bài viết rõ điều kiện cắt tỉa trước khi code.',
        'Chuyển một lời giải đệ quy sâu sang lặp dùng ngăn xếp tường minh, so mức dùng bộ nhớ.',
        'Viết bộ sinh dữ liệu ngẫu nhiên đối chiếu lời giải nhanh với lời giải vét cạn.',
      ],
      selfCheck: [
        {
          q: 'Một lời giải đệ quy cần gì để chắc chắn dừng?',
          a: 'Mỗi lời gọi phải thu nhỏ bài toán theo một đại lượng giảm dần và có trường hợp cơ sở chặn lại.',
        },
        {
          q: 'Cắt tỉa sai thì hậu quả gì?',
          a: 'Bỏ mất nghiệm đúng mà chương trình vẫn chạy trơn tru — loại lỗi chỉ kiểm thử đối chiếu mới bắt được.',
        },
      ],
      doneSignals: [
        'Ước lượng được số nhánh phải duyệt trước khi chạy.',
        'Có bộ kiểm thử ngẫu nhiên đối chiếu cho ít nhất năm bài.',
      ],
    },
    {
      moduleId: 'algo-s2-m2',
      // Cảnh cho thấy sift-up chỉ đụng tới đúng MỘT đường từ lá mới lên gốc — không phải
      // toàn bộ đống — nên chi phí tỉ lệ chiều cao cây (log n), không phải kích thước đống.
      animation: {
        title: 'Đống nhị phân: thêm phần tử rồi nổi lên tới đúng chỗ',
        description:
          'Một đống nhị phân nhỏ dạng cây, sáu nút đã đúng thứ tự. Thêm một giá trị mới nhỏ hơn mọi nút hiện có vào vị trí trống cuối cùng, là con của một nút giữa cây. Nút mới được so với nút cha: vì nhỏ hơn nên đổi chỗ, đi lên một bậc. Ở vị trí mới nó lại được so với cha tiếp theo là nút gốc: vẫn nhỏ hơn nên đổi chỗ lần nữa, lần này lên tới gốc. Gốc không còn cha để so nên dừng lại, khung viền báo đã đúng xuất hiện ở gốc. Điểm mấu chốt: toàn bộ thao tác chỉ đi qua đúng một đường thẳng từ lá mới lên gốc, nên chi phí tỉ lệ với chiều cao cây — tức lôgarit số phần tử — chứ không phải với toàn bộ đống.',
        viewBoxWidth: 440,
        viewBoxHeight: 200,
        durationMs: 8500,
        loop: true,
        shapes: [
          { kind: 'line', id: 'e-1-2', x1: 220, y1: 30, x2: 120, y2: 90, stroke: 'muted' },
          { kind: 'line', id: 'e-1-3', x1: 220, y1: 30, x2: 320, y2: 90, stroke: 'muted' },
          { kind: 'line', id: 'e-2-4', x1: 120, y1: 90, x2: 70, y2: 150, stroke: 'muted' },
          { kind: 'line', id: 'e-2-5', x1: 120, y1: 90, x2: 170, y2: 150, stroke: 'muted' },
          { kind: 'line', id: 'e-3-6', x1: 320, y1: 90, x2: 270, y2: 150, stroke: 'muted' },
          { kind: 'line', id: 'e-3-7', x1: 320, y1: 90, x2: 370, y2: 150, stroke: 'muted' },
          // Các nút KHÔNG di chuyển của đống (không tham gia hai lần đổi chỗ).
          {
            kind: 'circle',
            id: 'nut-5',
            cx: 120,
            cy: 90,
            r: 14,
            fill: 'surface',
            stroke: 'primary',
          },
          { kind: 'label', id: 'nhan-5', x: 120, y: 95, text: '5', size: 16, anchor: 'middle' },
          {
            kind: 'circle',
            id: 'nut-8',
            cx: 70,
            cy: 150,
            r: 13,
            fill: 'surface',
            stroke: 'primary',
          },
          { kind: 'label', id: 'nhan-8', x: 70, y: 155, text: '8', size: 14, anchor: 'middle' },
          {
            kind: 'circle',
            id: 'nut-9',
            cx: 170,
            cy: 150,
            r: 13,
            fill: 'surface',
            stroke: 'primary',
          },
          { kind: 'label', id: 'nhan-9', x: 170, y: 155, text: '9', size: 14, anchor: 'middle' },
          {
            kind: 'circle',
            id: 'nut-6',
            cx: 270,
            cy: 150,
            r: 13,
            fill: 'surface',
            stroke: 'primary',
          },
          { kind: 'label', id: 'nhan-6', x: 270, y: 155, text: '6', size: 14, anchor: 'middle' },
          // Nút giá trị 3: ban đầu ở giữa cây, bị đẩy xuống vị trí lá khi nút mới nổi lên.
          {
            kind: 'circle',
            id: 'nut-3',
            cx: 320,
            cy: 90,
            r: 14,
            fill: 'surface',
            stroke: 'primary',
            keyframes: [
              { atMs: 0, dx: 0, dy: 0 },
              { atMs: 1000, dx: 0, dy: 0 },
              { atMs: 1800, dx: 50, dy: 60 },
              { atMs: 8500, dx: 50, dy: 60 },
            ],
          },
          {
            kind: 'label',
            id: 'nhan-3',
            x: 320,
            y: 95,
            text: '3',
            size: 16,
            anchor: 'middle',
            keyframes: [
              { atMs: 0, dx: 0, dy: 0 },
              { atMs: 1000, dx: 0, dy: 0 },
              { atMs: 1800, dx: 50, dy: 60 },
              { atMs: 8500, dx: 50, dy: 60 },
            ],
          },
          // Nút giá trị 2: gốc ban đầu, bị đẩy xuống vị trí con khi nút mới nổi lên tới gốc.
          {
            kind: 'circle',
            id: 'nut-2',
            cx: 220,
            cy: 30,
            r: 16,
            fill: 'surface',
            stroke: 'primary',
            keyframes: [
              { atMs: 0, dx: 0, dy: 0 },
              { atMs: 2600, dx: 0, dy: 0 },
              { atMs: 3400, dx: 100, dy: 60 },
              { atMs: 8500, dx: 100, dy: 60 },
            ],
          },
          {
            kind: 'label',
            id: 'nhan-2',
            x: 220,
            y: 35,
            text: '2',
            size: 18,
            anchor: 'middle',
            keyframes: [
              { atMs: 0, dx: 0, dy: 0 },
              { atMs: 2600, dx: 0, dy: 0 },
              { atMs: 3400, dx: 100, dy: 60 },
              { atMs: 8500, dx: 100, dy: 60 },
            ],
          },
          // Nút mới (giá trị 1): bắt đầu ở lá vừa thêm, nổi lên hai bậc tới gốc. Viền màu nhấn
          // để luôn nhận ra đây là nút đang được theo dõi trong suốt cảnh.
          {
            kind: 'circle',
            id: 'nut-1-moi',
            cx: 370,
            cy: 150,
            r: 13,
            fill: 'surface',
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, dx: 0, dy: 0 },
              { atMs: 1000, dx: 0, dy: 0 },
              { atMs: 1800, dx: -50, dy: -60 },
              { atMs: 2600, dx: -50, dy: -60 },
              { atMs: 3400, dx: -150, dy: -120 },
              { atMs: 8500, dx: -150, dy: -120 },
            ],
          },
          {
            kind: 'label',
            id: 'nhan-1-moi',
            x: 370,
            y: 155,
            text: '1',
            size: 14,
            anchor: 'middle',
            fill: 'accent',
            keyframes: [
              { atMs: 0, dx: 0, dy: 0 },
              { atMs: 1000, dx: 0, dy: 0 },
              { atMs: 1800, dx: -50, dy: -60 },
              { atMs: 2600, dx: -50, dy: -60 },
              { atMs: 3400, dx: -150, dy: -120 },
              { atMs: 8500, dx: -150, dy: -120 },
            ],
          },
          // Lớp phủ báo "đã đúng chỗ" tại gốc, hiện ra khi sift-up dừng lại.
          {
            kind: 'circle',
            id: 'goc-dung',
            cx: 220,
            cy: 30,
            r: 16,
            stroke: 'correct',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 3400, opacity: 0 },
              { atMs: 3700, opacity: 1 },
              { atMs: 8500, opacity: 1 },
            ],
          },
        ],
        captions: [
          { atMs: 0, text: 'Thêm giá trị 1 vào cuối đống, ở vị trí con của nút giá trị 3.' },
          { atMs: 1000, text: 'So với nút cha (giá trị 3): 1 nhỏ hơn nên đổi chỗ cho nhau.' },
          { atMs: 1800, text: '1 đã lên một bậc, giờ so với cha mới của vị trí đó (giá trị 2).' },
          { atMs: 2600, text: '1 vẫn nhỏ hơn 2 nên tiếp tục đổi chỗ, đi lên tới gốc.' },
          { atMs: 3400, text: 'Gốc không còn cha để so — đống lại đúng thứ tự.' },
          {
            atMs: 3700,
            text: 'Toàn bộ quá trình chỉ đụng tới đúng một đường thẳng từ lá mới lên gốc.',
          },
        ],
      },
      objective:
        'Chọn và cài đặt đúng cấu trúc cây cho bài toán, giải thích được độ phức tạp từng thao tác.',
      practice: [
        'Cài cây tìm kiếm nhị phân và đo suy biến khi chèn dữ liệu đã sắp xếp.',
        'Dùng hàng đợi ưu tiên giải bài toán chọn k phần tử lớn nhất trên luồng dữ liệu.',
        'Cài cây tiền tố cho gợi ý từ khoá và đo bộ nhớ so với danh sách phẳng.',
      ],
      selfCheck: [
        {
          q: 'Vì sao cây tìm kiếm nhị phân không cân bằng lại nguy hiểm?',
          a: 'Dữ liệu đã sắp xếp biến nó thành danh sách liên kết, thao tác từ logarit tụt xuống tuyến tính.',
        },
        {
          q: 'Khi nào hàng đợi ưu tiên hơn hẳn sắp xếp toàn bộ?',
          a: 'Khi chỉ cần k phần tử đầu trên tập rất lớn hoặc trên luồng dữ liệu không giữ hết được.',
        },
      ],
      doneSignals: [
        'Nói được độ phức tạp từng thao tác mà không tra lại.',
        'Chọn cấu trúc dựa trên đặc điểm dữ liệu, không theo thói quen.',
      ],
    },
    {
      moduleId: 'algo-s2-m3',
      // Cảnh cho thấy BFS thăm theo LỚP: mọi đỉnh cách nguồn k bước được chốt trước mọi đỉnh
      // cách nguồn k+1 bước, nên khi cạnh không trọng số, thứ tự chốt CHÍNH LÀ khoảng cách ngắn nhất.
      animation: {
        title: 'BFS: lan truyền theo từng lớp khoảng cách',
        description:
          'Một đồ thị tám đỉnh nối với nhau bằng các đoạn thẳng, bắt đầu từ một đỉnh xuất phát. Việc thăm lan ra theo từng lớp: đỉnh xuất phát được chốt khoảng cách 0 trước tiên, hai đỉnh liền kề nó vào hàng đợi (viền màu nhấn báo đang chờ xét) rồi lần lượt được chốt khoảng cách 1 (viền báo đã chốt, kèm nhãn số). Các đỉnh liền kề của lớp 1 vào hàng đợi và lần lượt được chốt khoảng cách 2, rồi tới lớp xa nhất được chốt khoảng cách 3. Điểm mấu chốt: vì luôn xử lý xong hết một lớp rồi mới sang lớp kế tiếp, đỉnh nào được chốt trước chắc chắn có khoảng cách ngắn hơn hoặc bằng đỉnh chốt sau — nên với đồ thị không có trọng số trên cạnh, cách lan truyền theo lớp này luôn cho đúng đường đi ngắn nhất.',
        viewBoxWidth: 440,
        viewBoxHeight: 240,
        durationMs: 8500,
        loop: true,
        shapes: [
          { kind: 'line', id: 'e-s-a', x1: 40, y1: 120, x2: 140, y2: 60, stroke: 'muted' },
          { kind: 'line', id: 'e-s-b', x1: 40, y1: 120, x2: 140, y2: 180, stroke: 'muted' },
          { kind: 'line', id: 'e-a-c', x1: 140, y1: 60, x2: 240, y2: 30, stroke: 'muted' },
          { kind: 'line', id: 'e-a-d', x1: 140, y1: 60, x2: 240, y2: 120, stroke: 'muted' },
          { kind: 'line', id: 'e-b-d', x1: 140, y1: 180, x2: 240, y2: 120, stroke: 'muted' },
          { kind: 'line', id: 'e-b-e', x1: 140, y1: 180, x2: 240, y2: 210, stroke: 'muted' },
          { kind: 'line', id: 'e-c-f', x1: 240, y1: 30, x2: 340, y2: 60, stroke: 'muted' },
          { kind: 'line', id: 'e-d-g', x1: 240, y1: 120, x2: 340, y2: 165, stroke: 'muted' },
          { kind: 'line', id: 'e-e-g', x1: 240, y1: 210, x2: 340, y2: 165, stroke: 'muted' },

          // Đỉnh xuất phát S — vào hàng đợi ngay từ mốc 0 vì nó là điểm bắt đầu.
          {
            kind: 'circle',
            id: 'dinh-s',
            cx: 40,
            cy: 120,
            r: 16,
            fill: 'surface',
            stroke: 'primary',
          },
          {
            kind: 'circle',
            id: 's-cho',
            cx: 40,
            cy: 120,
            r: 16,
            fill: 'surface',
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 400, opacity: 1 },
              { atMs: 650, opacity: 0 },
              { atMs: 8500, opacity: 0 },
            ],
          },
          {
            kind: 'circle',
            id: 's-chot',
            cx: 40,
            cy: 120,
            r: 16,
            fill: 'surface',
            stroke: 'correct',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 400, opacity: 0 },
              { atMs: 700, opacity: 1 },
              { atMs: 8500, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 's-nhan',
            x: 40,
            y: 145,
            text: '0',
            size: 13,
            anchor: 'middle',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 400, opacity: 0 },
              { atMs: 700, opacity: 1 },
              { atMs: 8500, opacity: 1 },
            ],
          },

          // Lớp 1: A và B — vào hàng đợi khi S vừa chốt xong (400ms).
          {
            kind: 'circle',
            id: 'dinh-a',
            cx: 140,
            cy: 60,
            r: 16,
            fill: 'surface',
            stroke: 'primary',
          },
          {
            kind: 'circle',
            id: 'a-cho',
            cx: 140,
            cy: 60,
            r: 16,
            fill: 'surface',
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 400, opacity: 0 },
              { atMs: 600, opacity: 1 },
              { atMs: 1600, opacity: 1 },
              { atMs: 1850, opacity: 0 },
              { atMs: 8500, opacity: 0 },
            ],
          },
          {
            kind: 'circle',
            id: 'a-chot',
            cx: 140,
            cy: 60,
            r: 16,
            fill: 'surface',
            stroke: 'correct',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 1600, opacity: 0 },
              { atMs: 1900, opacity: 1 },
              { atMs: 8500, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'a-nhan',
            x: 140,
            y: 85,
            text: '1',
            size: 13,
            anchor: 'middle',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 1600, opacity: 0 },
              { atMs: 1900, opacity: 1 },
              { atMs: 8500, opacity: 1 },
            ],
          },
          {
            kind: 'circle',
            id: 'dinh-b',
            cx: 140,
            cy: 180,
            r: 16,
            fill: 'surface',
            stroke: 'primary',
          },
          {
            kind: 'circle',
            id: 'b-cho',
            cx: 140,
            cy: 180,
            r: 16,
            fill: 'surface',
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 400, opacity: 0 },
              { atMs: 600, opacity: 1 },
              { atMs: 2000, opacity: 1 },
              { atMs: 2250, opacity: 0 },
              { atMs: 8500, opacity: 0 },
            ],
          },
          {
            kind: 'circle',
            id: 'b-chot',
            cx: 140,
            cy: 180,
            r: 16,
            fill: 'surface',
            stroke: 'correct',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 2000, opacity: 0 },
              { atMs: 2300, opacity: 1 },
              { atMs: 8500, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'b-nhan',
            x: 140,
            y: 205,
            text: '1',
            size: 13,
            anchor: 'middle',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 2000, opacity: 0 },
              { atMs: 2300, opacity: 1 },
              { atMs: 8500, opacity: 1 },
            ],
          },

          // Lớp 2: C, D vào hàng đợi khi A chốt (1600ms); E vào hàng đợi khi B chốt (2000ms).
          {
            kind: 'circle',
            id: 'dinh-c',
            cx: 240,
            cy: 30,
            r: 16,
            fill: 'surface',
            stroke: 'primary',
          },
          {
            kind: 'circle',
            id: 'c-cho',
            cx: 240,
            cy: 30,
            r: 16,
            fill: 'surface',
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 1600, opacity: 0 },
              { atMs: 1800, opacity: 1 },
              { atMs: 3200, opacity: 1 },
              { atMs: 3450, opacity: 0 },
              { atMs: 8500, opacity: 0 },
            ],
          },
          {
            kind: 'circle',
            id: 'c-chot',
            cx: 240,
            cy: 30,
            r: 16,
            fill: 'surface',
            stroke: 'correct',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 3200, opacity: 0 },
              { atMs: 3500, opacity: 1 },
              { atMs: 8500, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'c-nhan',
            x: 240,
            y: 12,
            text: '2',
            size: 13,
            anchor: 'middle',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 3200, opacity: 0 },
              { atMs: 3500, opacity: 1 },
              { atMs: 8500, opacity: 1 },
            ],
          },
          {
            kind: 'circle',
            id: 'dinh-d',
            cx: 240,
            cy: 120,
            r: 16,
            fill: 'surface',
            stroke: 'primary',
          },
          {
            kind: 'circle',
            id: 'd-cho',
            cx: 240,
            cy: 120,
            r: 16,
            fill: 'surface',
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 1600, opacity: 0 },
              { atMs: 1800, opacity: 1 },
              { atMs: 3600, opacity: 1 },
              { atMs: 3850, opacity: 0 },
              { atMs: 8500, opacity: 0 },
            ],
          },
          {
            kind: 'circle',
            id: 'd-chot',
            cx: 240,
            cy: 120,
            r: 16,
            fill: 'surface',
            stroke: 'correct',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 3600, opacity: 0 },
              { atMs: 3900, opacity: 1 },
              { atMs: 8500, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'd-nhan',
            x: 240,
            y: 145,
            text: '2',
            size: 13,
            anchor: 'middle',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 3600, opacity: 0 },
              { atMs: 3900, opacity: 1 },
              { atMs: 8500, opacity: 1 },
            ],
          },
          {
            kind: 'circle',
            id: 'dinh-e',
            cx: 240,
            cy: 210,
            r: 16,
            fill: 'surface',
            stroke: 'primary',
          },
          {
            kind: 'circle',
            id: 'e-cho',
            cx: 240,
            cy: 210,
            r: 16,
            fill: 'surface',
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 2000, opacity: 0 },
              { atMs: 2200, opacity: 1 },
              { atMs: 4000, opacity: 1 },
              { atMs: 4250, opacity: 0 },
              { atMs: 8500, opacity: 0 },
            ],
          },
          {
            kind: 'circle',
            id: 'e-chot',
            cx: 240,
            cy: 210,
            r: 16,
            fill: 'surface',
            stroke: 'correct',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 4000, opacity: 0 },
              { atMs: 4300, opacity: 1 },
              { atMs: 8500, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'e-nhan',
            x: 240,
            y: 235,
            text: '2',
            size: 13,
            anchor: 'middle',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 4000, opacity: 0 },
              { atMs: 4300, opacity: 1 },
              { atMs: 8500, opacity: 1 },
            ],
          },

          // Lớp 3: F vào hàng đợi khi C chốt (3200ms); G vào hàng đợi khi D chốt (3600ms).
          {
            kind: 'circle',
            id: 'dinh-f',
            cx: 340,
            cy: 60,
            r: 16,
            fill: 'surface',
            stroke: 'primary',
          },
          {
            kind: 'circle',
            id: 'f-cho',
            cx: 340,
            cy: 60,
            r: 16,
            fill: 'surface',
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 3200, opacity: 0 },
              { atMs: 3400, opacity: 1 },
              { atMs: 5200, opacity: 1 },
              { atMs: 5450, opacity: 0 },
              { atMs: 8500, opacity: 0 },
            ],
          },
          {
            kind: 'circle',
            id: 'f-chot',
            cx: 340,
            cy: 60,
            r: 16,
            fill: 'surface',
            stroke: 'correct',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 5200, opacity: 0 },
              { atMs: 5500, opacity: 1 },
              { atMs: 8500, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'f-nhan',
            x: 340,
            y: 42,
            text: '3',
            size: 13,
            anchor: 'middle',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 5200, opacity: 0 },
              { atMs: 5500, opacity: 1 },
              { atMs: 8500, opacity: 1 },
            ],
          },
          {
            kind: 'circle',
            id: 'dinh-g',
            cx: 340,
            cy: 165,
            r: 16,
            fill: 'surface',
            stroke: 'primary',
          },
          {
            kind: 'circle',
            id: 'g-cho',
            cx: 340,
            cy: 165,
            r: 16,
            fill: 'surface',
            stroke: 'accent',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 3600, opacity: 0 },
              { atMs: 3800, opacity: 1 },
              { atMs: 5600, opacity: 1 },
              { atMs: 5850, opacity: 0 },
              { atMs: 8500, opacity: 0 },
            ],
          },
          {
            kind: 'circle',
            id: 'g-chot',
            cx: 340,
            cy: 165,
            r: 16,
            fill: 'surface',
            stroke: 'correct',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 5600, opacity: 0 },
              { atMs: 5900, opacity: 1 },
              { atMs: 8500, opacity: 1 },
            ],
          },
          {
            kind: 'label',
            id: 'g-nhan',
            x: 340,
            y: 190,
            text: '3',
            size: 13,
            anchor: 'middle',
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 5600, opacity: 0 },
              { atMs: 5900, opacity: 1 },
              { atMs: 8500, opacity: 1 },
            ],
          },
        ],
        captions: [
          { atMs: 0, text: 'Bắt đầu tại đỉnh xuất phát, khoảng cách 0.' },
          {
            atMs: 400,
            text: 'Đỉnh xuất phát được chốt xong, hai đỉnh liền kề vào hàng đợi — đây là lớp 1.',
          },
          {
            atMs: 1600,
            text: 'Đỉnh đầu của lớp 1 được chốt khoảng cách 1, các đỉnh liền kề của nó vào hàng đợi — bắt đầu lớp 2.',
          },
          { atMs: 2000, text: 'Đỉnh còn lại của lớp 1 cũng được chốt khoảng cách 1.' },
          { atMs: 3200, text: 'Lần lượt các đỉnh của lớp 2 được chốt khoảng cách 2, mở ra lớp 3.' },
          {
            atMs: 5200,
            text: 'Các đỉnh của lớp 3 được chốt khoảng cách 3 — xa nhất trong đồ thị này.',
          },
          { atMs: 5600, text: 'Toàn bộ đồ thị đã được thăm theo đúng thứ tự lớp gần tới xa.' },
        ],
      },
      objective:
        'Mô hình hoá được bài toán đời thật thành đồ thị và chọn đúng thuật toán đường đi cho nó.',
      practice: [
        'Chuyển một bài toán thật thành đồ thị: định nghĩa rõ đỉnh là gì, cạnh là gì, trọng số là gì.',
        'Cài Dijkstra và so sánh thời gian với tìm kiếm theo chiều rộng trên đồ thị không trọng số.',
        'Dùng hợp-tìm để gom nhóm trên tập ít nhất mười nghìn phần tử.',
      ],
      selfCheck: [
        {
          q: 'Khi nào không được dùng Dijkstra?',
          a: 'Khi có cạnh trọng số âm; lúc đó phải dùng thuật toán chịu được cạnh âm.',
        },
        {
          q: 'Bước khó nhất khi giải bài toán đồ thị là gì?',
          a: 'Mô hình hoá: quyết định cái gì là đỉnh và cái gì là cạnh, vì chọn sai là thuật toán nào cũng không cứu được.',
        },
      ],
      doneSignals: [
        'Nhìn một bài toán mới là nhận ra được cấu trúc đồ thị bên dưới.',
        'Có số đo thời gian thật trên đồ thị lớn, không chỉ lý thuyết.',
      ],
    },
    {
      moduleId: 'algo-s2-m4',
      // Cảnh cho thấy vì sao xét theo thứ tự KẾT THÚC sớm nhất (không phải bắt đầu sớm nhất)
      // lại tối ưu: mỗi lần chọn xong, khoảng vừa chọn chừa lại nhiều thời gian trống nhất
      // có thể cho các lựa chọn tiếp theo.
      animation: {
        title: 'Tham lam: xếp lịch bằng cách chọn kết thúc sớm nhất',
        description:
          'Bảy khoảng thời gian được vẽ thành các thanh ngang xếp theo hàng trên một trục thời gian. Thuật toán xét từng khoảng theo đúng thứ tự KẾT THÚC sớm nhất trước, không theo thứ tự bắt đầu: khoảng nào kết thúc sớm nhất và chưa chồng lấn với khoảng đã chọn thì được chọn (viền báo đã chọn), khoảng nào chồng lấn với một khoảng đã chọn thì bị loại (mờ đi, có viền báo đã loại). Kết quả cuối cùng là ba khoảng không chồng lấn nhau. Điểm mấu chốt: luôn ưu tiên khoảng kết thúc sớm nhất, vì nó chừa lại nhiều thời gian trống nhất cho các lựa chọn tiếp theo, nên tổng số khoảng chọn được là nhiều nhất có thể.',
        viewBoxWidth: 440,
        viewBoxHeight: 230,
        // Nhịp giãn rộng CÓ CHỦ Ý (7 quyết định cách nhau ≥1000ms, mỗi lần chuyển trạng thái
        // rộng 400ms, luôn cách quyết định liền kề ít nhất 600ms) — đủ đệm để không lộ trạng
        // thái nửa vời khi soi ở BẤT KỲ mốc phần trăm nào của durationMs.
        durationMs: 13000,
        loop: true,
        shapes: [
          { kind: 'line', id: 'truc', x1: 40, y1: 212, x2: 400, y2: 212, stroke: 'muted' },

          // A: 1–4, xét đầu tiên (kết thúc sớm nhất trong tất cả) — được chọn.
          {
            kind: 'rect',
            id: 'kv-a',
            x: 72,
            y: 30,
            w: 96,
            h: 20,
            rx: 4,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          { kind: 'label', id: 'nhan-a', x: 120, y: 44, text: 'A', size: 12, anchor: 'middle' },
          {
            kind: 'rect',
            id: 'kv-a-chon',
            x: 72,
            y: 30,
            w: 96,
            h: 20,
            rx: 4,
            fill: 'surface',
            stroke: 'correct',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 1200, opacity: 0 },
              { atMs: 1600, opacity: 1 },
              { atMs: 13000, opacity: 1 },
            ],
          },

          // B: 3–5, xét thứ hai — chồng lấn với A đã chọn nên bị loại.
          {
            kind: 'rect',
            id: 'kv-b',
            x: 136,
            y: 56,
            w: 64,
            h: 20,
            rx: 4,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 2200, opacity: 1 },
              { atMs: 2600, opacity: 0.35 },
              { atMs: 13000, opacity: 0.35 },
            ],
          },
          {
            kind: 'label',
            id: 'nhan-b',
            x: 168,
            y: 70,
            text: 'B',
            size: 12,
            anchor: 'middle',
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 2200, opacity: 1 },
              { atMs: 2600, opacity: 0.35 },
              { atMs: 13000, opacity: 0.35 },
            ],
          },
          {
            kind: 'rect',
            id: 'kv-b-loai',
            x: 136,
            y: 56,
            w: 64,
            h: 20,
            rx: 4,
            fill: 'surface',
            stroke: 'warn',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 2200, opacity: 0 },
              { atMs: 2600, opacity: 1 },
              { atMs: 13000, opacity: 1 },
            ],
          },

          // C: 0–6, xét thứ ba — chồng lấn với A đã chọn nên bị loại.
          {
            kind: 'rect',
            id: 'kv-c',
            x: 40,
            y: 82,
            w: 192,
            h: 20,
            rx: 4,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 4800, opacity: 1 },
              { atMs: 5200, opacity: 0.35 },
              { atMs: 13000, opacity: 0.35 },
            ],
          },
          {
            kind: 'label',
            id: 'nhan-c',
            x: 136,
            y: 96,
            text: 'C',
            size: 12,
            anchor: 'middle',
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 4800, opacity: 1 },
              { atMs: 5200, opacity: 0.35 },
              { atMs: 13000, opacity: 0.35 },
            ],
          },
          {
            kind: 'rect',
            id: 'kv-c-loai',
            x: 40,
            y: 82,
            w: 192,
            h: 20,
            rx: 4,
            fill: 'surface',
            stroke: 'warn',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 4800, opacity: 0 },
              { atMs: 5200, opacity: 1 },
              { atMs: 13000, opacity: 1 },
            ],
          },

          // D: 5–7, xét thứ tư — bắt đầu sau khi A kết thúc, không chồng lấn nên được chọn.
          {
            kind: 'rect',
            id: 'kv-d',
            x: 200,
            y: 108,
            w: 64,
            h: 20,
            rx: 4,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          { kind: 'label', id: 'nhan-d', x: 232, y: 122, text: 'D', size: 12, anchor: 'middle' },
          {
            kind: 'rect',
            id: 'kv-d-chon',
            x: 200,
            y: 108,
            w: 64,
            h: 20,
            rx: 4,
            fill: 'surface',
            stroke: 'correct',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 5800, opacity: 0 },
              { atMs: 6200, opacity: 1 },
              { atMs: 13000, opacity: 1 },
            ],
          },

          // E: 3–9, xét thứ năm — chồng lấn với D đã chọn nên bị loại.
          {
            kind: 'rect',
            id: 'kv-e',
            x: 136,
            y: 134,
            w: 192,
            h: 20,
            rx: 4,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 8000, opacity: 1 },
              { atMs: 8400, opacity: 0.35 },
              { atMs: 13000, opacity: 0.35 },
            ],
          },
          {
            kind: 'label',
            id: 'nhan-e',
            x: 232,
            y: 148,
            text: 'E',
            size: 12,
            anchor: 'middle',
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 8000, opacity: 1 },
              { atMs: 8400, opacity: 0.35 },
              { atMs: 13000, opacity: 0.35 },
            ],
          },
          {
            kind: 'rect',
            id: 'kv-e-loai',
            x: 136,
            y: 134,
            w: 192,
            h: 20,
            rx: 4,
            fill: 'surface',
            stroke: 'warn',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 8000, opacity: 0 },
              { atMs: 8400, opacity: 1 },
              { atMs: 13000, opacity: 1 },
            ],
          },

          // F: 6–10, xét thứ sáu — chồng lấn với D đã chọn nên bị loại.
          {
            kind: 'rect',
            id: 'kv-f',
            x: 232,
            y: 160,
            w: 128,
            h: 20,
            rx: 4,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 9000, opacity: 1 },
              { atMs: 9400, opacity: 0.35 },
              { atMs: 13000, opacity: 0.35 },
            ],
          },
          {
            kind: 'label',
            id: 'nhan-f',
            x: 296,
            y: 174,
            text: 'F',
            size: 12,
            anchor: 'middle',
            keyframes: [
              { atMs: 0, opacity: 1 },
              { atMs: 9000, opacity: 1 },
              { atMs: 9400, opacity: 0.35 },
              { atMs: 13000, opacity: 0.35 },
            ],
          },
          {
            kind: 'rect',
            id: 'kv-f-loai',
            x: 232,
            y: 160,
            w: 128,
            h: 20,
            rx: 4,
            fill: 'surface',
            stroke: 'warn',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 9000, opacity: 0 },
              { atMs: 9400, opacity: 1 },
              { atMs: 13000, opacity: 1 },
            ],
          },

          // G: 8–11, xét cuối cùng — bắt đầu sau khi D kết thúc, không chồng lấn nên được chọn.
          {
            kind: 'rect',
            id: 'kv-g',
            x: 296,
            y: 186,
            w: 96,
            h: 20,
            rx: 4,
            fill: 'surface',
            stroke: 'primary',
            strokeWidth: 2,
          },
          { kind: 'label', id: 'nhan-g', x: 344, y: 200, text: 'G', size: 12, anchor: 'middle' },
          {
            kind: 'rect',
            id: 'kv-g-chon',
            x: 296,
            y: 186,
            w: 96,
            h: 20,
            rx: 4,
            fill: 'surface',
            stroke: 'correct',
            strokeWidth: 3,
            keyframes: [
              { atMs: 0, opacity: 0 },
              { atMs: 11300, opacity: 0 },
              { atMs: 11700, opacity: 1 },
              { atMs: 13000, opacity: 1 },
            ],
          },
        ],
        captions: [
          {
            atMs: 0,
            text: 'Bảy khoảng thời gian xếp theo hàng, thuật toán xét lần lượt theo thứ tự kết thúc sớm nhất trước.',
          },
          { atMs: 1200, text: 'Khoảng A kết thúc sớm nhất trong toàn bộ — được chọn ngay.' },
          { atMs: 2200, text: 'Khoảng B chồng lấn với A đã chọn — bị loại.' },
          { atMs: 4800, text: 'Khoảng C cũng chồng lấn với A — bị loại.' },
          { atMs: 5800, text: 'Khoảng D bắt đầu sau khi A kết thúc, không chồng lấn — được chọn.' },
          { atMs: 8000, text: 'Khoảng E chồng lấn với D — bị loại.' },
          { atMs: 9000, text: 'Khoảng F cũng chồng lấn với D — bị loại.' },
          {
            atMs: 11300,
            text: 'Khoảng G bắt đầu sau khi D kết thúc — được chọn. Kết quả: ba khoảng A, D, G không chồng lấn nhau.',
          },
        ],
      },
      objective:
        'Nhận ra được khi nào chiến lược tham lam đúng và biết bác bỏ nó bằng phản ví dụ khi sai.',
      practice: [
        'Giải năm bài lịch biểu bằng tham lam, mỗi bài viết một dòng lý do vì sao chọn tham lam đó đúng.',
        'Tìm phản ví dụ bác bỏ một ý tưởng tham lam nghe rất hợp lý.',
        'So sánh lời giải tham lam với quy hoạch động trên cùng bộ dữ liệu.',
      ],
      selfCheck: [
        {
          q: 'Làm sao biết một chiến lược tham lam là đúng?',
          a: 'Phải chứng minh được lựa chọn tốt nhất tại chỗ không loại mất nghiệm tối ưu toàn cục; cảm giác hợp lý không phải chứng minh.',
        },
        {
          q: 'Phản ví dụ có giá trị gì?',
          a: 'Một phản ví dụ đủ bác bỏ hoàn toàn, tiết kiệm hàng giờ cố cứu một hướng sai.',
        },
      ],
      doneSignals: [
        'Trước khi code đã biết tham lam có đúng hay không.',
        'Có sổ ghi các phản ví dụ đã tìm được để dùng lại.',
      ],
    },
  ],
  rubric: [
    {
      id: 'algo-s2-r1',
      text: 'Chạy được trên dữ liệu thật có ít nhất mười nghìn đỉnh, hoàn tất trong ngưỡng thời gian đã đặt.',
      howToProve: 'Bảng thời gian chạy trên ba kích thước dữ liệu tăng dần, kèm cấu hình máy.',
    },
    {
      id: 'algo-s2-r2',
      text: 'So sánh ít nhất hai thuật toán cho cùng bài toán, có số đo và kết luận chọn cái nào.',
      howToProve: 'Bảng so sánh thời gian và bộ nhớ, kèm lệnh chạy để người khác lặp lại.',
    },
    {
      id: 'algo-s2-r3',
      text: 'Có kiểm thử đối chiếu ngẫu nhiên với lời giải vét cạn cho ít nhất năm bài.',
      howToProve: 'Chạy bộ sinh ngẫu nhiên mười nghìn ca, không ca nào lệch.',
    },
    {
      id: 'algo-s2-r4',
      text: 'Mọi thuật toán trong dự án đều ghi rõ độ phức tạp thời gian và bộ nhớ.',
      howToProve: 'Bảng tổng hợp trong tài liệu dự án, đối chiếu với số đo thực nghiệm.',
    },
    {
      id: 'algo-s2-r5',
      text: 'Xử lý đúng các ca biên: đồ thị rỗng, không có đường đi, đồ thị không liên thông.',
      howToProve: 'Bộ kiểm thử liệt kê từng ca biên và kết quả mong đợi, chạy xanh.',
    },
  ],
  specBrief: {
    scopeDo: [
      'Bộ giải một bài toán đồ thị đời thật: chỉ đường, xếp lịch hoặc gợi ý.',
      'So sánh thực nghiệm ít nhất hai thuật toán.',
      'Bộ kiểm thử đối chiếu ngẫu nhiên và ca biên.',
    ],
    scopeDont: [
      'KHÔNG làm giao diện đồ hoạ cầu kỳ — mục tiêu là thuật toán, in ra dòng lệnh là đủ.',
      'KHÔNG tối ưu vi mô trước khi chọn đúng thuật toán; đổi thuật toán thắng mọi vi tối ưu.',
      'KHÔNG dùng thư viện có sẵn cho chính thuật toán đang học.',
    ],
    touchpoints: [
      'Module đọc và mô hình hoá dữ liệu thành đồ thị, tách khỏi thuật toán.',
      'Mỗi thuật toán một file, cùng một giao diện hàm để hoán đổi được.',
      'Bộ sinh dữ liệu ngẫu nhiên và bộ đo thời gian.',
    ],
    contracts: [
      'Mọi thuật toán nhận cùng cấu trúc đồ thị và trả cùng kiểu kết quả, để so sánh được trực tiếp.',
      'Đồ thị không có đường đi thì trả kết quả rỗng rõ ràng, không ném lỗi.',
      'Hạt giống ngẫu nhiên khai báo rõ để tái hiện được lần chạy.',
    ],
    acceptance: [
      'Năm tiêu chí rubric đạt, có bảng số đo kèm theo.',
      'Người khác chạy lại được toàn bộ số đo bằng một lệnh.',
    ],
    invariants: [
      'Kết quả không đổi giữa các lần chạy với cùng dữ liệu vào.',
      'Lời giải nhanh luôn khớp lời giải vét cạn trên dữ liệu nhỏ.',
      'Không thuật toán nào sửa dữ liệu đồ thị đầu vào.',
    ],
    conventions: [
      'Mọi số đo ghi kèm cấu hình máy và lệnh đã chạy.',
      'Đặt tên biến theo ngôn ngữ bài toán, không dùng một chữ cái cho mọi thứ.',
      'Mỗi nhánh logic phức tạp có ít nhất một kiểm thử ca biên.',
    ],
  },
}
