// lessonsLazy.ts — TỆP SINH TỰ ĐỘNG, ĐỪNG SỬA TAY.
// Sinh bởi `npm run gen:stem-lesson-index` (scripts/gen-stem-lesson-index.ts).
// Thêm hoặc sửa bài học xong PHẢI chạy lại lệnh đó, nếu không chỉ mục lệch với nội dung thật.
import type { StemLessonSummary } from '@dhcb/core-contracts/stemLesson'
import type { PhysicsLesson } from './lessonTypes.js'

export const LESSON_INDEX: StemLessonSummary[] = [
  {
    id: 'ly10-c1-b1',
    grade: '10',
    chapterNumber: 1,
    chapterTitle: 'Mở đầu',
    lessonNumber: 1,
    title: 'Làm quen với Vật lí',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c1',
  },
  {
    id: 'ly10-c1-b2',
    grade: '10',
    chapterNumber: 1,
    chapterTitle: 'Mở đầu',
    lessonNumber: 2,
    title: 'Các quy tắc an toàn trong phòng thực hành Vật lí',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c1',
  },
  {
    id: 'ly10-c1-b3',
    grade: '10',
    chapterNumber: 1,
    chapterTitle: 'Mở đầu',
    lessonNumber: 3,
    title: 'Thực hành tính sai số trong phép đo. Ghi kết quả đo',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c1',
  },
  {
    id: 'ly10-c2-b4',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Động học',
    lessonNumber: 4,
    title: 'Độ dịch chuyển và quãng đường đi được',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c2',
  },
  {
    id: 'ly10-c2-b5',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Động học',
    lessonNumber: 5,
    title: 'Tốc độ và vận tốc',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c2',
  },
  {
    id: 'ly10-c2-b6',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Động học',
    lessonNumber: 6,
    title: 'Thực hành: Đo tốc độ của vật chuyển động',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c2',
  },
  {
    id: 'ly10-c2-b7',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Động học',
    lessonNumber: 7,
    title: 'Đồ thị độ dịch chuyển – thời gian',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c2',
  },
  {
    id: 'ly10-c2-b8',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Động học',
    lessonNumber: 8,
    title: 'Chuyển động biến đổi. Gia tốc',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c2',
  },
  {
    id: 'ly10-c2-b9',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Động học',
    lessonNumber: 9,
    title: 'Chuyển động thẳng biến đổi đều',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c2',
  },
  {
    id: 'ly10-c2-b10',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Động học',
    lessonNumber: 10,
    title: 'Sự rơi tự do',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'ly10c2',
  },
  {
    id: 'ly10-c2-b11',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Động học',
    lessonNumber: 11,
    title: 'Thực hành: Đo gia tốc rơi tự do',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c2',
  },
  {
    id: 'ly10-c2-b12',
    grade: '10',
    chapterNumber: 2,
    chapterTitle: 'Động học',
    lessonNumber: 12,
    title: 'Chuyển động ném',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'ly10c2',
  },
  {
    id: 'ly10-c3-b13',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Động lực học',
    lessonNumber: 13,
    title: 'Tổng hợp và phân tích lực. Cân bằng lực',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'ly10c3',
  },
  {
    id: 'ly10-c3-b14',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Động lực học',
    lessonNumber: 14,
    title: 'Định luật 1 Newton',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c3',
  },
  {
    id: 'ly10-c3-b15',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Động lực học',
    lessonNumber: 15,
    title: 'Định luật 2 Newton',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c3',
  },
  {
    id: 'ly10-c3-b16',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Động lực học',
    lessonNumber: 16,
    title: 'Định luật 3 Newton',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'ly10c3',
  },
  {
    id: 'ly10-c3-b17',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Động lực học',
    lessonNumber: 17,
    title: 'Trọng lực và lực căng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c3',
  },
  {
    id: 'ly10-c3-b18',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Động lực học',
    lessonNumber: 18,
    title: 'Lực ma sát',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c3',
  },
  {
    id: 'ly10-c3-b19',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Động học',
    lessonNumber: 19,
    title: 'Lực cản và lực nâng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c3',
  },
  {
    id: 'ly10-c3-b20',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Động lực học',
    lessonNumber: 20,
    title: 'Một số ví dụ về cách giải các bài toán thuộc phần động lực học',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c3',
  },
  {
    id: 'ly10-c3-b21',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Động học',
    lessonNumber: 21,
    title: 'Moment lực. Cân bằng của vật rắn',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c3',
  },
  {
    id: 'ly10-c3-b22',
    grade: '10',
    chapterNumber: 3,
    chapterTitle: 'Động học',
    lessonNumber: 22,
    title: 'Thực hành: Tổng hợp lực',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c3',
  },
  {
    id: 'ly10-c4-b23',
    grade: '10',
    chapterNumber: 4,
    chapterTitle: 'Năng lượng, công, công suất',
    lessonNumber: 23,
    title: 'Năng lượng. Công cơ học',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c4',
  },
  {
    id: 'ly10-c4-b24',
    grade: '10',
    chapterNumber: 4,
    chapterTitle: 'Năng lượng, công, công suất',
    lessonNumber: 24,
    title: 'Công suất',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c4',
  },
  {
    id: 'ly10-c4-b25',
    grade: '10',
    chapterNumber: 4,
    chapterTitle: 'Năng lượng, công, công suất',
    lessonNumber: 25,
    title: 'Động năng, thế năng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c4',
  },
  {
    id: 'ly10-c4-b26',
    grade: '10',
    chapterNumber: 4,
    chapterTitle: 'Năng lượng, công, công suất',
    lessonNumber: 26,
    title: 'Cơ năng và định luật bảo toàn cơ năng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c4',
  },
  {
    id: 'ly10-c4-b27',
    grade: '10',
    chapterNumber: 4,
    chapterTitle: 'Năng lượng, công, công suất',
    lessonNumber: 27,
    title: 'Hiệu suất',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c4',
  },
  {
    id: 'ly10-c5-b28',
    grade: '10',
    chapterNumber: 5,
    chapterTitle: 'Động lượng',
    lessonNumber: 28,
    title: 'Động lượng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c5',
  },
  {
    id: 'ly10-c5-b29',
    grade: '10',
    chapterNumber: 5,
    chapterTitle: 'Động lượng',
    lessonNumber: 29,
    title: 'Định luật bảo toàn động lượng',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'ly10c5',
  },
  {
    id: 'ly10-c5-b30',
    grade: '10',
    chapterNumber: 5,
    chapterTitle: 'Động lượng',
    lessonNumber: 30,
    title: 'Thực hành: Xác định động lượng của vật trước và sau va chạm',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c5',
  },
  {
    id: 'ly10-c6-b31',
    grade: '10',
    chapterNumber: 6,
    chapterTitle: 'Chuyển động tròn đều',
    lessonNumber: 31,
    title: 'Động học của chuyển động tròn đều',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c6',
  },
  {
    id: 'ly10-c6-b32',
    grade: '10',
    chapterNumber: 6,
    chapterTitle: 'Chuyển động tròn đều',
    lessonNumber: 32,
    title: 'Lực hướng tâm và gia tốc hướng tâm',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'ly10c6',
  },
  {
    id: 'ly10-c7-b33',
    grade: '10',
    chapterNumber: 7,
    chapterTitle: 'Biến dạng của vật rắn. Áp suất chất lỏng',
    lessonNumber: 33,
    title: 'Biến dạng của vật rắn',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c7',
  },
  {
    id: 'ly10-c7-b34',
    grade: '10',
    chapterNumber: 7,
    chapterTitle: 'Biến dạng của vật rắn. Áp suất chất lỏng',
    lessonNumber: 34,
    title: 'Khối lượng riêng. Áp suất chất lỏng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly10c7',
  },
  {
    id: 'ly11-c1-b1',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Dao động',
    lessonNumber: 1,
    title: 'Dao động điều hoà',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'ly11c1',
  },
  {
    id: 'ly11-c1-b2',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Dao động',
    lessonNumber: 2,
    title: 'Mô tả dao động điều hoà',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c1',
  },
  {
    id: 'ly11-c1-b3',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Dao động',
    lessonNumber: 3,
    title: 'Vận tốc, gia tốc trong dao động điều hoà',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c1',
  },
  {
    id: 'ly11-c1-b4',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Dao động',
    lessonNumber: 4,
    title: 'Bài tập về dao động điều hoà',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c1',
  },
  {
    id: 'ly11-c1-b5',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Dao động',
    lessonNumber: 5,
    title: 'Động năng. Thế năng. Sự chuyển hoá năng lượng trong dao động điều hoà',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'ly11c1',
  },
  {
    id: 'ly11-c1-b6',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Dao động',
    lessonNumber: 6,
    title: 'Dao động tắt dần. Dao động cưỡng bức. Hiện tượng cộng hưởng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c1',
  },
  {
    id: 'ly11-c1-b7',
    grade: '11',
    chapterNumber: 1,
    chapterTitle: 'Dao động',
    lessonNumber: 7,
    title: 'Bài tập về sự chuyển hoá năng lượng trong dao động điều hoà',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c1',
  },
  {
    id: 'ly11-c2-b8',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Sóng',
    lessonNumber: 8,
    title: 'Mô tả sóng',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'ly11c2',
  },
  {
    id: 'ly11-c2-b9',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Sóng',
    lessonNumber: 9,
    title: 'Sóng ngang. Sóng dọc. Sự truyền năng lượng của sóng cơ',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c2',
  },
  {
    id: 'ly11-c2-b10',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Sóng',
    lessonNumber: 10,
    title: 'Thực hành: Đo tần số của sóng âm',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c2',
  },
  {
    id: 'ly11-c2-b11',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Sóng',
    lessonNumber: 11,
    title: 'Sóng điện từ',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c2',
  },
  {
    id: 'ly11-c2-b12',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Sóng',
    lessonNumber: 12,
    title: 'Giao thoa sóng',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'ly11c2',
  },
  {
    id: 'ly11-c2-b13',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Sóng',
    lessonNumber: 13,
    title: 'Sóng dừng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c2',
  },
  {
    id: 'ly11-c2-b14',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Sóng',
    lessonNumber: 14,
    title: 'Bài tập về sóng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c2',
  },
  {
    id: 'ly11-c2-b15',
    grade: '11',
    chapterNumber: 2,
    chapterTitle: 'Sóng',
    lessonNumber: 15,
    title: 'Thực hành: Đo tốc độ truyền âm',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c2',
  },
  {
    id: 'ly11-c3-b16',
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Điện trường',
    lessonNumber: 16,
    title: 'Lực tương tác giữa các điện tích',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c3',
  },
  {
    id: 'ly11-c3-b17',
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Điện trường',
    lessonNumber: 17,
    title: 'Khái niệm điện trường',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'ly11c3',
  },
  {
    id: 'ly11-c3-b18',
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Điện trường',
    lessonNumber: 18,
    title: 'Điện trường đều',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c3',
  },
  {
    id: 'ly11-c3-b19',
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Điện trường',
    lessonNumber: 19,
    title: 'Thế năng điện',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c3',
  },
  {
    id: 'ly11-c3-b20',
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Điện trường',
    lessonNumber: 20,
    title: 'Điện thế',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c3',
  },
  {
    id: 'ly11-c3-b21',
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Điện trường',
    lessonNumber: 21,
    title: 'Tụ điện',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c3',
  },
  {
    id: 'ly11-c4-b22',
    grade: '11',
    chapterNumber: 4,
    chapterTitle: 'Dòng điện. Mạch điện',
    lessonNumber: 22,
    title: 'Cường độ dòng điện',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'ly11c4',
  },
  {
    id: 'ly11-c4-b23',
    grade: '11',
    chapterNumber: 4,
    chapterTitle: 'Dòng điện. Mạch điện',
    lessonNumber: 23,
    title: 'Điện trở. Định luật Ohm',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c4',
  },
  {
    id: 'ly11-c4-b24',
    grade: '11',
    chapterNumber: 4,
    chapterTitle: 'Dòng điện. Mạch điện',
    lessonNumber: 24,
    title: 'Nguồn điện',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c4',
  },
  {
    id: 'ly11-c4-b25',
    grade: '11',
    chapterNumber: 4,
    chapterTitle: 'Dòng điện. Mạch điện',
    lessonNumber: 25,
    title: 'Năng lượng và công suất điện',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c4',
  },
  {
    id: 'ly11-c4-b26',
    grade: '11',
    chapterNumber: 4,
    chapterTitle: 'Dòng điện. Mạch điện',
    lessonNumber: 26,
    title: 'Thực hành: Đo suất điện động và điện trở trong của pin điện hoá',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly11c4',
  },
  {
    id: 'ly12-c1-b1',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Vật lí nhiệt',
    lessonNumber: 1,
    title: 'Cấu trúc của chất. Sự chuyển thế',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c1',
  },
  {
    id: 'ly12-c1-b2',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Vật lí nhiệt',
    lessonNumber: 2,
    title: 'Nội năng. Định luật I của nhiệt động lực học',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c1',
  },
  {
    id: 'ly12-c1-b3',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Vật lí nhiệt',
    lessonNumber: 3,
    title: 'Nhiệt độ. Thang nhiệt độ – nhiệt kế',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c1',
  },
  {
    id: 'ly12-c1-b4',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Vật lí nhiệt',
    lessonNumber: 4,
    title: 'Nhiệt dung riêng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c1',
  },
  {
    id: 'ly12-c1-b5',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Vật lí nhiệt',
    lessonNumber: 5,
    title: 'Nhiệt nóng chảy riêng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c1',
  },
  {
    id: 'ly12-c1-b6',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Vật lí nhiệt',
    lessonNumber: 6,
    title: 'Nhiệt hoá hơi riêng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c1',
  },
  {
    id: 'ly12-c1-b7',
    grade: '12',
    chapterNumber: 1,
    chapterTitle: 'Vật lí nhiệt',
    lessonNumber: 7,
    title: 'Bài tập về vật lí nhiệt',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c1',
  },
  {
    id: 'ly12-c2-b8',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Khí lí tưởng',
    lessonNumber: 8,
    title: 'Định luật Boyle. Định luật Charles',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c2',
  },
  {
    id: 'ly12-c2-b9',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Khí lí tưởng',
    lessonNumber: 9,
    title: 'Phương trình trạng thái của khí lí tưởng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c2',
  },
  {
    id: 'ly12-c2-b10',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Khí lí tưởng',
    lessonNumber: 10,
    title: 'Thuyết động học phân tử chất khí',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c2',
  },
  {
    id: 'ly12-c2-b11',
    grade: '12',
    chapterNumber: 2,
    chapterTitle: 'Khí lí tưởng',
    lessonNumber: 11,
    title: 'Bài tập về khí lí tưởng',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c2',
  },
  {
    id: 'ly12-c3-b12',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Từ trường',
    lessonNumber: 12,
    title: 'Đại cương về từ trường',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c3',
  },
  {
    id: 'ly12-c3-b13',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Từ trường',
    lessonNumber: 13,
    title: 'Lực từ. Cảm ứng từ',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c3',
  },
  {
    id: 'ly12-c3-b14',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Từ trường',
    lessonNumber: 14,
    title: 'Từ trường của dòng điện chạy trong các dây dẫn có hình dạng đặc biệt',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c3',
  },
  {
    id: 'ly12-c3-b15',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Từ trường',
    lessonNumber: 15,
    title: 'Lực Lorentz',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'ly12c3',
  },
  {
    id: 'ly12-c3-b16',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Từ trường',
    lessonNumber: 16,
    title: 'Tự cảm',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c3',
  },
  {
    id: 'ly12-c3-b17',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Từ trường',
    lessonNumber: 17,
    title: 'Máy biến áp. Truyền tải điện năng đi xa',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c3',
  },
  {
    id: 'ly12-c3-b18',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Từ trường',
    lessonNumber: 18,
    title: 'Ứng dụng của từ trường',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c3',
  },
  {
    id: 'ly12-c3-b19',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Từ trường',
    lessonNumber: 19,
    title: 'Bài tập về từ trường',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c3',
  },
  {
    id: 'ly12-c4-b20',
    grade: '12',
    chapterNumber: 4,
    chapterTitle: 'Vật lí hạt nhân',
    lessonNumber: 20,
    title: 'Khái niệm sơ lược về hạt nhân. Cấu trúc hạt nhân',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c4',
  },
  {
    id: 'ly12-c4-b21',
    grade: '12',
    chapterNumber: 4,
    chapterTitle: 'Vật lí hạt nhân',
    lessonNumber: 21,
    title: 'Lực hạt nhân. Năng lượng liên kết hạt nhân',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c4',
  },
  {
    id: 'ly12-c4-b22',
    grade: '12',
    chapterNumber: 4,
    chapterTitle: 'Vật lí hạt nhân',
    lessonNumber: 22,
    title: 'Phản ứng hạt nhân. Định luật bảo toàn trong phản ứng hạt nhân',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c4',
  },
  {
    id: 'ly12-c4-b23',
    grade: '12',
    chapterNumber: 4,
    chapterTitle: 'Vật lí hạt nhân',
    lessonNumber: 23,
    title: 'Hiện tượng phóng xạ',
    track: 'core',
    hasAnimation: true,
    reviewStatus: 'draft',
    chapterKey: 'ly12c4',
  },
  {
    id: 'ly12-c4-b24',
    grade: '12',
    chapterNumber: 4,
    chapterTitle: 'Vật lí hạt nhân',
    lessonNumber: 24,
    title: 'Phân hạch và nhiệt hạch',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c4',
  },
  {
    id: 'ly12-c4-b25',
    grade: '12',
    chapterNumber: 4,
    chapterTitle: 'Vật lí hạt nhân',
    lessonNumber: 25,
    title: 'Bài tập về vật lí hạt nhân',
    track: 'core',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'ly12c4',
  },
  {
    id: 'ly10-c91-b1',
    grade: '10',
    chapterNumber: 91,
    chapterTitle: 'Chuyên đề HSG: Cơ học',
    lessonNumber: 1,
    title: 'Cơ hệ nhiều vật nối dây: kỷ luật tách vật',
    track: 'advanced',
    advancedTier: 'hsg-truong',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'lyhsgcohoc',
  },
  {
    id: 'ly10-c91-b2',
    grade: '10',
    chapterNumber: 91,
    chapterTitle: 'Chuyên đề HSG: Cơ học',
    lessonNumber: 2,
    title: 'Hệ quy chiếu phi quán tính và lực quán tính',
    track: 'advanced',
    advancedTier: 'hsg-tinh',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'lyhsgcohoc',
  },
  {
    id: 'ly10-c91-b3',
    grade: '10',
    chapterNumber: 91,
    chapterTitle: 'Chuyên đề HSG: Cơ học',
    lessonNumber: 3,
    title: 'Vật trượt trên nêm tự do: phối hợp hai định luật bảo toàn',
    track: 'advanced',
    advancedTier: 'hsg-quoc-gia',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'lyhsgcohoc',
  },
  {
    id: 'ly11-c92-b1',
    grade: '11',
    chapterNumber: 92,
    chapterTitle: 'Chuyên đề HSG: Dao động',
    lessonNumber: 1,
    title: 'Ghép lò xo và độ cứng tương đương',
    track: 'advanced',
    advancedTier: 'hsg-truong',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'lyhsgdaodong',
  },
  {
    id: 'ly11-c92-b2',
    grade: '11',
    chapterNumber: 92,
    chapterTitle: 'Chuyên đề HSG: Dao động',
    lessonNumber: 2,
    title: 'Con lắc trong trường lực lạ: kỹ thuật gia tốc trọng trường hiệu dụng',
    track: 'advanced',
    advancedTier: 'hsg-tinh',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'lyhsgdaodong',
  },
  {
    id: 'ly11-c92-b3',
    grade: '11',
    chapterNumber: 92,
    chapterTitle: 'Chuyên đề HSG: Dao động',
    lessonNumber: 3,
    title: 'Hệ hai vật dao động: điều kiện không trượt và va chạm giữa chừng',
    track: 'advanced',
    advancedTier: 'hsg-quoc-gia',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'lyhsgdaodong',
  },
  {
    id: 'ly12-c93-b1',
    grade: '12',
    chapterNumber: 93,
    chapterTitle: 'Chuyên đề HSG: Nhiệt động lực học và điện từ',
    lessonNumber: 1,
    title: 'Đọc chu trình trên giản đồ p–V: công là diện tích',
    track: 'advanced',
    advancedTier: 'hsg-truong',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'lyhsgnhietdientu',
  },
  {
    id: 'ly12-c93-b2',
    grade: '12',
    chapterNumber: 93,
    chapterTitle: 'Chuyên đề HSG: Nhiệt động lực học và điện từ',
    lessonNumber: 2,
    title: 'Định luật I cho từng quá trình và hiệu suất chu trình',
    track: 'advanced',
    advancedTier: 'hsg-tinh',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'lyhsgnhietdientu',
  },
  {
    id: 'ly12-c93-b3',
    grade: '12',
    chapterNumber: 93,
    chapterTitle: 'Chuyên đề HSG: Nhiệt động lực học và điện từ',
    lessonNumber: 3,
    title: 'Thanh dẫn trượt trên ray: lực cản phụ thuộc vận tốc và vận tốc giới hạn',
    track: 'advanced',
    advancedTier: 'hsg-quoc-gia',
    hasAnimation: false,
    reviewStatus: 'draft',
    chapterKey: 'lyhsgnhietdientu',
  },
]

export const CHAPTER_LOADERS: Record<string, () => Promise<PhysicsLesson[]>> = {
  ly10c1: () => import('./lessons/ly10c1.js').then((m) => m.LY10_C1_LESSONS),
  ly10c2: () => import('./lessons/ly10c2.js').then((m) => m.LY10_C2_LESSONS),
  ly10c3: () => import('./lessons/ly10c3.js').then((m) => m.LY10_C3_LESSONS),
  ly10c4: () => import('./lessons/ly10c4.js').then((m) => m.LY10_C4_LESSONS),
  ly10c5: () => import('./lessons/ly10c5.js').then((m) => m.LY10_C5_LESSONS),
  ly10c6: () => import('./lessons/ly10c6.js').then((m) => m.LY10_C6_LESSONS),
  ly10c7: () => import('./lessons/ly10c7.js').then((m) => m.LY10_C7_LESSONS),
  ly11c1: () => import('./lessons/ly11c1.js').then((m) => m.LY11_C1_LESSONS),
  ly11c2: () => import('./lessons/ly11c2.js').then((m) => m.LY11_C2_LESSONS),
  ly11c3: () => import('./lessons/ly11c3.js').then((m) => m.LY11_C3_LESSONS),
  ly11c4: () => import('./lessons/ly11c4.js').then((m) => m.LY11_C4_LESSONS),
  ly12c1: () => import('./lessons/ly12c1.js').then((m) => m.LY12_C1_LESSONS),
  ly12c2: () => import('./lessons/ly12c2.js').then((m) => m.LY12_C2_LESSONS),
  ly12c3: () => import('./lessons/ly12c3.js').then((m) => m.LY12_C3_LESSONS),
  ly12c4: () => import('./lessons/ly12c4.js').then((m) => m.LY12_C4_LESSONS),
  lyhsgcohoc: () => import('./lessons/lyhsgcohoc.js').then((m) => m.LY_HSG_CO_HOC_LESSONS),
  lyhsgdaodong: () => import('./lessons/lyhsgdaodong.js').then((m) => m.LY_HSG_DAO_DONG_LESSONS),
  lyhsgnhietdientu: () =>
    import('./lessons/lyhsgnhietdientu.js').then((m) => m.LY_HSG_NHIET_DIEN_TU_LESSONS),
}
