// lessons/ly11c3.ts — Vật lí 11, Chương 3: Điện trường (6 bài).
import type { PhysicsLesson } from '../lessonTypes.js'

export const LY11_C3_LESSONS: PhysicsLesson[] = [
  {
    id: 'ly11-c3-b16',
    // Khoảng cách giảm một nửa thì lực Coulomb mạnh lên GẤP BỐN — hai cặp mũi tên vẽ đúng tỉ lệ 1 và 4.
    animation: {
      title: 'Giảm nửa khoảng cách, lực mạnh gấp bốn',
      description:
        'Hai điện tích điểm cùng dấu, mỗi cái 2 µC, đặt cách nhau 20 cm trong không khí. Lúc đầu hai mũi tên lực đẩy hướng ra xa nhau và khá ngắn: F = k·q₁q₂/r² = 9·10⁹ × (2·10⁻⁶)² : 0,2² = 0,9 N. Sau đó hai điện tích được đưa lại gần nhau, khoảng cách chỉ còn một nửa là 10 cm. Hai mũi tên lực mới hiện ra và dài GẤP BỐN LẦN mũi tên cũ: F = 3,6 N. Khoảng cách giảm 2 lần mà lực tăng 4 lần vì trong công thức Coulomb r nằm ở mẫu và được BÌNH PHƯƠNG. Chú ý hai mũi tên luôn bằng nhau về độ lớn dù có thể hai điện tích khác nhau về độ lớn — đó là hệ quả của định luật 3 Newton — và chúng hướng ra xa nhau vì hai điện tích cùng dấu thì đẩy nhau.',
      viewBoxWidth: 380,
      viewBoxHeight: 210,
      durationMs: 4000,
      loop: true,
      shapes: [
        {
          kind: 'line',
          id: 'truc',
          x1: 10,
          y1: 120,
          x2: 370,
          y2: 120,
          stroke: 'muted',
          strokeWidth: 1.5,
          dash: '4 4',
        },
        {
          kind: 'circle',
          id: 'dien-tich-1',
          cx: 100,
          cy: 120,
          r: 15,
          fill: 'primary',
          keyframes: [
            { atMs: 0, dx: 0 },
            { atMs: 1500, dx: 0 },
            { atMs: 2500, dx: 45 },
            { atMs: 4000, dx: 45 },
          ],
        },
        {
          kind: 'circle',
          id: 'dien-tich-2',
          cx: 280,
          cy: 120,
          r: 15,
          fill: 'primary',
          keyframes: [
            { atMs: 0, dx: 0 },
            { atMs: 1500, dx: 0 },
            { atMs: 2500, dx: -45 },
            { atMs: 4000, dx: -45 },
          ],
        },
        {
          kind: 'arrow',
          id: 'luc-ngan-1',
          x1: 84,
          y1: 120,
          x2: 54,
          y2: 120,
          stroke: 'correct',
          strokeWidth: 3,
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 1500, opacity: 1 },
            { atMs: 1800, opacity: 0 },
            { atMs: 4000, opacity: 0 },
          ],
        },
        {
          kind: 'arrow',
          id: 'luc-ngan-2',
          x1: 296,
          y1: 120,
          x2: 326,
          y2: 120,
          stroke: 'correct',
          strokeWidth: 3,
          keyframes: [
            { atMs: 0, opacity: 1 },
            { atMs: 1500, opacity: 1 },
            { atMs: 1800, opacity: 0 },
            { atMs: 4000, opacity: 0 },
          ],
        },
        {
          kind: 'arrow',
          id: 'luc-dai-1',
          x1: 129,
          y1: 120,
          x2: 9,
          y2: 120,
          stroke: 'correct',
          strokeWidth: 4,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 2500, opacity: 0 },
            { atMs: 2800, opacity: 1 },
            { atMs: 4000, opacity: 1 },
          ],
        },
        {
          kind: 'arrow',
          id: 'luc-dai-2',
          x1: 251,
          y1: 120,
          x2: 371,
          y2: 120,
          stroke: 'correct',
          strokeWidth: 4,
          opacity: 0,
          keyframes: [
            { atMs: 0, opacity: 0 },
            { atMs: 2500, opacity: 0 },
            { atMs: 2800, opacity: 1 },
            { atMs: 4000, opacity: 1 },
          ],
        },
        {
          kind: 'label',
          id: 'nhan-q1',
          keyframes: [
            { atMs: 0, dx: 0 },
            { atMs: 1500, dx: 0 },
            { atMs: 2500, dx: 45 },
            { atMs: 4000, dx: 45 },
          ],
          x: 100,
          y: 126,
          text: '+q',
          size: 14,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'nhan-q2',
          keyframes: [
            { atMs: 0, dx: 0 },
            { atMs: 1500, dx: 0 },
            { atMs: 2500, dx: -45 },
            { atMs: 4000, dx: -45 },
          ],
          x: 280,
          y: 126,
          text: '+q',
          size: 14,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'nhan-ct',
          x: 10,
          y: 26,
          text: 'F = k·q₁q₂ / r² với k = 9·10⁹',
          size: 14,
          anchor: 'start',
          fill: 'primary',
        },
        {
          kind: 'label',
          id: 'nhan-truoc',
          x: 10,
          y: 52,
          text: 'r = 20 cm → F = 0,9 N',
          size: 13,
          anchor: 'start',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'nhan-sau',
          x: 10,
          y: 72,
          text: 'r = 10 cm → F = 3,6 N (gấp 4 vì r bị bình phương)',
          size: 13,
          anchor: 'start',
          fill: 'accent',
        },
        {
          kind: 'label',
          id: 'nhan-kl',
          x: 10,
          y: 186,
          text: 'Hai lực luôn bằng nhau và ngược chiều · cùng dấu thì đẩy nhau',
          size: 12,
          anchor: 'start',
          fill: 'muted',
        },
      ],
      captions: [
        { atMs: 0, text: 'Hai điện tích +2 µC cách nhau 20 cm, lực đẩy 0,9 N.' },
        { atMs: 2500, text: 'Đưa lại gần còn 10 cm.' },
        { atMs: 2800, text: 'Mũi tên lực dài gấp bốn: F = 3,6 N.' },
      ],
    },
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Điện trường',
    lessonNumber: 16,
    title: 'Lực tương tác giữa các điện tích',
    hook:
      'Chà xát quả bóng bay vào áo len, nó có thể dính chặt vào bức tường hay làm uốn cong cả dòng nước chảy từ vòi nước. ' +
      'Lực vô hình hút đẩy các vật ở xa nhau này là gì? Chúng tuân theo quy luật toán học nào?',
    theory:
      'ĐIỆN TÍCH (ELECTRIC CHARGE):\n' +
      '— Có hai loại điện tích: điện tích dương (+) và điện tích âm (-).\n' +
      '— Tương tác điện tích: Các điện tích cùng dấu thì đẩy nhau, trái dấu thì hút nhau. Đơn vị đo điện tích trong hệ SI: Coulomb (C).\n\n' +
      "ĐỊNH LUẬT COULOMB (COULOMB'S LAW):\n" +
      '— Phát biểu: Độ lớn của lực tương tác giữa hai điện tích điểm đặt đứng yên trong chân không tỉ lệ thuận với tích độ lớn của hai điện tích và tỉ lệ nghịch với bình phương khoảng cách giữa chúng.\n' +
      '— Công thức trong chân không: F = k * |q₁.q₂| / r².\n' +
      '  — F: Lực tương tác tĩnh điện (N).\n' +
      '  — q₁, q₂: Điện tích của hai điện tích điểm (C).\n' +
      '  — r: Khoảng cách giữa hai điện tích điểm (m).\n' +
      '  — k: Hằng số Coulomb (k ≈ 9 * 10⁹ N.m²/C²).\n' +
      '— Tương tác trong điện môi đồng tính: Lực tương tác tĩnh điện giảm đi ε lần so với chân không: F = k * |q₁.q₂| / (ε.r²).\n' +
      '  — ε: Hằng số điện môi của môi trường (điện môi chân không ε = 1, không khí ε ≈ 1, điện môi khác ε > 1).',
    workedExample: {
      problem:
        'Hai điện tích điểm q₁ = 2 * 10⁻⁸ C và q₂ = -3 * 10⁻⁸ C đặt cách nhau r = 3 cm trong chân không. ' +
        'Xác định lực tương tác tĩnh điện giữa chúng (là lực hút hay lực đẩy, tính độ lớn).',
      steps: [
        'Nhận xét: Hai điện tích trái dấu (q₁ dương, q₂ âm) nên lực tương tác là lực hút.',
        'Đổi khoảng cách sang đơn vị mét: r = 3 cm = 0,03 m.',
        'Áp dụng công thức định luật Coulomb: F = k * |q₁.q₂| / r².',
        'Thay số: F = 9 * 10⁹ * |2 * 10⁻⁸ * (-3 * 10⁻⁸)| / 0,03².',
        'Tính toán: F = 9 * 10⁹ * 6 * 10⁻¹⁶ / 0,0009 = 6 * 10⁻³ N = 0,006 N.',
      ],
      answer: 'Lực hút, độ lớn F = 0,006 N.',
    },
    checkQuestions: [
      {
        prompt:
          'Viết công thức tính độ lớn lực tương tác tĩnh điện F giữa hai điện tích điểm q₁, q₂ đặt cách nhau khoảng cách r trong môi trường điện môi có hằng số điện môi ε.',
        choices: [
          { id: 'cl_1', label: 'F = k * |q₁.q₂| / (ε * r²)' },
          { id: 'cl_2', label: 'F = k * |q₁.q₂| / r²' },
          { id: 'cl_3', label: 'F = k * |q₁.q₂| * ε / r²' },
        ],
        answer: {
          kind: 'choice',
          correctIds: ['cl_1'],
        },
        explain:
          'Trong môi trường điện môi đồng tính, lực tĩnh điện Coulomb giảm đi ε lần: F = k|q₁q₂|/(εr²).',
      },
      {
        prompt:
          'Hai điện tích điểm trong chân không q₁ = 10⁻⁹ C và q₂ = 2 * 10⁻⁹ C đặt cách nhau r = 0,03 m. Tính độ lớn lực đẩy giữa chúng.',
        answer: {
          kind: 'numeric',
          value: 2e-5,
          unit: 'N',
        },
        explain:
          'F = k * |q₁.q₂| / r² = 9 * 10⁹ * (10⁻⁹ * 2 * 10⁻⁹) / 0,03² = 18 * 10⁻⁹ / 0,0009 = 2 * 10⁻⁵ N.',
      },
    ],
    srsCards: [
      {
        hoi: 'Đơn vị Coulomb (C) đo đại lượng vật lí nào?',
        dap: 'Đo điện tích. Một vật mang điện tích 1 C khi có một điện lượng 1 C chuyển qua nó.',
      },
      {
        hoi: 'Hằng số điện môi ε của chân không có giá trị bằng bao nhiêu?',
        dap: 'Bằng 1.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'ly11-c3-b17',
    // Đường sức của điện tích dương và âm + một điện tích thử để thấy điện trường "có sẵn ở đó"
    // chứ không phải chỉ xuất hiện khi ta đặt vật vào.
    animation: {
      title: 'Điện trường quanh điện tích điểm và điện tích thử',
      description:
        'Bên trái là một điện tích dương Q, bên phải là một điện tích âm −Q. Các mũi tên toả ra tám hướng quanh Q cho biết hướng của vectơ cường độ điện trường E tại mỗi điểm: hướng RA XA điện tích dương và hướng VÀO điện tích âm. Các mũi tên này có sẵn trong không gian ngay cả khi chưa đặt vật gì vào — điện trường là một dạng vật chất tồn tại quanh điện tích, không phải thứ chỉ sinh ra lúc có vật khác đến gần. Một điện tích thử dương q (chấm nhỏ) được thả ở giữa: nó bị Q đẩy ra và bị −Q hút vào, cả hai tác dụng đều đẩy nó chạy từ trái sang phải dọc theo đường sức. Lực đặt lên nó là F = q·E, nên nếu đổi q thành điện tích âm thì nó sẽ chạy ngược lại, còn E tại mỗi điểm thì vẫn thế.',
      viewBoxWidth: 420,
      viewBoxHeight: 240,
      durationMs: 3000,
      loop: true,
      shapes: [
        { kind: 'circle', id: 'dien-tich-duong', cx: 90, cy: 120, r: 18, fill: 'primary' },
        { kind: 'circle', id: 'dien-tich-am', cx: 330, cy: 120, r: 18, fill: 'accent' },
        {
          kind: 'label',
          id: 'nhan-q-duong',
          x: 90,
          y: 126,
          text: '+Q',
          size: 14,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'nhan-q-am',
          x: 330,
          y: 126,
          text: '−Q',
          size: 14,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'arrow',
          id: 'sd-1',
          x1: 112,
          y1: 120,
          x2: 160,
          y2: 120,
          stroke: 'primary',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'sd-2',
          x1: 106,
          y1: 104,
          x2: 140,
          y2: 70,
          stroke: 'primary',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'sd-3',
          x1: 90,
          y1: 98,
          x2: 90,
          y2: 50,
          stroke: 'primary',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'sd-4',
          x1: 74,
          y1: 104,
          x2: 40,
          y2: 70,
          stroke: 'primary',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'sd-5',
          x1: 68,
          y1: 120,
          x2: 20,
          y2: 120,
          stroke: 'primary',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'sd-6',
          x1: 74,
          y1: 136,
          x2: 40,
          y2: 170,
          stroke: 'primary',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'sd-7',
          x1: 90,
          y1: 142,
          x2: 90,
          y2: 190,
          stroke: 'primary',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'sd-8',
          x1: 106,
          y1: 136,
          x2: 140,
          y2: 170,
          stroke: 'primary',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'sa-1',
          x1: 260,
          y1: 120,
          x2: 308,
          y2: 120,
          stroke: 'accent',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'sa-2',
          x1: 380,
          y1: 70,
          x2: 346,
          y2: 104,
          stroke: 'accent',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'sa-3',
          x1: 330,
          y1: 50,
          x2: 330,
          y2: 98,
          stroke: 'accent',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'sa-4',
          x1: 280,
          y1: 70,
          x2: 314,
          y2: 104,
          stroke: 'accent',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'sa-5',
          x1: 400,
          y1: 120,
          x2: 352,
          y2: 120,
          stroke: 'accent',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'sa-6',
          x1: 280,
          y1: 170,
          x2: 314,
          y2: 136,
          stroke: 'accent',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'sa-7',
          x1: 330,
          y1: 190,
          x2: 330,
          y2: 142,
          stroke: 'accent',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'sa-8',
          x1: 380,
          y1: 170,
          x2: 346,
          y2: 136,
          stroke: 'accent',
          strokeWidth: 2,
        },
        {
          kind: 'circle',
          id: 'dien-tich-thu',
          cx: 160,
          cy: 120,
          r: 8,
          fill: 'neutral',
          keyframes: [
            { atMs: 0, dx: 0 },
            { atMs: 1000, dx: 20 },
            { atMs: 2000, dx: 60 },
            { atMs: 3000, dx: 140 },
          ],
        },
        {
          kind: 'label',
          id: 'nhan-q-thu',
          keyframes: [
            { atMs: 0, dx: 0, opacity: 1 },
            { atMs: 1000, dx: 20, opacity: 1 },
            { atMs: 2000, dx: 60, opacity: 1 },
            { atMs: 2400, dx: 92, opacity: 0 },
            { atMs: 3000, dx: 140, opacity: 0 },
          ],
          x: 160,
          y: 100,
          text: 'q thử (+)',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'nhan-ct',
          x: 210,
          y: 222,
          text: 'F = q·E — E có sẵn, q chỉ để "đo" nó',
          size: 13,
          anchor: 'middle',
          fill: 'neutral',
        },
      ],
      captions: [
        { atMs: 0, text: 'Đường sức toả ra từ điện tích dương và chụm vào điện tích âm.' },
        { atMs: 1500, text: 'Điện tích thử dương chạy dọc theo đường sức: bị +Q đẩy, bị −Q hút.' },
        { atMs: 3000, text: 'Bỏ điện tích thử đi, điện trường vẫn còn nguyên ở đó.' },
      ],
    },
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Điện trường',
    lessonNumber: 17,
    title: 'Khái niệm điện trường',
    hook:
      'Làm thế nào một điện tích lại tác dụng lực hút hoặc đẩy lên một điện tích khác cách nó một khoảng xa mà không hề chạm trực tiếp? ' +
      'Xung quanh điện tích có một dạng vật chất vô hình lan toả gọi là Điện trường.',
    theory:
      'ĐIỆN TRƯỜNG (ELECTRIC FIELD):\n' +
      '— Điện trường là một dạng vật chất bao quanh các điện tích và truyền tương tác lực điện giữa chúng. Điện tích đặt trong điện trường sẽ chịu tác dụng của lực điện.\n\n' +
      'CƯỜNG ĐỘ ĐIỆN TRƯỜNG (ELECTRIC FIELD STRENGTH):\n' +
      '— Là đại lượng đặc trưng cho điện trường về phương diện tác dụng lực. Đo bằng thương số giữa lực điện tác dụng lên điện tích thử và độ lớn điện tích thử đó.\n' +
      '— Công thức vectơ: vectơ E = vectơ F / q  ⇒  vectơ F = q * vectơ E.\n' +
      '— Độ lớn: E = F / |q|. Đơn vị trong hệ SI: Volt trên mét (V/m).\n\n' +
      'ĐIỆN TRƯỜNG CỦA ĐIỆN TÍCH ĐIỂM Q:\n' +
      '— Độ lớn cường độ điện trường do điện tích điểm Q gây ra tại điểm cách nó khoảng r trong chân không:\n' +
      '  E = k * |Q| / r²  (Trong điện môi: E = k * |Q| / (ε.r²)).\n' +
      '— Hướng của vectơ E:\n' +
      '  — Hướng ra xa Q nếu Q là điện tích dương (Q > 0).\n' +
      '  — Hướng về phía Q nếu Q là điện tích âm (Q < 0).\n' +
      '— Nguyên lí chồng chất điện trường: Vectơ cường độ điện trường tổng hợp tại một điểm bằng tổng các vectơ thành phần: vectơ E = vectơ E₁ + vectơ E₂ + ...',
    workedExample: {
      problem:
        'Tính độ lớn cường độ điện trường do điện tích điểm Q = 10⁻⁹ C gây ra tại một điểm cách nó r = 3 cm = 0,03 m trong chân không.',
      steps: [
        'Xác định các thông số: Q = 10⁻⁹ C, r = 0,03 m, hằng số k = 9 * 10⁹ N.m²/C².',
        'Áp dụng công thức cường độ điện trường điện tích điểm: E = k * |Q| / r².',
        'Thay số: E = 9 * 10⁹ * 10⁻⁹ / 0,03².',
        'Tính toán: E = 9 / 0,0009 = 10000 V/m.',
      ],
      answer: 'E = 10000 V/m.',
    },
    checkQuestions: [
      {
        prompt: 'Đơn vị đo chuẩn của cường độ điện trường trong hệ SI là gì?',
        choices: [
          { id: 'ef_1', label: 'Volt trên mét (V/m)' },
          { id: 'ef_2', label: 'Newton trên Coulomb (N/C)' },
          { id: 'ef_3', label: 'Cả hai đơn vị trên đều đúng' },
        ],
        answer: {
          kind: 'choice',
          correctIds: ['ef_3'],
        },
        explain:
          'Cường độ điện trường đo bằng F/q nên có đơn vị N/C, trong thực tế thường dùng V/m. Cả hai đơn vị đều đúng và tương đương nhau.',
      },
      {
        prompt:
          'Một điện tích thử q = 2 * 10⁻⁹ C đặt tại một điểm trong điện trường chịu tác dụng của lực điện F = 10⁻⁵ N. Tính độ lớn cường độ điện trường tại điểm đó.',
        answer: {
          kind: 'numeric',
          value: 5000,
          unit: 'V/m',
        },
        explain:
          'E = F / q = 10⁻⁵ / (2 * 10⁻⁹) = 5000 V/m. Cường độ điện trường E là đại lượng đặc trưng cho điện trường tại một điểm, không phụ thuộc vào điện tích thử q đặt vào.',
      },
    ],
    srsCards: [
      {
        hoi: 'Vectơ cường độ điện trường gây ra bởi điện tích dương hướng về phía điện tích hay ra xa nó?',
        dap: 'Hướng ra xa điện tích dương, dọc theo đường thẳng nối điện tích đó với điểm đang xét.',
      },
      {
        hoi: 'Phát biểu nguyên lí chồng chất điện trường.',
        dap: 'Cường độ điện trường do nhiều điện tích gây ra tại một điểm bằng tổng vectơ các cường độ điện trường do từng điện tích riêng lẻ gây ra.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'ly11-c3-b18',
    // Giữa hai bản song song: đường sức song song cách đều, điện tích thử chuyển động nhanh dần đều vì F = qE không đổi.
    animation: {
      title: 'Điện tích thử trong điện trường đều giữa hai bản',
      description:
        'Giữa hai bản kim loại phẳng song song nối vào hiệu điện thế 120 V, các đường sức được vẽ SONG SONG và CÁCH ĐỀU nhau, hướng từ bản dương sang bản âm — đó chính là dấu hiệu nhận ra điện trường đều. Một điện tích dương nhỏ được thả nhẹ sát bản dương rồi chuyển động về phía bản âm: các khoảng dịch chuyển của nó dài dần ra theo tỉ lệ 1 : 3 : 5, đúng dạng chuyển động nhanh dần đều, vì lực điện F = qE có độ lớn và hướng như nhau tại mọi điểm nên gia tốc không đổi. Cường độ điện trường tính bằng E = U/d = 120 : 0,04 = 3000 V/m, và giá trị này giống hệt nhau ở gần bản, ở giữa hay ở sát mép. Điện trường đều là mô hình của tụ điện phẳng và là nền của bài toán điện tích chuyển động trong điện trường.',
      viewBoxWidth: 360,
      viewBoxHeight: 266,
      durationMs: 4000,
      loop: true,
      shapes: [
        { kind: 'rect', id: 'ban-duong', x: 60, y: 44, w: 260, h: 10, rx: 2, fill: 'primary' },
        { kind: 'rect', id: 'ban-am', x: 60, y: 196, w: 260, h: 10, rx: 2, fill: 'accent' },
        {
          kind: 'arrow',
          id: 'suc-0',
          x1: 90,
          y1: 58,
          x2: 90,
          y2: 192,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'suc-1',
          x1: 130,
          y1: 58,
          x2: 130,
          y2: 192,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'suc-2',
          x1: 170,
          y1: 58,
          x2: 170,
          y2: 192,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'suc-3',
          x1: 210,
          y1: 58,
          x2: 210,
          y2: 192,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'suc-4',
          x1: 250,
          y1: 58,
          x2: 250,
          y2: 192,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'suc-5',
          x1: 290,
          y1: 58,
          x2: 290,
          y2: 192,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'circle',
          id: 'dien-tich-thu',
          cx: 190,
          cy: 68,
          r: 9,
          fill: 'correct',
          keyframes: [
            { atMs: 0, dy: 0 },
            { atMs: 1000, dy: 7.5 },
            { atMs: 2000, dy: 30 },
            { atMs: 3000, dy: 67.5 },
            { atMs: 4000, dy: 120 },
          ],
        },
        {
          kind: 'arrow',
          id: 'luc-dien',
          x1: 190,
          y1: 78,
          x2: 190,
          y2: 106,
          stroke: 'correct',
          strokeWidth: 3,
          keyframes: [
            { atMs: 0, dy: 0, opacity: 1 },
            { atMs: 1000, dy: 7.5, opacity: 1 },
            { atMs: 2000, dy: 30, opacity: 1 },
            { atMs: 3000, dy: 67.5, opacity: 1 },
            { atMs: 3300, dy: 81.7, opacity: 0 },
            { atMs: 4000, dy: 120, opacity: 0 },
          ],
        },
        {
          kind: 'line',
          id: 'do-d',
          x1: 46,
          y1: 54,
          x2: 46,
          y2: 196,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'nhan-d',
          x: 40,
          y: 122,
          text: 'd =',
          size: 12,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'nhan-d-so',
          x: 40,
          y: 138,
          text: '4 cm',
          size: 12,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'nhan-duong',
          x: 326,
          y: 52,
          text: '+ + +',
          size: 13,
          anchor: 'start',
          fill: 'primary',
        },
        {
          kind: 'label',
          id: 'nhan-am',
          x: 326,
          y: 206,
          text: '− − −',
          size: 13,
          anchor: 'start',
          fill: 'accent',
        },
        {
          kind: 'label',
          id: 'nhan-f',
          x: 12,
          y: 254,
          text: '→ lực F = qE không đổi: điện tích chuyển động nhanh dần đều',
          size: 12,
          anchor: 'start',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'nhan-e',
          x: 12,
          y: 26,
          text: 'U = 120 V · E = U/d = 3000 V/m',
          size: 14,
          anchor: 'start',
          fill: 'primary',
        },
        {
          kind: 'label',
          id: 'nhan-kl',
          x: 12,
          y: 236,
          text: 'Đường sức song song và cách đều → E như nhau ở mọi điểm',
          size: 12,
          anchor: 'start',
          fill: 'muted',
        },
      ],
      captions: [
        { atMs: 0, text: 'Thả điện tích dương sát bản dương, vận tốc đầu bằng 0.' },
        { atMs: 2000, text: 'Lực điện không đổi nên vật chuyển động nhanh dần đều.' },
        { atMs: 4000, text: 'Tới bản âm: quãng đường từng giây theo tỉ lệ 1 : 3 : 5.' },
      ],
    },
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Điện trường',
    lessonNumber: 18,
    title: 'Điện trường đều',
    hook:
      'Trong khoảng không gian giữa hai tấm kim loại phẳng song song tích điện trái dấu bằng nhau, cường độ điện trường có độ lớn và hướng như nhau tại mọi điểm. ' +
      'Đó chính là Điện trường đều — mô hình nền của tụ điện phẳng và của các máy gia tốc hạt.',
    theory:
      'ĐỊNH NGHĨA ĐIỆN TRƯỜNG ĐỀU (UNIFORM ELECTRIC FIELD):\n' +
      '— Điện trường đều là điện trường mà vectơ cường độ điện trường tại mọi điểm đều có cùng phương, cùng chiều và cùng độ lớn.\n' +
      '— Đường sức điện: Là những đường thẳng song song, cùng chiều và cách đều nhau.\n\n' +
      'ĐIỆN TRƯỜNG GIỮA HAI BẢN KIM LOẠI PHẲNG SONG SONG TIÊU BIỂU:\n' +
      '— Hai bản kim loại đặt song song, cách nhau một khoảng d, tích điện bằng nhau nhưng trái dấu.\n' +
      '— Cường độ điện trường đều bên trong: E = U / d (U là hiệu điện thế giữa hai bản kim loại, d là khoảng cách giữa hai bản).\n\n' +
      'CHUYỂN ĐỘNG CỦA ĐIỆN TÍCH TRONG ĐIỆN TRƯỜNG ĐỀU:\n' +
      '— Hạt tích điện q, khối lượng m đặt trong điện trường đều chịu lực điện không đổi: vectơ F = q * vectơ E.\n' +
      '— Sinh ra gia tốc không đổi: vectơ a = q * vectơ E / m.\n' +
      '  — Nếu hạt phóng dọc theo đường sức điện: chuyển động thẳng biến đổi đều (nhanh dần đều nếu q và E cùng hướng, chậm dần đều nếu ngược hướng).\n' +
      '  — Nếu hạt phóng vuông góc với đường sức điện: chuyển động giống như chuyển động ném ngang (quỹ đạo là một parabol).',
    workedExample: {
      problem:
        'Hai bản kim loại phẳng song song nằm ngang cách nhau d = 2 cm = 0,02 m, nối với hiệu điện thế U = 200 V. ' +
        'Xác định cường độ điện trường đều E giữa hai bản.',
      steps: [
        'Xác định các thông số: hiệu điện thế U = 200 V, khoảng cách d = 0,02 m.',
        'Áp dụng công thức liên hệ trong điện trường đều: E = U / d.',
        'Thay số: E = 200 / 0,02 = 10000 V/m.',
        'Kết luận: Cường độ điện trường đều giữa hai bản là 10000 V/m.',
      ],
      answer: 'E = 10000 V/m.',
    },
    checkQuestions: [
      {
        prompt:
          'Viết hệ thức liên hệ giữa cường độ điện trường E của điện trường đều với hiệu điện thế U và khoảng cách d giữa hai bản kim loại.',
        choices: [
          { id: 'uf_1', label: 'E = U / d' },
          { id: 'uf_2', label: 'E = U * d' },
          { id: 'uf_3', label: 'U = E / d' },
        ],
        answer: {
          kind: 'choice',
          correctIds: ['uf_1'],
        },
        explain:
          'Cường độ điện trường đều bằng hiệu điện thế chia cho khoảng cách dọc theo đường sức: E = U/d.',
      },
      {
        prompt:
          'Hai bản kim loại song song tích điện trái dấu cách nhau 0,01 m. Hiệu điện thế giữa hai bản là 50 V. Tính cường độ điện trường đều giữa hai bản.',
        answer: {
          kind: 'numeric',
          value: 5000,
          unit: 'V/m',
        },
        explain:
          'Giữa hai bản song song, điện trường là ĐỀU nên liên hệ với hiệu điện thế rất gọn: E = U / d = 50 / 0,01 = 5000 V/m. Khoảng cách d phải tính bằng MÉT — để nguyên 1 cm là kết quả lệch 100 lần.',
      },
    ],
    srsCards: [
      {
        hoi: 'Đường sức điện của điện trường đều có hình dạng và phân bố thế nào?',
        dap: 'Là những đường thẳng song song, cùng chiều và cách đều nhau.',
      },
      {
        hoi: 'Quỹ đạo chuyển động của một điện tích bay vuông góc vào điện trường đều có hình dạng gì?',
        dap: 'Có hình dạng đường parabol (tương tự chuyển động ném ngang).',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'ly11-c3-b19',
    // Hai đường đi khác nhau giữa cùng hai điểm cho CÙNG một công — công của lực điện chỉ phụ thuộc đầu và cuối.
    animation: {
      title: 'Công của lực điện không phụ thuộc đường đi',
      description:
        'Trong một điện trường đều hướng xuống, hai điện tích giống nhau cùng xuất phát từ điểm M và cùng phải tới điểm N, nhưng đi theo hai đường khác hẳn nhau. Điện tích thứ nhất đi thẳng theo đường chéo MN. Điện tích thứ hai đi theo đường gấp khúc: trước hết chạy NGANG, vuông góc với đường sức, sau đó mới đi thẳng xuống. Dù đường thứ hai dài hơn hẳn, công của lực điện trên hai đường là như nhau: A = qEd, trong đó d chỉ là hình chiếu của đoạn MN lên phương đường sức, phần bằng nhau ở cả hai hành trình. Lí do là đoạn đi ngang vuông góc với lực điện nên không sinh công một chút nào. Vì công chỉ phụ thuộc điểm đầu và điểm cuối nên lực điện là lực thế, và ta định nghĩa được thế năng điện W = qEd tại mỗi điểm.',
      viewBoxWidth: 340,
      viewBoxHeight: 240,
      durationMs: 4000,
      loop: true,
      shapes: [
        {
          kind: 'arrow',
          id: 'suc-0',
          x1: 40,
          y1: 52,
          x2: 40,
          y2: 200,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'suc-1',
          x1: 90,
          y1: 52,
          x2: 90,
          y2: 200,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'suc-2',
          x1: 140,
          y1: 52,
          x2: 140,
          y2: 200,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'suc-3',
          x1: 190,
          y1: 52,
          x2: 190,
          y2: 200,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'suc-4',
          x1: 240,
          y1: 52,
          x2: 240,
          y2: 200,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'suc-5',
          x1: 290,
          y1: 52,
          x2: 290,
          y2: 200,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'polyline',
          id: 'duong-thang',
          points: [
            [80, 70],
            [250, 190],
          ],
          stroke: 'primary',
          strokeWidth: 2,
          dash: '5 4',
        },
        {
          kind: 'polyline',
          id: 'duong-gap',
          points: [
            [80, 70],
            [250, 70],
            [250, 190],
          ],
          stroke: 'accent',
          strokeWidth: 2,
          dash: '5 4',
        },
        {
          kind: 'circle',
          id: 'hat-di-thang',
          cx: 80,
          cy: 70,
          r: 8,
          fill: 'primary',
          keyframes: [
            { atMs: 0, dx: 0, dy: 0 },
            { atMs: 3000, dx: 170, dy: 120 },
            { atMs: 4000, dx: 170, dy: 120 },
          ],
        },
        {
          kind: 'circle',
          id: 'hat-di-gap',
          cx: 80,
          cy: 70,
          r: 8,
          fill: 'accent',
          keyframes: [
            { atMs: 0, dx: 0, dy: 0 },
            { atMs: 1700, dx: 170, dy: 0 },
            { atMs: 3000, dx: 170, dy: 120 },
            { atMs: 4000, dx: 170, dy: 120 },
          ],
        },
        {
          kind: 'line',
          id: 'chieu-d',
          x1: 306,
          y1: 70,
          x2: 306,
          y2: 190,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'nhan-m',
          x: 72,
          y: 62,
          text: 'M',
          size: 14,
          anchor: 'end',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'nhan-n',
          x: 258,
          y: 206,
          text: 'N',
          size: 14,
          anchor: 'start',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'nhan-d',
          x: 312,
          y: 134,
          text: 'd',
          size: 13,
          anchor: 'start',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'nhan-ngang',
          x: 165,
          y: 46,
          text: 'đoạn ngang: công = 0',
          size: 11,
          anchor: 'middle',
          fill: 'accent',
        },
        {
          kind: 'label',
          id: 'nhan-a',
          x: 12,
          y: 26,
          text: 'A = qEd — d là hình chiếu MN lên phương đường sức',
          size: 13,
          anchor: 'start',
          fill: 'primary',
        },
        {
          kind: 'label',
          id: 'nhan-kl',
          x: 12,
          y: 232,
          text: 'Hai đường khác nhau, cùng một công → lực điện là lực thế',
          size: 12,
          anchor: 'start',
          fill: 'muted',
        },
      ],
      captions: [
        { atMs: 0, text: 'Hai điện tích cùng rời M, một đi thẳng, một đi gấp khúc.' },
        { atMs: 1700, text: 'Đoạn chạy ngang vuông góc đường sức nên không sinh công.' },
        { atMs: 3000, text: 'Cùng tới N: công của lực điện bằng nhau, A = qEd.' },
      ],
    },
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Điện trường',
    lessonNumber: 19,
    title: 'Thế năng điện',
    hook:
      'Giống như một hòn đá được nâng lên cao có thế năng trọng trường tích luỹ, ' +
      'một điện tích dương bị đẩy ngược lại mà vẫn ép được tới gần một điện tích dương khác cũng tích luỹ Thế năng điện.',
    theory:
      'CÔNG CỦA LỰC ĐIỆN TRONG ĐIỆN TRƯỜNG ĐỀU:\n' +
      '— Lực điện tác dụng lên điện tích q đặt trong điện trường đều E là F = q.E.\n' +
      '— Khi q di chuyển từ điểm M đến điểm N, công của lực điện được tính bằng công thức:\n' +
      '  A_MN = q * E * d\n' +
      '  — d: Hình chiếu của quãng đường di chuyển MN lên phương đường sức điện (d > 0 nếu hình chiếu cùng chiều đường sức, d < 0 nếu ngược chiều).\n' +
      '— Đặc điểm: Công của lực điện không phụ thuộc vào hình dạng đường đi từ M đến N mà chỉ phụ thuộc vào vị trí của điểm đầu M và điểm cuối N (lực điện là lực thế).\n\n' +
      'THẾ NĂNG CỦA ĐIỆN TÍCH TRONG ĐIỆN TRƯỜNG:\n' +
      '— Thế năng của điện tích q tại điểm M đặc trưng cho khả năng sinh công của điện trường khi đặt q tại đó:\n' +
      '  W_M = A_M∞ = q * E * d_M (chọn mốc thế năng ở vô cực hoặc bản âm).',
    workedExample: {
      problem:
        'Một điện tích q = 2 * 10⁻⁹ C di chuyển một đoạn đường s = 10 cm dọc theo một đường sức của điện trường đều ' +
        'có cường độ E = 5000 V/m. Tính công của lực điện trường thực hiện khi điện tích di chuyển cùng chiều đường sức.',
      steps: [
        'Xác định các thông số: q = 2 * 10⁻⁹ C, E = 5000 V/m.',
        'Vì điện tích di chuyển cùng chiều đường sức nên d = s = 10 cm = 0,1 m.',
        'Áp dụng công thức công lực điện: A = q * E * d.',
        'Thay số: A = 2 * 10⁻⁹ * 5000 * 0,1 = 10⁻⁶ J.',
      ],
      answer: 'A = 10⁻⁶ J.',
    },
    checkQuestions: [
      {
        prompt:
          'Công của lực điện tác dụng lên điện tích q khi di chuyển từ điểm M đến điểm N trong điện trường đều E phụ thuộc vào yếu tố nào?',
        choices: [
          { id: 'wk_1', label: 'Hình dạng đường đi của điện tích' },
          { id: 'wk_2', label: 'Vị trí của điểm đầu M và điểm cuối N' },
          { id: 'wk_3', label: 'Tốc độ di chuyển của điện tích' },
        ],
        answer: {
          kind: 'choice',
          correctIds: ['wk_2'],
        },
        explain:
          'Vì lực điện là lực thế, công của nó chỉ phụ thuộc vào điểm đầu và điểm cuối của quỹ đạo chuyển động.',
      },
      {
        prompt:
          'Một điện tích q = 10⁻⁹ C di chuyển trong điện trường đều E = 1000 V/m. Biết hình chiếu quãng đường di chuyển dọc theo chiều đường sức điện là d = 0,05 m. Tính công của lực điện trường thực hiện.',
        answer: {
          kind: 'numeric',
          value: 5e-8,
          unit: 'J',
        },
        explain:
          'A = q * E * d = 10⁻⁹ * 1000 * 0,05 = 5 * 10⁻⁸ J. Ở đây d phải là hình chiếu quãng đường LÊN phương đường sức điện, không phải quãng đường di chuyển thực tế của điện tích.',
      },
    ],
    srsCards: [
      {
        hoi: 'Tại sao lực điện trường được coi là lực thế?',
        dap: 'Vì công của lực điện trường khi di chuyển một điện tích chỉ phụ thuộc vào điểm đầu và điểm cuối, không phụ thuộc vào hình dạng đường đi.',
      },
      {
        hoi: 'Viết công thức tính công của lực điện trường đều đối với điện tích q dịch chuyển quãng đường có hình chiếu d trên đường sức.',
        dap: 'A = qEd.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'ly11-c3-b20',
    // Mặt đẳng thế: đi dọc theo nó thì U = 0 và công = 0; đi cắt ngang từ 90 V xuống 30 V mới có công.
    animation: {
      title: 'Đi dọc mặt đẳng thế thì không tốn công',
      description:
        'Trong điện trường đều, ba đường nét đứt nằm ngang là ba mặt đẳng thế ứng với điện thế 90 V, 60 V và 30 V; các đường sức thẳng đứng luôn vuông góc với chúng và hướng về phía điện thế thấp. Điện tích thứ nhất chạy DỌC theo mặt 90 V từ trái sang phải: điểm đầu và điểm cuối có cùng điện thế nên hiệu điện thế U = 0, và công của lực điện A = qU cũng bằng 0 — đi bao xa cũng vậy. Điện tích thứ hai đi CẮT NGANG các mặt đẳng thế, từ mặt 90 V xuống mặt 30 V: hiệu điện thế U = 90 − 30 = 60 V, nên công A = qU khác 0 và thế năng của nó giảm đi đúng bằng phần công đó. Điện thế đo mức năng lượng của một đơn vị điện tích tại mỗi điểm; chỉ HIỆU điện thế giữa hai điểm mới quyết định công, còn chọn mốc 0 ở đâu là tuỳ ta.',
      viewBoxWidth: 340,
      viewBoxHeight: 300,
      durationMs: 4000,
      loop: true,
      shapes: [
        {
          kind: 'arrow',
          id: 'suc-0',
          x1: 50,
          y1: 56,
          x2: 50,
          y2: 224,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'suc-1',
          x1: 100,
          y1: 56,
          x2: 100,
          y2: 224,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'suc-2',
          x1: 150,
          y1: 56,
          x2: 150,
          y2: 224,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'suc-3',
          x1: 200,
          y1: 56,
          x2: 200,
          y2: 224,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'suc-4',
          x1: 250,
          y1: 56,
          x2: 250,
          y2: 224,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'arrow',
          id: 'suc-5',
          x1: 300,
          y1: 56,
          x2: 300,
          y2: 224,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'line',
          id: 'dang-the-90',
          x1: 30,
          y1: 70,
          x2: 320,
          y2: 70,
          stroke: 'accent',
          strokeWidth: 2,
          dash: '6 4',
        },
        {
          kind: 'line',
          id: 'dang-the-60',
          x1: 30,
          y1: 140,
          x2: 320,
          y2: 140,
          stroke: 'accent',
          strokeWidth: 2,
          dash: '6 4',
        },
        {
          kind: 'line',
          id: 'dang-the-30',
          x1: 30,
          y1: 210,
          x2: 320,
          y2: 210,
          stroke: 'accent',
          strokeWidth: 2,
          dash: '6 4',
        },
        {
          kind: 'circle',
          id: 'hat-doc',
          cx: 70,
          cy: 70,
          r: 8,
          fill: 'primary',
          keyframes: [
            { atMs: 0, dx: 0 },
            { atMs: 3000, dx: 110 },
            { atMs: 4000, dx: 110 },
          ],
        },
        {
          kind: 'circle',
          id: 'hat-cat-ngang',
          cx: 260,
          cy: 70,
          r: 8,
          fill: 'primary',
          keyframes: [
            { atMs: 0, dy: 0 },
            { atMs: 3000, dy: 140 },
            { atMs: 4000, dy: 140 },
          ],
        },
        {
          kind: 'label',
          id: 'nhan-90',
          x: 26,
          y: 66,
          text: '90 V',
          size: 12,
          anchor: 'end',
          fill: 'accent',
        },
        {
          kind: 'label',
          id: 'nhan-60',
          x: 26,
          y: 136,
          text: '60 V',
          size: 12,
          anchor: 'end',
          fill: 'accent',
        },
        {
          kind: 'label',
          id: 'nhan-30',
          x: 26,
          y: 206,
          text: '30 V',
          size: 12,
          anchor: 'end',
          fill: 'accent',
        },
        {
          kind: 'label',
          id: 'nhan-doc',
          x: 12,
          y: 248,
          text: 'Hạt trái đi dọc mặt đẳng thế 90 V: U = 0 → A = 0',
          size: 12,
          anchor: 'start',
          fill: 'primary',
        },
        {
          kind: 'label',
          id: 'nhan-cat',
          x: 12,
          y: 266,
          text: 'Hạt phải đi từ 90 V xuống 30 V: U = 60 V → A = qU',
          size: 12,
          anchor: 'start',
          fill: 'primary',
        },
        {
          kind: 'label',
          id: 'nhan-ct',
          x: 12,
          y: 26,
          text: 'A = qU với U = V(M) − V(N)',
          size: 14,
          anchor: 'start',
          fill: 'primary',
        },
        {
          kind: 'label',
          id: 'nhan-kl',
          x: 12,
          y: 290,
          text: 'Đường sức ⊥ mặt đẳng thế, hướng về phía điện thế thấp',
          size: 11,
          anchor: 'start',
          fill: 'muted',
        },
      ],
      captions: [
        { atMs: 0, text: 'Hai điện tích cùng xuất phát trên mặt đẳng thế 90 V.' },
        { atMs: 1500, text: 'Hạt bên trái đi ngang, vẫn ở 90 V nên công bằng 0.' },
        { atMs: 3000, text: 'Hạt bên phải xuống mặt 30 V: U = 60 V nên có công A = qU.' },
      ],
    },
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Điện trường',
    lessonNumber: 20,
    title: 'Điện thế',
    hook:
      'Chúng ta thường nghe nói pin tiểu 1,5V, ổ cắm điện nhà 220V. V hay Volt chính là đơn vị đo Điện thế và Hiệu điện thế. ' +
      'Điện thế đại diện cho mức năng lượng của điện trường tại mỗi điểm.',
    theory:
      'ĐIỆN THẾ (ELECTRIC POTENTIAL):\n' +
      '— Điện thế tại một điểm M trong điện trường là đại lượng đặc trưng cho điện trường về phương diện tạo ra thế năng khi đặt tại đó một điện tích q.\n' +
      '— Công thức: V_M = W_M / q = A_M∞ / q. Đơn vị: Volt (V).\n\n' +
      'HIỆU ĐIỆN THẾ (POTENTIAL DIFFERENCE):\n' +
      '— Hiệu điện thế giữa hai điểm M và N trong điện trường là hiệu số giữa điện thế của M và N. Nó đặc trưng cho khả năng sinh công của điện trường khi di chuyển q giữa hai điểm đó.\n' +
      '— Công thức: U_MN = V_M - V_N = A_MN / q. Đơn vị: Volt (V).\n\n' +
      'HỆ THỨC GIỮA CƯỜNG ĐỘ ĐIỆN TRƯỜNG VÀ HIỆU ĐIỆN THẾ:\n' +
      '— Trong điện trường đều: E = U_MN / d  ⇒  U_MN = E * d.',
    workedExample: {
      problem:
        'Điện thế tại điểm M là V_M = 50 V, điện thế tại điểm N là V_N = 20 V. ' +
        'a) Tính hiệu điện thế U_MN.\n' +
        'b) Tính công của điện trường làm dịch chuyển điện tích q = 2 * 10⁻⁶ C từ M đến N.',
      steps: [
        'Tính hiệu điện thế: U_MN = V_M - V_N = 50 - 20 = 30 V.',
        'Áp dụng công thức tính công: A_MN = q * U_MN.',
        'Thay số: A_MN = 2 * 10⁻⁶ * 30 = 6 * 10⁻⁵ J = 60 μJ.',
      ],
      answer: 'U_MN = 30 V; A_MN = 6 * 10⁻⁵ J.',
    },
    checkQuestions: [
      {
        prompt:
          'Viết công thức định nghĩa hiệu điện thế U_MN giữa hai điểm M, N dựa trên công A_MN dịch chuyển điện tích q.',
        choices: [
          { id: 'pt_1', label: 'U_MN = A_MN / q' },
          { id: 'pt_2', label: 'U_MN = A_MN * q' },
          { id: 'pt_3', label: 'U_MN = q / A_MN' },
        ],
        answer: {
          kind: 'choice',
          correctIds: ['pt_1'],
        },
        explain:
          'Hiệu điện thế bằng thương số giữa công lực điện dịch chuyển q và giá trị điện tích q: U = A/q.',
      },
      {
        prompt:
          'Điện thế tại điểm A trong điện trường là 100 V, tại điểm B là 40 V. Tính công của lực điện trường thực hiện để dịch chuyển điện tích q = 10⁻⁹ C từ A đến B.',
        answer: {
          kind: 'numeric',
          value: 6e-8,
          unit: 'J',
        },
        explain: 'U_AB = V_A - V_B = 100 - 40 = 60 V. A_AB = q * U_AB = 10⁻⁹ * 60 = 6 * 10⁻⁸ J.',
      },
    ],
    srsCards: [
      {
        hoi: 'Đơn vị đo hiệu điện thế trong hệ SI là gì?',
        dap: 'Volt (V).',
      },
      {
        hoi: 'Mối liên hệ giữa hiệu điện thế U giữa hai điểm và cường độ điện trường đều E có hình chiếu d là gì?',
        dap: 'U = E * d.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'ly11-c3-b21',
    // Nạp tụ: electron chạy tới bản tụ, hiệu điện thế tăng theo đường cong tiến dần tới U của nguồn rồi dòng tắt.
    animation: {
      title: 'Quá trình nạp điện cho tụ điện',
      description:
        'Đóng khoá K, mạch kín gồm nguồn và tụ điện bắt đầu hoạt động. Các chấm điện tích chạy trong dây tới đọng lại trên hai bản tụ: bản nối cực dương mất electron nên tích điện dương, bản kia thừa electron nên tích điện âm — hai bản luôn mang điện tích trái dấu và bằng nhau về độ lớn. Đồ thị bên phải vẽ hiệu điện thế giữa hai bản theo thời gian: lúc đầu u tăng rất nhanh, sau đó chậm dần và tiến tới đúng hiệu điện thế của nguồn rồi nằm ngang. Càng về sau các chấm điện tích chạy càng thưa rồi ngừng hẳn: dòng nạp giảm về 0 vì tụ đã đầy. Điện dung đo khả năng chứa điện của tụ: C = Q/U, còn năng lượng dự trữ trong điện trường giữa hai bản là W = ½CU². Chú ý tụ KHÔNG cho dòng một chiều đi qua lâu dài; nó chỉ nạp rồi ngừng.',
      viewBoxWidth: 380,
      viewBoxHeight: 250,
      durationMs: 5000,
      loop: true,
      shapes: [
        {
          kind: 'polyline',
          id: 'day-tren',
          points: [
            [50, 170],
            [50, 70],
            [120, 70],
          ],
          stroke: 'neutral',
          strokeWidth: 3,
        },
        {
          kind: 'polyline',
          id: 'day-duoi',
          points: [
            [152, 70],
            [200, 70],
            [200, 170],
            [50, 170],
          ],
          stroke: 'neutral',
          strokeWidth: 3,
        },
        {
          kind: 'line',
          id: 'ban-tu-1',
          x1: 120,
          y1: 46,
          x2: 120,
          y2: 94,
          stroke: 'primary',
          strokeWidth: 5,
        },
        {
          kind: 'line',
          id: 'ban-tu-2',
          x1: 152,
          y1: 46,
          x2: 152,
          y2: 94,
          stroke: 'accent',
          strokeWidth: 5,
        },
        { kind: 'rect', id: 'nguon', x: 100, y: 162, w: 46, h: 16, rx: 3, fill: 'neutral' },
        {
          kind: 'circle',
          id: 'hat-1',
          cx: 200,
          cy: 140,
          r: 5,
          fill: 'correct',
          keyframes: [
            { atMs: 0, dx: 0, dy: 0, opacity: 1 },
            { atMs: 700, dx: 0, dy: -70 },
            { atMs: 1100, dx: -46, dy: -70, opacity: 1 },
            { atMs: 1200, dx: -46, dy: -70, opacity: 0 },
            { atMs: 5000, dx: -46, dy: -70, opacity: 0 },
          ],
        },
        {
          kind: 'circle',
          id: 'hat-2',
          cx: 200,
          cy: 140,
          r: 5,
          fill: 'correct',
          opacity: 0,
          keyframes: [
            { atMs: 0, dx: 0, dy: 0, opacity: 0 },
            { atMs: 1200, dx: 0, dy: 0, opacity: 1 },
            { atMs: 2200, dx: 0, dy: -70 },
            { atMs: 2800, dx: -46, dy: -70, opacity: 1 },
            { atMs: 2900, dx: -46, dy: -70, opacity: 0 },
            { atMs: 5000, dx: -46, dy: -70, opacity: 0 },
          ],
        },
        {
          kind: 'circle',
          id: 'hat-3',
          cx: 200,
          cy: 140,
          r: 5,
          fill: 'correct',
          opacity: 0,
          keyframes: [
            { atMs: 0, dx: 0, dy: 0, opacity: 0 },
            { atMs: 2900, dx: 0, dy: 0, opacity: 1 },
            { atMs: 4200, dx: 0, dy: -70 },
            { atMs: 4900, dx: -46, dy: -70, opacity: 1 },
            { atMs: 5000, dx: -46, dy: -70, opacity: 0 },
          ],
        },
        {
          kind: 'line',
          id: 'truc-x',
          x1: 240,
          y1: 200,
          x2: 370,
          y2: 200,
          stroke: 'neutral',
          strokeWidth: 2,
        },
        {
          kind: 'line',
          id: 'truc-y',
          x1: 240,
          y1: 200,
          x2: 240,
          y2: 50,
          stroke: 'neutral',
          strokeWidth: 2,
        },
        {
          kind: 'polyline',
          id: 'do-thi-u',
          points: [
            [240, 200],
            [242, 192.26],
            [244, 185.02],
            [246, 178.25],
            [248, 171.91],
            [250, 165.98],
            [252, 160.44],
            [254, 155.25],
            [256, 150.4],
            [258, 145.86],
            [260, 141.61],
            [262, 137.64],
            [264, 133.92],
            [266, 130.44],
            [268, 127.19],
            [270, 124.15],
            [272, 121.3],
            [274, 118.63],
            [276, 116.14],
            [278, 113.81],
            [280, 111.63],
            [282, 109.59],
            [284, 107.68],
            [286, 105.9],
            [288, 104.23],
            [290, 102.67],
            [292, 101.2],
            [294, 99.84],
            [296, 98.56],
            [298, 97.36],
            [300, 96.24],
            [302, 95.19],
            [304, 94.21],
            [306, 93.3],
            [308, 92.44],
            [310, 91.64],
            [312, 90.89],
            [314, 90.18],
            [316, 89.53],
            [318, 88.91],
            [320, 88.34],
            [322, 87.8],
            [324, 87.3],
            [326, 86.83],
            [328, 86.39],
            [330, 85.97],
            [332, 85.59],
            [334, 85.23],
            [336, 84.89],
            [338, 84.58],
            [340, 84.28],
            [342, 84],
            [344, 83.75],
            [346, 83.5],
            [348, 83.28],
            [350, 83.07],
            [352, 82.87],
            [354, 82.68],
            [356, 82.51],
            [358, 82.35],
            [360, 82.2],
          ],
          stroke: 'primary',
          strokeWidth: 3,
        },
        {
          kind: 'line',
          id: 'muc-u-nguon',
          x1: 240,
          y1: 80,
          x2: 368,
          y2: 80,
          stroke: 'muted',
          strokeWidth: 1.5,
          dash: '5 4',
        },
        {
          kind: 'circle',
          id: 'con-tro-u',
          cx: 240,
          cy: 200,
          r: 5,
          fill: 'accent',
          keyframes: [
            { atMs: 0, dx: 0, dy: 0 },
            { atMs: 1250, dx: 30, dy: -75.9 },
            { atMs: 2500, dx: 60, dy: -103.8 },
            { atMs: 3750, dx: 90, dy: -114 },
            { atMs: 5000, dx: 120, dy: -117.8 },
          ],
        },
        {
          kind: 'label',
          id: 'nhan-tu',
          x: 136,
          y: 38,
          text: 'tụ điện C',
          size: 11,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'nhan-cong',
          x: 112,
          y: 66,
          text: '+',
          size: 14,
          anchor: 'end',
          fill: 'primary',
        },
        {
          kind: 'label',
          id: 'nhan-tru',
          x: 160,
          y: 66,
          text: '−',
          size: 14,
          anchor: 'start',
          fill: 'accent',
        },
        {
          kind: 'label',
          id: 'nhan-nguon',
          x: 123,
          y: 194,
          text: 'nguồn + khoá K',
          size: 11,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'nhan-u',
          x: 246,
          y: 74,
          text: 'U nguồn',
          size: 11,
          anchor: 'start',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'nhan-truc-u',
          x: 246,
          y: 62,
          text: 'u',
          size: 12,
          anchor: 'start',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'nhan-truc-t',
          x: 370,
          y: 218,
          text: 't',
          size: 12,
          anchor: 'end',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'nhan-ct',
          x: 12,
          y: 26,
          text: 'C = Q/U · W = ½CU²',
          size: 14,
          anchor: 'start',
          fill: 'primary',
        },
        {
          kind: 'label',
          id: 'nhan-kl',
          x: 12,
          y: 236,
          text: 'Dòng nạp giảm dần về 0 — tụ không cho dòng một chiều đi qua lâu dài',
          size: 11,
          anchor: 'start',
          fill: 'muted',
        },
      ],
      captions: [
        { atMs: 0, text: 'Đóng khoá K: điện tích bắt đầu chạy tới hai bản tụ.' },
        { atMs: 2500, text: 'u đã gần bằng U của nguồn, các chấm điện tích thưa dần.' },
        { atMs: 5000, text: 'Tụ đầy: u bằng U nguồn, dòng nạp tắt hẳn.' },
      ],
    },
    grade: '11',
    chapterNumber: 3,
    chapterTitle: 'Điện trường',
    lessonNumber: 21,
    title: 'Tụ điện',
    hook:
      'Đèn flash của điện thoại cần một lượng điện năng cực lớn phóng ra chỉ trong một mili giây để chớp sáng. ' +
      'Viên pin thường không thể phóng điện nhanh như vậy, nhưng Tụ điện làm được điều đó một cách hoàn hảo.',
    theory:
      'TỤ ĐIỆN LÀ GÌ (CAPACITOR):\n' +
      '— Tụ điện là một hệ gồm hai vật dẫn đặt gần nhau và ngăn cách nhau bằng một lớp điện môi (chất cách điện). Nó dùng để tích và phóng điện năng.\n\n' +
      'ĐIỆN DUNG CỦA TỤ ĐIỆN (CAPACITANCE):\n' +
      '— Điện dung C là đại lượng đặc trưng cho khả năng tích điện của tụ điện ở một hiệu điện thế nhất định. Đo bằng tỉ số giữa điện tích Q của tụ và hiệu điện thế U giữa hai bản tụ.\n' +
      '— Công thức: C = Q / U  ⇒  Q = C * U.\n' +
      '— Đơn vị: Farad (F). Các ước số thông dụng: Microfarad (μF = 10⁻⁶ F), Nanofarad (nF = 10⁻⁹ F), Picofarad (pF = 10⁻¹² F).\n\n' +
      'NĂNG LƯỢNG ĐIỆN TRƯỜNG CỦA TỤ ĐIỆN:\n' +
      '— Khi tích điện, tụ điện tích luỹ năng lượng dưới dạng năng lượng điện trường trong lớp điện môi:\n' +
      '  W = 1/2.Q.U = 1/2.C.U² = 1/2.Q² / C.',
    workedExample: {
      problem:
        'Một tụ điện có điện dung C = 10 μF được tích điện dưới hiệu điện thế U = 12 V. ' +
        'Tính điện tích Q mà tụ điện tích được và năng lượng điện trường W của tụ điện.',
      steps: [
        'Đổi điện dung sang đơn vị chuẩn F: C = 10 μF = 10 * 10⁻⁶ F = 10⁻⁵ F.',
        'Tính điện tích Q tích được: Q = C * U = 10⁻⁵ * 12 = 1,2 * 10⁻⁴ C.',
        'Tính năng lượng điện trường W của tụ: W = 1/2.C.U² = 0,5 * 10⁻⁵ * 12² = 0,5 * 10⁻⁵ * 144 = 7,2 * 10⁻⁴ J.',
      ],
      answer: 'Q = 1,2 * 10⁻⁴ C; W = 7,2 * 10⁻⁴ J.',
    },
    checkQuestions: [
      {
        prompt:
          'Viết công thức liên hệ giữa điện tích Q, điện dung C và hiệu điện thế U của một tụ điện.',
        choices: [
          { id: 'cap_1', label: 'Q = C * U' },
          { id: 'cap_2', label: 'Q = C / U' },
          { id: 'cap_3', label: 'C = Q * U' },
        ],
        answer: {
          kind: 'choice',
          correctIds: ['cap_1'],
        },
        explain:
          'Điện tích tích được tỉ lệ thuận với hiệu điện thế qua hệ số tỉ lệ điện dung C: Q = CU.',
      },
      {
        prompt:
          'Một tụ điện có điện dung C = 2 * 10⁻⁶ F (2 μF) được nối vào nguồn điện có hiệu điện thế U = 50 V. Tính năng lượng điện trường tích luỹ trong tụ điện.',
        answer: {
          kind: 'numeric',
          value: 0.0025,
          unit: 'J',
        },
        explain: 'W = 1/2.C.U² = 0,5 * (2 * 10⁻⁶) * 50² = 10⁻⁶ * 2500 = 0,0025 J.',
      },
    ],
    srsCards: [
      {
        hoi: 'Cấu tạo cơ bản của tụ điện là gì?',
        dap: 'Gồm hai vật dẫn đặt song song gần nhau và cách điện với nhau bằng một lớp điện môi.',
      },
      {
        hoi: 'Nêu công thức liên hệ giữa năng lượng điện trường W tích tụ với điện tích Q và điện dung C.',
        dap: 'W = 1/2 * Q² / C.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
]
