// lessons/ly12c3.ts — Vật lí 12, Chương 3: Từ trường (8 bài).
import type { PhysicsLesson } from '../lessonTypes.js'

export const LY12_C3_LESSONS: PhysicsLesson[] = [
  {
    id: 'ly12-c3-b12',
    animation: {
      title: 'Đường sức từ và cách kim la bàn chỉ ra chúng',
      description:
        'Thanh nam châm ở giữa có cực Bắc (N) bên phải, cực Nam (S) bên trái. Các đường cong khép kín bao quanh là đường sức từ: quy ước chúng đi ra từ cực Bắc, vòng ra ngoài không gian rồi đi vào cực Nam. Ba kim la bàn đặt ở ba vị trí khác nhau lần lượt xoay về đúng phương tiếp tuyến của đường sức đi qua chỗ nó đứng, đầu đỏ chỉ theo chiều của đường sức — đó là cách ta "nhìn thấy" một trường vốn vô hình. Nơi các đường sức dày hơn (sát hai cực) là nơi từ trường mạnh hơn, kim quay về vị trí cân bằng dứt khoát hơn.',
      viewBoxWidth: 460,
      viewBoxHeight: 240,
      durationMs: 3000,
      loop: true,
      shapes: [
        {
          kind: 'rect',
          id: 'nc-s',
          x: 160,
          y: 105,
          w: 70,
          h: 34,
          fill: 'primary',
        },
        {
          kind: 'rect',
          id: 'nc-n',
          x: 230,
          y: 105,
          w: 70,
          h: 34,
          fill: 'danger',
        },
        {
          kind: 'label',
          id: 'l-s',
          x: 195,
          y: 128,
          text: 'S',
          size: 18,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'label',
          id: 'l-n',
          x: 265,
          y: 128,
          text: 'N',
          size: 18,
          anchor: 'middle',
          fill: 'surface',
        },
        {
          kind: 'polyline',
          id: 'ds0',
          points: [
            [195.0, 122.0],
            [195.3, 124.4],
            [196.0, 126.8],
            [197.3, 129.1],
            [199.0, 131.3],
            [201.2, 133.4],
            [203.8, 135.3],
            [206.8, 137.0],
            [210.1, 138.5],
            [213.7, 139.7],
            [217.6, 140.7],
            [221.6, 141.4],
            [225.8, 141.9],
            [230.0, 142.0],
            [234.2, 141.9],
            [238.4, 141.4],
            [242.4, 140.7],
            [246.3, 139.7],
            [249.9, 138.5],
            [253.2, 137.0],
            [256.2, 135.3],
            [258.8, 133.4],
            [261.0, 131.3],
            [262.7, 129.1],
            [264.0, 126.8],
            [264.7, 124.4],
            [265.0, 122.0],
            [264.7, 119.6],
            [264.0, 117.2],
            [262.7, 114.9],
            [261.0, 112.7],
            [258.8, 110.6],
            [256.2, 108.7],
            [253.2, 107.0],
            [249.9, 105.5],
            [246.3, 104.3],
            [242.4, 103.3],
            [238.4, 102.6],
            [234.2, 102.1],
            [230.0, 102.0],
            [225.8, 102.1],
            [221.6, 102.6],
            [217.6, 103.3],
            [213.7, 104.3],
            [210.1, 105.5],
            [206.8, 107.0],
            [203.8, 108.7],
            [201.2, 110.6],
            [199.0, 112.7],
            [197.3, 114.9],
            [196.0, 117.2],
            [195.3, 119.6],
            [195.0, 122.0],
          ],
          stroke: 'muted',
          strokeWidth: 1.8,
        },
        {
          kind: 'polyline',
          id: 'ds1',
          points: [
            [140.0, 122.0],
            [140.7, 129.5],
            [142.6, 136.8],
            [145.8, 144.0],
            [150.3, 150.8],
            [155.9, 157.2],
            [162.6, 163.1],
            [170.3, 168.4],
            [178.9, 173.0],
            [188.2, 176.9],
            [198.1, 180.0],
            [208.5, 182.2],
            [219.2, 183.5],
            [230.0, 184.0],
            [240.8, 183.5],
            [251.5, 182.2],
            [261.9, 180.0],
            [271.8, 176.9],
            [281.1, 173.0],
            [289.7, 168.4],
            [297.4, 163.1],
            [304.1, 157.2],
            [309.7, 150.8],
            [314.2, 144.0],
            [317.4, 136.8],
            [319.3, 129.5],
            [320.0, 122.0],
            [319.3, 114.5],
            [317.4, 107.2],
            [314.2, 100.0],
            [309.7, 93.2],
            [304.1, 86.8],
            [297.4, 80.9],
            [289.7, 75.6],
            [281.1, 71.0],
            [271.8, 67.1],
            [261.9, 64.0],
            [251.5, 61.8],
            [240.8, 60.5],
            [230.0, 60.0],
            [219.2, 60.5],
            [208.5, 61.8],
            [198.1, 64.0],
            [188.2, 67.1],
            [178.9, 71.0],
            [170.3, 75.6],
            [162.6, 80.9],
            [155.9, 86.8],
            [150.3, 93.2],
            [145.8, 100.0],
            [142.6, 107.2],
            [140.7, 114.5],
            [140.0, 122.0],
          ],
          stroke: 'muted',
          strokeWidth: 1.8,
        },
        {
          kind: 'polyline',
          id: 'ds2',
          points: [
            [85.0, 122.0],
            [86.1, 134.5],
            [89.2, 146.9],
            [94.4, 158.9],
            [101.6, 170.3],
            [110.7, 181.1],
            [121.5, 191.0],
            [133.8, 199.8],
            [147.6, 207.6],
            [162.6, 214.1],
            [178.6, 219.2],
            [195.3, 223.0],
            [212.5, 225.2],
            [230.0, 226.0],
            [247.5, 225.2],
            [264.7, 223.0],
            [281.4, 219.2],
            [297.4, 214.1],
            [312.4, 207.6],
            [326.2, 199.8],
            [338.5, 191.0],
            [349.3, 181.1],
            [358.4, 170.3],
            [365.6, 158.9],
            [370.8, 146.9],
            [373.9, 134.5],
            [375.0, 122.0],
            [373.9, 109.5],
            [370.8, 97.1],
            [365.6, 85.1],
            [358.4, 73.7],
            [349.3, 62.9],
            [338.5, 53.0],
            [326.2, 44.2],
            [312.4, 36.4],
            [297.4, 29.9],
            [281.4, 24.8],
            [264.7, 21.0],
            [247.5, 18.8],
            [230.0, 18.0],
            [212.5, 18.8],
            [195.3, 21.0],
            [178.6, 24.8],
            [162.6, 29.9],
            [147.6, 36.4],
            [133.8, 44.2],
            [121.5, 53.0],
            [110.7, 62.9],
            [101.6, 73.7],
            [94.4, 85.1],
            [89.2, 97.1],
            [86.1, 109.5],
            [85.0, 122.0],
          ],
          stroke: 'muted',
          strokeWidth: 1.8,
        },
        {
          kind: 'polyline',
          id: 'dsd0',
          points: [
            [195.0, 122.0],
            [195.3, 119.6],
            [196.0, 117.2],
            [197.3, 114.9],
            [199.0, 112.7],
            [201.2, 110.6],
            [203.8, 108.7],
            [206.8, 107.0],
            [210.1, 105.5],
            [213.7, 104.3],
            [217.6, 103.3],
            [221.6, 102.6],
            [225.8, 102.1],
            [230.0, 102.0],
            [234.2, 102.1],
            [238.4, 102.6],
            [242.4, 103.3],
            [246.3, 104.3],
            [249.9, 105.5],
            [253.2, 107.0],
            [256.2, 108.7],
            [258.8, 110.6],
            [261.0, 112.7],
            [262.7, 114.9],
            [264.0, 117.2],
            [264.7, 119.6],
            [265.0, 122.0],
            [264.7, 124.4],
            [264.0, 126.8],
            [262.7, 129.1],
            [261.0, 131.3],
            [258.8, 133.4],
            [256.2, 135.3],
            [253.2, 137.0],
            [249.9, 138.5],
            [246.3, 139.7],
            [242.4, 140.7],
            [238.4, 141.4],
            [234.2, 141.9],
            [230.0, 142.0],
            [225.8, 141.9],
            [221.6, 141.4],
            [217.6, 140.7],
            [213.7, 139.7],
            [210.1, 138.5],
            [206.8, 137.0],
            [203.8, 135.3],
            [201.2, 133.4],
            [199.0, 131.3],
            [197.3, 129.1],
            [196.0, 126.8],
            [195.3, 124.4],
            [195.0, 122.0],
          ],
          stroke: 'muted',
          strokeWidth: 1.8,
        },
        {
          kind: 'polyline',
          id: 'dsd1',
          points: [
            [140.0, 122.0],
            [140.7, 114.5],
            [142.6, 107.2],
            [145.8, 100.0],
            [150.3, 93.2],
            [155.9, 86.8],
            [162.6, 80.9],
            [170.3, 75.6],
            [178.9, 71.0],
            [188.2, 67.1],
            [198.1, 64.0],
            [208.5, 61.8],
            [219.2, 60.5],
            [230.0, 60.0],
            [240.8, 60.5],
            [251.5, 61.8],
            [261.9, 64.0],
            [271.8, 67.1],
            [281.1, 71.0],
            [289.7, 75.6],
            [297.4, 80.9],
            [304.1, 86.8],
            [309.7, 93.2],
            [314.2, 100.0],
            [317.4, 107.2],
            [319.3, 114.5],
            [320.0, 122.0],
            [319.3, 129.5],
            [317.4, 136.8],
            [314.2, 144.0],
            [309.7, 150.8],
            [304.1, 157.2],
            [297.4, 163.1],
            [289.7, 168.4],
            [281.1, 173.0],
            [271.8, 176.9],
            [261.9, 180.0],
            [251.5, 182.2],
            [240.8, 183.5],
            [230.0, 184.0],
            [219.2, 183.5],
            [208.5, 182.2],
            [198.1, 180.0],
            [188.2, 176.9],
            [178.9, 173.0],
            [170.3, 168.4],
            [162.6, 163.1],
            [155.9, 157.2],
            [150.3, 150.8],
            [145.8, 144.0],
            [142.6, 136.8],
            [140.7, 129.5],
            [140.0, 122.0],
          ],
          stroke: 'muted',
          strokeWidth: 1.8,
        },
        {
          kind: 'polyline',
          id: 'dsd2',
          points: [
            [85.0, 122.0],
            [86.1, 109.5],
            [89.2, 97.1],
            [94.4, 85.1],
            [101.6, 73.7],
            [110.7, 62.9],
            [121.5, 53.0],
            [133.8, 44.2],
            [147.6, 36.4],
            [162.6, 29.9],
            [178.6, 24.8],
            [195.3, 21.0],
            [212.5, 18.8],
            [230.0, 18.0],
            [247.5, 18.8],
            [264.7, 21.0],
            [281.4, 24.8],
            [297.4, 29.9],
            [312.4, 36.4],
            [326.2, 44.2],
            [338.5, 53.0],
            [349.3, 62.9],
            [358.4, 73.7],
            [365.6, 85.1],
            [370.8, 97.1],
            [373.9, 109.5],
            [375.0, 122.0],
            [373.9, 134.5],
            [370.8, 146.9],
            [365.6, 158.9],
            [358.4, 170.3],
            [349.3, 181.1],
            [338.5, 191.0],
            [326.2, 199.8],
            [312.4, 207.6],
            [297.4, 214.1],
            [281.4, 219.2],
            [264.7, 223.0],
            [247.5, 225.2],
            [230.0, 226.0],
            [212.5, 225.2],
            [195.3, 223.0],
            [178.6, 219.2],
            [162.6, 214.1],
            [147.6, 207.6],
            [133.8, 199.8],
            [121.5, 191.0],
            [110.7, 181.1],
            [101.6, 170.3],
            [94.4, 158.9],
            [89.2, 146.9],
            [86.1, 134.5],
            [85.0, 122.0],
          ],
          stroke: 'muted',
          strokeWidth: 1.8,
        },
        {
          kind: 'circle',
          id: 'kim-o1',
          cx: 230,
          cy: 40,
          r: 12,
          stroke: 'neutral',
          strokeWidth: 1.5,
        },
        {
          kind: 'line',
          id: 'kim1',
          x1: 218,
          y1: 48,
          x2: 242,
          y2: 32,
          stroke: 'danger',
          strokeWidth: 3,
          keyframes: [
            {
              atMs: 0,
              rotate: 70,
            },
            {
              atMs: 1800,
              rotate: 0,
            },
            {
              atMs: 3000,
              rotate: 0,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'kim-o2',
          cx: 360,
          cy: 122,
          r: 12,
          stroke: 'neutral',
          strokeWidth: 1.5,
        },
        {
          kind: 'line',
          id: 'kim2',
          x1: 348,
          y1: 130,
          x2: 372,
          y2: 114,
          stroke: 'danger',
          strokeWidth: 3,
          keyframes: [
            {
              atMs: 0,
              rotate: -80,
            },
            {
              atMs: 1800,
              rotate: 16,
            },
            {
              atMs: 3000,
              rotate: 16,
            },
          ],
        },
        {
          kind: 'circle',
          id: 'kim-o3',
          cx: 230,
          cy: 205,
          r: 12,
          stroke: 'neutral',
          strokeWidth: 1.5,
        },
        {
          kind: 'line',
          id: 'kim3',
          x1: 218,
          y1: 197,
          x2: 242,
          y2: 213,
          stroke: 'danger',
          strokeWidth: 3,
          keyframes: [
            {
              atMs: 0,
              rotate: 110,
            },
            {
              atMs: 1800,
              rotate: 0,
            },
            {
              atMs: 3000,
              rotate: 0,
            },
          ],
        },
        {
          kind: 'label',
          id: 'ghi',
          x: 230,
          y: 232,
          text: 'kim la bàn nằm theo tiếp tuyến đường sức',
          size: 12,
          anchor: 'middle',
          fill: 'muted',
        },
      ],
    },
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Từ trường',
    lessonNumber: 12,
    title: 'Đại cương về từ trường',
    hook:
      'Một cây kim la bàn luôn tự động quay về hướng Bắc, và hai thanh nam châm có thể đẩy hoặc hút nhau từ xa mà không cần tiếp xúc. ' +
      'Lực vô hình nào đã kết nối chúng? Đó chính là từ trường.',
    theory:
      'KHÁI NIỆM TỪ TRƯỜNG:\n' +
      '— Từ trường: Là một dạng vật chất tồn tại xung quanh nam châm, dòng điện hoặc hạt mang điện chuyển động, biểu hiện bằng việc tác dụng lực từ lên nam châm, dòng điện hoặc hạt mang điện chuyển động khác đặt trong nó.\n' +
      '— Tương tác từ: Tương tác giữa nam châm với nam châm, giữa nam châm với dòng điện, và giữa hai dòng điện với nhau.\n\n' +
      'ĐƯỜNG SỨC TỪ:\n' +
      '— Đường sức từ: Là những đường vẽ trong không gian có từ trường, sao cho tiếp tuyến tại mỗi điểm trùng với hướng của từ trường tại điểm đó.\n' +
      '— Các đặc điểm của đường sức từ:\n' +
      '  1. Qua mỗi điểm trong không gian chỉ vẽ được một đường sức từ duy nhất.\n' +
      '  2. Các đường sức từ là những đường cong khép kín hoặc vô hạn ở hai đầu.\n' +
      '  3. Quy ước chiều đường sức từ: Đi ra từ cực Bắc (N) và đi vào cực Nam (S) của nam châm.\n' +
      '  4. Nơi nào từ trường mạnh thì đường sức từ vẽ dày, nơi nào từ trường yếu thì đường sức từ vẽ thưa.\n\n' +
      'TỪ PHỔ:\n' +
      '— Từ phổ: Hình ảnh các đường sức từ được hình thành bởi các mạt sắt rắc trên tấm phẳng đặt trong từ trường. Từ phổ giúp ta hình dung trực quan hình dạng của từ trường.',
    workedExample: {
      problem: 'Trình bày đặc điểm và chiều của đường sức từ bên ngoài một thanh nam châm thẳng.',
      steps: [
        'Nhận xét hình dạng: Các đường sức từ bên ngoài thanh nam châm thẳng là những đường cong khép kín.',
        'Mô tả chiều: Đi ra khỏi cực Bắc (North - N) và đi vào cực Nam (South - S).',
        'Nhận xét độ dày thưa: Đường sức từ dày nhất ở gần hai cực của nam châm (nơi từ trường mạnh nhất) và thưa dần khi ra xa.',
      ],
      answer: 'Là đường cong khép kín đi ra từ cực Bắc (N) và đi vào cực Nam (S) của nam châm.',
    },
    checkQuestions: [
      {
        prompt: 'Từ trường không tồn tại xung quanh đối tượng nào sau đây?',
        choices: [
          { id: 'tt_1', label: 'Một điện tích đứng yên' },
          { id: 'tt_2', label: 'Một dòng điện chạy trong dây dẫn' },
          { id: 'tt_3', label: 'Một thanh nam châm' },
          { id: 'tt_4', label: 'Một hạt electron đang bay' },
        ],
        answer: {
          kind: 'choice',
          correctIds: ['tt_1'],
        },
        explain:
          'Từ trường chỉ tồn tại xung quanh nam châm, dòng điện hoặc điện tích chuyển động. Điện tích đứng yên chỉ tạo ra điện trường.',
      },
      {
        prompt: 'Theo quy ước, chiều của đường sức từ bên ngoài thanh nam châm là:',
        choices: [
          { id: 'ch_1', label: 'Ra ở cực Bắc, vào ở cực Nam' },
          { id: 'ch_2', label: 'Ra ở cực Nam, vào ở cực Bắc' },
          { id: 'ch_3', label: 'Đi từ cực âm sang cực dương' },
          { id: 'ch_4', label: 'Đi từ trung tâm ra hai cực' },
        ],
        answer: {
          kind: 'choice',
          correctIds: ['ch_1'],
        },
        explain:
          'Quy ước chiều đường sức từ của nam châm là đi ra từ cực Bắc (North) và đi vào ở cực Nam (South).',
      },
    ],
    srsCards: [
      {
        hoi: 'Từ trường là gì?',
        dap: 'Là một dạng vật chất tồn tại xung quanh nam châm, dòng điện hoặc hạt mang điện chuyển động, biểu hiện bằng lực từ.',
      },
      {
        hoi: 'Quy ước chiều đường sức từ bên ngoài nam châm?',
        dap: 'Đi ra từ cực Bắc (N) và đi vào cực Nam (S).',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'ly12-c3-b13',
    animation: {
      title: 'Quy tắc bàn tay trái: ba đại lượng vuông góc từng đôi',
      description:
        'Một đoạn dây dẫn mang dòng điện I (mũi tên nằm ngang, màu chính) được đặt trong từ trường đều B. Các dấu × rải trên nền cho biết B hướng vuông góc với mặt phẳng hình vẽ, đi từ ngoài vào trong trang giấy. Lực từ F tác dụng lên đoạn dây (mũi tên thẳng đứng) vuông góc với CẢ I lẫn B, độ lớn F = B·I·L·sinα với α là góc giữa dây và B. Khi đoạn dây quay dần cho song song với B — lúc α về 0 — mũi tên lực co ngắn lại rồi biến mất: dây song song với đường sức thì không chịu lực từ. Đây là lí do sinα có mặt trong công thức, và cũng là nguyên lí quay của động cơ điện.',
      viewBoxWidth: 440,
      viewBoxHeight: 240,
      durationMs: 4000,
      loop: true,
      shapes: [
        {
          kind: 'label',
          id: 'bx0',
          x: 50,
          y: 50,
          text: '×',
          size: 16,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'bx1',
          x: 110,
          y: 50,
          text: '×',
          size: 16,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'bx2',
          x: 170,
          y: 50,
          text: '×',
          size: 16,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'bx3',
          x: 230,
          y: 50,
          text: '×',
          size: 16,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'bx4',
          x: 290,
          y: 50,
          text: '×',
          size: 16,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'bx5',
          x: 350,
          y: 50,
          text: '×',
          size: 16,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'bx6',
          x: 50,
          y: 110,
          text: '×',
          size: 16,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'bx7',
          x: 110,
          y: 110,
          text: '×',
          size: 16,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'bx8',
          x: 170,
          y: 110,
          text: '×',
          size: 16,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'bx9',
          x: 230,
          y: 110,
          text: '×',
          size: 16,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'bx10',
          x: 290,
          y: 110,
          text: '×',
          size: 16,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'bx11',
          x: 350,
          y: 110,
          text: '×',
          size: 16,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'bx12',
          x: 50,
          y: 170,
          text: '×',
          size: 16,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'bx13',
          x: 110,
          y: 170,
          text: '×',
          size: 16,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'bx14',
          x: 170,
          y: 170,
          text: '×',
          size: 16,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'bx15',
          x: 230,
          y: 170,
          text: '×',
          size: 16,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'bx16',
          x: 290,
          y: 170,
          text: '×',
          size: 16,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'bx17',
          x: 350,
          y: 170,
          text: '×',
          size: 16,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'arrow',
          id: 'day',
          x1: 110,
          y1: 140,
          x2: 300,
          y2: 140,
          stroke: 'primary',
          strokeWidth: 4,
          keyframes: [
            {
              atMs: 0,
              rotate: 0,
            },
            {
              atMs: 2500,
              rotate: 0,
            },
            {
              atMs: 4000,
              rotate: -62,
            },
          ],
        },
        {
          kind: 'label',
          id: 'n-i',
          x: 205,
          y: 162,
          text: 'I',
          size: 16,
          anchor: 'middle',
          fill: 'primary',
        },
        {
          kind: 'arrow',
          id: 'luc',
          x1: 205,
          y1: 140,
          x2: 205,
          y2: 60,
          stroke: 'danger',
          strokeWidth: 4,
          keyframes: [
            {
              atMs: 0,
              scale: 1,
            },
            {
              atMs: 2500,
              scale: 1,
            },
            {
              atMs: 4000,
              scale: 0.1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'n-f',
          x: 224,
          y: 88,
          text: 'F = B·I·L·sinα',
          size: 13,
          anchor: 'start',
          fill: 'neutral',
        },
        {
          kind: 'label',
          id: 'n-b',
          x: 60,
          y: 226,
          text: 'B ⊥ mặt phẳng hình vẽ, hướng vào trong (dấu ×)',
          size: 12,
          anchor: 'start',
          fill: 'muted',
        },
      ],
      captions: [
        {
          atMs: 0,
          text: 'Dây vuông góc với B: lực từ lớn nhất',
        },
        {
          atMs: 2600,
          text: 'Quay dây về song song với B: lực từ giảm rồi triệt tiêu',
        },
      ],
    },
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Từ trường',
    lessonNumber: 13,
    title: 'Lực từ. Cảm ứng từ',
    hook:
      'Làm thế nào để tạo ra chuyển động quay của động cơ điện trong quạt hay máy bơm? ' +
      'Tất cả hoạt động dựa trên lực từ tác dụng lên dây dẫn có dòng điện chạy qua đặt trong từ trường.',
    theory:
      'LỰC TỪ TÁC DỤNG LÊN ĐOẠN DÂY DẪN THẲNG MANG DÒNG ĐIỆN:\n' +
      'Một đoạn dây dẫn thẳng có chiều dài L, mang dòng điện I, đặt trong từ trường đều có cảm ứng từ B, chịu tác dụng của lực từ F:\n' +
      '— Độ lớn (Công thức Ampere):\n' +
      '  F = B * I * L * sin(theta)\n' +
      'Trong đó theta là góc hợp bởi chiều dòng điện (hướng của dây) và chiều cảm ứng từ B.\n' +
      '— Chiều: Xác định theo Quy tắc bàn tay trái:\n' +
      '  + Đặt bàn tay trái sao cho các đường sức từ đâm vào lòng bàn tay.\n' +
      '  + Chiều từ cổ tay đến ngón tay giữa trùng với chiều dòng điện.\n' +
      '  + Ngón tay cái choãi ra 90 độ chỉ chiều của lực từ F.\n\n' +
      'CẢM ỨNG TỪ:\n' +
      '— Cảm ứng từ (B): Đại lượng vectơ đặc trưng cho từ trường về phương diện tác dụng lực. Vectơ cảm ứng từ B có:\n' +
      '  + Phương: Trùng với phương của nam châm thử cân bằng tại điểm đó.\n' +
      '  + Chiều: Từ cực Nam sang cực Bắc của nam châm thử.\n' +
      '— Đơn vị: Tesla (T).',
    workedExample: {
      problem:
        'Một đoạn dây dẫn thẳng dài 0.5 m mang dòng điện 2 A đặt vuông góc với một từ trường đều có cảm ứng từ B = 0.4 T. ' +
        'Tính độ lớn của lực từ tác dụng lên đoạn dây.',
      steps: [
        'Xác định các thông số: L = 0.5 m, I = 2 A, B = 0.4 T.',
        'Xác định góc theta: Vì đặt vuông góc nên theta = 90 độ, sin(theta) = 1.',
        'Áp dụng công thức F = B * I * L * sin(theta).',
        'Tính toán: F = 0.4 * 2 * 0.5 * 1 = 0.4 N.',
      ],
      answer: 'F = 0.4 N.',
    },
    checkQuestions: [
      {
        prompt: 'Đơn vị đo cảm ứng từ B trong hệ SI là:',
        choices: [
          { id: 'b_1', label: 'Tesla (T)' },
          { id: 'b_2', label: 'Weber (Wb)' },
          { id: 'b_3', label: 'Henry (H)' },
          { id: 'b_4', label: 'Ampere (A)' },
        ],
        answer: {
          kind: 'choice',
          correctIds: ['b_1'],
        },
        explain:
          'Đơn vị đo cảm ứng từ B là Tesla (T). Weber (Wb) là đơn vị từ thông, Henry (H) là độ tự cảm.',
      },
      {
        prompt:
          'Một đoạn dây dẫn thẳng dài 0.2 m mang dòng điện 5 A đặt song song với các đường sức từ của một từ trường đều có B = 0.5 T. ' +
          'Tính độ lớn lực từ (theo đơn vị N) tác dụng lên đoạn dây dẫn.',
        answer: {
          kind: 'numeric',
          value: 0,
          unit: 'N',
        },
        explain:
          'Khi dây dẫn đặt song song với đường sức từ, góc theta = 0 hoặc 180 độ. Khi đó sin(theta) = 0 => F = B * I * L * sin(theta) = 0 N.',
      },
    ],
    srsCards: [
      {
        hoi: 'Viết công thức tính độ lớn lực từ tác dụng lên đoạn dây dẫn thẳng?',
        dap: 'F = B * I * L * sin(theta).',
      },
      {
        hoi: 'Độ lớn lực từ bằng 0 khi góc theta giữa dòng điện và B bằng bao nhiêu?',
        dap: 'Bằng 0 độ hoặc 180 độ (dây dẫn đặt song song đường sức từ).',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'ly12-c3-b14',
    animation: {
      title: 'Từ trường của dòng điện thẳng: những vòng tròn đồng tâm',
      description:
        'Dây dẫn thẳng dài đặt vuông góc với trang giấy, dấu chấm ở tâm cho biết dòng điện I hướng từ trong ra phía người xem. Đường sức từ do dòng điện này sinh ra là các đường TRÒN đồng tâm nằm trong mặt phẳng vuông góc với dây, tâm nằm ngay trên dây — khác hẳn đường sức của nam châm thẳng vốn đi từ cực này sang cực kia. Chiều của chúng xác định bằng quy tắc nắm tay phải: ngón cái chỉ theo chiều dòng điện thì bốn ngón khum lại chỉ chiều đường sức, ở đây là ngược chiều kim đồng hồ. Càng xa dây thì vòng càng thưa vì cảm ứng từ giảm theo B = 2·10⁻⁷·I/r, tỉ lệ nghịch với khoảng cách.',
      viewBoxWidth: 420,
      viewBoxHeight: 240,
      durationMs: 3000,
      loop: true,
      shapes: [
        {
          kind: 'circle',
          id: 'day-tron',
          cx: 210,
          cy: 120,
          r: 10,
          stroke: 'primary',
          strokeWidth: 3,
        },
        {
          kind: 'circle',
          id: 'cham',
          cx: 210,
          cy: 120,
          r: 4,
          fill: 'primary',
        },
        {
          kind: 'label',
          id: 'n-i2',
          x: 210,
          y: 100,
          text: 'I hướng ra',
          size: 12,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'circle',
          id: 'v0',
          cx: 210,
          cy: 120,
          r: 30,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'circle',
          id: 'v1',
          cx: 210,
          cy: 120,
          r: 58,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'circle',
          id: 'v2',
          cx: 210,
          cy: 120,
          r: 86,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'circle',
          id: 'v3',
          cx: 210,
          cy: 120,
          r: 114,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'circle',
          id: 'hat',
          cx: 210,
          cy: 90,
          r: 6,
          fill: 'accent',
          keyframes: [
            {
              atMs: 0,
              rotate: 0,
            },
            {
              atMs: 3000,
              rotate: 360,
            },
          ],
        },
        {
          kind: 'arrow',
          id: 'mt1',
          x1: 240,
          y1: 120,
          x2: 240,
          y2: 96,
          stroke: 'accent',
          strokeWidth: 2.5,
        },
        {
          kind: 'arrow',
          id: 'mt2',
          x1: 180,
          y1: 120,
          x2: 180,
          y2: 144,
          stroke: 'accent',
          strokeWidth: 2.5,
        },
        {
          kind: 'label',
          id: 'n-qt',
          x: 210,
          y: 226,
          text: 'quy tắc nắm tay phải · B = 2·10⁻⁷·I/r',
          size: 13,
          anchor: 'middle',
          fill: 'primary',
        },
        {
          kind: 'label',
          id: 'n-thua',
          x: 210,
          y: 205,
          text: 'càng xa dây, vòng càng thưa: từ trường yếu dần',
          size: 11,
          anchor: 'middle',
          fill: 'muted',
        },
      ],
    },
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Từ trường',
    lessonNumber: 14,
    title: 'Từ trường của dòng điện chạy trong các dây dẫn có hình dạng đặc biệt',
    hook:
      'Mỗi hình dạng dây dẫn khác nhau khi mang dòng điện sẽ tạo ra các đường sức từ có hình dạng và độ lớn khác nhau. ' +
      'Nắm vững các công thức này là nền tảng thiết kế các nam châm điện dùng trong công nghiệp.',
    theory:
      'TỪ TRƯỜNG CỦA DÒNG ĐIỆN TRONG DÂY DẪN THẲNG DÀI VÔ HẠN:\n' +
      '— Các đường sức từ là những đường tròn đồng tâm nằm trong mặt phẳng vuông góc với dây dẫn, tâm nằm trên dây dẫn.\n' +
      '— Chiều đường sức từ xác định bằng Quy tắc nắm tay phải.\n' +
      '— Độ lớn cảm ứng từ tại điểm cách dây dẫn khoảng cách r:\n' +
      '  B = 2 * 10⁻⁷ * I / r\n\n' +
      'TỪ TRƯỜNG CỦA DÒNG ĐIỆN TRONG DÂY DẪN UỐN THÀNH VÒNG TRÒN:\n' +
      '— Độ lớn cảm ứng từ tại tâm của vòng tròn bán kính R gồm N vòng dây quấn sát:\n' +
      '  B = 2pi * 10⁻⁷ * N * I / R\n\n' +
      'TỪ TRƯỜNG CỦA DÒNG ĐIỆN TRONG ỐNG DÂY HÌNH TRỤ (SOLENOID):\n' +
      '— Từ trường bên trong lòng ống dây là từ trường đều, các đường sức từ thẳng song song đều nhau.\n' +
      '— Độ lớn cảm ứng từ bên trong lòng ống dây dài L có N vòng dây:\n' +
      '  B = 4pi * 10⁻⁷ * (N / L) * I = 4pi * 10⁻⁷ * n * I\n' +
      'Trong đó n = N/L là mật độ vòng dây.',
    workedExample: {
      problem:
        'Một dòng điện có cường độ 5 A chạy qua dây dẫn thẳng dài đặt trong không khí. ' +
        'Tính độ lớn cảm ứng từ tại một điểm cách dây dẫn 10 cm (0.1 m).',
      steps: [
        'Xác định thông số: I = 5 A, r = 10 cm = 0.1 m.',
        'Áp dụng công thức cảm ứng từ của dây dẫn thẳng dài: B = 2 * 10^-7 * I / r.',
        'Thay số: B = 2 * 10^-7 * 5 / 0.1.',
        'Tính toán: B = 10^-5 T.',
      ],
      answer: 'B = 10^-5 T.',
    },
    checkQuestions: [
      {
        prompt:
          'Để tính độ lớn cảm ứng từ tại một điểm cách dây dẫn thẳng dài mang dòng điện I một khoảng r, ta dùng công thức nào?',
        choices: [
          { id: 'f_1', label: 'B = 2.10^-7 * I / r' },
          { id: 'f_2', label: 'B = 2pi.10^-7 * I / r' },
          { id: 'f_3', label: 'B = 4pi.10^-7 * I / r' },
          { id: 'f_4', label: 'B = 2.10^-7 * I * r' },
        ],
        answer: {
          kind: 'choice',
          correctIds: ['f_1'],
        },
        explain: 'Công thức cảm ứng từ của dây dẫn thẳng dài là B = 2*10^-7 * I / r.',
      },
      {
        prompt:
          'Một ống dây hình trụ dài 0.5 m có 500 vòng dây. Khi có dòng điện cường độ 2 A chạy qua ống dây, ' +
          'độ lớn cảm ứng từ bên trong lòng ống dây xấp xỉ bằng bao nhiêu (lấy pi = 3.14)?',
        choices: [
          { id: 'o_1', label: '2.51e-3 T' },
          { id: 'o_2', label: '1.26e-3 T' },
          { id: 'o_3', label: '5.02e-3 T' },
          { id: 'o_4', label: '2.51e-4 T' },
        ],
        answer: {
          kind: 'choice',
          correctIds: ['o_1'],
        },
        explain:
          'B = 4 * pi * 10^-7 * N * I / L = 4 * 3.14 * 10^-7 * 500 * 2 / 0.5 = 2.512 * 10^-3 T.',
      },
    ],
    srsCards: [
      {
        hoi: 'Công thức tính cảm ứng từ của dòng điện chạy trong dây dẫn thẳng dài?',
        dap: 'B = 2 * 10^-7 * I / r.',
      },
      {
        hoi: 'Công thức tính cảm ứng từ tại tâm vòng tròn dây dẫn?',
        dap: 'B = 2pi * 10^-7 * N * I / R.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'ly12-c3-b15',
    // Vì sao hạt mang điện đi vòng tròn trong từ trường đều: lực Lorentz luôn vuông góc vận tốc
    // nên chỉ bẻ hướng, không làm hạt nhanh hay chậm đi.
    animation: {
      title: 'Hạt mang điện bay vào từ trường đều thì đi theo đường tròn',
      description:
        'Các dấu × rải đều trên hình biểu diễn từ trường đều B hướng vuông góc với mặt phẳng hình vẽ và đi từ ngoài vào trong trang giấy. Một hạt mang điện dương bay vào vùng từ trường này với vận tốc v vuông góc với B. Lực Lorentz f = q·v·B·sinα luôn vuông góc với cả v và B, nghĩa là nó luôn vuông góc với hướng đi của hạt: mũi tên lực (nét ngắn) luôn chỉ vào tâm đường tròn, còn mũi tên vận tốc luôn nằm theo tiếp tuyến. Lực vuông góc với đường đi thì KHÔNG sinh công, nên tốc độ của hạt không đổi, chỉ có hướng đổi liên tục — đúng điều kiện của chuyển động tròn đều. Cân bằng lực hướng tâm qvB = mv²/R cho bán kính quỹ đạo R = mv/(qB): hạt càng nặng hoặc bay càng nhanh thì vòng càng rộng, từ trường càng mạnh thì vòng càng hẹp. Nếu hạt mang điện âm, nó sẽ vòng theo chiều ngược lại với cùng bán kính đó.',
      viewBoxWidth: 420,
      viewBoxHeight: 240,
      durationMs: 4000,
      loop: true,
      shapes: [
        {
          kind: 'label',
          id: 'b-1',
          x: 40,
          y: 40,
          text: '×',
          size: 18,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'b-2',
          x: 110,
          y: 40,
          text: '×',
          size: 18,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'b-3',
          x: 180,
          y: 40,
          text: '×',
          size: 18,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'b-4',
          x: 250,
          y: 40,
          text: '×',
          size: 18,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'b-5',
          x: 40,
          y: 110,
          text: '×',
          size: 18,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'b-6',
          x: 110,
          y: 110,
          text: '×',
          size: 18,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'b-7',
          x: 180,
          y: 110,
          text: '×',
          size: 18,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'b-8',
          x: 250,
          y: 110,
          text: '×',
          size: 18,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'b-9',
          x: 40,
          y: 180,
          text: '×',
          size: 18,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'b-10',
          x: 110,
          y: 180,
          text: '×',
          size: 18,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'b-11',
          x: 180,
          y: 180,
          text: '×',
          size: 18,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'b-12',
          x: 250,
          y: 180,
          text: '×',
          size: 18,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'circle',
          id: 'quy-dao-tron',
          cx: 120,
          cy: 100,
          r: 80,
          stroke: 'muted',
          strokeWidth: 2,
          dash: '5 5',
        },
        { kind: 'circle', id: 'tam-quy-dao', cx: 120, cy: 100, r: 3, fill: 'neutral' },
        {
          kind: 'circle',
          id: 'hat-mang-dien',
          cx: 120,
          cy: 180,
          r: 9,
          fill: 'primary',
          keyframes: [
            { atMs: 0, dx: 0, dy: 0 },
            { atMs: 500, dx: 56.6, dy: -23.4 },
            { atMs: 1000, dx: 80, dy: -80 },
            { atMs: 1500, dx: 56.6, dy: -136.6 },
            { atMs: 2000, dx: 0, dy: -160 },
            { atMs: 2500, dx: -56.6, dy: -136.6 },
            { atMs: 3000, dx: -80, dy: -80 },
            { atMs: 3500, dx: -56.6, dy: -23.4 },
            { atMs: 4000, dx: 0, dy: 0 },
          ],
        },
        {
          kind: 'arrow',
          id: 'van-toc-vao',
          x1: 60,
          y1: 180,
          x2: 108,
          y2: 180,
          stroke: 'primary',
          strokeWidth: 3,
        },
        {
          kind: 'arrow',
          id: 'luc-lorentz',
          x1: 120,
          y1: 170,
          x2: 120,
          y2: 118,
          stroke: 'accent',
          strokeWidth: 3,
        },
        {
          kind: 'label',
          id: 'nhan-v',
          x: 62,
          y: 200,
          text: 'v',
          size: 14,
          anchor: 'start',
          fill: 'primary',
        },
        {
          kind: 'label',
          id: 'nhan-f',
          x: 132,
          y: 146,
          text: 'f ⊥ v (hướng vào tâm)',
          size: 12,
          anchor: 'start',
          fill: 'accent',
        },
        {
          kind: 'label',
          id: 'nhan-b',
          x: 300,
          y: 40,
          text: 'B vuông góc, hướng vào trong trang',
          size: 12,
          anchor: 'start',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'nhan-r',
          x: 300,
          y: 120,
          text: 'R = mv / (qB)',
          size: 14,
          anchor: 'start',
          fill: 'neutral',
        },
      ],
      captions: [
        { atMs: 0, text: 'Hạt dương bay vào vùng từ trường với v vuông góc B.' },
        {
          atMs: 1000,
          text: 'Lực Lorentz luôn vuông góc với vận tốc nên chỉ bẻ hướng, không sinh công.',
        },
        { atMs: 2000, text: 'Tốc độ không đổi, hướng đổi đều — đó chính là chuyển động tròn đều.' },
        { atMs: 4000, text: 'Bán kính R = mv/(qB); từ trường mạnh hơn thì vòng tròn hẹp lại.' },
      ],
    },
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Từ trường',
    lessonNumber: 15,
    title: 'Lực Lorentz',
    hook:
      'Từ trường của Trái Đất đóng vai trò như một lá chắn bảo vệ chúng ta khỏi luồng bức xạ vũ trụ có hại bằng cách ' +
      'bẻ cong đường đi của các hạt mang điện, tạo nên những dải cực quang tuyệt đẹp ở hai đầu cực. Lực bẻ cong đó chính là lực Lorentz.',
    theory:
      'ĐỊNH NGHĨA LỰC LORENTZ:\n' +
      '— Lực Lorentz: Là lực do từ trường tác dụng lên một hạt mang điện chuyển động.\n\n' +
      'ĐẶC ĐIỂM CỦA LỰC LORENTZ:\n' +
      'Một hạt có điện tích q chuyển động với vận tốc v trong từ trường đều B:\n' +
      '— Độ lớn: F = |q| * v * B * sin(theta)\n' +
      'Trong đó theta là góc giữa vectơ vận tốc v và vectơ cảm ứng từ B.\n' +
      '— Phương: Vuông góc với cả v và B.\n' +
      '— Chiều: Xác định bằng Quy tắc bàn tay trái:\n' +
      '  + Đặt bàn tay trái sao cho các đường sức từ đâm vào lòng bàn tay.\n' +
      '  + Chiều từ cổ tay đến ngón tay giữa trùng với chiều vận tốc v của hạt.\n' +
      '  + Nếu q > 0: Ngón tay cái choãi ra 90 độ chỉ chiều lực Lorentz.\n' +
      '  + Nếu q < 0: Lực Lorentz có chiều ngược với chiều chỉ của ngón tay cái.\n\n' +
      'CHUYỂN ĐỘNG CỦA HẠT MANG ĐIỆN TRONG TỪ TRƯỜNG ĐỀU:\n' +
      'Khi hạt bay vuông góc với các đường sức từ (theta = 90 độ):\n' +
      '— Lực Lorentz đóng vai trò lực hướng tâm làm hạt chuyển động tròn đều.\n' +
      '— Bán kính quỹ đạo tròn: R = (m * v) / (|q| * B).',
    workedExample: {
      problem:
        'Một hạt electron (q = -1.6e-19 C) bay vuông góc vào một từ trường đều B = 0.5 T với vận tốc v = 2e6 m/s. ' +
        'Tính độ lớn của lực Lorentz tác dụng lên electron.',
      steps: [
        'Xác định thông số: |q| = 1.6 * 10^-19 C, v = 2 * 10^6 m/s, B = 0.5 T.',
        'Xác định góc theta: Vì bay vuông góc nên theta = 90 độ, sin(theta) = 1.',
        'Áp dụng công thức tính độ lớn lực Lorentz: F = |q| * v * B * sin(theta).',
        'Tính toán: F = 1.6 * 10^-19 * 2 * 10^6 * 0.5 * 1 = 1.6 * 10^-13 N.',
      ],
      answer: 'F = 1.6 * 10^-13 N.',
    },
    checkQuestions: [
      {
        prompt: 'Lực Lorentz tác dụng lên hạt mang điện chuyển động trong từ trường có phương:',
        choices: [
          { id: 'pl_1', label: 'Vuông góc với cả vận tốc v và cảm ứng từ B' },
          { id: 'pl_2', label: 'Song song với cảm ứng từ B' },
          { id: 'pl_3', label: 'Trùng với phương của vận tốc v' },
          { id: 'pl_4', label: 'Nằm trong mặt phẳng chứa vận tốc v và cảm ứng từ B' },
        ],
        answer: {
          kind: 'choice',
          correctIds: ['pl_1'],
        },
        explain:
          'Phương của lực Lorentz luôn vuông góc với cả vectơ vận tốc v và vectơ cảm ứng từ B.',
      },
      {
        prompt:
          'Một proton (q = 1.6e-19 C) chuyển động song song với đường sức từ của một từ trường đều B = 0.8 T. ' +
          'Lực Lorentz tác dụng lên proton có độ lớn bằng bao nhiêu?',
        answer: {
          kind: 'numeric',
          value: 0,
          unit: 'N',
        },
        explain:
          'Khi hạt chuyển động song song với đường sức từ, góc theta = 0 hoặc 180 độ, sin(theta) = 0. Do đó, lực Lorentz F = 0 N.',
      },
    ],
    srsCards: [
      {
        hoi: 'Lực Lorentz là gì?',
        dap: 'Là lực do từ trường tác dụng lên một hạt mang điện chuyển động.',
      },
      {
        hoi: 'Công thức tính bán kính quỹ đạo R của hạt mang điện bay vuông góc vào từ trường đều?',
        dap: 'R = m * v / (|q| * B).',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'ly12-c3-b16',
    animation: {
      title: 'Tự cảm: cuộn dây chống lại chính sự đổi dòng của nó',
      description:
        'Cuộn dây nối với nguồn qua một khoá K. Khi đóng khoá, dòng điện I trong mạch KHÔNG nhảy ngay lên giá trị cuối mà tăng dần (đường cong đi lên ở đồ thị bên phải). Lí do: dòng tăng làm từ thông qua chính cuộn dây tăng, theo định luật Lenz cuộn sinh một suất điện động tự cảm e = −L·ΔI/Δt có chiều CHỐNG LẠI sự tăng đó — mũi tên nét đứt ngược chiều dòng. Khi dòng ổn định thì ΔI/Δt = 0 nên e tắt hẳn. Ngắt khoá thì ngược lại: dòng sụt rất nhanh, e đổi chiều để cố duy trì dòng, và vì Δt cực bé nên e có thể rất lớn — đó là lí do ta thấy tia lửa điện ở cầu dao khi ngắt mạch có cuộn cảm.',
      viewBoxWidth: 460,
      viewBoxHeight: 230,
      durationMs: 5000,
      loop: true,
      shapes: [
        {
          kind: 'line',
          id: 'm1',
          x1: 40,
          y1: 60,
          x2: 40,
          y2: 160,
          stroke: 'neutral',
          strokeWidth: 2,
        },
        {
          kind: 'line',
          id: 'm2',
          x1: 40,
          y1: 160,
          x2: 190,
          y2: 160,
          stroke: 'neutral',
          strokeWidth: 2,
        },
        {
          kind: 'line',
          id: 'm3',
          x1: 40,
          y1: 60,
          x2: 90,
          y2: 60,
          stroke: 'neutral',
          strokeWidth: 2,
        },
        {
          kind: 'line',
          id: 'm4',
          x1: 150,
          y1: 60,
          x2: 190,
          y2: 60,
          stroke: 'neutral',
          strokeWidth: 2,
        },
        {
          kind: 'line',
          id: 'm5',
          x1: 190,
          y1: 60,
          x2: 190,
          y2: 160,
          stroke: 'neutral',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'n-k',
          x: 120,
          y: 44,
          text: 'K',
          size: 14,
          anchor: 'middle',
          fill: 'neutral',
        },
        {
          kind: 'line',
          id: 'khoa',
          x1: 90,
          y1: 60,
          x2: 150,
          y2: 60,
          stroke: 'primary',
          strokeWidth: 3,
        },
        {
          kind: 'rect',
          id: 'cuon',
          x: 178,
          y: 88,
          w: 24,
          h: 44,
          stroke: 'primary',
          strokeWidth: 3,
        },
        {
          kind: 'label',
          id: 'n-l',
          x: 214,
          y: 114,
          text: 'L',
          size: 15,
          anchor: 'start',
          fill: 'neutral',
        },
        {
          kind: 'arrow',
          id: 'dong',
          x1: 70,
          y1: 175,
          x2: 150,
          y2: 175,
          stroke: 'primary',
          strokeWidth: 3,
          keyframes: [
            {
              atMs: 0,
              scale: 0.1,
            },
            {
              atMs: 2500,
              scale: 1,
            },
            {
              atMs: 5000,
              scale: 1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'n-idong',
          x: 110,
          y: 196,
          text: 'I',
          size: 14,
          anchor: 'middle',
          fill: 'primary',
        },
        {
          kind: 'arrow',
          id: 'etc',
          x1: 150,
          y1: 205,
          x2: 70,
          y2: 205,
          stroke: 'danger',
          strokeWidth: 2.5,
          keyframes: [
            {
              atMs: 0,
              opacity: 1,
            },
            {
              atMs: 2500,
              opacity: 0.1,
            },
            {
              atMs: 5000,
              opacity: 0.1,
            },
          ],
        },
        {
          kind: 'label',
          id: 'n-e',
          x: 110,
          y: 224,
          text: 'e = −L·ΔI/Δt chống lại sự tăng',
          size: 11,
          anchor: 'middle',
          fill: 'muted',
        },
        {
          kind: 'line',
          id: 'gt',
          x1: 270,
          y1: 170,
          x2: 440,
          y2: 170,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'line',
          id: 'gp',
          x1: 270,
          y1: 40,
          x2: 270,
          y2: 170,
          stroke: 'muted',
          strokeWidth: 2,
        },
        {
          kind: 'label',
          id: 'g-t',
          x: 436,
          y: 188,
          text: 't',
          size: 12,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'label',
          id: 'g-i',
          x: 266,
          y: 38,
          text: 'I',
          size: 12,
          anchor: 'end',
          fill: 'muted',
        },
        {
          kind: 'polyline',
          id: 'duong-i',
          points: [
            [270, 170.0],
            [276, 155.4],
            [282, 142.9],
            [288, 132.3],
            [294, 123.2],
            [300, 115.4],
            [306, 108.8],
            [312, 103.1],
            [318, 98.3],
            [324, 94.1],
            [330, 90.6],
            [336, 87.6],
            [342, 85.0],
            [348, 82.8],
            [354, 81.0],
            [360, 79.4],
            [366, 78.0],
            [372, 76.8],
            [378, 75.8],
            [384, 75.0],
            [390, 74.3],
            [396, 73.6],
            [402, 73.1],
            [408, 72.6],
            [414, 72.3],
            [420, 71.9],
            [426, 71.6],
            [432, 71.4],
          ],
          stroke: 'primary',
          strokeWidth: 3,
        },
        {
          kind: 'line',
          id: 'bao-hoa',
          x1: 270,
          y1: 70,
          x2: 440,
          y2: 70,
          stroke: 'muted',
          strokeWidth: 1.2,
          dash: '4 4',
        },
        {
          kind: 'circle',
          id: 'chay-i',
          cx: 270,
          cy: 170,
          r: 6,
          fill: 'accent',
          keyframes: [
            {
              atMs: 0,
              dx: 0,
              dy: 0,
            },
            {
              atMs: 2500,
              dx: 82,
              dy: -89,
            },
            {
              atMs: 5000,
              dx: 164,
              dy: -98,
            },
          ],
        },
      ],
      captions: [
        {
          atMs: 0,
          text: 'Đóng khoá: dòng tăng dần, tự cảm chống lại',
        },
        {
          atMs: 2600,
          text: 'Dòng ổn định: ΔI/Δt = 0 nên suất điện động tự cảm tắt',
        },
      ],
    },
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Từ trường',
    lessonNumber: 16,
    title: 'Tự cảm',
    hook:
      'Khi ta đột ngột rút phích cắm điện của một lò sưởi hay bóng đèn công suất lớn, ta thường thấy một tia lửa điện nhỏ phát ra. ' +
      'Hiện tượng này do chính cuộn dây trong mạch sinh ra nhằm chống lại sự giảm nhanh của dòng điện. Đó là hiện tượng tự cảm.',
    theory:
      'TỪ THÔNG RIÊNG CỦA MỘT MẠCH KÍN:\n' +
      '— Khi có dòng điện cường độ i chạy qua mạch kín, nó tạo từ thông riêng:\n' +
      '  Phi = L * i\n' +
      'Trong đó L là độ tự cảm (hệ số tự cảm) của mạch. Đơn vị là Henry (H).\n\n' +
      'HIỆN TƯỢNG TỰ CẢM:\n' +
      '— Hiện tượng tự cảm: Là hiện tượng cảm ứng điện từ xảy ra trong một mạch kín do chính sự biến đổi của cường độ dòng điện trong mạch đó gây ra.\n\n' +
      'SUẤT ĐIỆN ĐỘNG TỰ CẢM:\n' +
      '— Khi dòng điện trong mạch biến thiên, xuất hiện suất điện động tự cảm:\n' +
      '  etc = -L * (di / dt)\n' +
      '— Độ lớn của suất điện động tự cảm tỉ lệ thuận với tốc độ biến thiên cường độ dòng điện trong mạch.',
    workedExample: {
      problem:
        'Một ống dây có độ tự cảm L = 0.2 H. Trong khoảng thời gian 0.1 s, cường độ dòng điện trong ống dây giảm đều từ 2 A xuống 0 A. ' +
        'Tính độ lớn suất điện động tự cảm xuất hiện trong ống dây.',
      steps: [
        'Xác định các thông số: L = 0.2 H, dt = 0.1 s, di = i2 - i1 = 0 - 2 = -2 A.',
        'Áp dụng công thức độ lớn suất điện động tự cảm: |etc| = L * |di / dt|.',
        'Thay số: |etc| = 0.2 * |-2| / 0.1.',
        'Tính toán: |etc| = 4 V.',
      ],
      answer: 'etc_magnitude = 4 V.',
    },
    checkQuestions: [
      {
        prompt: 'Đơn vị đo độ tự cảm L trong hệ SI là:',
        choices: [
          { id: 'l_1', label: 'Henry (H)' },
          { id: 'l_2', label: 'Weber (Wb)' },
          { id: 'l_3', label: 'Tesla (T)' },
          { id: 'l_4', label: 'Farad (F)' },
        ],
        answer: {
          kind: 'choice',
          correctIds: ['l_1'],
        },
        explain:
          'Đơn vị đo hệ số tự cảm (độ tự cảm) L là Henry (H). L đặc trưng cho khả năng ống dây tự cảm sinh suất điện động cảm ứng khi dòng điện qua nó biến thiên: e = -L.ΔI/Δt.',
      },
      {
        prompt:
          'Một ống dây có độ tự cảm 0.5 H. Nếu tốc độ biến thiên của cường độ dòng điện trong ống dây là 10 A/s, ' +
          'thì độ lớn suất điện động tự cảm xuất hiện trong ống dây là bao nhiêu Volt?',
        answer: {
          kind: 'numeric',
          value: 5,
          unit: 'V',
        },
        explain:
          'Suất điện động tự cảm chỉ sinh ra khi dòng qua ống dây BIẾN THIÊN, và tỉ lệ với tốc độ biến thiên ấy: |e_tc| = L * |di/dt| = 0,5 * 10 = 5 V. Dòng không đổi thì di/dt = 0 nên không có suất điện động tự cảm, dù dòng lớn đến đâu.',
      },
    ],
    srsCards: [
      {
        hoi: 'Hiện tượng tự cảm là gì?',
        dap: 'Là hiện tượng cảm ứng điện từ xảy ra do chính sự biến đổi cường độ dòng điện trong mạch.',
      },
      {
        hoi: 'Suất điện động tự cảm tỉ lệ với đại lượng nào?',
        dap: 'Tốc độ biến thiên cường độ dòng điện trong mạch.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'ly12-c3-b17',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Từ trường',
    lessonNumber: 17,
    title: 'Máy biến áp. Truyền tải điện năng đi xa',
    hook:
      'Các nhà máy điện thường phát ra điện thế hàng kilôvôn, nhưng để truyền tải điện năng đi xa hàng trăm kilômét, người ta phải nâng điện áp lên hàng trăm kilôvôn, ' +
      'sau đó lại hạ xuống 220 V để đưa vào gia đình sử dụng. Thiết bị thực hiện nhiệm vụ này một cách hiệu quả là máy biến áp.',
    theory:
      'MÁY BIẾN ÁP:\n' +
      '— Máy biến áp: Là thiết bị có khả năng biến đổi điện áp xoay chiều mà không làm thay đổi tần số.\n' +
      '— Cấu tạo: Gồm hai cuộn dây sơ cấp (N1 vòng) và thứ cấp (N2 vòng) quấn trên cùng lõi sắt non pha silic.\n' +
      '— Công thức máy biến áp lí tưởng: U2 / U1 = I1 / I2 = N2 / N1.\n' +
      '— Phân loại: N2 > N1: Máy tăng áp; N2 < N1: Máy hạ áp.\n\n' +
      'TRUYỀN TẢI ĐIỆN NĂNG ĐI XA:\n' +
      '— Hao phí điện năng do toả nhiệt trên đường dây: Php = r * I² = r * P² / (U² * cos²(phi)).\n' +
      '— Để giảm hao phí Php, giải pháp hiệu quả nhất là tăng điện áp truyền tải U trước khi đưa lên dây dẫn. Tăng U lên k lần thì hao phí Php giảm đi k² lần.',
    workedExample: {
      problem:
        'Một máy biến áp lí tưởng có số vòng dây cuộn sơ cấp là 1000 vòng, cuộn thứ cấp có 200 vòng. ' +
        'Đặt vào hai đầu cuộn sơ cấp điện áp xoay chiều U1 = 220 V. Tính điện áp hiệu dụng ở hai đầu cuộn thứ cấp để hở.',
      steps: [
        'Xác định thông số: N1 = 1000 vòng, N2 = 200 vòng, U1 = 220 V.',
        'Áp dụng công thức máy biến áp lý tưởng: U2 / U1 = N2 / N1 => U2 = U1 * (N2 / N1).',
        'Thay số: U2 = 220 * (200 / 1000) = 44 V.',
        'Kết luận: Điện áp hiệu dụng ở cuộn thứ cấp để hở là 44 V.',
      ],
      answer: 'U2 = 44 V.',
    },
    checkQuestions: [
      {
        prompt:
          'Đối với một máy biến áp lí tưởng, nếu số vòng dây cuộn thứ cấp lớn hơn cuộn sơ cấp (N2 > N1) thì nó có tác dụng:',
        choices: [
          { id: 'ap_1', label: 'Tăng điện áp, giảm cường độ dòng điện' },
          { id: 'ap_2', label: 'Giảm điện áp, tăng cường độ dòng điện' },
          { id: 'ap_3', label: 'Tăng điện áp, tăng tần số dòng điện' },
          { id: 'ap_4', label: 'Giảm điện áp, giảm tần số dòng điện' },
        ],
        answer: {
          kind: 'choice',
          correctIds: ['ap_1'],
        },
        explain:
          'Khi N2 > N1 thì U2 > U1 và I2 < I1, máy biến áp đóng vai trò là máy tăng áp (tăng điện áp và giảm cường độ dòng điện).',
      },
      {
        prompt:
          'Khi truyền tải một công suất điện xoay chiều P đi xa, nếu tăng điện áp ở hai đầu đường dây truyền tải lên 10 lần ' +
          'thì công suất hao phí do toả nhiệt trên đường dây sẽ thay đổi như thế nào?',
        choices: [
          { id: 'hp_1', label: 'Giảm đi 100 lần' },
          { id: 'hp_2', label: 'Tăng lên 100 lần' },
          { id: 'hp_3', label: 'Giảm đi 10 lần' },
          { id: 'hp_4', label: 'Tăng lên 10 lần' },
        ],
        answer: {
          kind: 'choice',
          correctIds: ['hp_1'],
        },
        explain:
          'Hao phí tỉ lệ nghịch với bình phương điện áp U. Khi U tăng 10 lần thì hao phí giảm 10^2 = 100 lần.',
      },
    ],
    srsCards: [
      {
        hoi: 'Hệ thức liên hệ giữa điện áp hiệu dụng U và số vòng dây N ở hai cuộn dây máy biến áp?',
        dap: 'U2 / U1 = N2 / N1.',
      },
      {
        hoi: 'Hao phí truyền tải điện năng giảm đi bao nhiêu lần khi tăng điện áp lên 5 lần?',
        dap: 'Giảm đi 25 lần.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'ly12-c3-b18',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Từ trường',
    lessonNumber: 18,
    title: 'Ứng dụng của từ trường',
    hook:
      'Làm thế nào một đoàn tàu cao tốc Maglev nặng hàng chục tấn có thể "lơ lửng" trên không trung và lao đi với vận tốc 600 km/h? ' +
      'Làm sao máy chụp MRI có thể nhìn thấy chi tiết tế bào não mà không cần phẫu thuật? Tất cả là nhờ các ứng dụng kỳ diệu của từ trường.',
    theory:
      'NAM CHÂM ĐIỆN CÔNG NGHIỆP:\n' +
      '— Cấu tạo gồm cuộn dây điện quấn quanh lõi sắt non. Lõi sắt non làm tăng từ trường lên nhiều lần và mất hết từ tính khi ngắt điện.\n' +
      '— Ứng dụng: Cần cẩu điện hút kim loại vụn.\n\n' +
      'ĐỘNG CƠ ĐIỆN VÀ LOA ĐIỆN:\n' +
      '— Động cơ điện: Biến đổi điện năng thành cơ năng dựa trên lực từ tác dụng lên cuộn dây mang điện đặt trong từ trường làm rotor quay.\n' +
      '— Loa điện: Dòng điện xoay chiều âm tần chạy vào cuộn dây đặt trong từ trường biến thiên làm rung màng loa tạo sóng âm.\n\n' +
      'TÀU ĐỆM TỪ (MAGLEV):\n' +
      '— Sử dụng lực đẩy và lực hút từ trường của nam châm siêu dẫn cực mạnh để nâng tàu lơ lửng trên đường ray (triệt tiêu ma sát) và đẩy tàu tiến lên.\n\n' +
      'CHỤP CỘNG HƯỞNG TỪ (MRI):\n' +
      '— Sử dụng từ trường mạnh của nam châm siêu dẫn và sóng vô tuyến để định hướng lại mômen từ nguyên tử hydro trong cơ thể tạo ảnh sắc nét.',
    workedExample: {
      problem: 'Nêu nguyên lí hoạt động cơ bản của loa điện dùng trong các thiết bị âm thanh.',
      steps: [
        'Dòng điện xoay chiều mang tín hiệu âm tần chạy qua một cuộn dây nhỏ.',
        'Cuộn dây này được đặt trong từ trường của một nam châm vĩnh cửu mạnh.',
        'Dưới tác dụng của lực từ biến thiên tuần hoàn, cuộn dây dao động dọc và kéo màng loa dao động theo.',
        'Màng loa dao động nén và giãn không khí xung quanh, tạo ra sóng âm truyền đi.',
      ],
      answer:
        'Biến dao động điện thành dao động cơ của màng loa nhờ lực từ tác dụng lên cuộn dây mang điện đặt trong từ trường.',
    },
    checkQuestions: [
      {
        prompt:
          'Thiết bị y học nào sau đây ứng dụng từ trường mạnh của nam châm siêu dẫn để ghi hình cơ thể người?',
        choices: [
          { id: 'm_1', label: 'Máy chụp cộng hưởng từ (MRI)' },
          { id: 'm_2', label: 'Máy chụp cắt lớp vi tính (CT)' },
          { id: 'm_3', label: 'Máy chụp X-quang' },
          { id: 'm_4', label: 'Máy siêu âm' },
        ],
        answer: {
          kind: 'choice',
          correctIds: ['m_1'],
        },
        explain:
          'Máy chụp cộng hưởng từ (MRI - Magnetic Resonance Imaging) sử dụng từ trường mạnh và sóng vô tuyến để tái tạo cấu trúc cơ thể.',
      },
      {
        prompt:
          'Lõi của nam châm điện thường được làm bằng vật liệu gì để dễ từ hoá và dễ mất từ tính khi ngắt dòng điện?',
        choices: [
          { id: 'v_1', label: 'Sắt non' },
          { id: 'v_2', label: 'Thép cacbon cao' },
          { id: 'v_3', label: 'Đồng thau' },
          { id: 'v_4', label: 'Thạch anh' },
        ],
        answer: {
          kind: 'choice',
          correctIds: ['v_1'],
        },
        explain:
          'Sắt non (soft iron) có độ thẩm từ cao, dễ bị nhiễm từ mạnh nhưng cũng nhanh chóng mất từ tính khi ngắt dòng điện.',
      },
    ],
    srsCards: [
      {
        hoi: 'MRI viết tắt của phương pháp chẩn đoán hình ảnh nào?',
        dap: 'Chụp cộng hưởng từ (Magnetic Resonance Imaging).',
      },
      {
        hoi: 'Tại sao lõi nam châm điện làm bằng sắt non thay vì thép?',
        dap: 'Vì sắt non mất từ tính rất nhanh khi ngắt dòng điện, giúp điều khiển nam châm dễ dàng.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
  {
    id: 'ly12-c3-b19',
    grade: '12',
    chapterNumber: 3,
    chapterTitle: 'Từ trường',
    lessonNumber: 19,
    title: 'Bài tập về từ trường',
    hook: 'Tổng hợp và giải quyết các bài tập nâng cao về từ trường giúp hệ thống lại toàn bộ kiến thức về lực từ, lực Lorentz, tự cảm và máy biến áp.',
    theory:
      'HỆ THỐNG CÔNG THỨC TRỌNG TÂM:\n' +
      '1. Lực từ: F = B * I * L * sin(theta)\n' +
      '2. Lực Lorentz: F = |q| * v * B * sin(theta)\n' +
      '3. Suất điện động tự cảm: etc = -L * (di / dt)\n' +
      '4. Máy biến áp lý tưởng: U2 / U1 = N2 / N1',
    workedExample: {
      problem:
        'Một dây dẫn thẳng mang dòng điện cường độ 3 A được đặt trong từ trường đều có B = 0.5 T. ' +
        'Chiều dài của dây dẫn là 0.4 m. Góc hợp bởi dây dẫn và đường sức từ là 30 độ. Tính độ lớn lực từ tác dụng lên dây.',
      steps: [
        'Xác định thông số: I = 3 A, B = 0.5 T, L = 0.4 m, theta = 30 độ.',
        'Tính giá trị sin: sin(30) = 0.5.',
        'Áp dụng công thức lực từ: F = B * I * L * sin(theta).',
        'Thay số và tính: F = 0.5 * 3 * 0.4 * 0.5 = 0.3 N.',
      ],
      answer: 'F = 0.3 N.',
    },
    checkQuestions: [
      {
        prompt:
          'Một ống dây có độ tự cảm 0.1 H. Cường độ dòng điện biến thiên đều với tốc độ 20 A/s. ' +
          'Độ lớn suất điện động tự cảm xuất hiện trong ống dây là bao nhiêu Volt?',
        answer: {
          kind: 'numeric',
          value: 2,
          unit: 'V',
        },
        explain:
          'Cùng công thức tự cảm: e_tc = L * |di/dt| = 0,1 * 20 = 2 V. Dấu trừ trong công thức đầy đủ (định luật Lenz) chỉ nói suất điện động CHỐNG LẠI sự biến thiên của dòng; đề hỏi ĐỘ LỚN nên lấy trị tuyệt đối.',
      },
      {
        prompt:
          'Một máy biến áp lí tưởng có số vòng dây cuộn sơ cấp là 2200 vòng và cuộn thứ cấp là 110 vòng. ' +
          'Nếu đặt vào hai đầu cuộn sơ cấp điện áp xoay chiều hiệu dụng 220 V thì điện áp hiệu dụng ở hai đầu cuộn thứ cấp để hở là bao nhiêu Volt?',
        answer: {
          kind: 'numeric',
          value: 11,
          unit: 'V',
        },
        explain:
          'U2 = U1 * (N2 / N1) = 220 * (110 / 2200) = 11 V. Số vòng thứ cấp ít hơn sơ cấp (N2 < N1) nên đây là máy hạ áp — dễ nhầm lẫn nếu quên tỉ lệ thuận giữa U và N.',
      },
    ],
    srsCards: [
      {
        hoi: 'Lực Lorentz tác dụng lên điện tích chuyển động đạt cực đại khi nào?',
        dap: 'Khi điện tích bay vuông góc với đường sức từ (theta = 90 độ).',
      },
      {
        hoi: 'Suất điện động tự cảm xuất hiện khi nào?',
        dap: 'Khi có sự biến thiên của cường độ dòng điện trong chính mạch đó.',
      },
    ],
    track: 'core',
    reviewStatus: 'draft',
  },
]
